Quader: benchmarks/benchmark_main.cpp File Reference
benchmark_main.cpp File Reference
#include "benchmark_main.hpp"
#include <algorithm>
#include <chrono>
#include <iostream>
#include <string>
#include <string_view>
#include <utility>
Namespaces
namespace quader
namespace quader::benchmarks
Functions
BenchmarkRunConfig quader::benchmarks::parse_benchmark_config (int argc, char **argv)
BenchmarkResult quader::benchmarks::run_benchmark (std::string name, const BenchmarkRunConfig &config, const BenchmarkBody &body)
void quader::benchmarks::print_jsonl (const BenchmarkResult &result)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 113 of file benchmark_main.cpp.
References quader::benchmarks::parse_benchmark_config(), quader::benchmarks::print_jsonl(), quader::benchmarks::run_crimson_packet_pipeline_benchmark(), and quader::benchmarks::run_crimson_upload_benchmark().