Quader: quader::ui::DocumentSelectionAdapter Class Reference
quader::ui::DocumentSelectionAdapter Class Reference final
Synchronizes document object selection with a Qt item selection model.
#include <document_selection_adapter.hpp>
Public Slots
void sync_from_document ()
Project document selection into the Qt selection model.
Public Member Functions
DocumentSelectionAdapter (DocumentItemModel &model, QItemSelectionModel &selection_model, DocumentUiController &documents, QObject *parent=nullptr)
Construct an adapter over model, view selection, and document services.
Detailed Description
Synchronizes document object selection with a Qt item selection model.
Definition at line 27 of file document_selection_adapter.hpp.
Constructor & Destructor Documentation
DocumentSelectionAdapter()
quader::ui::DocumentSelectionAdapter::DocumentSelectionAdapter (DocumentItemModel & model, QItemSelectionModel & selection_model, DocumentUiController & documents, QObject * parent = nullptr)
Construct an adapter over model, view selection, and document services.
Definition at line 31 of file document_selection_adapter.cpp.
References quader::ui::DocumentUiController::selection_changed(), and sync_from_document().
Member Function Documentation
sync_from_document
void quader::ui::DocumentSelectionAdapter::sync_from_document () slot
Project document selection into the Qt selection model.
Definition at line 45 of file document_selection_adapter.cpp.
References quader::ui::Kind, and quader::ui::Name.
Referenced by DocumentSelectionAdapter().
The documentation for this class was generated from the following files:
src/ui/models/document_selection_adapter.hpp
src/ui/models/document_selection_adapter.cpp