Quader: quader::ui::CrimsonViewportRenderHost Class Reference
quader::ui::CrimsonViewportRenderHost Class Reference final
Public Member Functions
CrimsonViewportRenderHost ()
CrimsonViewportRenderHost (const quader::document::Document &document, const quader::tools::ToolManager &tool_manager)
~CrimsonViewportRenderHost () override
ViewportRenderResult initialize_surface (const NativeViewportSurface &surface, ViewportPixelSize size, double device_pixel_ratio) override
Initialize rendering for a native viewport surface.
ViewportRenderResult resize_surface (ViewportPixelSize size, double device_pixel_ratio) override
Resize the native viewport surface.
ViewportRenderResult render_frame (const ViewportRenderRequest &request) override
Render one frame from a borrowed request payload.
void shutdown_surface () override
Shut down rendering for the current surface.
std::optional< ViewportFrameStats > latest_frame_stats () const override
Return the latest frame stats if available.
std::optional< ViewportDiagnosticsSnapshot > latest_diagnostics () const override
Return the latest diagnostics snapshot if available.
QString renderer_name () const override
Return the renderer display name.
Public Member Functions inherited from quader::ui::IViewportRenderHost
virtual ~IViewportRenderHost ()=default
Destroy the render host.
Detailed Description
Definition at line 379 of file crimson_viewport_render_host.cpp.
Constructor & Destructor Documentation
CrimsonViewportRenderHost() [1/2]
quader::ui::CrimsonViewportRenderHost::CrimsonViewportRenderHost () default
CrimsonViewportRenderHost() [2/2]
quader::ui::CrimsonViewportRenderHost::CrimsonViewportRenderHost (const quader::document::Document & document, const quader::tools::ToolManager & tool_manager)
Definition at line 431 of file crimson_viewport_render_host.cpp.
~CrimsonViewportRenderHost()
quader::ui::CrimsonViewportRenderHost::~CrimsonViewportRenderHost () override
Definition at line 437 of file crimson_viewport_render_host.cpp.
References shutdown_surface().
Member Function Documentation
initialize_surface()
ViewportRenderResult quader::ui::CrimsonViewportRenderHost::initialize_surface (const NativeViewportSurface & surface, ViewportPixelSize size, double device_pixel_ratio) nodiscard override virtual
Initialize rendering for a native viewport surface.
Implements quader::ui::IViewportRenderHost.
Definition at line 441 of file crimson_viewport_render_host.cpp.
References crimson::Auto, crimson::RendererStatus::backend_name, crimson::RendererConfig::backend_preference, crimson::Renderer::create(), crimson::RendererConfig::enable_debug_text, crimson::RendererConfig::shader_root, shutdown_surface(), quader::ui::ViewportRenderResult::success(), and crimson::RendererConfig::vsync.
latest_diagnostics()
std::optional< ViewportDiagnosticsSnapshot > quader::ui::CrimsonViewportRenderHost::latest_diagnostics () const nodiscard override virtual
Return the latest diagnostics snapshot if available.
Implements quader::ui::IViewportRenderHost.
Definition at line 537 of file crimson_viewport_render_host.cpp.
References quader::ui::viewport_diagnostics_from_crimson().
latest_frame_stats()
std::optional< ViewportFrameStats > quader::ui::CrimsonViewportRenderHost::latest_frame_stats () const nodiscard override virtual
Return the latest frame stats if available.
Implements quader::ui::IViewportRenderHost.
Definition at line 533 of file crimson_viewport_render_host.cpp.
render_frame()
ViewportRenderResult quader::ui::CrimsonViewportRenderHost::render_frame (const ViewportRenderRequest & request) nodiscard override virtual
Render one frame from a borrowed request payload.
Implements quader::ui::IViewportRenderHost.
Definition at line 479 of file crimson_viewport_render_host.cpp.
References crimson::FrameBuilder::build_prototype_snapshot(), quader::ui::ViewportRenderRequest::cameras, crimson::FrameRenderResult::completed_picking_results, quader::ui::ViewportRenderRequest::device_pixel_ratio, quader::ui::ViewportRenderRequest::elapsed_seconds, quader::ui::ViewportRenderResult::failure(), quader::ui::ViewportRenderRequest::panes, quader::ui::ViewportRenderRequest::picking_requests, quader::ui::ViewportRenderRequest::prototype_animation_enabled, crimson::FrameRenderResult::stats, quader::ui::ViewportRenderResult::success(), and quader::ui::ViewportRenderRequest::surface_size.
renderer_name()
QString quader::ui::CrimsonViewportRenderHost::renderer_name () const nodiscard override virtual
Return the renderer display name.
Implements quader::ui::IViewportRenderHost.
Definition at line 545 of file crimson_viewport_render_host.cpp.
resize_surface()
ViewportRenderResult quader::ui::CrimsonViewportRenderHost::resize_surface (ViewportPixelSize size, double device_pixel_ratio) nodiscard override virtual
Resize the native viewport surface.
Implements quader::ui::IViewportRenderHost.
Definition at line 464 of file crimson_viewport_render_host.cpp.
References quader::ui::ViewportRenderResult::failure(), and quader::ui::ViewportRenderResult::success().
shutdown_surface()
void quader::ui::CrimsonViewportRenderHost::shutdown_surface () override virtual
Shut down rendering for the current surface.
Implements quader::ui::IViewportRenderHost.
Definition at line 528 of file crimson_viewport_render_host.cpp.
Referenced by initialize_surface(), and ~CrimsonViewportRenderHost().
The documentation for this class was generated from the following file:
src/ui/viewport/crimson_viewport_render_host.cpp