Quader: crimson::gpu::GpuPicking Class Reference
crimson::gpu::GpuPicking Class Reference final
Owns GPU picking target submission and delayed readback resolution.
#include <gpu_picking.hpp>
Classes
struct Impl
Public Member Functions
GpuPicking ()
Construct an empty picking subsystem.
~GpuPicking ()
Release GPU resources.
GpuPicking (const GpuPicking &)=delete
Copying is disabled because the implementation owns GPU handles/readbacks.
GpuPicking & operator= (const GpuPicking &)=delete
Copying is disabled because the implementation owns GPU handles/readbacks.
bool initialize (PickingIdTargetFormat target_format, RendererStatus &status)
Initialize picking resources for the selected target format.
void shutdown () noexcept
Release all owned picking resources and pending readbacks.
bool ready () const noexcept
Return true after successful initialization and before shutdown.
GpuPickingFrameResult submit_frame_requests (const FrameSnapshot &snapshot, const GpuMeshCache &mesh_cache, const GpuProgramCache &program_cache, RenderMeshHandle unit_box_mesh, RenderProgramHandle picking_program, std::uint32_t completed_bgfx_frame)
Detailed Description
Owns GPU picking target submission and delayed readback resolution.
Definition at line 38 of file gpu_picking.hpp.
Constructor & Destructor Documentation
GpuPicking() [1/2]
crimson::gpu::GpuPicking::GpuPicking ()
Construct an empty picking subsystem.
Definition at line 152 of file gpu_picking.cpp.
Referenced by GpuPicking(), and operator=().
~GpuPicking()
crimson::gpu::GpuPicking::~GpuPicking ()
Release GPU resources.
Definition at line 155 of file gpu_picking.cpp.
References shutdown().
GpuPicking() [2/2]
crimson::gpu::GpuPicking::GpuPicking (const GpuPicking &) delete
Copying is disabled because the implementation owns GPU handles/readbacks.
References GpuPicking().
Member Function Documentation
initialize()
bool crimson::gpu::GpuPicking::initialize (PickingIdTargetFormat target_format, RendererStatus & status) nodiscard
Initialize picking resources for the selected target format.
Definition at line 159 of file gpu_picking.cpp.
References shutdown().
operator=()
GpuPicking & crimson::gpu::GpuPicking::operator= (const GpuPicking &) delete
Copying is disabled because the implementation owns GPU handles/readbacks.
References GpuPicking(), ready(), and submit_frame_requests().
ready()
bool crimson::gpu::GpuPicking::ready () const nodiscard noexcept
Return true after successful initialization and before shutdown.
Definition at line 219 of file gpu_picking.cpp.
Referenced by operator=(), and submit_frame_requests().
shutdown()
void crimson::gpu::GpuPicking::shutdown () noexcept
Release all owned picking resources and pending readbacks.
Definition at line 210 of file gpu_picking.cpp.
Referenced by initialize(), and ~GpuPicking().
submit_frame_requests()
GpuPickingFrameResult crimson::gpu::GpuPicking::submit_frame_requests (const FrameSnapshot & snapshot, const GpuMeshCache & mesh_cache, const GpuProgramCache & program_cache, RenderMeshHandle unit_box_mesh, RenderProgramHandle picking_program, std::uint32_t completed_bgfx_frame) nodiscard
Submit all picking work for one frame.
Parameters
snapshot Frame snapshot containing picking requests.
mesh_cache Mesh cache used to draw pickable objects.
program_cache Program cache containing the picking shader.
unit_box_mesh Fallback mesh handle used for bounding proxies.
picking_program Program handle selected for the picking pass.
completed_bgfx_frame Latest bgfx frame index known complete.
Returns
Completed readback results and count of new readbacks.
Definition at line 223 of file gpu_picking.cpp.
References crimson::gpu::GpuPickingFrameResult::completed_results, crimson::encode_picking_id_rgba8(), crimson::gpu::GpuMeshCache::get(), crimson::is_valid_handle(), crimson::None, crimson::FrameSnapshot::objects(), crimson::picking_id_rgba8_to_unorm(), crimson::picking_payload_for_object(), crimson::picking_readback_requested(), crimson::FrameSnapshot::picking_requests(), crimson::gpu::GpuProgramCache::program(), ready(), crimson::PickingRequest::request_id, crimson::gpu::GpuPickingFrameResult::scheduled_readbacks, crimson::PickingRequest::view_index, and crimson::FrameSnapshot::views().
Referenced by operator=().
The documentation for this class was generated from the following files:
src/crimson/gpu/gpu_picking.hpp
src/crimson/gpu/gpu_picking.cpp