Quader: quader::tools::ToolContext Class Reference
quader::tools::ToolContext Class Reference final
Services exposed to editor tools without giving tools UI ownership.
#include <tool_context.hpp>
Public Member Functions
ToolContext (quader::document::Document &document, quader::commands::CommandHistory &command_history) noexcept
const quader::document::Document & document () const noexcept
Return the document visible to tools.
quader::commands::CommandHistory & command_history () noexcept
Return the command history used for undoable tool commits.
const quader::commands::CommandHistory & command_history () const noexcept
Return the command history used for undoable tool commits.
quader::commands::CommandResult execute_command (std::unique_ptr< quader::commands::ICommand > command)
void set_after_command_applied (std::function< void()> callback)
Set a callback invoked after a command is applied successfully.
Detailed Description
Services exposed to editor tools without giving tools UI ownership.
Definition at line 22 of file tool_context.hpp.
Constructor & Destructor Documentation
ToolContext()
quader::tools::ToolContext::ToolContext (quader::document::Document & document, quader::commands::CommandHistory & command_history) noexcept
Construct a tool context over a document and command history.
Parameters
document Document that tools read and mutate through commands.
command_history Command history used to apply undoable tool commands.
Definition at line 16 of file tool_context.cpp.
References command_history(), and document().
Member Function Documentation
command_history() [1/2]
const quader::commands::CommandHistory & quader::tools::ToolContext::command_history () const nodiscard noexcept
Return the command history used for undoable tool commits.
Definition at line 30 of file tool_context.cpp.
command_history() [2/2]
quader::commands::CommandHistory & quader::tools::ToolContext::command_history () nodiscard noexcept
Return the command history used for undoable tool commits.
Definition at line 26 of file tool_context.cpp.
Referenced by ToolContext().
document()
const quader::document::Document & quader::tools::ToolContext::document () const nodiscard noexcept
Return the document visible to tools.
Definition at line 22 of file tool_context.cpp.
Referenced by ToolContext().
execute_command()
quader::commands::CommandResult quader::tools::ToolContext::execute_command (std::unique_ptr< quader::commands::ICommand > command) nodiscard
Execute a tool command through the command history.
Parameters
command Command to execute against the document.
Returns
Command result from the history; the after-apply callback runs only when applied.
Definition at line 34 of file tool_context.cpp.
set_after_command_applied()
void quader::tools::ToolContext::set_after_command_applied (std::function< void()> callback)
Set a callback invoked after a command is applied successfully.
Definition at line 43 of file tool_context.cpp.
The documentation for this class was generated from the following files:
src/tools/tool_context.hpp
src/tools/tool_context.cpp