Quader: quader::io::ImportExportRegistry Class Reference
quader::io::ImportExportRegistry Class Reference final
Owns registered importers and exporters and resolves them by path.
#include <import_export_registry.hpp>
Public Member Functions
quader::foundation::Result< void, IoError > register_importer (std::unique_ptr< IImporter > importer)
quader::foundation::Result< void, IoError > register_exporter (std::unique_ptr< IExporter > exporter)
const IImporter * importer_for_path (const std::filesystem::path &path) const
const IExporter * exporter_for_path (const std::filesystem::path &path) const
std::vector< FileFormatDescriptor > import_formats () const
std::vector< FileFormatDescriptor > export_formats () const
Detailed Description
Owns registered importers and exporters and resolves them by path.
Definition at line 24 of file import_export_registry.hpp.
Member Function Documentation
export_formats()
std::vector< FileFormatDescriptor > quader::io::ImportExportRegistry::export_formats () const nodiscard
Return registered export format descriptors.
Returns
Descriptors copied from registered exporters.
Definition at line 155 of file import_export_registry.cpp.
exporter_for_path()
const IExporter * quader::io::ImportExportRegistry::exporter_for_path (const std::filesystem::path & path) const nodiscard
Resolve an exporter by path extension.
Parameters
path Destination path to match.
Returns
Borrowed exporter, or nullptr when none matches.
Definition at line 134 of file import_export_registry.cpp.
References quader::io::descriptor_supports_extension().
import_formats()
std::vector< FileFormatDescriptor > quader::io::ImportExportRegistry::import_formats () const nodiscard
Return registered import format descriptors.
Returns
Descriptors copied from registered importers.
Definition at line 145 of file import_export_registry.cpp.
importer_for_path()
const IImporter * quader::io::ImportExportRegistry::importer_for_path (const std::filesystem::path & path) const nodiscard
Resolve an importer by path extension.
Parameters
path Source path to match.
Returns
Borrowed importer, or nullptr when none matches.
Definition at line 123 of file import_export_registry.cpp.
References quader::io::descriptor_supports_extension().
register_exporter()
quader::foundation::Result< void, IoError > quader::io::ImportExportRegistry::register_exporter (std::unique_ptr< IExporter > exporter) nodiscard
Register an exporter.
Parameters
exporter Exporter to take ownership of.
Returns
Success, or an I/O error for invalid registration.
Definition at line 106 of file import_export_registry.cpp.
References quader::foundation::Result< T, E >::failure(), and quader::foundation::Result< T, E >::success().
register_importer()
quader::foundation::Result< void, IoError > quader::io::ImportExportRegistry::register_importer (std::unique_ptr< IImporter > importer) nodiscard
Register an importer.
Parameters
importer Importer to take ownership of.
Returns
Success, or an I/O error for invalid registration.
Definition at line 89 of file import_export_registry.cpp.
References quader::foundation::Result< T, E >::failure(), and quader::foundation::Result< T, E >::success().
The documentation for this class was generated from the following files:
src/io/import_export_registry.hpp
src/io/import_export_registry.cpp