Quader: quader::tools::ITool Class Reference
quader::tools::ITool Class Reference abstract
Base interface for toolkit-neutral editor tools.
#include <tool.hpp>
Public Member Functions
virtual ~ITool ()=default
Destroy the tool.
virtual ToolId id () const noexcept=0
Return the stable tool id.
virtual void activate (ToolContext &context)
Called when the tool becomes active.
virtual void deactivate (ToolContext &context)
Called when the tool is deactivated.
virtual void cancel (ToolContext &context)
Cancel any in-progress interaction.
virtual bool on_pointer_event (const PointerEvent &event, ToolContext &context)
Handle a pointer event.
virtual bool on_key_event (const KeyEvent &event, ToolContext &context)
Handle a key event.
virtual ToolPreview preview () const
Return the current preview payload.
Detailed Description
Base interface for toolkit-neutral editor tools.
Definition at line 20 of file tool.hpp.
Constructor & Destructor Documentation
~ITool()
virtual quader::tools::ITool::~ITool () virtual default
Destroy the tool.
Member Function Documentation
activate()
void quader::tools::ITool::activate (ToolContext & context) virtual
Called when the tool becomes active.
Reimplemented in quader::tools::BoxTool.
Definition at line 14 of file tool.cpp.
Referenced by id(), and quader::tools::ToolManager::set_active_tool().
cancel()
void quader::tools::ITool::cancel (ToolContext & context) virtual
Cancel any in-progress interaction.
Reimplemented in quader::tools::BoxTool.
Definition at line 22 of file tool.cpp.
Referenced by id().
deactivate()
void quader::tools::ITool::deactivate (ToolContext & context) virtual
Called when the tool is deactivated.
Reimplemented in quader::tools::BoxTool.
Definition at line 18 of file tool.cpp.
Referenced by id().
id()
virtual ToolId quader::tools::ITool::id () const nodiscard pure virtual noexcept
Return the stable tool id.
Implemented in quader::tools::BoxTool.
References activate(), cancel(), deactivate(), on_key_event(), on_pointer_event(), and preview().
on_key_event()
bool quader::tools::ITool::on_key_event (const KeyEvent & event, ToolContext & context) nodiscard virtual
Handle a key event.
Reimplemented in quader::tools::BoxTool.
Definition at line 32 of file tool.cpp.
Referenced by id().
on_pointer_event()
bool quader::tools::ITool::on_pointer_event (const PointerEvent & event, ToolContext & context) nodiscard virtual
Handle a pointer event.
Reimplemented in quader::tools::BoxTool.
Definition at line 26 of file tool.cpp.
Referenced by id().
preview()
ToolPreview quader::tools::ITool::preview () const nodiscard virtual
Return the current preview payload.
Reimplemented in quader::tools::BoxTool.
Definition at line 38 of file tool.cpp.
Referenced by id().
The documentation for this class was generated from the following files:
src/tools/tool.hpp
src/tools/tool.cpp