Quader: crimson::ScopedCpuTimer Class Reference
crimson::ScopedCpuTimer Class Reference final
RAII CPU timer that writes elapsed microseconds into a counter.
#include <frame_profiler.hpp>
Public Member Functions
ScopedCpuTimer (std::uint64_t &destination) noexcept
~ScopedCpuTimer ()
Stop the timer and write elapsed microseconds.
ScopedCpuTimer (const ScopedCpuTimer &)=delete
Timers cannot be copied because they own one timing scope.
ScopedCpuTimer & operator= (const ScopedCpuTimer &)=delete
Timers cannot be copied because they own one timing scope.
Detailed Description
RAII CPU timer that writes elapsed microseconds into a counter.
Definition at line 20 of file frame_profiler.hpp.
Constructor & Destructor Documentation
ScopedCpuTimer() [1/2]
crimson::ScopedCpuTimer::ScopedCpuTimer (std::uint64_t & destination) explicit noexcept
Start a timer.
Parameters
destination Counter that receives elapsed microseconds at destruction.
Definition at line 14 of file frame_profiler.cpp.
Referenced by operator=(), and ScopedCpuTimer().
~ScopedCpuTimer()
crimson::ScopedCpuTimer::~ScopedCpuTimer ()
Stop the timer and write elapsed microseconds.
Definition at line 19 of file frame_profiler.cpp.
ScopedCpuTimer() [2/2]
crimson::ScopedCpuTimer::ScopedCpuTimer (const ScopedCpuTimer &) delete
Timers cannot be copied because they own one timing scope.
References ScopedCpuTimer().
Member Function Documentation
operator=()
ScopedCpuTimer & crimson::ScopedCpuTimer::operator= (const ScopedCpuTimer &) delete
Timers cannot be copied because they own one timing scope.
References ScopedCpuTimer().
The documentation for this class was generated from the following files:
src/crimson/diagnostics/frame_profiler.hpp
src/crimson/diagnostics/frame_profiler.cpp