Quader: quader::ui::PanelHost Class Reference
quader::ui::PanelHost Class Reference final
Owns dock widgets and workspace persistence for application panels.
#include <panel_host.hpp>
Public Member Functions
PanelHost (QMainWindow &main_window, PanelContext context, QObject *parent=nullptr)
Construct a panel host for main_window.
QDockWidget & add_panel (PanelSpec spec, QWidget *panel_widget)
Add a panel widget wrapped in a dock widget.
QDockWidget * dock (PanelId id) const
Return the dock for id, or nullptr when not registered.
void show_panel (PanelId id)
Show a registered panel.
void hide_panel (PanelId id)
Hide a registered panel.
void bind_panel_visibility_action (PanelId panel, ActionRegistry &actions, ActionId action)
Bind a checkable action to one panel's visibility.
void save_workspace (SettingsService &settings) const
Save dock visibility and main-window workspace state.
void restore_workspace (SettingsService &settings)
Restore dock visibility and main-window workspace state.
void reset_to_default_layout ()
Reset all docks to their default areas and visibility.
Detailed Description
Owns dock widgets and workspace persistence for application panels.
Definition at line 42 of file panel_host.hpp.
Constructor & Destructor Documentation
PanelHost()
quader::ui::PanelHost::PanelHost (QMainWindow & main_window, PanelContext context, QObject * parent = nullptr) explicit
Construct a panel host for main_window.
Definition at line 23 of file panel_host.cpp.
Member Function Documentation
add_panel()
QDockWidget & quader::ui::PanelHost::add_panel (PanelSpec spec, QWidget * panel_widget)
Add a panel widget wrapped in a dock widget.
Definition at line 26 of file panel_host.cpp.
References quader::ui::PanelSpec::allowed_areas, quader::ui::PanelSpec::default_area, quader::ui::PanelSpec::default_visible, dock(), quader::ui::PanelSpec::id, quader::ui::panel_object_name(), QUADER_ASSERT, and quader::ui::PanelSpec::title.
bind_panel_visibility_action()
void quader::ui::PanelHost::bind_panel_visibility_action (PanelId panel, ActionRegistry & actions, ActionId action)
Bind a checkable action to one panel's visibility.
Definition at line 60 of file panel_host.cpp.
References quader::ui::ActionRegistry::action(), dock(), hide_panel(), QUADER_ASSERT, and show_panel().
dock()
QDockWidget * quader::ui::PanelHost::dock (PanelId id) const nodiscard
Return the dock for id, or nullptr when not registered.
Definition at line 42 of file panel_host.cpp.
Referenced by add_panel(), bind_panel_visibility_action(), hide_panel(), reset_to_default_layout(), and show_panel().
hide_panel()
void quader::ui::PanelHost::hide_panel (PanelId id)
Hide a registered panel.
Definition at line 54 of file panel_host.cpp.
References dock().
Referenced by bind_panel_visibility_action().
reset_to_default_layout()
void quader::ui::PanelHost::reset_to_default_layout ()
Reset all docks to their default areas and visibility.
Definition at line 110 of file panel_host.cpp.
References quader::ui::Diagnostics, dock(), quader::ui::Properties, and quader::ui::Scene.
restore_workspace()
void quader::ui::PanelHost::restore_workspace (SettingsService & settings)
Restore dock visibility and main-window workspace state.
Definition at line 93 of file panel_host.cpp.
References quader::ui::SettingsService::panel_visible().
save_workspace()
void quader::ui::PanelHost::save_workspace (SettingsService & settings) const
Save dock visibility and main-window workspace state.
Definition at line 85 of file panel_host.cpp.
References quader::ui::SettingsService::set_panel_visible().
show_panel()
void quader::ui::PanelHost::show_panel (PanelId id)
Show a registered panel.
Definition at line 47 of file panel_host.cpp.
References dock().
Referenced by bind_panel_visibility_action().
The documentation for this class was generated from the following files:
src/ui/panels/panel_host.hpp
src/ui/panels/panel_host.cpp