Quader: quader::ui::ViewportLayoutState Class Reference
quader::ui::ViewportLayoutState Class Reference final
Stores split fractions and derives viewport pane rectangles.
#include <viewport_layout_state.hpp>
Public Member Functions
ViewportLayoutMode mode () const noexcept
Return the active layout mode.
void set_mode (ViewportLayoutMode mode) noexcept
Set the active layout mode.
bool quad_enabled () const noexcept
Return true when quad layout is enabled.
void set_quad_enabled (bool enabled) noexcept
Enable or disable quad layout.
float vertical_split () const noexcept
Return vertical split fraction in [0, 1].
float horizontal_split () const noexcept
Return horizontal split fraction in [0, 1].
void set_vertical_split (float value) noexcept
Store a clamped vertical split fraction.
void set_horizontal_split (float value) noexcept
Store a clamped horizontal split fraction.
ViewportPaneArray panes_for (ViewportPixelSize size) const
Return pane rectangles for size.
int pane_count () const noexcept
Return active pane count.
int pane_at (ViewportPixelSize size, ViewportPoint point) const
Return the pane index under point, or -1 when none.
ViewportSplitHandle splitter_at (ViewportPixelSize size, ViewportPoint point) const
Return the splitter handle under point.
void set_split_from_position (ViewportPixelSize size, ViewportSplitHandle handle, ViewportPoint point) noexcept
Update split fraction from pointer position.
ViewportRect vertical_splitter_rect (ViewportPixelSize size) const noexcept
Return the vertical splitter rectangle.
ViewportRect horizontal_splitter_rect (ViewportPixelSize size) const noexcept
Return the horizontal splitter rectangle.
Detailed Description
Stores split fractions and derives viewport pane rectangles.
Definition at line 17 of file viewport_layout_state.hpp.
Member Function Documentation
horizontal_split()
float quader::ui::ViewportLayoutState::horizontal_split () const nodiscard noexcept
Return horizontal split fraction in [0, 1].
Definition at line 52 of file viewport_layout_state.cpp.
horizontal_splitter_rect()
ViewportRect quader::ui::ViewportLayoutState::horizontal_splitter_rect (ViewportPixelSize size) const nodiscard noexcept
Return the horizontal splitter rectangle.
Definition at line 157 of file viewport_layout_state.cpp.
mode()
ViewportLayoutMode quader::ui::ViewportLayoutState::mode () const nodiscard noexcept
Return the active layout mode.
Definition at line 32 of file viewport_layout_state.cpp.
Referenced by set_mode().
pane_at()
int quader::ui::ViewportLayoutState::pane_at (ViewportPixelSize size, ViewportPoint point) const nodiscard
Return the pane index under point, or -1 when none.
Definition at line 99 of file viewport_layout_state.cpp.
References quader::ui::ViewportRect::height, pane_count(), panes_for(), quader::ui::ViewportRect::width, quader::ui::ViewportPoint::x, quader::ui::ViewportRect::x, quader::ui::ViewportPoint::y, and quader::ui::ViewportRect::y.
pane_count()
int quader::ui::ViewportLayoutState::pane_count () const nodiscard noexcept
Return active pane count.
Definition at line 95 of file viewport_layout_state.cpp.
References quader::ui::pane_count_for_layout().
Referenced by pane_at().
panes_for()
ViewportPaneArray quader::ui::ViewportLayoutState::panes_for (ViewportPixelSize size) const nodiscard
Return pane rectangles for size.
Definition at line 64 of file viewport_layout_state.cpp.
References quader::ui::ViewportPixelSize::height, quader::ui::Quad, and quader::ui::ViewportPixelSize::width.
Referenced by pane_at().
quad_enabled()
bool quader::ui::ViewportLayoutState::quad_enabled () const nodiscard noexcept
Return true when quad layout is enabled.
Definition at line 40 of file viewport_layout_state.cpp.
References quader::ui::Quad.
set_horizontal_split()
void quader::ui::ViewportLayoutState::set_horizontal_split (float value) noexcept
Store a clamped horizontal split fraction.
Definition at line 60 of file viewport_layout_state.cpp.
set_mode()
void quader::ui::ViewportLayoutState::set_mode (ViewportLayoutMode mode) noexcept
Set the active layout mode.
Definition at line 36 of file viewport_layout_state.cpp.
References mode().
set_quad_enabled()
void quader::ui::ViewportLayoutState::set_quad_enabled (bool enabled) noexcept
Enable or disable quad layout.
Definition at line 44 of file viewport_layout_state.cpp.
References quader::ui::Quad, and quader::ui::Single.
set_split_from_position()
void quader::ui::ViewportLayoutState::set_split_from_position (ViewportPixelSize size, ViewportSplitHandle handle, ViewportPoint point) noexcept
Update split fraction from pointer position.
Definition at line 134 of file viewport_layout_state.cpp.
References quader::ui::Horizontal, and quader::ui::Vertical.
set_vertical_split()
void quader::ui::ViewportLayoutState::set_vertical_split (float value) noexcept
Store a clamped vertical split fraction.
Definition at line 56 of file viewport_layout_state.cpp.
splitter_at()
ViewportSplitHandle quader::ui::ViewportLayoutState::splitter_at (ViewportPixelSize size, ViewportPoint point) const nodiscard
Return the splitter handle under point.
Definition at line 111 of file viewport_layout_state.cpp.
References quader::ui::ViewportPixelSize::height, quader::ui::Horizontal, quader::ui::kViewportSplitterHitTolerance, quader::ui::None, quader::ui::Quad, quader::ui::Vertical, quader::ui::ViewportPixelSize::width, quader::ui::ViewportPoint::x, and quader::ui::ViewportPoint::y.
vertical_split()
float quader::ui::ViewportLayoutState::vertical_split () const nodiscard noexcept
Return vertical split fraction in [0, 1].
Definition at line 48 of file viewport_layout_state.cpp.
vertical_splitter_rect()
ViewportRect quader::ui::ViewportLayoutState::vertical_splitter_rect (ViewportPixelSize size) const nodiscard noexcept
Return the vertical splitter rectangle.
Definition at line 151 of file viewport_layout_state.cpp.
The documentation for this class was generated from the following files:
src/ui/viewport/viewport_layout_state.hpp
src/ui/viewport/viewport_layout_state.cpp