Quader: crimson::Renderer Class Reference
crimson::Renderer Class Reference final
#include <renderer.hpp>
Classes
struct Impl
Public Member Functions
~Renderer ()
Shut down the renderer and release GPU resources.
Renderer (const Renderer &)=delete
Renderers are move-blocked because the implementation owns native resources.
Renderer & operator= (const Renderer &)=delete
Renderers are move-blocked because the implementation owns native resources.
quader::foundation::Result< void, RendererDiagnostic > resize (const ViewportExtent &extent)
quader::foundation::Result< FrameRenderResult, RendererDiagnostic > render (const FrameSnapshot &snapshot)
RendererStatus status () const
std::optional< FrameStats > latest_frame_stats () const
RendererDiagnosticsSnapshot diagnostics_snapshot () const
std::string debug_dump_last_frame_graph () const
Static Public Member Functions
static quader::foundation::Result< std::unique_ptr< Renderer >, RendererDiagnostic > create (RendererConfig config, const NativeSurfaceDescriptor &surface)
Detailed Description
Public Crimson renderer facade.
The facade owns the GPU device implementation and consumes immutable frame snapshots. It does not own document or modeling state.
Definition at line 32 of file renderer.hpp.
Constructor & Destructor Documentation
~Renderer()
crimson::Renderer::~Renderer () default
Shut down the renderer and release GPU resources.
Renderer()
crimson::Renderer::Renderer (const Renderer &) delete
Renderers are move-blocked because the implementation owns native resources.
References Renderer().
Referenced by create(), operator=(), and Renderer().
Member Function Documentation
create()
quader::foundation::Result< std::unique_ptr< Renderer >, RendererDiagnostic > crimson::Renderer::create (RendererConfig config, const NativeSurfaceDescriptor & surface) static nodiscard
Create and initialize a renderer for a native surface.
Parameters
config Renderer startup configuration.
surface Native host surface descriptor.
Returns
Renderer instance, or a startup diagnostic.
Definition at line 81 of file renderer.cpp.
References crimson::RendererStatus::diagnostics, crimson::NativeSurfaceDescriptor::extent, crimson::Fatal, crimson::make_v1_correctness_render_graph(), Renderer(), and crimson::RuntimeInitializationFailed.
Referenced by quader::ui::CrimsonViewportRenderHost::initialize_surface().
debug_dump_last_frame_graph()
std::string crimson::Renderer::debug_dump_last_frame_graph () const nodiscard
Dump the latest frame graph for debugging.
Returns
Human-readable graph dump, or an empty string before rendering.
Definition at line 183 of file renderer.cpp.
diagnostics_snapshot()
RendererDiagnosticsSnapshot crimson::Renderer::diagnostics_snapshot () const nodiscard
Build a diagnostics snapshot for UI/test consumers.
Returns
Snapshot containing status, counters, recent diagnostics, and graph dump.
Definition at line 164 of file renderer.cpp.
References crimson::RendererDiagnosticsSnapshot::counters, crimson::RendererDiagnosticsSnapshot::frame_graph_dump, crimson::RendererDiagnosticsSnapshot::latest_frame_stats, crimson::make_bounded_renderer_status_snapshot(), crimson::make_diagnostic_ring_from_recent(), crimson::make_render_pass_stats(), crimson::make_renderer_counters(), crimson::RendererDiagnosticsSnapshot::pass_stats, crimson::RendererDiagnosticsSnapshot::recent_diagnostics, crimson::DiagnosticRing::snapshot(), status(), and crimson::RendererDiagnosticsSnapshot::status.
latest_frame_stats()
std::optional< FrameStats > crimson::Renderer::latest_frame_stats () const nodiscard
Return stats for the latest rendered frame.
Returns
Frame stats, or empty when no frame has completed.
Definition at line 160 of file renderer.cpp.
operator=()
Renderer & crimson::Renderer::operator= (const Renderer &) delete
Renderers are move-blocked because the implementation owns native resources.
References Renderer().
render()
quader::foundation::Result< FrameRenderResult, RendererDiagnostic > crimson::Renderer::render (const FrameSnapshot & snapshot) nodiscard
Render one immutable frame snapshot.
Parameters
snapshot Frame data consumed by the renderer.
Returns
Frame result, or a renderer diagnostic.
Definition at line 134 of file renderer.cpp.
References quader::foundation::Result< T, E >::failure(), resize(), and crimson::FrameSnapshot::target_extent().
resize()
quader::foundation::Result< void, RendererDiagnostic > crimson::Renderer::resize (const ViewportExtent & extent) nodiscard
Resize the renderer's target extent.
Parameters
extent New viewport extent.
Returns
Success, or a resize diagnostic.
Definition at line 109 of file renderer.cpp.
References crimson::ViewportExtent::device_pixel_ratio, crimson::RendererStatus::diagnostics, crimson::Error, quader::foundation::Result< T, E >::failure(), crimson::ViewportExtent::height_px, crimson::ResizeFailed, quader::foundation::Result< T, E >::success(), and crimson::ViewportExtent::width_px.
Referenced by render().
status()
RendererStatus crimson::Renderer::status () const nodiscard
Return renderer status by value.
Returns
Current status snapshot.
Definition at line 156 of file renderer.cpp.
Referenced by diagnostics_snapshot().
The documentation for this class was generated from the following files:
src/crimson/renderer.hpp
src/crimson/renderer.cpp