Quader: crimson::PickingIdAllocator Class Reference
crimson::PickingIdAllocator Class Reference final
#include <picking.hpp>
Public Member Functions
PickingIdAllocator (PickingRequestId request_id=0)
Construct an allocator for a request id.
void begin_request (PickingRequestId request_id)
Clear payload storage and begin a new request.
PickingRequestId request_id () const noexcept
Return the request id associated with current allocations.
std::uint32_t allocate (PickingPayload payload)
Store a payload and return its non-zero raw id.
std::optional< PickingPayload > resolve (std::uint32_t raw_id) const
Resolve a raw id, returning empty for zero or out-of-range ids.
std::span< const PickingPayload > payloads () const noexcept
Borrow allocated payloads until the allocator is reset or destroyed.
Detailed Description
Allocates per-frame raw picking ids and resolves them back to payloads.
Raw id zero is reserved for "no hit"; allocated ids are one-based indexes into payload storage.
Definition at line 90 of file picking.hpp.
Constructor & Destructor Documentation
PickingIdAllocator()
crimson::PickingIdAllocator::PickingIdAllocator (PickingRequestId request_id = 0) explicit
Construct an allocator for a request id.
Definition at line 44 of file picking.cpp.
References request_id().
Member Function Documentation
allocate()
std::uint32_t crimson::PickingIdAllocator::allocate (PickingPayload payload) nodiscard
Store a payload and return its non-zero raw id.
Definition at line 56 of file picking.cpp.
begin_request()
void crimson::PickingIdAllocator::begin_request (PickingRequestId request_id)
Clear payload storage and begin a new request.
Definition at line 47 of file picking.cpp.
References request_id().
payloads()
std::span< const PickingPayload > crimson::PickingIdAllocator::payloads () const nodiscard noexcept
Borrow allocated payloads until the allocator is reset or destroyed.
Definition at line 73 of file picking.cpp.
request_id()
PickingRequestId crimson::PickingIdAllocator::request_id () const nodiscard noexcept
Return the request id associated with current allocations.
Definition at line 52 of file picking.cpp.
Referenced by begin_request(), and PickingIdAllocator().
resolve()
std::optional< PickingPayload > crimson::PickingIdAllocator::resolve (std::uint32_t raw_id) const nodiscard
Resolve a raw id, returning empty for zero or out-of-range ids.
Definition at line 65 of file picking.cpp.
The documentation for this class was generated from the following files:
src/crimson/picking/picking.hpp
src/crimson/picking/picking.cpp