Quader: quader::foundation::Result< T, E > Class Template Reference
quader::foundation::Result< T, E > Class Template Reference final
#include <result.hpp>
Public Member Functions
bool has_value () const noexcept
operator bool () const noexcept
T & value () &
const T & value () const &
T && value () &&
E & error () &
const E & error () const &
E && error () &&
Static Public Member Functions
static Result success (T value)
static Result failure (E error)
Detailed Description
template<class T, class E>
class quader::foundation::Result< T, E >
Tagged success-or-error result for operations with a value payload.
Result stores either a T success value or an E error value. Calling value() or error() for the inactive state is a programmer error and is checked with QUADER_ASSERT.
Template Parameters
T Success value type.
E Error value type.
Definition at line 31 of file result.hpp.
Member Function Documentation
error() [1/3]
template<class T, class E> E & quader::foundation::Result< T, E >::error () & inline nodiscard
Access the error value.
Returns
Mutable reference to the stored error.
Definition at line 114 of file result.hpp.
References QUADER_ASSERT.
Referenced by failure().
error() [2/3]
template<class T, class E> E && quader::foundation::Result< T, E >::error () && inline nodiscard
Move the error value out of the result.
Returns
Rvalue reference to the stored error.
Definition at line 136 of file result.hpp.
References QUADER_ASSERT.
error() [3/3]
template<class T, class E> const E & quader::foundation::Result< T, E >::error () const & inline nodiscard
Access the error value.
Returns
Immutable reference to the stored error.
Definition at line 125 of file result.hpp.
References QUADER_ASSERT.
failure()
template<class T, class E> Result quader::foundation::Result< T, E >::failure (E error) inline static nodiscard
Create a failed result.
Parameters
error Error stored in the failure state.
Returns
Result containing error.
Definition at line 54 of file result.hpp.
References error().
Referenced by crimson::RenderResourceRegistry::add(), crimson::MaterialSystem::bind_texture(), quader::io::build_document_from_import(), crimson::FrameBuilder::build_prototype_snapshot(), quader::mesh::Polyhedron::compact_storage(), quader::mesh::MeshAttributes::create(), crimson::MaterialSystem::create_default_material(), quader::mesh::Polyhedron::create_face(), crimson::MaterialSystem::create_material(), quader::document::Document::create_mesh_object(), quader::mesh::Polyhedron::delete_face(), quader::document::Document::delete_object(), quader::mesh::Polyhedron::delete_vertex(), quader::io::ExportService::export_file(), quader::mesh::Polyhedron::halfedge_edge(), quader::mesh::Polyhedron::halfedge_face(), quader::mesh::Polyhedron::halfedge_origin(), quader::mesh::Polyhedron::halfedge_target(), quader::io::ImportService::import_file(), quader::mesh::Polyhedron::is_boundary_halfedge(), quader::mesh::ops::make_box_from_bounds(), quader::mesh::ops::make_box_from_corners(), quader::io::gltf::map_gltf_material_to_crimson(), quader::mesh::Polyhedron::next_halfedge(), quader::mesh::Polyhedron::opposite_halfedge(), quader::mesh::Polyhedron::previous_halfedge(), crimson::RenderMeshUploadTracker::process_uploads(), quader::io::ImportExportRegistry::register_exporter(), quader::io::ImportExportRegistry::register_importer(), quader::document::ObjectStore::remove_mesh_object(), quader::document::Document::rename_object(), crimson::Renderer::render(), crimson::gpu::GpuDevice::render_frame(), crimson::Renderer::resize(), quader::document::ObjectStore::restore_mesh_object(), quader::document::Selection::set_components(), quader::document::Selection::set_objects(), crimson::MaterialSystem::set_parameter(), quader::document::Document::set_transform(), quader::mesh::Polyhedron::set_vertex_position(), crimson::RenderGraph::validate(), quader::document::Document::validate_component_ref(), crimson::validate_material_instance(), quader::document::Document::validate_object_id(), crimson::validate_render_mesh_upload_desc(), quader::mesh::MeshAttributes::value(), quader::mesh::MeshAttributes::value(), quader::mesh::Polyhedron::vertex_attribute(), quader::mesh::Polyhedron::vertex_attribute(), quader::mesh::Polyhedron::vertex_outgoing_halfedge(), and quader::mesh::Polyhedron::vertex_position().
has_value()
template<class T, class E> bool quader::foundation::Result< T, E >::has_value () const inline nodiscard noexcept
Check whether this result is successful.
Returns
True when a T value is active.
Definition at line 63 of file result.hpp.
Referenced by operator bool(), quader::foundation::Result< void, E >::operator bool(), and quader::foundation::Result< void, E >::value().
operator bool()
template<class T, class E> quader::foundation::Result< T, E >::operator bool () const inline explicit nodiscard noexcept
Check whether this result is successful.
Returns
True when a T value is active.
Definition at line 72 of file result.hpp.
References has_value().
success()
template<class T, class E> Result quader::foundation::Result< T, E >::success (T value) inline static nodiscard
Create a successful result.
Parameters
value Value stored in the success state.
Returns
Result containing value.
Definition at line 44 of file result.hpp.
References value().
Referenced by crimson::RenderResourceRegistry::add(), crimson::MaterialSystem::bind_texture(), quader::io::build_document_from_import(), crimson::FrameBuilder::build_prototype_snapshot(), quader::mesh::Polyhedron::compact_storage(), quader::mesh::MeshAttributes::create(), quader::mesh::Polyhedron::create_face(), crimson::MaterialSystem::create_material(), quader::document::ObjectStore::create_mesh_object(), quader::mesh::Polyhedron::delete_face(), quader::document::Document::delete_object(), quader::mesh::Polyhedron::delete_vertex(), quader::mesh::Polyhedron::halfedge_edge(), quader::mesh::Polyhedron::halfedge_face(), quader::mesh::Polyhedron::halfedge_origin(), quader::mesh::Polyhedron::halfedge_target(), quader::io::ImportService::import_file(), quader::mesh::Polyhedron::is_boundary_halfedge(), quader::mesh::ops::make_box_from_corners(), quader::io::gltf::map_gltf_material_to_crimson(), quader::document::Document::mark_mesh_geometry_changed(), quader::document::Document::mark_mesh_topology_changed(), quader::mesh::Polyhedron::next_halfedge(), quader::mesh::Polyhedron::opposite_halfedge(), quader::mesh::Polyhedron::previous_halfedge(), crimson::RenderMeshUploadTracker::process_uploads(), quader::io::ImportExportRegistry::register_exporter(), quader::io::ImportExportRegistry::register_importer(), quader::document::ObjectStore::remove_mesh_object(), quader::document::Document::rename_object(), crimson::gpu::GpuDevice::render_frame(), crimson::Renderer::resize(), quader::document::Document::restore_mesh_object(), quader::document::ObjectStore::restore_mesh_object(), quader::document::Selection::set_components(), quader::document::Selection::set_objects(), crimson::MaterialSystem::set_parameter(), quader::document::Document::set_selection(), quader::document::Document::set_transform(), quader::mesh::Polyhedron::set_vertex_position(), crimson::RenderGraph::validate(), quader::document::Document::validate_component_ref(), crimson::validate_material_instance(), quader::document::Document::validate_object_id(), crimson::validate_render_mesh_upload_desc(), quader::mesh::MeshAttributes::value(), quader::mesh::MeshAttributes::value(), quader::mesh::Polyhedron::vertex_outgoing_halfedge(), and quader::mesh::Polyhedron::vertex_position().
value() [1/3]
template<class T, class E> T & quader::foundation::Result< T, E >::value () & inline nodiscard
Access the success value.
Returns
Mutable reference to the stored value.
Definition at line 81 of file result.hpp.
References QUADER_ASSERT.
Referenced by success().
value() [2/3]
template<class T, class E> T && quader::foundation::Result< T, E >::value () && inline nodiscard
Move the success value out of the result.
Returns
Rvalue reference to the stored value.
Definition at line 103 of file result.hpp.
References QUADER_ASSERT.
value() [3/3]
template<class T, class E> const T & quader::foundation::Result< T, E >::value () const & inline nodiscard
Access the success value.
Returns
Immutable reference to the stored value.
Definition at line 92 of file result.hpp.
References QUADER_ASSERT.
The documentation for this class was generated from the following file:
src/foundation/result.hpp