Quader: quader::foundation::Result< void, E > Class Template Reference
quader::foundation::Result< void, E > Class Template Reference final
#include <result.hpp>
Public Member Functions
bool has_value () const noexcept
operator bool () const noexcept
void value () const
Assert that this result is successful.
E & error () &
const E & error () const &
E && error () &&
Static Public Member Functions
static Result success ()
static Result failure (E error)
Detailed Description
template<class E>
class quader::foundation::Result< void, E >
Tagged success-or-error result for operations with no success payload.
Template Parameters
E Error value type.
Definition at line 166 of file result.hpp.
Member Function Documentation
error() [1/3]
template<class E> E & quader::foundation::Result< void, E >::error () & inline nodiscard
Access the error value.
Returns
Mutable reference to the stored error.
Definition at line 218 of file result.hpp.
References QUADER_ASSERT.
Referenced by failure().
error() [2/3]
template<class E> E && quader::foundation::Result< void, E >::error () && inline nodiscard
Move the error value out of the result.
Returns
Rvalue reference to the stored error.
Definition at line 240 of file result.hpp.
References QUADER_ASSERT.
error() [3/3]
template<class E> const E & quader::foundation::Result< void, E >::error () const & inline nodiscard
Access the error value.
Returns
Immutable reference to the stored error.
Definition at line 229 of file result.hpp.
References QUADER_ASSERT.
failure()
template<class E> Result quader::foundation::Result< void, E >::failure (E error) inline static nodiscard
Create a failed void result.
Parameters
error Error stored in the failure state.
Returns
Result containing error.
Definition at line 186 of file result.hpp.
References error().
has_value()
template<class E> bool quader::foundation::Result< void, E >::has_value () const inline nodiscard noexcept
Check whether this result is successful.
Returns
True when the success state is active.
Definition at line 195 of file result.hpp.
operator bool()
template<class E> quader::foundation::Result< void, E >::operator bool () const inline explicit nodiscard noexcept
Check whether this result is successful.
Returns
True when the success state is active.
Definition at line 204 of file result.hpp.
References quader::foundation::Result< T, E >::has_value().
success()
template<class E> Result quader::foundation::Result< void, E >::success () inline static nodiscard
Create a successful void result.
Returns
Result in the success state.
Definition at line 176 of file result.hpp.
value()
template<class E> void quader::foundation::Result< void, E >::value () const inline
Assert that this result is successful.
Definition at line 209 of file result.hpp.
References quader::foundation::Result< T, E >::has_value(), and QUADER_ASSERT.
The documentation for this class was generated from the following file:
src/foundation/result.hpp