Quader: quader::io::ExportService Class Reference
quader::io::ExportService Class Reference final
Service that selects an exporter from the registry and runs it.
#include <export_service.hpp>
Public Member Functions
ExportService (const ImportExportRegistry &registry)
quader::foundation::Result< ExportResult, IoError > export_file (const ExportRequest &request) const
Detailed Description
Service that selects an exporter from the registry and runs it.
Definition at line 20 of file export_service.hpp.
Constructor & Destructor Documentation
ExportService()
quader::io::ExportService::ExportService (const ImportExportRegistry & registry) explicit
Create an export service over a registry.
Parameters
registry Registry borrowed for the service lifetime.
Definition at line 16 of file export_service.cpp.
Member Function Documentation
export_file()
quader::foundation::Result< ExportResult, IoError > quader::io::ExportService::export_file (const ExportRequest & request) const nodiscard
Export a document using the exporter matching the request path.
Parameters
request Export request and borrowed document.
Returns
Export result, or an I/O error when no exporter can handle it.
Definition at line 19 of file export_service.cpp.
References quader::io::IExporter::export_file(), quader::io::ExportNotSupported, quader::foundation::Result< T, E >::failure(), quader::io::make_io_error(), quader::io::ExportRequest::path, quader::io::path_extension_without_dot(), and quader::io::UnsupportedFormat.
The documentation for this class was generated from the following files:
src/io/export_service.hpp
src/io/export_service.cpp