Quader: quader::ui::ActionRegistry Class Reference
quader::ui::ActionRegistry Class Reference final
#include <action_registry.hpp>
Signals
void action_triggered (quader::ui::ActionId id)
void action_toggled (quader::ui::ActionId id, bool checked)
Public Member Functions
ActionRegistry (QObject *parent=nullptr)
Construct an empty registry.
QAction & register_action (ActionId id, const ActionSpec &spec)
QAction & action (ActionId id) const
Return a registered action; callers must only request known ids.
bool contains (ActionId id) const noexcept
Return true when id has a registered action.
std::size_t size () const noexcept
Return the number of registered actions.
Detailed Description
Owns canonical QAction instances indexed by stable action id.
Actions are parent-owned by the registry. Menus, toolbars, and shortcuts borrow the same instances to keep enabled/checked state synchronized.
Definition at line 46 of file action_registry.hpp.
Constructor & Destructor Documentation
ActionRegistry()
quader::ui::ActionRegistry::ActionRegistry (QObject * parent = nullptr) explicit
Construct an empty registry.
Definition at line 20 of file action_registry.cpp.
Member Function Documentation
action()
QAction & quader::ui::ActionRegistry::action (ActionId id) const nodiscard
Return a registered action; callers must only request known ids.
Definition at line 47 of file action_registry.cpp.
References QUADER_ASSERT.
Referenced by quader::ui::PanelHost::bind_panel_visibility_action(), and register_action().
action_toggled
void quader::ui::ActionRegistry::action_toggled (quader::ui::ActionId id, bool checked) signal
Referenced by quader::ui::EditorActionController::EditorActionController(), and register_action().
action_triggered
void quader::ui::ActionRegistry::action_triggered (quader::ui::ActionId id) signal
Referenced by quader::ui::EditorActionController::EditorActionController(), and register_action().
contains()
bool quader::ui::ActionRegistry::contains (ActionId id) const nodiscard noexcept
Return true when id has a registered action.
Definition at line 53 of file action_registry.cpp.
register_action()
QAction & quader::ui::ActionRegistry::register_action (ActionId id, const ActionSpec & spec)
Register or replace an action for an id.
Parameters
id Stable action id.
spec Action metadata.
Returns
Registered action owned by this registry.
Definition at line 23 of file action_registry.cpp.
References action(), action_toggled(), action_triggered(), quader::ui::ActionSpec::checkable, quader::ui::ActionSpec::initially_enabled, quader::ui::ActionSpec::menu_role, quader::ui::ActionSpec::shortcut, quader::ui::ActionSpec::status_tip, and quader::ui::ActionSpec::text.
Referenced by quader::ui::register_standard_actions().
size()
std::size_t quader::ui::ActionRegistry::size () const nodiscard noexcept
Return the number of registered actions.
Definition at line 57 of file action_registry.cpp.
The documentation for this class was generated from the following files:
src/ui/actions/action_registry.hpp
src/ui/actions/action_registry.cpp