Quader: quader::commands::SetObjectTransformCommand Class Reference
quader::commands::SetObjectTransformCommand Class Reference final
Undoable command that replaces one object's transform.
#include <document_commands.hpp>
Public Member Functions
SetObjectTransformCommand (quader::document::ObjectId object, quader::document::Transform transform)
Construct a transform command for object.
std::string_view name () const noexcept override
Return the command display name.
CommandResult execute (quader::document::Document &document) override
Apply the new transform and capture the previous transform.
CommandResult undo (quader::document::Document &document) override
Restore the previous transform.
Public Member Functions inherited from quader::commands::ICommand
virtual ~ICommand ()=default
Destroy a command through the base interface.
virtual bool can_merge_with (const ICommand &next) const noexcept
virtual CommandResult merge_with (std::unique_ptr< ICommand > next)
Detailed Description
Undoable command that replaces one object's transform.
Definition at line 104 of file document_commands.hpp.
Constructor & Destructor Documentation
SetObjectTransformCommand()
quader::commands::SetObjectTransformCommand::SetObjectTransformCommand (quader::document::ObjectId object, quader::document::Transform transform)
Construct a transform command for object.
Definition at line 167 of file document_commands.cpp.
Member Function Documentation
execute()
CommandResult quader::commands::SetObjectTransformCommand::execute (quader::document::Document & document) nodiscard override virtual
Apply the new transform and capture the previous transform.
Implements quader::commands::ICommand.
Definition at line 176 of file document_commands.cpp.
References quader::commands::CommandResult::applied(), and quader::commands::CommandResult::rejected().
name()
std::string_view quader::commands::SetObjectTransformCommand::name () const nodiscard override virtual noexcept
Return the command display name.
Implements quader::commands::ICommand.
Definition at line 172 of file document_commands.cpp.
undo()
CommandResult quader::commands::SetObjectTransformCommand::undo (quader::document::Document & document) nodiscard override virtual
Restore the previous transform.
Implements quader::commands::ICommand.
Definition at line 196 of file document_commands.cpp.
References quader::commands::CommandResult::applied(), and quader::commands::CommandResult::rejected().
The documentation for this class was generated from the following files:
src/commands/document_commands.hpp
src/commands/document_commands.cpp