Quader: crimson::RenderMeshUploadTracker Class Reference
crimson::RenderMeshUploadTracker Class Reference final
Tracks uploaded render mesh revisions and upload counters.
#include <render_mesh_upload.hpp>
Public Member Functions
quader::foundation::Result< FrameUploadStats, RendererDiagnostic > process_uploads (std::span< const RenderMeshUploadDesc > uploads)
bool destroy (RenderMeshHandle handle) noexcept
std::size_t live_record_count () const noexcept
const RenderMeshUploadRecord * find (RenderMeshHandle handle) const noexcept
void clear () noexcept
Remove all tracked upload records.
Detailed Description
Tracks uploaded render mesh revisions and upload counters.
Definition at line 32 of file render_mesh_upload.hpp.
Member Function Documentation
clear()
void crimson::RenderMeshUploadTracker::clear () noexcept
Remove all tracked upload records.
Definition at line 141 of file render_mesh_upload.cpp.
destroy()
bool crimson::RenderMeshUploadTracker::destroy (RenderMeshHandle handle) nodiscard noexcept
Destroy a tracked upload record.
Parameters
handle Render mesh handle to remove.
Returns
True when a record was removed.
Definition at line 119 of file render_mesh_upload.cpp.
find()
const RenderMeshUploadRecord * crimson::RenderMeshUploadTracker::find (RenderMeshHandle handle) const nodiscard noexcept
Find a tracked upload record.
Parameters
handle Render mesh handle to resolve.
Returns
Borrowed record, or nullptr when absent.
Definition at line 134 of file render_mesh_upload.cpp.
live_record_count()
std::size_t crimson::RenderMeshUploadTracker::live_record_count () const nodiscard noexcept
Return the number of live tracked records.
Returns
Live record count.
Definition at line 130 of file render_mesh_upload.cpp.
process_uploads()
quader::foundation::Result< FrameUploadStats, RendererDiagnostic > crimson::RenderMeshUploadTracker::process_uploads (std::span< const RenderMeshUploadDesc > uploads) nodiscard
Validate/process upload descriptors and update tracked records.
Parameters
uploads Upload descriptors borrowed for this call.
Returns
Frame upload counters, or a renderer diagnostic.
Definition at line 82 of file render_mesh_upload.cpp.
References quader::foundation::Result< T, E >::failure(), crimson::RenderMeshUploadRecord::index_bytes, crimson::FrameUploadStats::mesh_create_count, crimson::FrameUploadStats::mesh_update_count, crimson::FrameUploadStats::skipped_clean_resource_count, quader::foundation::Result< T, E >::success(), crimson::FrameUploadStats::uploaded_index_bytes, crimson::RenderMeshUploadRecord::uploaded_revision, crimson::FrameUploadStats::uploaded_vertex_bytes, crimson::validate_render_mesh_upload_desc(), and crimson::RenderMeshUploadRecord::vertex_bytes.
Referenced by quader::benchmarks::run_crimson_upload_benchmark().
The documentation for this class was generated from the following files:
src/crimson/mesh/render_mesh_upload.hpp
src/crimson/mesh/render_mesh_upload.cpp