Quader: quader::ui::PropertyItemModel Class Reference
quader::ui::PropertyItemModel Class Reference final
Qt table model exposing editable document property descriptors.
#include <property_item_model.hpp>
Public Slots
void rebuild_from_document ()
Rebuild descriptors from the current document state.
void refresh_object (quader::document::ObjectId object)
Refresh descriptor rows associated with object.
Public Member Functions
PropertyItemModel (DocumentUiController &documents, QObject *parent=nullptr)
Construct a property model backed by document UI services.
int rowCount (const QModelIndex &parent={}) const override
Return property row count.
int columnCount (const QModelIndex &parent={}) const override
Return property column count.
QVariant data (const QModelIndex &index, int role) const override
Return data for a property cell.
bool setData (const QModelIndex &index, const QVariant &value, int role) override
Apply editable property changes through document commands.
Qt::ItemFlags flags (const QModelIndex &index) const override
Return item flags for a property cell.
QVariant headerData (int section, Qt::Orientation orientation, int role) const override
Return horizontal header text.
Detailed Description
Qt table model exposing editable document property descriptors.
Definition at line 32 of file property_item_model.hpp.
Constructor & Destructor Documentation
PropertyItemModel()
quader::ui::PropertyItemModel::PropertyItemModel (DocumentUiController & documents, QObject * parent = nullptr) explicit
Construct a property model backed by document UI services.
Definition at line 104 of file property_item_model.cpp.
References quader::ui::DocumentUiController::object_changed(), quader::ui::DocumentUiController::object_list_changed(), rebuild_from_document(), refresh_object(), quader::ui::register_ui_model_metatypes(), and quader::ui::DocumentUiController::selection_changed().
Member Function Documentation
columnCount()
int quader::ui::PropertyItemModel::columnCount (const QModelIndex & parent = {}) const nodiscard override
Return property column count.
Definition at line 126 of file property_item_model.cpp.
data()
QVariant quader::ui::PropertyItemModel::data (const QModelIndex & index, int role) const nodiscard override
Return data for a property cell.
Definition at line 131 of file property_item_model.cpp.
References quader::ui::property_item_roles::kDescriptorRole, quader::ui::property_item_roles::kEditableRole, quader::ui::property_item_roles::kPropertyPathRole, and quader::ui::property_item_roles::kValueKindRole.
flags()
Qt::ItemFlags quader::ui::PropertyItemModel::flags (const QModelIndex & index) const nodiscard override
Return item flags for a property cell.
Definition at line 182 of file property_item_model.cpp.
headerData()
QVariant quader::ui::PropertyItemModel::headerData (int section, Qt::Orientation orientation, int role) const nodiscard override
Return horizontal header text.
Definition at line 197 of file property_item_model.cpp.
References quader::ui::Label, and quader::ui::Value.
rebuild_from_document
void quader::ui::PropertyItemModel::rebuild_from_document () slot
Rebuild descriptors from the current document state.
Definition at line 214 of file property_item_model.cpp.
References quader::ui::build_property_descriptors().
Referenced by PropertyItemModel(), and refresh_object().
refresh_object
void quader::ui::PropertyItemModel::refresh_object (quader::document::ObjectId object) slot
Refresh descriptor rows associated with object.
Definition at line 220 of file property_item_model.cpp.
References rebuild_from_document().
Referenced by PropertyItemModel().
rowCount()
int quader::ui::PropertyItemModel::rowCount (const QModelIndex & parent = {}) const nodiscard override
Return property row count.
Definition at line 118 of file property_item_model.cpp.
setData()
bool quader::ui::PropertyItemModel::setData (const QModelIndex & index, const QVariant & value, int role) nodiscard override
Apply editable property changes through document commands.
Definition at line 167 of file property_item_model.cpp.
The documentation for this class was generated from the following files:
src/ui/models/property_item_model.hpp
src/ui/models/property_item_model.cpp