Quader: quader::document::ObjectStore Class Reference
quader::document::ObjectStore Class Reference final
#include <object_store.hpp>
Public Member Functions
quader::foundation::Result< ObjectId, DocumentError > create_mesh_object (std::string name, quader::mesh::Polyhedron mesh, Transform transform, PbrMaterial material)
quader::foundation::Result< void, DocumentError > restore_mesh_object (MeshObject object)
quader::foundation::Result< MeshObject, DocumentError > remove_mesh_object (ObjectId id)
MeshObject * find_mesh_object (ObjectId id) noexcept
Return a mutable object pointer, or nullptr for invalid or stale ids.
const MeshObject * find_mesh_object (ObjectId id) const noexcept
Return a const object pointer, or nullptr for invalid or stale ids.
bool contains (ObjectId id) const noexcept
Return true when id resolves to a live object.
std::vector< ObjectId > object_ids () const
Return ids for all live objects in slot order.
std::size_t size () const noexcept
Return the number of live objects.
Detailed Description
Owns mesh object slots and stable object id generation.
Removed slots are reused with incremented generations so stale ObjectId values stop resolving after deletion.
Definition at line 28 of file object_store.hpp.
Member Function Documentation
contains()
bool quader::document::ObjectStore::contains (ObjectId id) const nodiscard noexcept
Return true when id resolves to a live object.
Definition at line 111 of file object_store.cpp.
References find_mesh_object().
create_mesh_object()
quader::foundation::Result< ObjectId, DocumentError > quader::document::ObjectStore::create_mesh_object (std::string name, quader::mesh::Polyhedron mesh, Transform transform, PbrMaterial material) nodiscard
Create a mesh object in a live slot.
Parameters
name Object name to store.
mesh Mesh payload to move into the object.
transform Object transform.
material Object material.
Returns
New object id, or an object-store error.
Definition at line 17 of file object_store.cpp.
References quader::foundation::Result< T, E >::success().
find_mesh_object() [1/2]
const MeshObject * quader::document::ObjectStore::find_mesh_object (ObjectId id) const nodiscard noexcept
Return a const object pointer, or nullptr for invalid or stale ids.
Definition at line 98 of file object_store.cpp.
References quader::document::is_valid().
find_mesh_object() [2/2]
MeshObject * quader::document::ObjectStore::find_mesh_object (ObjectId id) nodiscard noexcept
Return a mutable object pointer, or nullptr for invalid or stale ids.
Definition at line 85 of file object_store.cpp.
References quader::document::is_valid().
Referenced by contains(), and remove_mesh_object().
object_ids()
std::vector< ObjectId > quader::document::ObjectStore::object_ids () const nodiscard
Return ids for all live objects in slot order.
Definition at line 115 of file object_store.cpp.
References size().
remove_mesh_object()
quader::foundation::Result< MeshObject, DocumentError > quader::document::ObjectStore::remove_mesh_object (ObjectId id) nodiscard
Remove a mesh object and return its owned payload.
Parameters
id Live object id to remove.
Returns
Removed object, or InvalidObject when id is not live.
Definition at line 67 of file object_store.cpp.
References quader::foundation::Result< T, E >::failure(), find_mesh_object(), quader::document::InvalidObject, quader::document::make_document_error(), and quader::foundation::Result< T, E >::success().
restore_mesh_object()
quader::foundation::Result< void, DocumentError > quader::document::ObjectStore::restore_mesh_object (MeshObject object) nodiscard
Restore a previously removed mesh object into its original slot.
Parameters
object Object snapshot with a valid, currently free id.
Returns
Success, or an error when the slot is unavailable.
Definition at line 38 of file object_store.cpp.
References quader::foundation::Result< T, E >::failure(), quader::document::InvalidObject, quader::document::is_valid(), quader::document::make_document_error(), quader::document::ObjectAlreadyExists, and quader::foundation::Result< T, E >::success().
size()
std::size_t quader::document::ObjectStore::size () const nodiscard noexcept
Return the number of live objects.
Definition at line 129 of file object_store.cpp.
Referenced by object_ids().
The documentation for this class was generated from the following files:
src/document/object_store.hpp
src/document/object_store.cpp