Quader: crimson::gpu::GpuOverlayRenderer Class Reference
crimson::gpu::GpuOverlayRenderer Class Reference final
Owns GPU state needed to submit unlit overlay grid and line primitives.
#include <gpu_overlay_renderer.hpp>
Classes
struct Impl
Public Member Functions
GpuOverlayRenderer ()
Construct an empty overlay renderer.
~GpuOverlayRenderer ()
Release GPU resources.
GpuOverlayRenderer (const GpuOverlayRenderer &)=delete
Copying is disabled because the implementation owns GPU handles.
GpuOverlayRenderer & operator= (const GpuOverlayRenderer &)=delete
Copying is disabled because the implementation owns GPU handles.
bool initialize (RendererStatus &status)
Initialize GPU overlay resources and append diagnostics on failure.
void shutdown () noexcept
Release all owned GPU overlay resources.
bool ready () const noexcept
Return true after successful initialization and before shutdown.
std::uint32_t submit_grid (bgfx::ViewId view_id, const RenderView &view, const PreparedGridOverlayCommand &grid, bgfx::ProgramHandle program) const noexcept
Submit one prepared grid overlay command.
std::uint32_t submit_lines (bgfx::ViewId view_id, const PreparedLineOverlayCommand &lines, bgfx::ProgramHandle program) const noexcept
Submit one prepared line overlay command.
Detailed Description
Owns GPU state needed to submit unlit overlay grid and line primitives.
Definition at line 25 of file gpu_overlay_renderer.hpp.
Constructor & Destructor Documentation
GpuOverlayRenderer() [1/2]
crimson::gpu::GpuOverlayRenderer::GpuOverlayRenderer ()
Construct an empty overlay renderer.
Definition at line 85 of file gpu_overlay_renderer.cpp.
Referenced by GpuOverlayRenderer(), and operator=().
~GpuOverlayRenderer()
crimson::gpu::GpuOverlayRenderer::~GpuOverlayRenderer () default
Release GPU resources.
GpuOverlayRenderer() [2/2]
crimson::gpu::GpuOverlayRenderer::GpuOverlayRenderer (const GpuOverlayRenderer &) delete
Copying is disabled because the implementation owns GPU handles.
References GpuOverlayRenderer().
Member Function Documentation
initialize()
bool crimson::gpu::GpuOverlayRenderer::initialize (RendererStatus & status) nodiscard
Initialize GPU overlay resources and append diagnostics on failure.
Definition at line 90 of file gpu_overlay_renderer.cpp.
References shutdown().
operator=()
GpuOverlayRenderer & crimson::gpu::GpuOverlayRenderer::operator= (const GpuOverlayRenderer &) delete
Copying is disabled because the implementation owns GPU handles.
References GpuOverlayRenderer(), ready(), submit_grid(), and submit_lines().
ready()
bool crimson::gpu::GpuOverlayRenderer::ready () const nodiscard noexcept
Return true after successful initialization and before shutdown.
Definition at line 146 of file gpu_overlay_renderer.cpp.
Referenced by operator=().
shutdown()
void crimson::gpu::GpuOverlayRenderer::shutdown () noexcept
Release all owned GPU overlay resources.
Definition at line 128 of file gpu_overlay_renderer.cpp.
Referenced by initialize().
submit_grid()
std::uint32_t crimson::gpu::GpuOverlayRenderer::submit_grid (bgfx::ViewId view_id, const RenderView & view, const PreparedGridOverlayCommand & grid, bgfx::ProgramHandle program) const nodiscard noexcept
Submit one prepared grid overlay command.
Definition at line 150 of file gpu_overlay_renderer.cpp.
References crimson::GridOverlayCommand::axis_line_scale, crimson::GridOverlayCommand::edge_softness_m, crimson::GridOverlayCommand::fade_end_m, crimson::GridOverlayCommand::fade_start_m, crimson::GridOverlayCommand::major_line_scale, crimson::GridOverlayCommand::major_spacing_m, crimson::GridOverlayCommand::minor_line_scale, crimson::GridOverlayCommand::minor_spacing_m, crimson::GridOverlayCommand::origin, crimson::GridOverlayCommand::orthographic_height_m, crimson::GridOverlayCommand::plane_height, crimson::GridOverlayCommand::plane_width, crimson::GridOverlayCommand::rotation_x, crimson::GridOverlayCommand::rotation_y, crimson::GridOverlayCommand::rotation_z, crimson::GridOverlayCommand::u_axis, crimson::GridOverlayCommand::v_axis, crimson::GridOverlayCommand::viewport_height_px, quader::math::Vec3::x, quader::math::Vec3::y, and quader::math::Vec3::z.
Referenced by operator=().
submit_lines()
std::uint32_t crimson::gpu::GpuOverlayRenderer::submit_lines (bgfx::ViewId view_id, const PreparedLineOverlayCommand & lines, bgfx::ProgramHandle program) const nodiscard noexcept
Submit one prepared line overlay command.
Definition at line 215 of file gpu_overlay_renderer.cpp.
References crimson::DepthTested, crimson::LineOverlaySegment::end, crimson::LineOverlaySegment::start, quader::math::Vec3::x, crimson::XRay, quader::math::Vec3::y, and quader::math::Vec3::z.
Referenced by operator=().
The documentation for this class was generated from the following files:
src/crimson/gpu/gpu_overlay_renderer.hpp
src/crimson/gpu/gpu_overlay_renderer.cpp