Quader: quader::ui::ViewportCameraController Class Reference
quader::ui::ViewportCameraController Class Reference final
Manages perspective and orthographic viewport cameras and navigation input.
#include <viewport_camera_controller.hpp>
Public Member Functions
ViewportCameraController ()
Construct default cameras.
void reset_default_cameras ()
Reset all cameras to default perspective/top/front/right states.
const ViewportCameraState & camera (int camera_index) const
Return camera state by index.
CameraProjection camera_projection (int camera_index) const
Return projection mode for a camera.
NavigationMode navigation_mode () const noexcept
Return current navigation mode.
int active_camera_index () const noexcept
Return active camera index.
void set_active_camera_index (int camera_index) noexcept
Set active camera index, clamped to supported cameras.
bool begin_navigation (int camera_index, NavigationMode mode, ViewportPoint position)
Begin a navigation gesture for a camera.
void update_navigation (ViewportPoint position, ViewportPixelSize viewport_size)
Update the active navigation gesture.
void end_navigation ()
End the active navigation gesture.
void set_navigation_anchor (ViewportPoint position) noexcept
Reset the navigation anchor without changing mode.
void apply_wheel_zoom (int camera_index, float wheel_steps, ViewportPixelSize viewport_size)
Apply wheel zoom to a camera.
void adjust_fly_speed (float wheel_steps) noexcept
Adjust fly-navigation speed.
void set_fly_key (ViewportFlyKey key, bool pressed) noexcept
Set pressed state for one fly key.
void clear_fly_keys () noexcept
Clear all fly-key pressed states.
void tick_fly_navigation (float delta_seconds)
Advance fly navigation by elapsed time.
ViewportCameraPose camera_pose (int camera_index) const
Return the derived camera pose by index.
ViewportCameraSnapshotArray camera_snapshots () const
Return render-facing snapshots for all supported cameras.
Detailed Description
Manages perspective and orthographic viewport cameras and navigation input.
Definition at line 71 of file viewport_camera_controller.hpp.
Constructor & Destructor Documentation
ViewportCameraController()
quader::ui::ViewportCameraController::ViewportCameraController ()
Construct default cameras.
Definition at line 303 of file viewport_camera_controller.cpp.
References reset_default_cameras().
Member Function Documentation
active_camera_index()
int quader::ui::ViewportCameraController::active_camera_index () const nodiscard noexcept
Return active camera index.
Definition at line 361 of file viewport_camera_controller.cpp.
adjust_fly_speed()
void quader::ui::ViewportCameraController::adjust_fly_speed (float wheel_steps) noexcept
Adjust fly-navigation speed.
Definition at line 495 of file viewport_camera_controller.cpp.
apply_wheel_zoom()
void quader::ui::ViewportCameraController::apply_wheel_zoom (int camera_index, float wheel_steps, ViewportPixelSize viewport_size)
Apply wheel zoom to a camera.
Definition at line 473 of file viewport_camera_controller.cpp.
References camera(), camera_pose(), quader::ui::Orthographic, and set_active_camera_index().
begin_navigation()
bool quader::ui::ViewportCameraController::begin_navigation (int camera_index, NavigationMode mode, ViewportPoint position) nodiscard
Begin a navigation gesture for a camera.
Definition at line 369 of file viewport_camera_controller.cpp.
References camera(), quader::ui::Fly, quader::ui::Orbit, quader::ui::Perspective, and set_active_camera_index().
camera()
const ViewportCameraState & quader::ui::ViewportCameraController::camera (int camera_index) const nodiscard
Return camera state by index.
Definition at line 349 of file viewport_camera_controller.cpp.
Referenced by apply_wheel_zoom(), begin_navigation(), camera_pose(), camera_projection(), camera_snapshots(), reset_default_cameras(), tick_fly_navigation(), and update_navigation().
camera_pose()
ViewportCameraPose quader::ui::ViewportCameraController::camera_pose (int camera_index) const nodiscard
Return the derived camera pose by index.
Definition at line 561 of file viewport_camera_controller.cpp.
References camera(), quader::ui::dot(), quader::ui::length(), quader::ui::normalized(), and quader::ui::Orthographic.
Referenced by apply_wheel_zoom(), camera_snapshots(), tick_fly_navigation(), and update_navigation().
camera_projection()
CameraProjection quader::ui::ViewportCameraController::camera_projection (int camera_index) const nodiscard
Return projection mode for a camera.
Definition at line 353 of file viewport_camera_controller.cpp.
References camera(), and quader::ui::ViewportCameraState::projection.
camera_snapshots()
ViewportCameraSnapshotArray quader::ui::ViewportCameraController::camera_snapshots () const nodiscard
Return render-facing snapshots for all supported cameras.
Definition at line 586 of file viewport_camera_controller.cpp.
References camera(), camera_pose(), quader::ui::ViewportCameraPose::eye, quader::ui::ViewportCameraPose::forward, quader::ui::ViewportCameraState::fov_degrees, quader::ui::ViewportCameraState::orthographic_size, quader::ui::ViewportCameraState::projection, quader::ui::ViewportCameraPose::target, and quader::ui::ViewportCameraPose::up.
clear_fly_keys()
void quader::ui::ViewportCameraController::clear_fly_keys () noexcept
Clear all fly-key pressed states.
Definition at line 516 of file viewport_camera_controller.cpp.
Referenced by end_navigation().
end_navigation()
void quader::ui::ViewportCameraController::end_navigation ()
End the active navigation gesture.
Definition at line 464 of file viewport_camera_controller.cpp.
References clear_fly_keys(), and quader::ui::None.
navigation_mode()
NavigationMode quader::ui::ViewportCameraController::navigation_mode () const nodiscard noexcept
Return current navigation mode.
Definition at line 357 of file viewport_camera_controller.cpp.
reset_default_cameras()
void quader::ui::ViewportCameraController::reset_default_cameras ()
Reset all cameras to default perspective/top/front/right states.
Definition at line 307 of file viewport_camera_controller.cpp.
References camera(), quader::ui::Orthographic, and quader::ui::Perspective.
Referenced by ViewportCameraController().
set_active_camera_index()
void quader::ui::ViewportCameraController::set_active_camera_index (int camera_index) noexcept
Set active camera index, clamped to supported cameras.
Definition at line 365 of file viewport_camera_controller.cpp.
Referenced by apply_wheel_zoom(), and begin_navigation().
set_fly_key()
void quader::ui::ViewportCameraController::set_fly_key (ViewportFlyKey key, bool pressed) noexcept
Set pressed state for one fly key.
Definition at line 499 of file viewport_camera_controller.cpp.
References quader::ui::Backward, quader::ui::Forward, quader::ui::Left, and quader::ui::Right.
set_navigation_anchor()
void quader::ui::ViewportCameraController::set_navigation_anchor (ViewportPoint position) noexcept
Reset the navigation anchor without changing mode.
Definition at line 469 of file viewport_camera_controller.cpp.
tick_fly_navigation()
void quader::ui::ViewportCameraController::tick_fly_navigation (float delta_seconds)
Advance fly navigation by elapsed time.
Definition at line 523 of file viewport_camera_controller.cpp.
References camera(), camera_pose(), quader::ui::Fly, quader::ui::length(), quader::ui::normalized(), quader::ui::Vec3::x, quader::ui::Vec3::y, and quader::ui::Vec3::z.
update_navigation()
void quader::ui::ViewportCameraController::update_navigation (ViewportPoint position, ViewportPixelSize viewport_size)
Update the active navigation gesture.
Definition at line 392 of file viewport_camera_controller.cpp.
References camera(), camera_pose(), quader::ui::Fly, quader::ui::ViewportPixelSize::height, quader::ui::length(), quader::ui::None, quader::ui::normalized(), quader::ui::Orbit, quader::ui::Orthographic, quader::ui::Pan, quader::ui::Perspective, quader::ui::ViewportPoint::x, and quader::ui::ViewportPoint::y.
The documentation for this class was generated from the following files:
src/ui/viewport/viewport_camera_controller.hpp
src/ui/viewport/viewport_camera_controller.cpp