Quader: quader::ui::ViewportController Class Reference
quader::ui::ViewportController Class Reference final
Coordinates viewport layout, navigation, tool input, and render-host calls.
#include <viewport_controller.hpp>
Signals
void renderer_ready (QString renderer_name)
Emitted after the renderer reports readiness.
void viewport_layout_changed (bool quad_enabled, QString layout_name)
Emitted when viewport layout mode changes.
void frame_stats_changed (quader::ui::ViewportFrameStats stats)
Emitted after frame stats change.
void render_error (QString summary, QString detail)
Emitted when render-host calls fail.
void frame_requested ()
Emitted when another frame should be scheduled.
Public Member Functions
ViewportController (IViewportRenderHost &render_host, QObject *parent=nullptr)
Construct a viewport controller without tool dispatch.
ViewportController (IViewportRenderHost &render_host, quader::tools::ToolManager &tool_manager, QObject *parent=nullptr)
Construct a viewport controller with tool dispatch.
~ViewportController () override=default
Destroy the controller; the render host remains externally owned.
bool surface_initialized () const noexcept
Return true when the render surface is initialized.
NavigationMode navigation_mode () const noexcept
Return current viewport navigation mode.
void initialize_surface (const NativeViewportSurface &surface, ViewportPixelSize size, double device_pixel_ratio)
Initialize the render surface and request a frame on success.
void resize_surface (ViewportPixelSize size, double device_pixel_ratio)
Resize the render surface.
void shutdown_surface ()
Shut down the render surface if initialized.
void set_quad_viewports_enabled (bool enabled)
Enable or disable quad viewport layout.
bool quad_viewports_enabled () const noexcept
Return true when quad viewport layout is active.
void set_prototype_animation_enabled (bool enabled)
Enable or disable prototype animation in render requests.
bool prototype_animation_enabled () const noexcept
Return true when prototype animation is enabled.
void render_frame (double elapsed_seconds, float delta_seconds)
Submit one frame to the render host.
void request_frame ()
Request that the viewport widget schedules another frame.
ViewportLayoutState & layout_state () noexcept
Return mutable layout state.
const ViewportLayoutState & layout_state () const noexcept
Return immutable layout state.
const ViewportCameraController & camera_controller () const noexcept
Return immutable camera controller state.
bool handle_mouse_press (ViewportMouseButton button, ViewportPoint point, bool shift_modifier, ViewportPixelSize size)
Handle a mouse press and dispatch navigation/tool input.
bool handle_mouse_move (ViewportPoint point, ViewportPixelSize size)
Handle a mouse move and dispatch navigation/tool input.
bool handle_mouse_release (ViewportMouseButton button, ViewportPoint point, ViewportPixelSize size)
Handle a mouse release and dispatch navigation/tool input.
void handle_wheel (float wheel_steps, ViewportPoint point, ViewportPixelSize size)
Handle wheel input for zoom/fly speed.
bool handle_key (ViewportKey key, bool pressed, bool auto_repeat)
Handle key input for navigation and tools.
Detailed Description
Coordinates viewport layout, navigation, tool input, and render-host calls.
Definition at line 34 of file viewport_controller.hpp.
Constructor & Destructor Documentation
ViewportController() [1/2]
quader::ui::ViewportController::ViewportController (IViewportRenderHost & render_host, QObject * parent = nullptr) explicit
Construct a viewport controller without tool dispatch.
Definition at line 144 of file viewport_controller.cpp.
ViewportController() [2/2]
quader::ui::ViewportController::ViewportController (IViewportRenderHost & render_host, quader::tools::ToolManager & tool_manager, QObject * parent = nullptr)
Construct a viewport controller with tool dispatch.
Definition at line 147 of file viewport_controller.cpp.
~ViewportController()
quader::ui::ViewportController::~ViewportController () override default
Destroy the controller; the render host remains externally owned.
References camera_controller(), handle_key(), handle_mouse_move(), handle_mouse_press(), handle_mouse_release(), handle_wheel(), initialize_surface(), layout_state(), navigation_mode(), prototype_animation_enabled(), quad_viewports_enabled(), render_frame(), request_frame(), resize_surface(), set_prototype_animation_enabled(), set_quad_viewports_enabled(), and shutdown_surface().
Member Function Documentation
camera_controller()
const ViewportCameraController & quader::ui::ViewportController::camera_controller () const nodiscard noexcept
Return immutable camera controller state.
Definition at line 280 of file viewport_controller.cpp.
Referenced by ~ViewportController().
frame_requested
void quader::ui::ViewportController::frame_requested () signal
Emitted when another frame should be scheduled.
References frame_requested().
Referenced by frame_requested(), request_frame(), and quader::ui::ViewportWidget::ViewportWidget().
frame_stats_changed
void quader::ui::ViewportController::frame_stats_changed (quader::ui::ViewportFrameStats stats) signal
Emitted after frame stats change.
References frame_stats_changed().
Referenced by frame_stats_changed(), and render_frame().
handle_key()
bool quader::ui::ViewportController::handle_key (ViewportKey key, bool pressed, bool auto_repeat) nodiscard
Handle key input for navigation and tools.
Definition at line 366 of file viewport_controller.cpp.
References quader::ui::A, quader::ui::Backward, quader::ui::D, quader::ui::Escape, quader::ui::Fly, quader::ui::Forward, quader::ui::Left, quader::ui::Other, request_frame(), quader::ui::Right, quader::ui::S, and quader::ui::W.
Referenced by ~ViewportController().
handle_mouse_move()
bool quader::ui::ViewportController::handle_mouse_move (ViewportPoint point, ViewportPixelSize size) nodiscard
Handle a mouse move and dispatch navigation/tool input.
Definition at line 318 of file viewport_controller.cpp.
References quader::tools::Move, quader::ui::None, quader::ui::Other, and request_frame().
Referenced by ~ViewportController().
handle_mouse_press()
bool quader::ui::ViewportController::handle_mouse_press (ViewportMouseButton button, ViewportPoint point, bool shift_modifier, ViewportPixelSize size) nodiscard
Handle a mouse press and dispatch navigation/tool input.
Definition at line 284 of file viewport_controller.cpp.
References quader::ui::Fly, quader::ui::Left, quader::ui::Middle, quader::ui::Orbit, quader::ui::Orthographic, quader::ui::Pan, quader::tools::Press, request_frame(), and quader::ui::Right.
Referenced by ~ViewportController().
handle_mouse_release()
bool quader::ui::ViewportController::handle_mouse_release (ViewportMouseButton button, ViewportPoint point, ViewportPixelSize size) nodiscard
Handle a mouse release and dispatch navigation/tool input.
Definition at line 333 of file viewport_controller.cpp.
References quader::ui::Left, quader::ui::None, quader::tools::Release, and request_frame().
Referenced by ~ViewportController().
handle_wheel()
void quader::ui::ViewportController::handle_wheel (float wheel_steps, ViewportPoint point, ViewportPixelSize size)
Handle wheel input for zoom/fly speed.
Definition at line 349 of file viewport_controller.cpp.
References quader::ui::Fly, and request_frame().
Referenced by ~ViewportController().
initialize_surface()
void quader::ui::ViewportController::initialize_surface (const NativeViewportSurface & surface, ViewportPixelSize size, double device_pixel_ratio)
Initialize the render surface and request a frame on success.
Definition at line 162 of file viewport_controller.cpp.
References quader::ui::ViewportRenderResult::ok, quader::ui::ViewportRenderResult::renderer_name, renderer_ready(), and request_frame().
Referenced by ~ViewportController().
layout_state() [1/2]
const ViewportLayoutState & quader::ui::ViewportController::layout_state () const nodiscard noexcept
Return immutable layout state.
Definition at line 276 of file viewport_controller.cpp.
layout_state() [2/2]
ViewportLayoutState & quader::ui::ViewportController::layout_state () nodiscard noexcept
Return mutable layout state.
Definition at line 272 of file viewport_controller.cpp.
Referenced by ~ViewportController().
navigation_mode()
NavigationMode quader::ui::ViewportController::navigation_mode () const nodiscard noexcept
Return current viewport navigation mode.
Definition at line 158 of file viewport_controller.cpp.
Referenced by ~ViewportController().
prototype_animation_enabled()
bool quader::ui::ViewportController::prototype_animation_enabled () const nodiscard noexcept
Return true when prototype animation is enabled.
Definition at line 233 of file viewport_controller.cpp.
Referenced by ~ViewportController().
quad_viewports_enabled()
bool quader::ui::ViewportController::quad_viewports_enabled () const nodiscard noexcept
Return true when quad viewport layout is active.
Definition at line 220 of file viewport_controller.cpp.
Referenced by ~ViewportController().
render_error
void quader::ui::ViewportController::render_error (QString summary, QString detail) signal
Emitted when render-host calls fail.
References render_error().
Referenced by render_error().
render_frame()
void quader::ui::ViewportController::render_frame (double elapsed_seconds, float delta_seconds)
Submit one frame to the render host.
Definition at line 237 of file viewport_controller.cpp.
References frame_stats_changed(), and quader::ui::ViewportRenderResult::ok.
Referenced by ~ViewportController().
renderer_ready
void quader::ui::ViewportController::renderer_ready (QString renderer_name) signal
Emitted after the renderer reports readiness.
References renderer_ready().
Referenced by initialize_surface(), and renderer_ready().
request_frame()
void quader::ui::ViewportController::request_frame ()
Request that the viewport widget schedules another frame.
Definition at line 268 of file viewport_controller.cpp.
References frame_requested().
Referenced by handle_key(), handle_mouse_move(), handle_mouse_press(), handle_mouse_release(), handle_wheel(), initialize_surface(), resize_surface(), set_prototype_animation_enabled(), set_quad_viewports_enabled(), and ~ViewportController().
resize_surface()
void quader::ui::ViewportController::resize_surface (ViewportPixelSize size, double device_pixel_ratio)
Resize the render surface.
Definition at line 184 of file viewport_controller.cpp.
References quader::ui::ViewportRenderResult::ok, and request_frame().
Referenced by ~ViewportController().
set_prototype_animation_enabled()
void quader::ui::ViewportController::set_prototype_animation_enabled (bool enabled)
Enable or disable prototype animation in render requests.
Definition at line 224 of file viewport_controller.cpp.
References request_frame().
Referenced by ~ViewportController().
set_quad_viewports_enabled()
void quader::ui::ViewportController::set_quad_viewports_enabled (bool enabled)
Enable or disable quad viewport layout.
Definition at line 208 of file viewport_controller.cpp.
References request_frame(), and viewport_layout_changed().
Referenced by ~ViewportController().
shutdown_surface()
void quader::ui::ViewportController::shutdown_surface ()
Shut down the render surface if initialized.
Definition at line 199 of file viewport_controller.cpp.
Referenced by ~ViewportController().
surface_initialized()
bool quader::ui::ViewportController::surface_initialized () const nodiscard noexcept
Return true when the render surface is initialized.
Definition at line 154 of file viewport_controller.cpp.
viewport_layout_changed
void quader::ui::ViewportController::viewport_layout_changed (bool quad_enabled, QString layout_name) signal
Emitted when viewport layout mode changes.
References viewport_layout_changed().
Referenced by set_quad_viewports_enabled(), viewport_layout_changed(), and quader::ui::ViewportWidget::ViewportWidget().
The documentation for this class was generated from the following files:
src/ui/viewport/viewport_controller.hpp
src/ui/viewport/viewport_controller.cpp