Quader: quader::ui::DiagnosticsItemModel Class Reference
quader::ui::DiagnosticsItemModel Class Reference final
Qt tree model presenting the latest viewport diagnostics snapshot.
#include <diagnostics_item_model.hpp>
Public Slots
void reload_from_service ()
Rebuild rows from the attached diagnostics service.
Public Member Functions
DiagnosticsItemModel (ViewportDiagnosticsService &diagnostics, QObject *parent=nullptr)
Construct a diagnostics model backed by a diagnostics service.
QModelIndex index (int row, int column, const QModelIndex &parent={}) const override
Return a model index for a diagnostics row.
QModelIndex parent (const QModelIndex &child) const override
Return the parent index for child.
int rowCount (const QModelIndex &parent={}) const override
Return row count for parent.
int columnCount (const QModelIndex &parent={}) const override
Return column count for parent.
QVariant data (const QModelIndex &index, int role) const override
Return diagnostics data for index and role.
Qt::ItemFlags flags (const QModelIndex &index) const override
Return item flags for diagnostics rows.
QVariant headerData (int section, Qt::Orientation orientation, int role) const override
Return horizontal header text.
QString copy_text_for_index (const QModelIndex &index) const
Return copy-ready text for one index.
QString copy_text_for_all () const
Return copy-ready text for all rows.
Detailed Description
Qt tree model presenting the latest viewport diagnostics snapshot.
Definition at line 58 of file diagnostics_item_model.hpp.
Constructor & Destructor Documentation
DiagnosticsItemModel()
quader::ui::DiagnosticsItemModel::DiagnosticsItemModel (ViewportDiagnosticsService & diagnostics, QObject * parent = nullptr) explicit
Construct a diagnostics model backed by a diagnostics service.
Definition at line 76 of file diagnostics_item_model.cpp.
References quader::ui::ViewportDiagnosticsService::diagnostics_changed(), quader::ui::ViewportDiagnosticsService::diagnostics_unavailable(), parent(), quader::ui::register_ui_model_metatypes(), and reload_from_service().
Member Function Documentation
columnCount()
int quader::ui::DiagnosticsItemModel::columnCount (const QModelIndex & parent = {}) const nodiscard override
Return column count for parent.
Definition at line 129 of file diagnostics_item_model.cpp.
Referenced by index().
copy_text_for_all()
QString quader::ui::DiagnosticsItemModel::copy_text_for_all () const nodiscard
Return copy-ready text for all rows.
Definition at line 200 of file diagnostics_item_model.cpp.
copy_text_for_index()
QString quader::ui::DiagnosticsItemModel::copy_text_for_index (const QModelIndex & index) const nodiscard
Return copy-ready text for one index.
Definition at line 195 of file diagnostics_item_model.cpp.
data()
QVariant quader::ui::DiagnosticsItemModel::data (const QModelIndex & index, int role) const nodiscard override
Return diagnostics data for index and role.
Definition at line 134 of file diagnostics_item_model.cpp.
References quader::ui::diagnostics_item_roles::kCategoryRole, quader::ui::diagnostics_item_roles::kCopyTextRole, quader::ui::diagnostics_item_roles::kFrameIndexRole, quader::ui::diagnostics_item_roles::kNodeKindRole, quader::ui::diagnostics_item_roles::kSeverityRole, and quader::ui::Section.
flags()
Qt::ItemFlags quader::ui::DiagnosticsItemModel::flags (const QModelIndex & index) const nodiscard override
Return item flags for diagnostics rows.
Definition at line 169 of file diagnostics_item_model.cpp.
headerData()
QVariant quader::ui::DiagnosticsItemModel::headerData (int section, Qt::Orientation orientation, int role) const nodiscard override
Return horizontal header text.
Definition at line 177 of file diagnostics_item_model.cpp.
References quader::ui::Detail, quader::ui::Name, and quader::ui::Value.
index()
QModelIndex quader::ui::DiagnosticsItemModel::index (int row, int column, const QModelIndex & parent = {}) const nodiscard override
Return a model index for a diagnostics row.
Definition at line 85 of file diagnostics_item_model.cpp.
References columnCount().
parent()
QModelIndex quader::ui::DiagnosticsItemModel::parent (const QModelIndex & child) const nodiscard override
Return the parent index for child.
Definition at line 103 of file diagnostics_item_model.cpp.
Referenced by DiagnosticsItemModel().
reload_from_service
void quader::ui::DiagnosticsItemModel::reload_from_service () slot
Rebuild rows from the attached diagnostics service.
Definition at line 208 of file diagnostics_item_model.cpp.
Referenced by DiagnosticsItemModel().
rowCount()
int quader::ui::DiagnosticsItemModel::rowCount (const QModelIndex & parent = {}) const nodiscard override
Return row count for parent.
Definition at line 117 of file diagnostics_item_model.cpp.
The documentation for this class was generated from the following files:
src/ui/models/diagnostics_item_model.hpp
src/ui/models/diagnostics_item_model.cpp