Quader: crimson::FrameSnapshot Class Reference
crimson::FrameSnapshot Class Reference final
#include <frame_snapshot.hpp>
Public Member Functions
FrameSnapshot (std::uint64_t frame_index, double elapsed_seconds, ViewportExtent target_extent, std::vector< RenderView > views, std::vector< RenderMeshUpload > mesh_uploads, std::vector< RenderObject > objects, std::vector< RenderLight > lights, RenderEnvironment environment, std::vector< OverlayCommand > overlays, std::vector< GridOverlayCommand > grid_overlay_payloads, std::vector< LineOverlaySegment > line_overlay_payloads, std::vector< PickingRequest > picking_requests, ViewportSettings viewport_settings, DebugViewMode debug_view=DebugViewMode::FinalColor)
Construct a snapshot by taking ownership of all frame payloads.
std::uint64_t frame_index () const noexcept
Monotonic frame index supplied by the caller.
double elapsed_seconds () const noexcept
Elapsed application time in seconds.
ViewportExtent target_extent () const noexcept
Render target extent for the frame.
std::span< const RenderView > views () const noexcept
Borrow render views owned by this snapshot.
std::span< const RenderMeshUpload > mesh_uploads () const noexcept
Borrow mesh uploads owned by this snapshot.
std::span< const RenderObject > objects () const noexcept
Borrow render objects owned by this snapshot.
std::span< const RenderLight > lights () const noexcept
Borrow render lights owned by this snapshot.
const RenderEnvironment & environment () const noexcept
Return the frame environment.
std::span< const OverlayCommand > overlays () const noexcept
Borrow overlay command records owned by this snapshot.
std::span< const GridOverlayCommand > grid_overlay_payloads () const noexcept
Borrow grid overlay payloads owned by this snapshot.
std::span< const LineOverlaySegment > line_overlay_payloads () const noexcept
Borrow line overlay payloads owned by this snapshot.
std::span< const PickingRequest > picking_requests () const noexcept
Borrow picking requests owned by this snapshot.
ViewportSettings viewport_settings () const noexcept
Return viewport render settings.
DebugViewMode debug_view () const noexcept
Return the requested debug view mode.
Detailed Description
Immutable renderer input for one frame.
The snapshot owns all spans returned by accessors. It is CPU-side frame data; GPU resource ownership remains in the renderer GPU layer.
Definition at line 65 of file frame_snapshot.hpp.
Constructor & Destructor Documentation
FrameSnapshot()
crimson::FrameSnapshot::FrameSnapshot (std::uint64_t frame_index, double elapsed_seconds, ViewportExtent target_extent, std::vector< RenderView > views, std::vector< RenderMeshUpload > mesh_uploads, std::vector< RenderObject > objects, std::vector< RenderLight > lights, RenderEnvironment environment, std::vector< OverlayCommand > overlays, std::vector< GridOverlayCommand > grid_overlay_payloads, std::vector< LineOverlaySegment > line_overlay_payloads, std::vector< PickingRequest > picking_requests, ViewportSettings viewport_settings, DebugViewMode debug_view = DebugViewMode::FinalColor)
Construct a snapshot by taking ownership of all frame payloads.
Definition at line 16 of file frame_snapshot.cpp.
References debug_view(), elapsed_seconds(), environment(), frame_index(), grid_overlay_payloads(), lights(), line_overlay_payloads(), mesh_uploads(), objects(), overlays(), picking_requests(), target_extent(), viewport_settings(), and views().
Member Function Documentation
debug_view()
DebugViewMode crimson::FrameSnapshot::debug_view () const nodiscard noexcept
Return the requested debug view mode.
Definition at line 98 of file frame_snapshot.cpp.
Referenced by FrameSnapshot().
elapsed_seconds()
double crimson::FrameSnapshot::elapsed_seconds () const nodiscard noexcept
Elapsed application time in seconds.
Definition at line 50 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), and crimson::gpu::GpuDevice::render_frame().
environment()
const RenderEnvironment & crimson::FrameSnapshot::environment () const nodiscard noexcept
Return the frame environment.
Definition at line 74 of file frame_snapshot.cpp.
Referenced by FrameSnapshot().
frame_index()
std::uint64_t crimson::FrameSnapshot::frame_index () const nodiscard noexcept
Monotonic frame index supplied by the caller.
Definition at line 46 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), and crimson::gpu::GpuDevice::render_frame().
grid_overlay_payloads()
std::span< const GridOverlayCommand > crimson::FrameSnapshot::grid_overlay_payloads () const nodiscard noexcept
Borrow grid overlay payloads owned by this snapshot.
Definition at line 82 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), and crimson::gpu::GpuDevice::render_frame().
lights()
std::span< const RenderLight > crimson::FrameSnapshot::lights () const nodiscard noexcept
Borrow render lights owned by this snapshot.
Definition at line 70 of file frame_snapshot.cpp.
Referenced by FrameSnapshot().
line_overlay_payloads()
std::span< const LineOverlaySegment > crimson::FrameSnapshot::line_overlay_payloads () const nodiscard noexcept
Borrow line overlay payloads owned by this snapshot.
Definition at line 86 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), and crimson::gpu::GpuDevice::render_frame().
mesh_uploads()
std::span< const RenderMeshUpload > crimson::FrameSnapshot::mesh_uploads () const nodiscard noexcept
Borrow mesh uploads owned by this snapshot.
Definition at line 62 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), and crimson::gpu::GpuDevice::render_frame().
objects()
std::span< const RenderObject > crimson::FrameSnapshot::objects () const nodiscard noexcept
Borrow render objects owned by this snapshot.
Definition at line 66 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), crimson::gpu::GpuDevice::render_frame(), and crimson::gpu::GpuPicking::submit_frame_requests().
overlays()
std::span< const OverlayCommand > crimson::FrameSnapshot::overlays () const nodiscard noexcept
Borrow overlay command records owned by this snapshot.
Definition at line 78 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), and crimson::gpu::GpuDevice::render_frame().
picking_requests()
std::span< const PickingRequest > crimson::FrameSnapshot::picking_requests () const nodiscard noexcept
Borrow picking requests owned by this snapshot.
Definition at line 90 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), crimson::gpu::GpuDevice::render_frame(), and crimson::gpu::GpuPicking::submit_frame_requests().
target_extent()
ViewportExtent crimson::FrameSnapshot::target_extent () const nodiscard noexcept
Render target extent for the frame.
Definition at line 54 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), crimson::Renderer::render(), and crimson::gpu::GpuDevice::render_frame().
viewport_settings()
ViewportSettings crimson::FrameSnapshot::viewport_settings () const nodiscard noexcept
Return viewport render settings.
Definition at line 94 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), and crimson::gpu::GpuDevice::render_frame().
views()
std::span< const RenderView > crimson::FrameSnapshot::views () const nodiscard noexcept
Borrow render views owned by this snapshot.
Definition at line 58 of file frame_snapshot.cpp.
Referenced by FrameSnapshot(), crimson::gpu::GpuDevice::render_frame(), and crimson::gpu::GpuPicking::submit_frame_requests().
The documentation for this class was generated from the following files:
src/crimson/frame/frame_snapshot.hpp
src/crimson/frame/frame_snapshot.cpp