Quader: crimson::FrameBuilder Class Reference
crimson::FrameBuilder Class Reference final
Builds immutable frame snapshots from viewport-facing input data.
#include <frame_builder.hpp>
Public Member Functions
quader::foundation::Result< FrameSnapshot, RendererDiagnostic > build_prototype_snapshot (const PrototypeViewportFrame &frame) const
Detailed Description
Builds immutable frame snapshots from viewport-facing input data.
Definition at line 21 of file frame_builder.hpp.
Member Function Documentation
build_prototype_snapshot()
quader::foundation::Result< FrameSnapshot, RendererDiagnostic > crimson::FrameBuilder::build_prototype_snapshot (const PrototypeViewportFrame & frame) const nodiscard
Build a renderer snapshot from a prototype viewport frame.
Parameters
frame Viewport frame data to validate and copy.
Returns
Snapshot ready for Crimson submission, or a renderer diagnostic.
Definition at line 54 of file frame_builder.cpp.
References crimson::PrototypeViewportView::camera_index, crimson::PrototypeViewportFrame::cameras, crimson::PrototypeViewportView::debug_name, crimson::PrototypeViewportFrame::elapsed_seconds, crimson::ViewportSettings::exposure_ev100, quader::foundation::Result< T, E >::failure(), crimson::FinalColor, crimson::PrototypeViewportRect::height, crimson::is_valid_extent(), crimson::is_valid_prototype_view(), crimson::PrototypeViewportFrame::line_overlay_payloads, crimson::make_grid_overlay_command(), crimson::make_grid_overlay_for_view(), crimson::PrototypeViewportFrame::mesh_uploads, crimson::PrototypeViewportFrame::objects, crimson::PrototypeViewportFrame::overlays, crimson::PrototypeViewportFrame::picking_requests, crimson::PrototypeViewportView::rect, quader::foundation::Result< T, E >::success(), crimson::PrototypeViewportFrame::target_extent, crimson::PrototypeViewportFrame::views, crimson::PrototypeViewportRect::width, crimson::PrototypeViewportRect::x, and crimson::PrototypeViewportRect::y.
Referenced by quader::ui::CrimsonViewportRenderHost::render_frame().
The documentation for this class was generated from the following files:
src/crimson/frame/frame_builder.hpp
src/crimson/frame/frame_builder.cpp