Quader: crimson::RenderResourceRegistry Class Reference
crimson::RenderResourceRegistry Class Reference final
Owns render graph resource records and resize generations.
#include <render_resource_registry.hpp>
Public Member Functions
quader::foundation::Result< void, std::string > add (RenderResourceDesc desc)
const RenderResourceRecord * find (std::string_view name) const noexcept
RenderResourceRecord * find (std::string_view name) noexcept
std::span< const RenderResourceRecord > resources () const noexcept
std::uint64_t resize_generation () const noexcept
void resize (ViewportExtent extent)
void clear () noexcept
Remove all resources and reset resize generation.
Detailed Description
Owns render graph resource records and resize generations.
Definition at line 22 of file render_resource_registry.hpp.
Member Function Documentation
add()
quader::foundation::Result< void, std::string > crimson::RenderResourceRegistry::add (RenderResourceDesc desc) nodiscard
Add a render resource.
Parameters
desc Resource descriptor to store.
Returns
Success, or a validation error string.
Definition at line 84 of file render_graph.cpp.
References crimson::RenderResourceDesc::extent, quader::foundation::Result< T, E >::failure(), find(), crimson::is_valid_extent(), crimson::RenderResourceDesc::name, crimson::RenderResourceDesc::sample_count, and quader::foundation::Result< T, E >::success().
clear()
void crimson::RenderResourceRegistry::clear () noexcept
Remove all resources and reset resize generation.
Definition at line 145 of file render_graph.cpp.
find() [1/2]
const RenderResourceRecord * crimson::RenderResourceRegistry::find (std::string_view name) const nodiscard noexcept
Find an immutable resource by name.
Parameters
name Resource name.
Returns
Borrowed record, or nullptr when absent.
Definition at line 105 of file render_graph.cpp.
Referenced by add().
find() [2/2]
RenderResourceRecord * crimson::RenderResourceRegistry::find (std::string_view name) nodiscard noexcept
Find a mutable resource by name.
Parameters
name Resource name.
Returns
Borrowed record, or nullptr when absent.
Definition at line 112 of file render_graph.cpp.
resize()
void crimson::RenderResourceRegistry::resize (ViewportExtent extent)
Resize all resize-dependent resources.
Parameters
extent New extent applied to resize-dependent resources.
Definition at line 127 of file render_graph.cpp.
References crimson::is_valid_extent().
resize_generation()
std::uint64_t crimson::RenderResourceRegistry::resize_generation () const nodiscard noexcept
Return the current resize generation.
Returns
Monotonic resize generation.
Definition at line 123 of file render_graph.cpp.
Referenced by crimson::RenderGraph::resize_generation().
resources()
std::span< const RenderResourceRecord > crimson::RenderResourceRegistry::resources () const nodiscard noexcept
Return registered resources.
Returns
Borrowed span valid until registry mutation.
Definition at line 119 of file render_graph.cpp.
Referenced by crimson::gpu::GpuFrameResources::synchronize_descriptors().
The documentation for this class was generated from the following files:
src/crimson/graph/render_resource_registry.hpp
src/crimson/graph/render_graph.cpp