Quader: quader::commands::CommandHistory Class Reference
quader::commands::CommandHistory Class Reference final
#include <command_history.hpp>
Public Member Functions
CommandResult execute (std::unique_ptr< ICommand > command, quader::document::Document &document)
CommandResult undo (quader::document::Document &document)
CommandResult redo (quader::document::Document &document)
bool can_undo () const noexcept
bool can_redo () const noexcept
std::string_view undo_name () const noexcept
std::string_view redo_name () const noexcept
void clear () noexcept
Drop all undo and redo history without mutating the document.
Detailed Description
Owns undo and redo stacks for document commands.
execute() applies commands immediately. Successful execution pushes the command onto the undo stack and clears redo history unless a merge consumes the command.
Definition at line 27 of file command_history.hpp.
Member Function Documentation
can_redo()
bool quader::commands::CommandHistory::can_redo () const nodiscard noexcept
Check whether a redo command is available.
Returns
True when the redo stack is not empty.
Definition at line 66 of file command_history.cpp.
Referenced by redo(), and redo_name().
can_undo()
bool quader::commands::CommandHistory::can_undo () const nodiscard noexcept
Check whether an undo command is available.
Returns
True when the undo stack is not empty.
Definition at line 62 of file command_history.cpp.
Referenced by undo(), and undo_name().
clear()
void quader::commands::CommandHistory::clear () noexcept
Drop all undo and redo history without mutating the document.
Definition at line 86 of file command_history.cpp.
execute()
CommandResult quader::commands::CommandHistory::execute (std::unique_ptr< ICommand > command, quader::document::Document & document) nodiscard
Execute and record a command.
Parameters
command Command to take ownership of.
document Document passed to the command.
Returns
Command result from execution or merge.
Definition at line 16 of file command_history.cpp.
References quader::commands::CommandResult::rejected().
redo()
CommandResult quader::commands::CommandHistory::redo (quader::document::Document & document) nodiscard
Redo the latest undone command.
Parameters
document Document passed to the command.
Returns
Command result, or a rejection when no redo is available.
Definition at line 47 of file command_history.cpp.
References can_redo(), and quader::commands::CommandResult::rejected().
redo_name()
std::string_view quader::commands::CommandHistory::redo_name () const nodiscard noexcept
Return the name of the next redo command.
Returns
Borrowed command name, or an empty view when redo is unavailable.
Definition at line 78 of file command_history.cpp.
References can_redo().
undo()
CommandResult quader::commands::CommandHistory::undo (quader::document::Document & document) nodiscard
Undo the latest applied command.
Parameters
document Document passed to the command.
Returns
Command result, or a rejection when no undo is available.
Definition at line 32 of file command_history.cpp.
References can_undo(), and quader::commands::CommandResult::rejected().
undo_name()
std::string_view quader::commands::CommandHistory::undo_name () const nodiscard noexcept
Return the name of the next undo command.
Returns
Borrowed command name, or an empty view when undo is unavailable.
Definition at line 70 of file command_history.cpp.
References can_undo().
The documentation for this class was generated from the following files:
src/commands/command_history.hpp
src/commands/command_history.cpp