Quader: quader::ui::SettingsService Class Reference
quader::ui::SettingsService Class Reference final
Scoped wrapper around QSettings for workspace and viewport state.
#include <settings_service.hpp>
Public Member Functions
SettingsService (QSettings &settings)
Construct a settings facade over an externally owned QSettings.
QVariant value (QStringView key, const QVariant &fallback={}) const
Read a raw settings value.
void set_value (QStringView key, const QVariant &value)
Write a raw settings value.
void remove_group (QStringView group)
Remove a settings group.
void sync ()
Flush pending settings writes.
QByteArray main_window_geometry () const
Return saved main-window geometry.
void set_main_window_geometry (const QByteArray &geometry)
Store main-window geometry.
QByteArray main_window_state () const
Return saved main-window dock state.
void set_main_window_state (const QByteArray &state)
Store main-window dock state.
QVariant viewport_value (QStringView key, const QVariant &fallback={}) const
Read a viewport-scoped setting.
void set_viewport_value (QStringView key, const QVariant &value)
Write a viewport-scoped setting.
QVariant workspace_value (QStringView key, const QVariant &fallback={}) const
Read a workspace-scoped setting.
void set_workspace_value (QStringView key, const QVariant &value)
Write a workspace-scoped setting.
bool panel_visible (PanelId id, bool fallback) const
Return saved panel visibility.
void set_panel_visible (PanelId id, bool visible)
Store panel visibility.
void reset_workspace ()
Remove persisted workspace state.
Static Public Attributes
static constexpr int kWorkspaceStateVersion = 2
Version for persisted workspace layout state.
Detailed Description
Scoped wrapper around QSettings for workspace and viewport state.
Definition at line 22 of file settings_service.hpp.
Constructor & Destructor Documentation
SettingsService()
quader::ui::SettingsService::SettingsService (QSettings & settings) explicit
Construct a settings facade over an externally owned QSettings.
Definition at line 29 of file settings_service.cpp.
Member Function Documentation
main_window_geometry()
QByteArray quader::ui::SettingsService::main_window_geometry () const nodiscard
Return saved main-window geometry.
Definition at line 50 of file settings_service.cpp.
main_window_state()
QByteArray quader::ui::SettingsService::main_window_state () const nodiscard
Return saved main-window dock state.
Definition at line 58 of file settings_service.cpp.
References kWorkspaceStateVersion.
panel_visible()
bool quader::ui::SettingsService::panel_visible (PanelId id, bool fallback) const nodiscard
Return saved panel visibility.
Definition at line 88 of file settings_service.cpp.
References quader::ui::panel_id_name().
Referenced by quader::ui::PanelHost::restore_workspace().
remove_group()
void quader::ui::SettingsService::remove_group (QStringView group)
Remove a settings group.
Definition at line 40 of file settings_service.cpp.
Referenced by reset_workspace().
reset_workspace()
void quader::ui::SettingsService::reset_workspace ()
Remove persisted workspace state.
Definition at line 98 of file settings_service.cpp.
References remove_group().
set_main_window_geometry()
void quader::ui::SettingsService::set_main_window_geometry (const QByteArray & geometry)
Store main-window geometry.
Definition at line 54 of file settings_service.cpp.
set_main_window_state()
void quader::ui::SettingsService::set_main_window_state (const QByteArray & state)
Store main-window dock state.
Definition at line 67 of file settings_service.cpp.
References kWorkspaceStateVersion.
set_panel_visible()
void quader::ui::SettingsService::set_panel_visible (PanelId id, bool visible)
Store panel visibility.
Definition at line 93 of file settings_service.cpp.
References quader::ui::panel_id_name().
Referenced by quader::ui::PanelHost::save_workspace().
set_value()
void quader::ui::SettingsService::set_value (QStringView key, const QVariant & value)
Write a raw settings value.
Definition at line 36 of file settings_service.cpp.
References value().
Referenced by set_viewport_value(), and set_workspace_value().
set_viewport_value()
void quader::ui::SettingsService::set_viewport_value (QStringView key, const QVariant & value)
Write a viewport-scoped setting.
Definition at line 76 of file settings_service.cpp.
References set_value(), and value().
set_workspace_value()
void quader::ui::SettingsService::set_workspace_value (QStringView key, const QVariant & value)
Write a workspace-scoped setting.
Definition at line 84 of file settings_service.cpp.
References set_value(), and value().
sync()
void quader::ui::SettingsService::sync ()
Flush pending settings writes.
Definition at line 46 of file settings_service.cpp.
value()
QVariant quader::ui::SettingsService::value (QStringView key, const QVariant & fallback = {}) const nodiscard
Read a raw settings value.
Definition at line 32 of file settings_service.cpp.
Referenced by set_value(), set_viewport_value(), set_workspace_value(), viewport_value(), and workspace_value().
viewport_value()
QVariant quader::ui::SettingsService::viewport_value (QStringView key, const QVariant & fallback = {}) const nodiscard
Read a viewport-scoped setting.
Definition at line 72 of file settings_service.cpp.
References value().
workspace_value()
QVariant quader::ui::SettingsService::workspace_value (QStringView key, const QVariant & fallback = {}) const nodiscard
Read a workspace-scoped setting.
Definition at line 80 of file settings_service.cpp.
References value().
Member Data Documentation
kWorkspaceStateVersion
int quader::ui::SettingsService::kWorkspaceStateVersion = 2 static constexpr
Version for persisted workspace layout state.
Definition at line 25 of file settings_service.hpp.
Referenced by main_window_state(), and set_main_window_state().
The documentation for this class was generated from the following files:
src/ui/services/settings_service.hpp
src/ui/services/settings_service.cpp