Quader: crimson::gpu::ShaderLibrary Class Reference
crimson::gpu::ShaderLibrary Class Reference final
Resolves compiled shader binary paths from a shader root.
#include <shader_library.hpp>
Public Member Functions
ShaderLibrary (std::filesystem::path shader_root)
const std::filesystem::path & shader_root () const noexcept
Return the shader root path.
std::filesystem::path shader_path (ShaderProgramId program, ShaderStage stage, ShaderTarget target) const
std::optional< ShaderBinaryRef > shader_binary (ShaderProgramId program, ShaderStage stage, ShaderTarget target) const
Detailed Description
Resolves compiled shader binary paths from a shader root.
Definition at line 53 of file shader_library.hpp.
Constructor & Destructor Documentation
ShaderLibrary()
crimson::gpu::ShaderLibrary::ShaderLibrary (std::filesystem::path shader_root) explicit
Create a shader library rooted at a directory.
Parameters
shader_root Directory containing compiled shader target folders.
Definition at line 34 of file shader_library.cpp.
References shader_root().
Member Function Documentation
shader_binary()
std::optional< ShaderBinaryRef > crimson::gpu::ShaderLibrary::shader_binary (ShaderProgramId program, ShaderStage stage, ShaderTarget target) const
Return a shader binary reference when the shader is known.
Parameters
program Shader program identifier.
stage Shader stage.
target Compiled target platform.
Returns
Binary reference, or empty for unknown shader names.
Definition at line 48 of file shader_library.cpp.
References crimson::gpu::shader_file_name(), and crimson::gpu::shader_target_directory_name().
Referenced by crimson::gpu::load_shader().
shader_path()
std::filesystem::path crimson::gpu::ShaderLibrary::shader_path (ShaderProgramId program, ShaderStage stage, ShaderTarget target) const
Return the absolute path for one shader binary.
Parameters
program Shader program identifier.
stage Shader stage.
target Compiled target platform.
Returns
Absolute shader binary path.
Definition at line 41 of file shader_library.cpp.
References crimson::gpu::shader_file_name(), and crimson::gpu::shader_target_directory_name().
shader_root()
const std::filesystem::path & crimson::gpu::ShaderLibrary::shader_root () const noexcept
Return the shader root path.
Definition at line 37 of file shader_library.cpp.
Referenced by crimson::gpu::load_shader(), and ShaderLibrary().
The documentation for this class was generated from the following files:
src/crimson/gpu/shader_library.hpp
src/crimson/gpu/shader_library.cpp