Quader: quader::ui::ViewportWidget Class Reference
quader::ui::ViewportWidget Class Reference final
QWidget host for native Crimson viewport rendering and input translation.
#include <viewport_widget.hpp>
Public Member Functions
ViewportWidget (ViewportController &controller, QWidget *parent=nullptr)
Construct a viewport widget driven by controller.
~ViewportWidget () override
Shut down the controller surface before widget destruction.
QSize minimumSizeHint () const override
Return the minimum size for one viewport pane.
QPaintEngine * paintEngine () const override
Return null because native rendering bypasses Qt painting.
NativeViewportSurface native_surface () const
Return the borrowed native surface handle for the widget.
ViewportPixelSize pixel_size () const
Return widget size in physical pixels.
Protected Member Functions
void showEvent (QShowEvent *event) override
Initialize the native render surface on first show.
void resizeEvent (QResizeEvent *event) override
Resize the native render surface.
void paintEvent (QPaintEvent *event) override
Submit a frame during paint handling.
void mousePressEvent (QMouseEvent *event) override
Translate Qt mouse press events to viewport input.
void mouseMoveEvent (QMouseEvent *event) override
Translate Qt mouse move events to viewport input.
void mouseReleaseEvent (QMouseEvent *event) override
Translate Qt mouse release events to viewport input.
void leaveEvent (QEvent *event) override
End hover/splitter state when the cursor leaves.
void wheelEvent (QWheelEvent *event) override
Translate Qt wheel events to viewport input.
void keyPressEvent (QKeyEvent *event) override
Translate Qt key press events to viewport input.
void keyReleaseEvent (QKeyEvent *event) override
Translate Qt key release events to viewport input.
bool eventFilter (QObject *watched, QEvent *event) override
Track child splitter-handle input.
Detailed Description
QWidget host for native Crimson viewport rendering and input translation.
Definition at line 30 of file viewport_widget.hpp.
Constructor & Destructor Documentation
ViewportWidget()
quader::ui::ViewportWidget::ViewportWidget (ViewportController & controller, QWidget * parent = nullptr) explicit
Construct a viewport widget driven by controller.
Definition at line 62 of file viewport_widget.cpp.
References quader::ui::ViewportController::frame_requested(), and quader::ui::ViewportController::viewport_layout_changed().
~ViewportWidget()
quader::ui::ViewportWidget::~ViewportWidget () override
Shut down the controller surface before widget destruction.
Definition at line 88 of file viewport_widget.cpp.
Member Function Documentation
eventFilter()
bool quader::ui::ViewportWidget::eventFilter (QObject * watched, QEvent * event) override protected
Track child splitter-handle input.
Definition at line 241 of file viewport_widget.cpp.
References quader::ui::Horizontal, quader::ui::None, and quader::ui::Vertical.
keyPressEvent()
void quader::ui::ViewportWidget::keyPressEvent (QKeyEvent * event) override protected
Translate Qt key press events to viewport input.
Definition at line 225 of file viewport_widget.cpp.
keyReleaseEvent()
void quader::ui::ViewportWidget::keyReleaseEvent (QKeyEvent * event) override protected
Translate Qt key release events to viewport input.
Definition at line 233 of file viewport_widget.cpp.
leaveEvent()
void quader::ui::ViewportWidget::leaveEvent (QEvent * event) override protected
End hover/splitter state when the cursor leaves.
Definition at line 206 of file viewport_widget.cpp.
References quader::ui::None.
minimumSizeHint()
QSize quader::ui::ViewportWidget::minimumSizeHint () const nodiscard override
Return the minimum size for one viewport pane.
Definition at line 93 of file viewport_widget.cpp.
mouseMoveEvent()
void quader::ui::ViewportWidget::mouseMoveEvent (QMouseEvent * event) override protected
Translate Qt mouse move events to viewport input.
Definition at line 171 of file viewport_widget.cpp.
References quader::ui::None, and pixel_size().
mousePressEvent()
void quader::ui::ViewportWidget::mousePressEvent (QMouseEvent * event) override protected
Translate Qt mouse press events to viewport input.
Definition at line 143 of file viewport_widget.cpp.
References quader::ui::None, and pixel_size().
mouseReleaseEvent()
void quader::ui::ViewportWidget::mouseReleaseEvent (QMouseEvent * event) override protected
Translate Qt mouse release events to viewport input.
Definition at line 187 of file viewport_widget.cpp.
References quader::ui::None, and pixel_size().
native_surface()
NativeViewportSurface quader::ui::ViewportWidget::native_surface () const nodiscard
Return the borrowed native surface handle for the widget.
Definition at line 101 of file viewport_widget.cpp.
References quader::ui::NativeViewportSurface::native_window, quader::ui::NativeViewportSurface::platform, quader::ui::NativeViewportSurface::Unknown, and quader::ui::NativeViewportSurface::WindowsHwnd.
Referenced by showEvent().
paintEngine()
QPaintEngine * quader::ui::ViewportWidget::paintEngine () const nodiscard override
Return null because native rendering bypasses Qt painting.
Definition at line 97 of file viewport_widget.cpp.
paintEvent()
void quader::ui::ViewportWidget::paintEvent (QPaintEvent * event) override protected
Submit a frame during paint handling.
Definition at line 138 of file viewport_widget.cpp.
pixel_size()
ViewportPixelSize quader::ui::ViewportWidget::pixel_size () const nodiscard
Return widget size in physical pixels.
Definition at line 113 of file viewport_widget.cpp.
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), resizeEvent(), showEvent(), and wheelEvent().
resizeEvent()
void quader::ui::ViewportWidget::resizeEvent (QResizeEvent * event) override protected
Resize the native render surface.
Definition at line 132 of file viewport_widget.cpp.
References pixel_size().
showEvent()
void quader::ui::ViewportWidget::showEvent (QShowEvent * event) override protected
Initialize the native render surface on first show.
Definition at line 121 of file viewport_widget.cpp.
References native_surface(), and pixel_size().
wheelEvent()
void quader::ui::ViewportWidget::wheelEvent (QWheelEvent * event) override protected
Translate Qt wheel events to viewport input.
Definition at line 214 of file viewport_widget.cpp.
References pixel_size().
The documentation for this class was generated from the following files:
src/ui/viewport/viewport_widget.hpp
src/ui/viewport/viewport_widget.cpp