Quader: quader::commands::CreateMeshObjectCommand Class Reference
quader::commands::CreateMeshObjectCommand Class Reference final
#include <document_commands.hpp>
Public Member Functions
CreateMeshObjectCommand (std::string name, quader::mesh::Polyhedron mesh, quader::document::Transform transform={}, quader::document::PbrMaterial material=quader::document::default_box_material())
std::string_view name () const noexcept override
Return the command display name.
CommandResult execute (quader::document::Document &document) override
Create or restore the mesh object in document.
CommandResult undo (quader::document::Document &document) override
Extract the created object for redo.
std::optional< quader::document::ObjectId > object_id () const noexcept
Return the created object id after successful execution.
Public Member Functions inherited from quader::commands::ICommand
virtual ~ICommand ()=default
Destroy a command through the base interface.
virtual bool can_merge_with (const ICommand &next) const noexcept
virtual CommandResult merge_with (std::unique_ptr< ICommand > next)
Detailed Description
Undoable command that creates a validated mesh object.
The command owns the input mesh until first execution, then stores the created object snapshot on undo so redo can restore the same object id.
Definition at line 31 of file document_commands.hpp.
Constructor & Destructor Documentation
CreateMeshObjectCommand()
quader::commands::CreateMeshObjectCommand::CreateMeshObjectCommand (std::string name, quader::mesh::Polyhedron mesh, quader::document::Transform transform = {}, quader::document::PbrMaterial material = quader::document::default_box_material())
Construct a create-object command.
Parameters
name Object name to create.
mesh Mesh payload to move into the document on execute.
transform Initial transform.
material Initial material.
Definition at line 23 of file document_commands.cpp.
References name().
Member Function Documentation
execute()
CommandResult quader::commands::CreateMeshObjectCommand::execute (quader::document::Document & document) nodiscard override virtual
Create or restore the mesh object in document.
Implements quader::commands::ICommand.
Definition at line 36 of file document_commands.cpp.
References quader::commands::CommandResult::applied(), and quader::commands::CommandResult::rejected().
name()
std::string_view quader::commands::CreateMeshObjectCommand::name () const nodiscard override virtual noexcept
Return the command display name.
Implements quader::commands::ICommand.
Definition at line 32 of file document_commands.cpp.
Referenced by CreateMeshObjectCommand().
object_id()
std::optional< quader::document::ObjectId > quader::commands::CreateMeshObjectCommand::object_id () const nodiscard noexcept
Return the created object id after successful execution.
Definition at line 83 of file document_commands.cpp.
undo()
CommandResult quader::commands::CreateMeshObjectCommand::undo (quader::document::Document & document) nodiscard override virtual
Extract the created object for redo.
Implements quader::commands::ICommand.
Definition at line 69 of file document_commands.cpp.
References quader::commands::CommandResult::applied(), and quader::commands::CommandResult::rejected().
The documentation for this class was generated from the following files:
src/commands/document_commands.hpp
src/commands/document_commands.cpp