Quader: crimson::gpu::UniqueGpuHandle< Handle, Traits > Class Template Reference
crimson::gpu::UniqueGpuHandle< Handle, Traits > Class Template Reference final
#include <gpu_resources.hpp>
Public Member Functions
UniqueGpuHandle () noexcept=default
Create an invalid handle wrapper.
UniqueGpuHandle (Handle handle) noexcept
~UniqueGpuHandle ()
Destroy the owned handle when valid.
UniqueGpuHandle (const UniqueGpuHandle &)=delete
Unique GPU handles cannot be copied.
UniqueGpuHandle & operator= (const UniqueGpuHandle &)=delete
Unique GPU handles cannot be copied.
UniqueGpuHandle (UniqueGpuHandle &&other) noexcept
Move ownership from another wrapper.
UniqueGpuHandle & operator= (UniqueGpuHandle &&other) noexcept
Move ownership from another wrapper.
bool valid () const noexcept
Handle get () const noexcept
Handle release () noexcept
void reset (Handle handle=Traits::invalid()) noexcept
Detailed Description
template<typename Handle, typename Traits>
class crimson::gpu::UniqueGpuHandle< Handle, Traits >
Move-only RAII wrapper for a native GPU handle.
Template Parameters
Handle Native handle type.
Traits Traits providing invalid, validity, and destroy operations.
Definition at line 29 of file gpu_resources.hpp.
Constructor & Destructor Documentation
UniqueGpuHandle() [1/4]
template<typename Handle, typename Traits> crimson::gpu::UniqueGpuHandle< Handle, Traits >::UniqueGpuHandle () default noexcept
Create an invalid handle wrapper.
UniqueGpuHandle() [2/4]
template<typename Handle, typename Traits> crimson::gpu::UniqueGpuHandle< Handle, Traits >::UniqueGpuHandle (Handle handle) inline explicit noexcept
Take ownership of a native handle.
Parameters
handle Native handle to own.
Definition at line 39 of file gpu_resources.hpp.
~UniqueGpuHandle()
template<typename Handle, typename Traits> crimson::gpu::UniqueGpuHandle< Handle, Traits >::~UniqueGpuHandle () inline
Destroy the owned handle when valid.
Definition at line 44 of file gpu_resources.hpp.
UniqueGpuHandle() [3/4]
template<typename Handle, typename Traits> crimson::gpu::UniqueGpuHandle< Handle, Traits >::UniqueGpuHandle (const UniqueGpuHandle< Handle, Traits > &) delete
Unique GPU handles cannot be copied.
UniqueGpuHandle() [4/4]
template<typename Handle, typename Traits> crimson::gpu::UniqueGpuHandle< Handle, Traits >::UniqueGpuHandle (UniqueGpuHandle< Handle, Traits > && other) inline noexcept
Move ownership from another wrapper.
Definition at line 54 of file gpu_resources.hpp.
Member Function Documentation
get()
template<typename Handle, typename Traits> Handle crimson::gpu::UniqueGpuHandle< Handle, Traits >::get () const inline nodiscard noexcept
Return the native handle without transferring ownership.
Returns
Owned native handle, possibly invalid.
Definition at line 81 of file gpu_resources.hpp.
Referenced by crimson::gpu::GpuFrameResources::framebuffer(), and crimson::gpu::GpuFrameResources::texture().
operator=() [1/2]
template<typename Handle, typename Traits> UniqueGpuHandle & crimson::gpu::UniqueGpuHandle< Handle, Traits >::operator= (const UniqueGpuHandle< Handle, Traits > &) delete
Unique GPU handles cannot be copied.
operator=() [2/2]
template<typename Handle, typename Traits> UniqueGpuHandle & crimson::gpu::UniqueGpuHandle< Handle, Traits >::operator= (UniqueGpuHandle< Handle, Traits > && other) inline noexcept
Move ownership from another wrapper.
Definition at line 59 of file gpu_resources.hpp.
release()
template<typename Handle, typename Traits> Handle crimson::gpu::UniqueGpuHandle< Handle, Traits >::release () inline nodiscard noexcept
Release ownership without destroying the handle.
Returns
Previously owned native handle.
Definition at line 90 of file gpu_resources.hpp.
reset()
template<typename Handle, typename Traits> void crimson::gpu::UniqueGpuHandle< Handle, Traits >::reset (Handle handle = Traits::invalid()) inline noexcept
Replace the owned handle.
Parameters
handle New native handle to own.
Definition at line 101 of file gpu_resources.hpp.
Referenced by crimson::gpu::GpuMeshCache::create_unit_box(), crimson::gpu::UniqueGpuHandle< bgfx::VertexBufferHandle, VertexBufferHandleTraits >::operator=(), crimson::gpu::GpuFrameResources::synchronize_descriptors(), crimson::gpu::GpuMeshCache::upload_mesh(), and crimson::gpu::UniqueGpuHandle< bgfx::VertexBufferHandle, VertexBufferHandleTraits >::~UniqueGpuHandle().
valid()
template<typename Handle, typename Traits> bool crimson::gpu::UniqueGpuHandle< Handle, Traits >::valid () const inline nodiscard noexcept
Check whether the owned native handle is valid.
Returns
True when Traits::is_valid() accepts the handle.
Definition at line 72 of file gpu_resources.hpp.
The documentation for this class was generated from the following file:
src/crimson/gpu/gpu_resources.hpp