Quader: crimson::gpu::GpuDevice Class Reference
crimson::gpu::GpuDevice Class Reference final
Owns the selected graphics backend and per-frame GPU execution path.
#include <gpu_device.hpp>
Classes
struct Impl
Public Member Functions
GpuDevice ()
Create an uninitialized GPU device wrapper.
~GpuDevice ()
Shut down and release GPU resources.
GpuDevice (const GpuDevice &)=delete
GPU devices cannot be copied because they own native runtime state.
GpuDevice & operator= (const GpuDevice &)=delete
GPU devices cannot be copied because they own native runtime state.
bool initialize (const RendererConfig &config, const NativeSurfaceDescriptor &surface)
void shutdown () noexcept
Shut down the graphics runtime if initialized.
bool resize (const ViewportExtent &extent)
quader::foundation::Result< FrameRenderResult, RendererDiagnostic > render_frame (const FrameSnapshot &snapshot, const RenderGraph &graph)
std::optional< FrameStats > latest_frame_stats () const noexcept
std::vector< RenderPassStats > latest_pass_stats () const
bool initialized () const noexcept
Return true when the graphics runtime is initialized.
std::optional< GraphicsBackend > selected_backend () const noexcept
Return the selected backend, or empty before initialization.
const RendererStatus & status () const noexcept
Return the current renderer status owned by the device.
Detailed Description
Owns the selected graphics backend and per-frame GPU execution path.
Definition at line 29 of file gpu_device.hpp.
Constructor & Destructor Documentation
GpuDevice() [1/2]
crimson::gpu::GpuDevice::GpuDevice ()
Create an uninitialized GPU device wrapper.
Definition at line 745 of file gpu_device.cpp.
Referenced by GpuDevice(), and operator=().
~GpuDevice()
crimson::gpu::GpuDevice::~GpuDevice ()
Shut down and release GPU resources.
Definition at line 748 of file gpu_device.cpp.
References shutdown().
GpuDevice() [2/2]
crimson::gpu::GpuDevice::GpuDevice (const GpuDevice &) delete
GPU devices cannot be copied because they own native runtime state.
References GpuDevice().
Member Function Documentation
initialize()
bool crimson::gpu::GpuDevice::initialize (const RendererConfig & config, const NativeSurfaceDescriptor & surface)
Initialize the graphics runtime for a native surface.
Parameters
config Renderer startup configuration.
surface Native host surface descriptor.
Returns
True when initialization succeeds.
Definition at line 752 of file gpu_device.cpp.
References crimson::AlphaCutoutPbr, crimson::RendererConfig::backend_preference, crimson::CapabilityMissing, crimson::gpu::choose_backend(), crimson::MaterialSystem::create_default_material(), crimson::gpu::GpuCapabilityValidation::diagnostics, crimson::RendererConfig::display_conversion, crimson::RendererConfig::enable_debug_text, crimson::NativeSurfaceDescriptor::extent, crimson::Fatal, crimson::gpu::graphics_backend_name(), crimson::has_error_diagnostic(), crimson::ViewportExtent::height_px, crimson::is_valid_native_surface_descriptor(), crimson::gpu::make_backend_unsupported_diagnostic(), crimson::OpaquePbr, crimson::OverlayLine, crimson::OverlayUnlit, crimson::Picking, crimson::NativeSurfaceDescriptor::platform, crimson::Present, crimson::RuntimeInitializationFailed, crimson::RendererConfig::shader_root, shutdown(), crimson::gpu::GpuCapabilityValidation::statuses, crimson::SurfaceUnavailable, crimson::ToneMap, crimson::TransparentPbr, crimson::gpu::validate_v1_capabilities(), and crimson::ViewportExtent::width_px.
initialized()
bool crimson::gpu::GpuDevice::initialized () const noexcept
Return true when the graphics runtime is initialized.
Definition at line 1393 of file gpu_device.cpp.
Referenced by operator=().
latest_frame_stats()
std::optional< FrameStats > crimson::gpu::GpuDevice::latest_frame_stats () const nodiscard noexcept
Return stats for the latest rendered frame.
Returns
Frame stats, or empty before a frame completes.
Definition at line 1385 of file gpu_device.cpp.
Referenced by operator=().
latest_pass_stats()
std::vector< RenderPassStats > crimson::gpu::GpuDevice::latest_pass_stats () const nodiscard
Return latest per-pass stats.
Returns
Per-pass stats copied from the latest frame.
Definition at line 1389 of file gpu_device.cpp.
Referenced by operator=().
operator=()
GpuDevice & crimson::gpu::GpuDevice::operator= (const GpuDevice &) delete
GPU devices cannot be copied because they own native runtime state.
References GpuDevice(), initialized(), latest_frame_stats(), latest_pass_stats(), render_frame(), resize(), selected_backend(), and status().
render_frame()
quader::foundation::Result< FrameRenderResult, RendererDiagnostic > crimson::gpu::GpuDevice::render_frame (const FrameSnapshot & snapshot, const RenderGraph & graph) nodiscard
Render one frame snapshot through the active graph.
Parameters
snapshot Immutable frame snapshot.
graph Validated render graph for the frame.
Returns
Frame result, or renderer diagnostic.
Definition at line 1027 of file gpu_device.cpp.
References crimson::DrawPacketBuildResult::alpha_cutout, crimson::FrameQueueStats::alpha_cutout_draw_count, crimson::OverlayDrawLists::always_on_top, crimson::AlwaysOnTop, crimson::build_instance_batches(), crimson::RenderView::camera, crimson::OverlayDrawLists::command_count(), crimson::gpu::GpuPickingFrameResult::completed_results, crimson::FrameTimingStats::cpu_frame_us, crimson::FrameTimingStats::cpu_packet_build_us, crimson::FrameTimingStats::cpu_resource_upload_us, crimson::FrameTimingStats::cpu_submit_us, crimson::DrawPacketBuildResult::culling, crimson::RenderView::debug_name, crimson::OverlayDrawLists::depth_tested, crimson::DepthTested, crimson::ViewportExtent::device_pixel_ratio, crimson::RendererStatus::diagnostics, crimson::ViewportSettings::draw_grid_overlay, crimson::ViewportSettings::draw_lit_surfaces, crimson::ViewportSettings::draw_overlays, crimson::DrawPacketBuildResult::draw_packet_count(), crimson::FramePacketStats::draw_packet_count, crimson::FrameQueueStats::draw_packet_count, crimson::FrameSnapshot::elapsed_seconds(), crimson::Error, crimson::ViewportSettings::exposure_compensation_ev, crimson::ViewportSettings::exposure_ev100, crimson::exposure_multiplier_from_ev100(), quader::foundation::Result< T, E >::failure(), crimson::FrameSnapshot::frame_index(), crimson::RendererDiagnostic::frame_index, crimson::FrameSnapshot::grid_overlay_payloads(), crimson::ViewportExtent::height_px, crimson::InvalidFrameSnapshot, crimson::is_valid_extent(), crimson::is_valid_render_view(), crimson::kHdrSceneColorTargetName, crimson::kToneMappedColorTargetName, crimson::FrameSnapshot::line_overlay_payloads(), crimson::make_frame_stats(), crimson::make_instancing_stats(), crimson::make_render_pass_stats(), crimson::FrameSnapshot::mesh_uploads(), crimson::FrameSnapshot::objects(), crimson::DrawPacketBuildResult::opaque, crimson::FrameQueueStats::opaque_draw_count, crimson::FrameQueueStats::overlay_draw_count, crimson::FramePacketStats::overlay_packet_count, crimson::FrameSnapshot::overlays(), crimson::DrawPacketBuildResult::packets, crimson::RenderGraph::passes(), crimson::FrameSnapshot::picking_requests(), crimson::OverlaySystem::prepare(), crimson::gpu::prepare_pbr_pass_packets(), resize(), crimson::ResizeFailed, crimson::ResourceCreationFailed, crimson::ResourceLifetimeError, crimson::gpu::GpuPickingFrameResult::scheduled_readbacks, status(), quader::foundation::Result< T, E >::success(), crimson::FrameSnapshot::target_extent(), crimson::ViewportSettings::tone_mapper, crimson::DrawPacketBuildResult::transparent, crimson::FrameQueueStats::transparent_draw_count, crimson::FrameSnapshot::viewport_settings(), crimson::FrameSnapshot::views(), crimson::FrameCullingStats::visible_object_count, crimson::ViewportExtent::width_px, crimson::XRay, and crimson::OverlayDrawLists::xray.
Referenced by operator=().
resize()
bool crimson::gpu::GpuDevice::resize (const ViewportExtent & extent)
Resize runtime targets.
Parameters
extent New viewport extent.
Returns
True when resize succeeds.
Definition at line 999 of file gpu_device.cpp.
References crimson::Error, crimson::ViewportExtent::height_px, crimson::is_valid_extent(), crimson::ResizeFailed, and crimson::ViewportExtent::width_px.
Referenced by operator=(), and render_frame().
selected_backend()
std::optional< GraphicsBackend > crimson::gpu::GpuDevice::selected_backend () const noexcept
Return the selected backend, or empty before initialization.
Definition at line 1397 of file gpu_device.cpp.
Referenced by operator=().
shutdown()
void crimson::gpu::GpuDevice::shutdown () noexcept
Shut down the graphics runtime if initialized.
Definition at line 971 of file gpu_device.cpp.
Referenced by initialize(), and ~GpuDevice().
status()
const RendererStatus & crimson::gpu::GpuDevice::status () const noexcept
Return the current renderer status owned by the device.
Definition at line 1401 of file gpu_device.cpp.
Referenced by operator=(), and render_frame().
The documentation for this class was generated from the following files:
src/crimson/gpu/gpu_device.hpp
src/crimson/gpu/gpu_device.cpp