Quader: quader::mesh::Polyhedron Class Reference
quader::mesh::Polyhedron Class Reference final
#include <polyhedron.hpp>
Public Member Functions
Polyhedron ()
Create an empty mesh.
~Polyhedron ()
Destroy the mesh and its backend storage.
Polyhedron (const Polyhedron &other)
Deep-copy mesh topology, positions, mappings, and attributes.
Polyhedron & operator= (const Polyhedron &other)
Deep-copy mesh topology, positions, mappings, and attributes.
Polyhedron (Polyhedron &&) noexcept
Move mesh storage and attributes.
Polyhedron & operator= (Polyhedron &&) noexcept
Move mesh storage and attributes.
VertexId create_vertex (quader::math::Vec3 position)
quader::foundation::Result< void, MeshError > delete_vertex (VertexId vertex)
quader::foundation::Result< FaceId, MeshError > create_face (std::span< const VertexId > vertices)
quader::foundation::Result< void, MeshError > delete_face (FaceId face)
bool is_valid (VertexId id) const noexcept
bool is_valid (HalfedgeId id) const noexcept
bool is_valid (EdgeId id) const noexcept
bool is_valid (FaceId id) const noexcept
std::size_t vertex_count () const noexcept
Return the number of live vertices.
std::size_t halfedge_count () const noexcept
Return the number of live halfedges.
std::size_t edge_count () const noexcept
Return the number of live edges.
std::size_t face_count () const noexcept
Return the number of live faces.
std::vector< VertexId > vertex_ids () const
Return all live vertex IDs.
std::vector< HalfedgeId > halfedge_ids () const
Return all live halfedge IDs.
std::vector< EdgeId > edge_ids () const
Return all live edge IDs.
std::vector< FaceId > face_ids () const
Return all live face IDs.
quader::foundation::Result< quader::math::Vec3, MeshError > vertex_position (VertexId vertex) const
quader::foundation::Result< void, MeshError > set_vertex_position (VertexId vertex, quader::math::Vec3 position)
quader::foundation::Result< HalfedgeId, MeshError > vertex_outgoing_halfedge (VertexId vertex) const
Return one outgoing halfedge for a vertex.
quader::foundation::Result< VertexId, MeshError > halfedge_origin (HalfedgeId halfedge) const
Return the origin vertex of a halfedge.
quader::foundation::Result< VertexId, MeshError > halfedge_target (HalfedgeId halfedge) const
Return the target vertex of a halfedge.
quader::foundation::Result< HalfedgeId, MeshError > opposite_halfedge (HalfedgeId halfedge) const
Return the opposite halfedge.
quader::foundation::Result< HalfedgeId, MeshError > next_halfedge (HalfedgeId halfedge) const
Return the next halfedge in a cycle.
quader::foundation::Result< HalfedgeId, MeshError > previous_halfedge (HalfedgeId halfedge) const
Return the previous halfedge in a cycle.
quader::foundation::Result< EdgeId, MeshError > halfedge_edge (HalfedgeId halfedge) const
Return the undirected edge owning a halfedge.
quader::foundation::Result< FaceId, MeshError > halfedge_face (HalfedgeId halfedge) const
Return the face associated with a halfedge.
quader::foundation::Result< bool, MeshError > is_boundary_halfedge (HalfedgeId halfedge) const
Check whether a halfedge belongs to a boundary cycle.
quader::foundation::Result< std::vector< HalfedgeId >, MeshError > face_halfedges (FaceId face) const
Return the halfedge cycle for a face.
quader::foundation::Result< std::array< HalfedgeId, 2 >, MeshError > edge_halfedges (EdgeId edge) const
Return the two halfedges associated with an edge.
quader::foundation::Result< MeshCompactionReport, MeshError > compact_storage ()
MeshAttributes & attributes () noexcept
const MeshAttributes & attributes () const noexcept
template<class T>
quader::foundation::Result< T *, MeshError > vertex_attribute (AttributeId attribute, VertexId vertex)
template<class T>
quader::foundation::Result< const T *, MeshError > vertex_attribute (AttributeId attribute, VertexId vertex) const
Friends
MeshValidationReport validate_mesh (const Polyhedron &mesh)
Detailed Description
Editable polygon mesh with stable generational element IDs.
Polyhedron owns topology, vertex positions, and mesh attributes. Expected failures are returned as Result errors; invalid identifiers do not throw.
Definition at line 72 of file polyhedron.hpp.
Constructor & Destructor Documentation
Polyhedron() [1/3]
quader::mesh::Polyhedron::Polyhedron ()
Create an empty mesh.
Definition at line 141 of file polyhedron.cpp.
Referenced by create_vertex(), operator=(), operator=(), Polyhedron(), Polyhedron(), validate_mesh, and ~Polyhedron().
~Polyhedron()
quader::mesh::Polyhedron::~Polyhedron () default
Destroy the mesh and its backend storage.
References Polyhedron().
Polyhedron() [2/3]
quader::mesh::Polyhedron::Polyhedron (const Polyhedron & other)
Deep-copy mesh topology, positions, mappings, and attributes.
Definition at line 146 of file polyhedron.cpp.
References Polyhedron().
Polyhedron() [3/3]
quader::mesh::Polyhedron::Polyhedron (Polyhedron &&) default noexcept
Move mesh storage and attributes.
References Polyhedron().
Member Function Documentation
attributes() [1/2]
const MeshAttributes & quader::mesh::Polyhedron::attributes () const nodiscard noexcept
Access immutable mesh attributes.
Returns
Attribute container owned by this mesh.
Definition at line 798 of file polyhedron.cpp.
attributes() [2/2]
MeshAttributes & quader::mesh::Polyhedron::attributes () nodiscard noexcept
Access mutable mesh attributes.
Returns
Attribute container owned by this mesh.
Definition at line 794 of file polyhedron.cpp.
Referenced by operator=().
compact_storage()
quader::foundation::Result< MeshCompactionReport, MeshError > quader::mesh::Polyhedron::compact_storage () nodiscard
Remove deleted storage slots and rebuild ID mappings.
Returns
Compaction counts, or an error when mappings cannot be preserved.
Definition at line 713 of file polyhedron.cpp.
References quader::mesh::CompactionFailed, edge_count(), face_count(), quader::foundation::Result< T, E >::failure(), halfedge_count(), is_valid(), quader::mesh::MeshCompactionReport::live_edges, quader::mesh::MeshCompactionReport::live_faces, quader::mesh::MeshCompactionReport::live_halfedges, quader::mesh::MeshCompactionReport::live_vertices, quader::mesh::make_mesh_error(), quader::mesh::MeshCompactionReport::removed_edges, quader::mesh::MeshCompactionReport::removed_faces, quader::mesh::MeshCompactionReport::removed_halfedges, quader::mesh::MeshCompactionReport::removed_vertices, quader::foundation::Result< T, E >::success(), validate_mesh, and vertex_count().
Referenced by operator=().
create_face()
quader::foundation::Result< FaceId, MeshError > quader::mesh::Polyhedron::create_face (std::span< const VertexId > vertices) nodiscard
Create a face from existing vertices.
Parameters
vertices Face vertices in winding order.
Returns
New face id, or a mesh error.
Definition at line 212 of file polyhedron.cpp.
References quader::geometry::all_points_finite(), quader::mesh::BackendRejectedFace, quader::mesh::DegenerateFace, quader::mesh::Edge, quader::mesh::Face, quader::mesh::FaceNeedsAtLeastThreeVertices, quader::foundation::Result< T, E >::failure(), quader::mesh::Halfedge, quader::geometry::has_degenerate_area(), quader::mesh::InvalidVertex, is_valid(), quader::mesh::make_mesh_error(), quader::mesh::NonFinitePosition, and quader::foundation::Result< T, E >::success().
Referenced by operator=().
create_vertex()
VertexId quader::mesh::Polyhedron::create_vertex (quader::math::Vec3 position) nodiscard
Create a vertex.
Parameters
position Vertex position.
Returns
Stable vertex identifier.
Definition at line 162 of file polyhedron.cpp.
References create_vertex(), Polyhedron(), and quader::mesh::Vertex.
Referenced by create_vertex(), and operator=().
delete_face()
quader::foundation::Result< void, MeshError > quader::mesh::Polyhedron::delete_face (FaceId face) nodiscard
Delete a face and its face-owned topology.
Parameters
face Face to delete.
Returns
Success, or an error when the face is invalid.
Definition at line 355 of file polyhedron.cpp.
References face_halfedges(), quader::foundation::Result< T, E >::failure(), halfedge_edge(), quader::foundation::GenerationalId< Tag >::index(), quader::foundation::GenerationalId< HalfedgeTag >::invalid(), quader::mesh::InvalidFace, is_valid(), quader::mesh::make_mesh_error(), opposite_halfedge(), and quader::foundation::Result< T, E >::success().
Referenced by operator=().
delete_vertex()
quader::foundation::Result< void, MeshError > quader::mesh::Polyhedron::delete_vertex (VertexId vertex) nodiscard
Delete an unreferenced vertex.
Parameters
vertex Vertex to delete.
Returns
Success, or an error when the vertex is invalid or referenced.
Definition at line 187 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidVertex, is_valid(), quader::mesh::make_mesh_error(), quader::foundation::Result< T, E >::success(), and quader::mesh::VertexStillReferenced.
Referenced by operator=().
edge_count()
std::size_t quader::mesh::Polyhedron::edge_count () const nodiscard noexcept
Return the number of live edges.
Definition at line 467 of file polyhedron.cpp.
Referenced by compact_storage(), and operator=().
edge_halfedges()
quader::foundation::Result< std::array< HalfedgeId, 2 >, MeshError > quader::mesh::Polyhedron::edge_halfedges (EdgeId edge) const nodiscard
Return the two halfedges associated with an edge.
Definition at line 692 of file polyhedron.cpp.
References quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidEdge, quader::mesh::InvalidHalfedge, is_valid(), and quader::mesh::make_mesh_error().
Referenced by operator=().
edge_ids()
std::vector< EdgeId > quader::mesh::Polyhedron::edge_ids () const nodiscard
Return all live edge IDs.
Definition at line 483 of file polyhedron.cpp.
Referenced by operator=().
face_count()
std::size_t quader::mesh::Polyhedron::face_count () const nodiscard noexcept
Return the number of live faces.
Definition at line 471 of file polyhedron.cpp.
Referenced by compact_storage(), and operator=().
face_halfedges()
quader::foundation::Result< std::vector< HalfedgeId >, MeshError > quader::mesh::Polyhedron::face_halfedges (FaceId face) const nodiscard
Return the halfedge cycle for a face.
Definition at line 667 of file polyhedron.cpp.
References quader::mesh::BrokenFaceCycle, quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidFace, quader::mesh::InvalidHalfedge, is_valid(), and quader::mesh::make_mesh_error().
Referenced by delete_face(), and operator=().
face_ids()
std::vector< FaceId > quader::mesh::Polyhedron::face_ids () const nodiscard
Return all live face IDs.
Definition at line 487 of file polyhedron.cpp.
Referenced by operator=().
halfedge_count()
std::size_t quader::mesh::Polyhedron::halfedge_count () const nodiscard noexcept
Return the number of live halfedges.
Definition at line 463 of file polyhedron.cpp.
Referenced by compact_storage(), and operator=().
halfedge_edge()
quader::foundation::Result< EdgeId, MeshError > quader::mesh::Polyhedron::halfedge_edge (HalfedgeId halfedge) const nodiscard
Return the undirected edge owning a halfedge.
Definition at line 622 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidEdge, quader::mesh::InvalidHalfedge, is_valid(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by delete_face(), and operator=().
halfedge_face()
quader::foundation::Result< FaceId, MeshError > quader::mesh::Polyhedron::halfedge_face (HalfedgeId halfedge) const nodiscard
Return the face associated with a halfedge.
Definition at line 637 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidFace, quader::mesh::InvalidHalfedge, is_valid(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by operator=().
halfedge_ids()
std::vector< HalfedgeId > quader::mesh::Polyhedron::halfedge_ids () const nodiscard
Return all live halfedge IDs.
Definition at line 479 of file polyhedron.cpp.
Referenced by operator=().
halfedge_origin()
quader::foundation::Result< VertexId, MeshError > quader::mesh::Polyhedron::halfedge_origin (HalfedgeId halfedge) const nodiscard
Return the origin vertex of a halfedge.
Definition at line 531 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidHalfedge, quader::mesh::InvalidVertex, is_valid(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by operator=().
halfedge_target()
quader::foundation::Result< VertexId, MeshError > quader::mesh::Polyhedron::halfedge_target (HalfedgeId halfedge) const nodiscard
Return the target vertex of a halfedge.
Definition at line 546 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidHalfedge, quader::mesh::InvalidVertex, is_valid(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by operator=().
is_boundary_halfedge()
quader::foundation::Result< bool, MeshError > quader::mesh::Polyhedron::is_boundary_halfedge (HalfedgeId halfedge) const nodiscard
Check whether a halfedge belongs to a boundary cycle.
Definition at line 658 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidHalfedge, is_valid(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by operator=().
is_valid() [1/4]
bool quader::mesh::Polyhedron::is_valid (EdgeId id) const nodiscard noexcept
Check whether an edge id resolves to a live edge.
Parameters
id Edge id to test.
Returns
True when the id is live and generation-matched.
Definition at line 443 of file polyhedron.cpp.
References is_valid().
is_valid() [2/4]
bool quader::mesh::Polyhedron::is_valid (FaceId id) const nodiscard noexcept
Check whether a face id resolves to a live face.
Parameters
id Face id to test.
Returns
True when the id is live and generation-matched.
Definition at line 451 of file polyhedron.cpp.
References is_valid().
is_valid() [3/4]
bool quader::mesh::Polyhedron::is_valid (HalfedgeId id) const nodiscard noexcept
Check whether a halfedge id resolves to a live halfedge.
Parameters
id Halfedge id to test.
Returns
True when the id is live and generation-matched.
Definition at line 435 of file polyhedron.cpp.
References is_valid().
is_valid() [4/4]
bool quader::mesh::Polyhedron::is_valid (VertexId id) const nodiscard noexcept
Check whether a vertex id resolves to a live vertex.
Parameters
id Vertex id to test.
Returns
True when the id is live and generation-matched.
Definition at line 427 of file polyhedron.cpp.
References is_valid().
Referenced by compact_storage(), create_face(), delete_face(), delete_vertex(), edge_halfedges(), face_halfedges(), halfedge_edge(), halfedge_face(), halfedge_origin(), halfedge_target(), is_boundary_halfedge(), is_valid(), is_valid(), is_valid(), is_valid(), next_halfedge(), operator=(), opposite_halfedge(), previous_halfedge(), set_vertex_position(), vertex_attribute(), vertex_attribute(), vertex_outgoing_halfedge(), and vertex_position().
next_halfedge()
quader::foundation::Result< HalfedgeId, MeshError > quader::mesh::Polyhedron::next_halfedge (HalfedgeId halfedge) const nodiscard
Return the next halfedge in a cycle.
Definition at line 577 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidHalfedge, is_valid(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by operator=().
operator=() [1/2]
Polyhedron & quader::mesh::Polyhedron::operator= (const Polyhedron & other)
Deep-copy mesh topology, positions, mappings, and attributes.
Definition at line 149 of file polyhedron.cpp.
References Polyhedron().
operator=() [2/2]
Polyhedron & quader::mesh::Polyhedron::operator= (Polyhedron &&) default noexcept
Move mesh storage and attributes.
References attributes(), compact_storage(), create_face(), create_vertex(), delete_face(), delete_vertex(), edge_count(), edge_halfedges(), edge_ids(), face_count(), face_halfedges(), face_ids(), halfedge_count(), halfedge_edge(), halfedge_face(), halfedge_ids(), halfedge_origin(), halfedge_target(), is_boundary_halfedge(), is_valid(), next_halfedge(), opposite_halfedge(), Polyhedron(), previous_halfedge(), set_vertex_position(), vertex_count(), vertex_ids(), vertex_outgoing_halfedge(), and vertex_position().
opposite_halfedge()
quader::foundation::Result< HalfedgeId, MeshError > quader::mesh::Polyhedron::opposite_halfedge (HalfedgeId halfedge) const nodiscard
Return the opposite halfedge.
Definition at line 561 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidHalfedge, is_valid(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by delete_face(), and operator=().
previous_halfedge()
quader::foundation::Result< HalfedgeId, MeshError > quader::mesh::Polyhedron::previous_halfedge (HalfedgeId halfedge) const nodiscard
Return the previous halfedge in a cycle.
Definition at line 599 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidHalfedge, is_valid(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by operator=().
set_vertex_position()
quader::foundation::Result< void, MeshError > quader::mesh::Polyhedron::set_vertex_position (VertexId vertex, quader::math::Vec3 position) nodiscard
Set a vertex position.
Parameters
vertex Vertex to mutate.
position New position.
Returns
Success, or an invalid-vertex error.
Definition at line 500 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidVertex, quader::math::is_finite(), is_valid(), quader::mesh::make_mesh_error(), quader::mesh::NonFinitePosition, and quader::foundation::Result< T, E >::success().
Referenced by operator=().
vertex_attribute() [1/2]
template<class T> quader::foundation::Result< T *, MeshError > quader::mesh::Polyhedron::vertex_attribute (AttributeId attribute, VertexId vertex) inline nodiscard
Access a mutable vertex attribute value.
Template Parameters
T Expected attribute value type.
Parameters
attribute Attribute id to resolve.
vertex Vertex whose slot is accessed.
Returns
Pointer valid until attribute storage mutation, or a mesh error.
Definition at line 234 of file polyhedron.hpp.
References quader::foundation::Result< T, E >::failure(), quader::mesh::InvalidVertex, is_valid(), quader::mesh::make_mesh_error(), and vertex_attribute().
Referenced by vertex_attribute().
vertex_attribute() [2/2]
template<class T> quader::foundation::Result< const T *, MeshError > quader::mesh::Polyhedron::vertex_attribute (AttributeId attribute, VertexId vertex) const inline nodiscard
Access an immutable vertex attribute value.
Template Parameters
T Expected attribute value type.
Parameters
attribute Attribute id to resolve.
vertex Vertex whose slot is accessed.
Returns
Pointer valid until attribute storage mutation, or a mesh error.
Definition at line 254 of file polyhedron.hpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidVertex, is_valid(), and quader::mesh::make_mesh_error().
vertex_count()
std::size_t quader::mesh::Polyhedron::vertex_count () const nodiscard noexcept
Return the number of live vertices.
Definition at line 459 of file polyhedron.cpp.
Referenced by compact_storage(), and operator=().
vertex_ids()
std::vector< VertexId > quader::mesh::Polyhedron::vertex_ids () const nodiscard
Return all live vertex IDs.
Definition at line 475 of file polyhedron.cpp.
Referenced by operator=().
vertex_outgoing_halfedge()
quader::foundation::Result< HalfedgeId, MeshError > quader::mesh::Polyhedron::vertex_outgoing_halfedge (VertexId vertex) const nodiscard
Return one outgoing halfedge for a vertex.
Definition at line 515 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidHalfedge, quader::mesh::InvalidVertex, is_valid(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by operator=().
vertex_position()
quader::foundation::Result< quader::math::Vec3, MeshError > quader::mesh::Polyhedron::vertex_position (VertexId vertex) const nodiscard
Return a vertex position.
Parameters
vertex Vertex to query.
Returns
Position, or an invalid-vertex error.
Definition at line 491 of file polyhedron.cpp.
References quader::foundation::Result< T, E >::failure(), quader::foundation::GenerationalId< Tag >::index(), quader::mesh::InvalidVertex, is_valid(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by operator=().
Friends And Related Symbol Documentation
validate_mesh
MeshValidationReport validate_mesh (const Polyhedron & mesh) friend
Validate mesh topology, mappings, attributes, and geometry invariants.
Parameters
mesh Mesh to inspect.
Returns
Validation report containing every issue detected by the pass.
Definition at line 116 of file mesh_validation.cpp.
References quader::mesh::MeshValidationReport::add_issue(), quader::geometry::all_points_finite(), quader::mesh::BoundaryPlaceholderMismatch, quader::mesh::BrokenNextPrevCycle, quader::mesh::BrokenOppositePair, quader::mesh::DegenerateFace, quader::mesh::EdgeReferenceMismatch, quader::mesh::FaceCycleMismatch, quader::geometry::has_degenerate_area(), quader::mesh::InvalidId, quader::math::is_finite(), quader::mesh::NonFinitePosition, Polyhedron(), and quader::mesh::VertexReferenceMismatch.
Referenced by compact_storage().
The documentation for this class was generated from the following files:
src/mesh/core/polyhedron.hpp
src/mesh/core/polyhedron.cpp