Quader: quader::ui::DiagnosticsPanel Class Reference
quader::ui::DiagnosticsPanel Class Reference final
Dockable panel that displays renderer diagnostics and frame stats.
#include <diagnostics_panel.hpp>
Public Member Functions
DiagnosticsPanel (PanelContext context, QWidget *parent=nullptr)
Construct the diagnostics panel with non-owning UI service context.
DiagnosticsItemModel & model () noexcept
Return the diagnostics model owned by the panel.
QTreeView & tree_view () noexcept
Return the tree view owned by the panel.
Protected Member Functions
void showEvent (QShowEvent *event) override
Refresh diagnostics when the panel is shown.
Detailed Description
Dockable panel that displays renderer diagnostics and frame stats.
Definition at line 27 of file diagnostics_panel.hpp.
Constructor & Destructor Documentation
DiagnosticsPanel()
quader::ui::DiagnosticsPanel::DiagnosticsPanel (PanelContext context, QWidget * parent = nullptr) explicit
Construct the diagnostics panel with non-owning UI service context.
Definition at line 33 of file diagnostics_panel.cpp.
References quader::ui::ViewportDiagnosticsService::diagnostics_unavailable(), quader::ui::ViewportDiagnosticsService::refresh(), and quader::ui::ViewportDiagnosticsService::summary_changed().
Member Function Documentation
model()
DiagnosticsItemModel & quader::ui::DiagnosticsPanel::model () nodiscard noexcept
Return the diagnostics model owned by the panel.
Definition at line 88 of file diagnostics_panel.cpp.
showEvent()
void quader::ui::DiagnosticsPanel::showEvent (QShowEvent * event) override protected
Refresh diagnostics when the panel is shown.
Definition at line 96 of file diagnostics_panel.cpp.
tree_view()
QTreeView & quader::ui::DiagnosticsPanel::tree_view () nodiscard noexcept
Return the tree view owned by the panel.
Definition at line 92 of file diagnostics_panel.cpp.
The documentation for this class was generated from the following files:
src/ui/panels/diagnostics_panel.hpp
src/ui/panels/diagnostics_panel.cpp