Quader: quader::document::Selection Class Reference
quader::document::Selection Class Reference final
#include <selection.hpp>
Public Member Functions
bool empty () const noexcept
Return true when no objects or components are selected.
void clear ()
Clear object and component selection.
quader::foundation::Result< void, DocumentError > set_objects (std::vector< ObjectId > objects)
quader::foundation::Result< void, DocumentError > set_components (std::vector< ComponentRef > components)
std::span< const ObjectId > selected_objects () const noexcept
Borrow selected object ids until the next mutation of this selection.
std::span< const ComponentRef > selected_components () const noexcept
Borrow selected component refs until the next mutation of this selection.
bool references_object (ObjectId object) const noexcept
Return true when object or component selection references object.
void remove_object (ObjectId object)
Remove selected object refs and component refs owned by object.
Friends
bool operator== (const Selection &, const Selection &)=default
Detailed Description
Stores either object selection or component selection for a document.
Object and component selections are mutually exclusive. Setters validate structural id validity, sort inputs, and remove duplicates.
Definition at line 61 of file selection.hpp.
Member Function Documentation
clear()
void quader::document::Selection::clear ()
Clear object and component selection.
Definition at line 81 of file selection.cpp.
empty()
bool quader::document::Selection::empty () const nodiscard noexcept
Return true when no objects or components are selected.
Definition at line 77 of file selection.cpp.
references_object()
bool quader::document::Selection::references_object (ObjectId object) const nodiscard noexcept
Return true when object or component selection references object.
Definition at line 134 of file selection.cpp.
remove_object()
void quader::document::Selection::remove_object (ObjectId object)
Remove selected object refs and component refs owned by object.
Definition at line 144 of file selection.cpp.
selected_components()
std::span< const ComponentRef > quader::document::Selection::selected_components () const nodiscard noexcept
Borrow selected component refs until the next mutation of this selection.
Definition at line 130 of file selection.cpp.
selected_objects()
std::span< const ObjectId > quader::document::Selection::selected_objects () const nodiscard noexcept
Borrow selected object ids until the next mutation of this selection.
Definition at line 126 of file selection.cpp.
set_components()
quader::foundation::Result< void, DocumentError > quader::document::Selection::set_components (std::vector< ComponentRef > components) nodiscard
Replace selection with component references.
Parameters
components Component references to select.
Returns
Success, or a document error for any structurally invalid id.
Definition at line 103 of file selection.cpp.
References quader::document::component_id_is_valid(), quader::document::component_kind(), quader::foundation::Result< T, E >::failure(), quader::document::InvalidObject, quader::document::make_document_error(), and quader::foundation::Result< T, E >::success().
set_objects()
quader::foundation::Result< void, DocumentError > quader::document::Selection::set_objects (std::vector< ObjectId > objects) nodiscard
Replace selection with object ids.
Parameters
objects Object ids to select.
Returns
Success, or InvalidObject when any id is structurally invalid.
Definition at line 86 of file selection.cpp.
References quader::foundation::Result< T, E >::failure(), quader::document::InvalidObject, quader::document::make_document_error(), and quader::foundation::Result< T, E >::success().
Friends And Related Symbol Documentation
operator==
bool operator== (const Selection & , const Selection &) friend
The documentation for this class was generated from the following files:
src/document/selection.hpp
src/document/selection.cpp