Quader: quader::commands::ICommand Class Reference
quader::commands::ICommand Class Reference abstract
#include <command.hpp>
Public Member Functions
virtual ~ICommand ()=default
Destroy a command through the base interface.
virtual std::string_view name () const noexcept=0
virtual CommandResult execute (quader::document::Document &document)=0
virtual CommandResult undo (quader::document::Document &document)=0
virtual bool can_merge_with (const ICommand &next) const noexcept
virtual CommandResult merge_with (std::unique_ptr< ICommand > next)
Detailed Description
Base interface for undoable document commands.
Commands are the mutation boundary for user-visible document edits. Concrete commands mutate a Document in execute() and restore prior state in undo().
Definition at line 27 of file command.hpp.
Constructor & Destructor Documentation
~ICommand()
virtual quader::commands::ICommand::~ICommand () virtual default
Destroy a command through the base interface.
Member Function Documentation
can_merge_with()
bool quader::commands::ICommand::can_merge_with (const ICommand & next) const nodiscard virtual noexcept
Check whether a later command can be merged into this command.
Parameters
next Later command proposed for merge.
Returns
True when merge_with() may consume next.
Definition at line 14 of file command.cpp.
Referenced by undo().
execute()
virtual CommandResult quader::commands::ICommand::execute (quader::document::Document & document) nodiscard pure virtual
Apply the command to a document.
Parameters
document Document to mutate.
Returns
Command result with diagnostics for rejected operations.
Implemented in quader::commands::ClearSelectionCommand, quader::commands::CreateMeshObjectCommand, quader::commands::DeleteObjectCommand, quader::commands::RenameObjectCommand, quader::commands::SetObjectTransformCommand, and quader::commands::SetSelectionCommand.
References execute().
Referenced by execute().
merge_with()
CommandResult quader::commands::ICommand::merge_with (std::unique_ptr< ICommand > next) nodiscard virtual
Merge a later command into this command.
Parameters
next Later command to consume.
Returns
CommandStatus::NotMergeable when the merge is rejected.
Definition at line 19 of file command.cpp.
References quader::commands::CommandResult::not_mergeable().
Referenced by undo().
name()
virtual std::string_view quader::commands::ICommand::name () const nodiscard pure virtual noexcept
Return the display name used by undo/redo UI.
Returns
Borrowed command name valid for the command lifetime.
Implemented in quader::commands::ClearSelectionCommand, quader::commands::CreateMeshObjectCommand, quader::commands::DeleteObjectCommand, quader::commands::RenameObjectCommand, quader::commands::SetObjectTransformCommand, and quader::commands::SetSelectionCommand.
undo()
virtual CommandResult quader::commands::ICommand::undo (quader::document::Document & document) nodiscard pure virtual
Undo a previously applied command.
Parameters
document Document to mutate back toward its previous state.
Returns
Command result with diagnostics for undo failures.
Implemented in quader::commands::ClearSelectionCommand, quader::commands::CreateMeshObjectCommand, quader::commands::DeleteObjectCommand, quader::commands::RenameObjectCommand, quader::commands::SetObjectTransformCommand, and quader::commands::SetSelectionCommand.
References can_merge_with(), merge_with(), and undo().
Referenced by undo().
The documentation for this class was generated from the following files:
src/commands/command.hpp
src/commands/command.cpp