Quader: quader::mesh::MeshAttributes Class Reference
quader::mesh::MeshAttributes Class Reference final
#include <mesh_attributes.hpp>
Public Member Functions
MeshAttributes ()=default
Create an empty attribute collection.
MeshAttributes (const MeshAttributes &other)
MeshAttributes & operator= (const MeshAttributes &other)
MeshAttributes (MeshAttributes &&) noexcept=default
Move an attribute collection.
MeshAttributes & operator= (MeshAttributes &&) noexcept=default
Move-assign an attribute collection.
template<class T>
quader::foundation::Result< AttributeId, MeshError > create (AttributeDomain domain, std::string name, T default_value)
std::size_t attribute_count () const noexcept
const AttributeDescriptor * descriptor (AttributeId id) const noexcept
template<class T>
quader::foundation::Result< T *, MeshError > value (AttributeId id, quader::foundation::IdIndex slot)
template<class T>
quader::foundation::Result< const T *, MeshError > value (AttributeId id, quader::foundation::IdIndex slot) const
void resize_domain (AttributeDomain domain, std::size_t size)
void reset_slot_to_defaults (AttributeDomain domain, quader::foundation::IdIndex slot)
Detailed Description
Owns typed attribute arrays for mesh element domains.
Attribute arrays are resized by domain and keep a default value used for new slots or slot reset. Attribute IDs are index-only and remain valid while their storage slot exists.
Definition at line 122 of file mesh_attributes.hpp.
Constructor & Destructor Documentation
MeshAttributes() [1/3]
quader::mesh::MeshAttributes::MeshAttributes () default
Create an empty attribute collection.
Referenced by MeshAttributes(), MeshAttributes(), operator=(), and operator=().
MeshAttributes() [2/3]
quader::mesh::MeshAttributes::MeshAttributes (const MeshAttributes & other) inline
Deep-copy all attribute storage.
Parameters
other Attribute collection to copy.
Definition at line 132 of file mesh_attributes.hpp.
References MeshAttributes().
MeshAttributes() [3/3]
quader::mesh::MeshAttributes::MeshAttributes (MeshAttributes &&) default noexcept
Move an attribute collection.
References MeshAttributes().
Member Function Documentation
attribute_count()
std::size_t quader::mesh::MeshAttributes::attribute_count () const inline nodiscard noexcept
Return the number of attribute arrays.
Returns
Attribute storage count.
Definition at line 202 of file mesh_attributes.hpp.
create()
template<class T> quader::foundation::Result< AttributeId, MeshError > quader::mesh::MeshAttributes::create (AttributeDomain domain, std::string name, T default_value) inline nodiscard
Create a typed attribute array.
Template Parameters
T Supported attribute value type.
Parameters
domain Mesh element domain indexed by the attribute.
name Name unique within domain.
default_value Value used for all current and future slots.
Returns
Attribute id, or an error when the name already exists.
Definition at line 176 of file mesh_attributes.hpp.
References quader::mesh::AttributeNameAlreadyExists, create(), quader::foundation::Result< T, E >::failure(), quader::mesh::AttributeValueTraits< T >::kSupported, quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
Referenced by create().
descriptor()
const AttributeDescriptor * quader::mesh::MeshAttributes::descriptor (AttributeId id) const inline nodiscard noexcept
Find an attribute descriptor.
Parameters
id Attribute id to resolve.
Returns
Pointer valid until mutation, or nullptr for invalid ids.
Definition at line 212 of file mesh_attributes.hpp.
operator=() [1/2]
MeshAttributes & quader::mesh::MeshAttributes::operator= (const MeshAttributes & other) inline
Deep-copy all attribute storage.
Parameters
other Attribute collection to copy.
Returns
This collection.
Definition at line 145 of file mesh_attributes.hpp.
References MeshAttributes().
operator=() [2/2]
MeshAttributes & quader::mesh::MeshAttributes::operator= (MeshAttributes &&) default noexcept
Move-assign an attribute collection.
References MeshAttributes().
reset_slot_to_defaults()
void quader::mesh::MeshAttributes::reset_slot_to_defaults (AttributeDomain domain, quader::foundation::IdIndex slot) inline
Reset a domain slot to each attribute array's default value.
Parameters
domain Domain containing slot.
slot Slot index to reset when present.
Definition at line 293 of file mesh_attributes.hpp.
resize_domain()
void quader::mesh::MeshAttributes::resize_domain (AttributeDomain domain, std::size_t size) inline
Resize all attribute arrays for a domain.
Parameters
domain Domain whose arrays are resized.
size New slot count.
Definition at line 278 of file mesh_attributes.hpp.
value() [1/2]
template<class T> quader::foundation::Result< T *, MeshError > quader::mesh::MeshAttributes::value (AttributeId id, quader::foundation::IdIndex slot) inline nodiscard
Access a mutable attribute slot.
Template Parameters
T Expected attribute value type.
Parameters
id Attribute id to resolve.
slot Domain slot index.
Returns
Pointer valid until attribute storage mutation, or an error.
Definition at line 229 of file mesh_attributes.hpp.
References quader::mesh::AttributeIndexOutOfRange, quader::mesh::AttributeTypeMismatch, quader::foundation::Result< T, E >::failure(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
value() [2/2]
template<class T> quader::foundation::Result< const T *, MeshError > quader::mesh::MeshAttributes::value (AttributeId id, quader::foundation::IdIndex slot) const inline nodiscard
Access an immutable attribute slot.
Template Parameters
T Expected attribute value type.
Parameters
id Attribute id to resolve.
slot Domain slot index.
Returns
Pointer valid until attribute storage mutation, or an error.
Definition at line 255 of file mesh_attributes.hpp.
References quader::mesh::AttributeIndexOutOfRange, quader::mesh::AttributeTypeMismatch, quader::foundation::Result< T, E >::failure(), quader::mesh::make_mesh_error(), and quader::foundation::Result< T, E >::success().
The documentation for this class was generated from the following file:
src/mesh/core/mesh_attributes.hpp