Quader: crimson::BaseShaderRegistry Class Reference
crimson::BaseShaderRegistry Class Reference final
Immutable lookup table for Crimson base shader definitions.
#include <base_shader_registry.hpp>
Public Member Functions
BaseShaderRegistry ()=default
Construct an empty registry.
BaseShaderRegistry (std::vector< BaseShaderDefinition > definitions)
Construct a registry from owned definitions.
const BaseShaderDefinition * find (BaseShaderId id) const noexcept
Find a base shader definition by id, or return nullptr.
std::span< const BaseShaderDefinition > definitions () const noexcept
Borrow all definitions owned by this registry.
bool empty () const noexcept
Return true when the registry contains no definitions.
Detailed Description
Immutable lookup table for Crimson base shader definitions.
Definition at line 20 of file base_shader_registry.hpp.
Constructor & Destructor Documentation
BaseShaderRegistry() [1/2]
crimson::BaseShaderRegistry::BaseShaderRegistry () default
Construct an empty registry.
References BaseShaderRegistry(), definitions(), empty(), and crimson::make_v1_base_shader_registry().
Referenced by BaseShaderRegistry().
BaseShaderRegistry() [2/2]
crimson::BaseShaderRegistry::BaseShaderRegistry (std::vector< BaseShaderDefinition > definitions) explicit
Construct a registry from owned definitions.
Definition at line 282 of file base_shader_registry.cpp.
References definitions().
Member Function Documentation
definitions()
std::span< const BaseShaderDefinition > crimson::BaseShaderRegistry::definitions () const nodiscard noexcept
Borrow all definitions owned by this registry.
Definition at line 295 of file base_shader_registry.cpp.
Referenced by BaseShaderRegistry(), and BaseShaderRegistry().
empty()
bool crimson::BaseShaderRegistry::empty () const nodiscard noexcept
Return true when the registry contains no definitions.
Definition at line 299 of file base_shader_registry.cpp.
Referenced by BaseShaderRegistry().
find()
const BaseShaderDefinition * crimson::BaseShaderRegistry::find (BaseShaderId id) const nodiscard noexcept
Find a base shader definition by id, or return nullptr.
Definition at line 285 of file base_shader_registry.cpp.
Referenced by quader::io::gltf::map_gltf_material_to_crimson(), and crimson::validate_material_instance().
The documentation for this class was generated from the following files:
src/crimson/material/base_shader_registry.hpp
src/crimson/material/base_shader_registry.cpp