Quader: quader::tools::ToolManager Class Reference
quader::tools::ToolManager Class Reference final
Owns registered editor tools and forwards host input to the active tool.
#include <tool_manager.hpp>
Public Member Functions
ToolManager (ToolContext context)
bool register_tool (std::unique_ptr< ITool > tool)
bool has_tool (ToolId id) const noexcept
Return true when a tool with the id is registered.
std::optional< ToolId > active_tool_id () const noexcept
Return the active tool id, or no value when no tool is active.
ITool * active_tool () noexcept
Return the active tool, or null when no tool is active.
const ITool * active_tool () const noexcept
Return the active tool, or null when no tool is active.
bool set_active_tool (ToolId id)
void clear_active_tool ()
Deactivate and clear the current active tool.
bool cancel_active_tool ()
Cancel the active tool interaction without changing the active tool.
bool dispatch_pointer_event (const PointerEvent &event)
Dispatch a pointer event to the active tool.
bool dispatch_key_event (const KeyEvent &event)
Dispatch a key event to the active tool.
ToolPreview preview () const
Return the active tool preview, or an empty preview when no tool is active.
ToolContext & context () noexcept
Return the shared tool context.
const ToolContext & context () const noexcept
Return the shared tool context.
Detailed Description
Owns registered editor tools and forwards host input to the active tool.
Definition at line 25 of file tool_manager.hpp.
Constructor & Destructor Documentation
ToolManager()
quader::tools::ToolManager::ToolManager (ToolContext context) explicit
Construct a manager with the services shared by all registered tools.
Parameters
context Document and command-history services retained by the manager.
Definition at line 16 of file tool_manager.cpp.
References context().
Member Function Documentation
active_tool() [1/2]
const ITool * quader::tools::ToolManager::active_tool () const nodiscard noexcept
Return the active tool, or null when no tool is active.
Definition at line 49 of file tool_manager.cpp.
active_tool() [2/2]
ITool * quader::tools::ToolManager::active_tool () nodiscard noexcept
Return the active tool, or null when no tool is active.
Definition at line 45 of file tool_manager.cpp.
active_tool_id()
std::optional< ToolId > quader::tools::ToolManager::active_tool_id () const nodiscard noexcept
Return the active tool id, or no value when no tool is active.
Definition at line 37 of file tool_manager.cpp.
cancel_active_tool()
bool quader::tools::ToolManager::cancel_active_tool () nodiscard
Cancel the active tool interaction without changing the active tool.
Definition at line 82 of file tool_manager.cpp.
clear_active_tool()
void quader::tools::ToolManager::clear_active_tool ()
Deactivate and clear the current active tool.
Definition at line 73 of file tool_manager.cpp.
context() [1/2]
const ToolContext & quader::tools::ToolManager::context () const nodiscard noexcept
Return the shared tool context.
Definition at line 119 of file tool_manager.cpp.
context() [2/2]
ToolContext & quader::tools::ToolManager::context () nodiscard noexcept
Return the shared tool context.
Definition at line 115 of file tool_manager.cpp.
Referenced by ToolManager().
dispatch_key_event()
bool quader::tools::ToolManager::dispatch_key_event (const KeyEvent & event) nodiscard
Dispatch a key event to the active tool.
Definition at line 99 of file tool_manager.cpp.
dispatch_pointer_event()
bool quader::tools::ToolManager::dispatch_pointer_event (const PointerEvent & event) nodiscard
Dispatch a pointer event to the active tool.
Definition at line 91 of file tool_manager.cpp.
has_tool()
bool quader::tools::ToolManager::has_tool (ToolId id) const nodiscard noexcept
Return true when a tool with the id is registered.
Definition at line 33 of file tool_manager.cpp.
preview()
ToolPreview quader::tools::ToolManager::preview () const nodiscard
Return the active tool preview, or an empty preview when no tool is active.
Definition at line 107 of file tool_manager.cpp.
register_tool()
bool quader::tools::ToolManager::register_tool (std::unique_ptr< ITool > tool) nodiscard
Register a tool by its stable id.
Parameters
tool Tool instance to take ownership of.
Returns
True when the tool was non-null and no tool with the same id existed.
Definition at line 19 of file tool_manager.cpp.
set_active_tool()
bool quader::tools::ToolManager::set_active_tool (ToolId id) nodiscard
Activate a registered tool and deactivate the previous active tool.
Parameters
id Tool id to activate.
Returns
True when the tool was registered.
Definition at line 53 of file tool_manager.cpp.
References quader::tools::ITool::activate().
The documentation for this class was generated from the following files:
src/tools/tool_manager.hpp
src/tools/tool_manager.cpp