Quader: crimson::gpu::GpuProgramCache Class Reference
crimson::gpu::GpuProgramCache Class Reference final
Loads and owns GPU shader programs keyed by Crimson program ids.
#include <gpu_program_cache.hpp>
Public Member Functions
RenderProgramHandle load_program (const ShaderLibrary &library, ShaderProgramId program, ShaderTarget target, RendererStatus &status)
bgfx::ProgramHandle program (RenderProgramHandle handle) const noexcept
RenderProgramHandle cached_handle (ShaderProgramId program) const noexcept
std::size_t live_program_count () const noexcept
Return the number of live GPU programs.
void clear () noexcept
Destroy all loaded GPU programs.
Detailed Description
Loads and owns GPU shader programs keyed by Crimson program ids.
Definition at line 23 of file gpu_program_cache.hpp.
Member Function Documentation
cached_handle()
RenderProgramHandle crimson::gpu::GpuProgramCache::cached_handle (ShaderProgramId program) const nodiscard noexcept
Return the cached handle for a program id.
Parameters
program Program id to resolve.
Returns
Cached public handle, or invalid handle when not loaded.
Definition at line 78 of file gpu_program_cache.cpp.
References program().
clear()
void crimson::gpu::GpuProgramCache::clear () noexcept
Destroy all loaded GPU programs.
Definition at line 87 of file gpu_program_cache.cpp.
live_program_count()
std::size_t crimson::gpu::GpuProgramCache::live_program_count () const nodiscard noexcept
Return the number of live GPU programs.
Definition at line 83 of file gpu_program_cache.cpp.
load_program()
RenderProgramHandle crimson::gpu::GpuProgramCache::load_program (const ShaderLibrary & library, ShaderProgramId program, ShaderTarget target, RendererStatus & status) nodiscard
Load or return a cached program.
Parameters
library Shader library used to resolve compiled shader binaries.
program Program identifier.
target Compiled shader target.
status Status receiving diagnostics.
Returns
Public program handle, or invalid handle on failure.
Definition at line 41 of file gpu_program_cache.cpp.
References crimson::RendererStatus::diagnostics, crimson::gpu::Fragment, crimson::gpu::load_shader(), program(), and crimson::gpu::Vertex.
program()
bgfx::ProgramHandle crimson::gpu::GpuProgramCache::program (RenderProgramHandle handle) const nodiscard noexcept
Resolve a bgfx program handle.
Parameters
handle Public program handle.
Returns
bgfx program handle, or invalid handle for missing/stale entries.
Definition at line 71 of file gpu_program_cache.cpp.
Referenced by cached_handle(), load_program(), and crimson::gpu::GpuPicking::submit_frame_requests().
The documentation for this class was generated from the following files:
src/crimson/gpu/gpu_program_cache.hpp
src/crimson/gpu/gpu_program_cache.cpp