Quader: quader::commands::SetSelectionCommand Class Reference
quader::commands::SetSelectionCommand Class Reference final
Command that replaces the document selection and can restore the prior selection.
#include <selection_commands.hpp>
Public Member Functions
SetSelectionCommand (quader::document::Selection selection)
std::string_view name () const noexcept override
CommandResult execute (quader::document::Document &document) override
CommandResult undo (quader::document::Document &document) override
Public Member Functions inherited from quader::commands::ICommand
virtual ~ICommand ()=default
Destroy a command through the base interface.
virtual bool can_merge_with (const ICommand &next) const noexcept
virtual CommandResult merge_with (std::unique_ptr< ICommand > next)
Detailed Description
Command that replaces the document selection and can restore the prior selection.
Definition at line 21 of file selection_commands.hpp.
Constructor & Destructor Documentation
SetSelectionCommand()
quader::commands::SetSelectionCommand::SetSelectionCommand (quader::document::Selection selection) explicit
Create a selection replacement command.
Parameters
selection Selection stored and later applied by execute().
Definition at line 23 of file selection_commands.cpp.
Member Function Documentation
execute()
CommandResult quader::commands::SetSelectionCommand::execute (quader::document::Document & document) nodiscard override virtual
Replace the document selection.
Parameters
document Document to mutate.
Returns
Applied result after storing the previous selection.
Implements quader::commands::ICommand.
Definition at line 30 of file selection_commands.cpp.
References quader::commands::CommandResult::applied(), and quader::commands::CommandResult::rejected().
name()
std::string_view quader::commands::SetSelectionCommand::name () const nodiscard override virtual noexcept
Return the display name used by undo/redo UI.
Returns
Static command name.
Implements quader::commands::ICommand.
Definition at line 26 of file selection_commands.cpp.
undo()
CommandResult quader::commands::SetSelectionCommand::undo (quader::document::Document & document) nodiscard override virtual
Restore the selection captured during execute().
Parameters
document Document to mutate.
Returns
Applied result when a previous selection was captured.
Implements quader::commands::ICommand.
Definition at line 46 of file selection_commands.cpp.
References quader::commands::CommandResult::applied(), and quader::commands::CommandResult::rejected().
The documentation for this class was generated from the following files:
src/commands/selection_commands.hpp
src/commands/selection_commands.cpp