Quader: quader::io::IoDiagnosticList Class Reference
quader::io::IoDiagnosticList Class Reference final
Ordered collection of import/export diagnostics.
#include <io_diagnostic.hpp>
Public Types
using container_type = std::vector<IoDiagnostic>
Container type used to store diagnostics.
using const_iterator = container_type::const_iterator
Constant iterator over stored diagnostics.
Public Member Functions
void add (IoDiagnostic diagnostic)
void add (IoSeverity severity, IoDiagnosticCode code, std::string message)
void add_error (IoDiagnosticCode code, std::string message)
void append (const IoDiagnosticList &diagnostics)
void clear () noexcept
Remove all diagnostics.
bool empty () const noexcept
Return true when no diagnostics are stored.
bool has_errors () const noexcept
Return true when at least one diagnostic has IoSeverity::Error.
std::size_t size () const noexcept
Return the number of stored diagnostics.
std::span< const IoDiagnostic > diagnostics () const noexcept
Return a borrowed span of stored diagnostics.
const IoDiagnostic & operator[] (std::size_t index) const noexcept
const_iterator begin () const noexcept
Return an iterator to the first diagnostic.
const_iterator end () const noexcept
Return an iterator one past the last diagnostic.
Detailed Description
Ordered collection of import/export diagnostics.
Definition at line 88 of file io_diagnostic.hpp.
Member Typedef Documentation
const_iterator
using quader::io::IoDiagnosticList::const_iterator = container_type::const_iterator
Constant iterator over stored diagnostics.
Definition at line 93 of file io_diagnostic.hpp.
container_type
using quader::io::IoDiagnosticList::container_type = std::vector<IoDiagnostic>
Container type used to store diagnostics.
Definition at line 91 of file io_diagnostic.hpp.
Member Function Documentation
add() [1/2]
void quader::io::IoDiagnosticList::add (IoDiagnostic diagnostic)
Append a diagnostic.
Parameters
diagnostic Diagnostic to append.
Definition at line 16 of file io_diagnostic.cpp.
Referenced by add(), add_error(), quader::io::build_document_from_import(), and quader::io::make_io_error().
add() [2/2]
void quader::io::IoDiagnosticList::add (IoSeverity severity, IoDiagnosticCode code, std::string message)
Append a diagnostic from fields.
Parameters
severity Severity assigned to the diagnostic.
code Diagnostic category.
message Message to store.
Definition at line 20 of file io_diagnostic.cpp.
References add().
add_error()
void quader::io::IoDiagnosticList::add_error (IoDiagnosticCode code, std::string message)
Append an error diagnostic.
Parameters
code Diagnostic category.
message Error message to store.
Definition at line 24 of file io_diagnostic.cpp.
References add(), and quader::io::Error.
append()
void quader::io::IoDiagnosticList::append (const IoDiagnosticList & diagnostics)
Append diagnostics from another list.
Parameters
diagnostics Diagnostics copied into this list.
Definition at line 28 of file io_diagnostic.cpp.
References diagnostics().
Referenced by quader::io::build_document_from_import(), and quader::io::gltf::map_gltf_material_to_crimson().
begin()
IoDiagnosticList::const_iterator quader::io::IoDiagnosticList::begin () const nodiscard noexcept
Return an iterator to the first diagnostic.
Definition at line 62 of file io_diagnostic.cpp.
clear()
void quader::io::IoDiagnosticList::clear () noexcept
Remove all diagnostics.
Definition at line 32 of file io_diagnostic.cpp.
diagnostics()
std::span< const IoDiagnostic > quader::io::IoDiagnosticList::diagnostics () const nodiscard noexcept
Return a borrowed span of stored diagnostics.
Definition at line 54 of file io_diagnostic.cpp.
Referenced by append().
empty()
bool quader::io::IoDiagnosticList::empty () const nodiscard noexcept
Return true when no diagnostics are stored.
Definition at line 36 of file io_diagnostic.cpp.
end()
IoDiagnosticList::const_iterator quader::io::IoDiagnosticList::end () const nodiscard noexcept
Return an iterator one past the last diagnostic.
Definition at line 66 of file io_diagnostic.cpp.
has_errors()
bool quader::io::IoDiagnosticList::has_errors () const nodiscard noexcept
Return true when at least one diagnostic has IoSeverity::Error.
Definition at line 40 of file io_diagnostic.cpp.
References quader::io::Error.
Referenced by quader::io::build_document_from_import(), and quader::io::ImportService::import_file().
operator[]()
const IoDiagnostic & quader::io::IoDiagnosticList::operator[] (std::size_t index) const nodiscard noexcept
Access a diagnostic by index.
Parameters
index Zero-based diagnostic index.
Returns
Diagnostic at index.
Definition at line 58 of file io_diagnostic.cpp.
size()
std::size_t quader::io::IoDiagnosticList::size () const nodiscard noexcept
Return the number of stored diagnostics.
Definition at line 50 of file io_diagnostic.cpp.
The documentation for this class was generated from the following files:
src/io/io_diagnostic.hpp
src/io/io_diagnostic.cpp