Quader: quader::ui::DocumentItemModel Class Reference
quader::ui::DocumentItemModel Class Reference final
Qt item model presenting document objects without owning document state.
#include <document_item_model.hpp>
Public Slots
void rebuild_from_document ()
Rebuild presentation rows from the current document.
void refresh_object (quader::document::ObjectId object)
Refresh one object row if it is visible.
void refresh_selection ()
Refresh selection roles for visible rows.
Public Member Functions
DocumentItemModel (DocumentUiController &documents, QObject *parent=nullptr)
Construct a model backed by a non-owning document UI controller reference.
QModelIndex index (int row, int column, const QModelIndex &parent={}) const override
Return a model index for a row, column, and parent.
QModelIndex parent (const QModelIndex &child) const override
Return the parent index for child.
int rowCount (const QModelIndex &parent={}) const override
Return row count for parent.
int columnCount (const QModelIndex &parent={}) const override
Return column count for parent.
QVariant data (const QModelIndex &index, int role) const override
Return model data for index and role.
bool setData (const QModelIndex &index, const QVariant &value, int role) override
Dispatch editable changes through document commands.
Qt::ItemFlags flags (const QModelIndex &index) const override
Return item flags for index.
QVariant headerData (int section, Qt::Orientation orientation, int role) const override
Return horizontal header text.
QModelIndex index_for_object (quader::document::ObjectId object, int column=static_cast< int >(DocumentItemColumn::Name)) const
Detailed Description
Qt item model presenting document objects without owning document state.
Definition at line 33 of file document_item_model.hpp.
Constructor & Destructor Documentation
DocumentItemModel()
quader::ui::DocumentItemModel::DocumentItemModel (DocumentUiController & documents, QObject * parent = nullptr) explicit
Construct a model backed by a non-owning document UI controller reference.
Definition at line 39 of file document_item_model.cpp.
References quader::ui::DocumentUiController::object_changed(), quader::ui::DocumentUiController::object_list_changed(), parent(), rebuild_from_document(), refresh_object(), refresh_selection(), quader::ui::register_ui_model_metatypes(), and quader::ui::DocumentUiController::selection_changed().
Member Function Documentation
columnCount()
int quader::ui::DocumentItemModel::columnCount (const QModelIndex & parent = {}) const nodiscard override
Return column count for parent.
Definition at line 81 of file document_item_model.cpp.
Referenced by index().
data()
QVariant quader::ui::DocumentItemModel::data (const QModelIndex & index, int role) const nodiscard override
Return model data for index and role.
Definition at line 86 of file document_item_model.cpp.
References quader::ui::document_item_roles::kKindRole, quader::ui::document_item_roles::kObjectIdRole, quader::ui::document_item_roles::kSelectedRole, quader::ui::document_item_roles::kUiNodeIdRole, and quader::ui::MeshObject.
flags()
Qt::ItemFlags quader::ui::DocumentItemModel::flags (const QModelIndex & index) const nodiscard override
Return item flags for index.
Definition at line 149 of file document_item_model.cpp.
headerData()
QVariant quader::ui::DocumentItemModel::headerData (int section, Qt::Orientation orientation, int role) const nodiscard override
Return horizontal header text.
Definition at line 162 of file document_item_model.cpp.
References quader::ui::Kind, and quader::ui::Name.
index()
QModelIndex quader::ui::DocumentItemModel::index (int row, int column, const QModelIndex & parent = {}) const nodiscard override
Return a model index for a row, column, and parent.
Definition at line 53 of file document_item_model.cpp.
References columnCount().
Referenced by index_for_object(), refresh_object(), and refresh_selection().
index_for_object()
QModelIndex quader::ui::DocumentItemModel::index_for_object (quader::document::ObjectId object, int column = static_cast<int>(DocumentItemColumn::Name)) const nodiscard
Return the model index for a document object.
Parameters
object Object id to locate.
column Column to address.
Returns
Matching index, or an invalid index when not visible.
Definition at line 180 of file document_item_model.cpp.
References index().
parent()
QModelIndex quader::ui::DocumentItemModel::parent (const QModelIndex & child) const nodiscard override
Return the parent index for child.
Definition at line 68 of file document_item_model.cpp.
Referenced by DocumentItemModel().
rebuild_from_document
void quader::ui::DocumentItemModel::rebuild_from_document () slot
Rebuild presentation rows from the current document.
Definition at line 190 of file document_item_model.cpp.
Referenced by DocumentItemModel().
refresh_object
void quader::ui::DocumentItemModel::refresh_object (quader::document::ObjectId object) slot
Refresh one object row if it is visible.
Definition at line 208 of file document_item_model.cpp.
References index(), quader::ui::document_item_roles::kKindRole, quader::ui::document_item_roles::kObjectIdRole, and quader::ui::document_item_roles::kSelectedRole.
Referenced by DocumentItemModel().
refresh_selection
void quader::ui::DocumentItemModel::refresh_selection () slot
Refresh selection roles for visible rows.
Definition at line 220 of file document_item_model.cpp.
References index().
Referenced by DocumentItemModel().
rowCount()
int quader::ui::DocumentItemModel::rowCount (const QModelIndex & parent = {}) const nodiscard override
Return row count for parent.
Definition at line 73 of file document_item_model.cpp.
setData()
bool quader::ui::DocumentItemModel::setData (const QModelIndex & index, const QVariant & value, int role) nodiscard override
Dispatch editable changes through document commands.
Definition at line 121 of file document_item_model.cpp.
The documentation for this class was generated from the following files:
src/ui/models/document_item_model.hpp
src/ui/models/document_item_model.cpp