Quader: quader::foundation::DiagnosticList Class Reference
quader::foundation::DiagnosticList Class Reference final
#include <diagnostic.hpp>
Public Types
using container_type = std::vector<Diagnostic>
Container type used to store diagnostics.
using const_iterator = container_type::const_iterator
Constant iterator over stored diagnostics.
Public Member Functions
void add (Diagnostic diagnostic)
void add (Severity severity, std::string message)
void clear () noexcept
Remove all diagnostics.
bool empty () const noexcept
std::size_t size () const noexcept
bool has_errors () const noexcept
std::span< const Diagnostic > diagnostics () const noexcept
const Diagnostic & operator[] (std::size_t index) const noexcept
const_iterator begin () const noexcept
const_iterator end () const noexcept
Detailed Description
Ordered collection of diagnostics.
The list owns diagnostic messages and exposes read-only spans and iterators for callers that need to inspect or forward them.
Definition at line 44 of file diagnostic.hpp.
Member Typedef Documentation
const_iterator
using quader::foundation::DiagnosticList::const_iterator = container_type::const_iterator
Constant iterator over stored diagnostics.
Definition at line 49 of file diagnostic.hpp.
container_type
using quader::foundation::DiagnosticList::container_type = std::vector<Diagnostic>
Container type used to store diagnostics.
Definition at line 47 of file diagnostic.hpp.
Member Function Documentation
add() [1/2]
void quader::foundation::DiagnosticList::add (Diagnostic diagnostic) inline
Append a diagnostic.
Parameters
diagnostic Diagnostic to take ownership of.
Definition at line 56 of file diagnostic.hpp.
Referenced by add(), quader::commands::CommandResult::rejected(), and quader::io::to_foundation_diagnostics().
add() [2/2]
void quader::foundation::DiagnosticList::add (Severity severity, std::string message) inline
Append a diagnostic from severity and message parts.
Parameters
severity Severity assigned to the diagnostic.
message Message to store.
Definition at line 66 of file diagnostic.hpp.
References add().
begin()
const_iterator quader::foundation::DiagnosticList::begin () const inline nodiscard noexcept
Return an iterator to the first diagnostic.
Returns
Constant begin iterator.
Definition at line 132 of file diagnostic.hpp.
clear()
void quader::foundation::DiagnosticList::clear () inline noexcept
Remove all diagnostics.
Definition at line 71 of file diagnostic.hpp.
diagnostics()
std::span< const Diagnostic > quader::foundation::DiagnosticList::diagnostics () const inline nodiscard noexcept
Return all diagnostics as a borrowed span.
Returns
Span valid until the list is mutated or destroyed.
Definition at line 113 of file diagnostic.hpp.
empty()
bool quader::foundation::DiagnosticList::empty () const inline nodiscard noexcept
Check whether no diagnostics are stored.
Returns
True when the list is empty.
Definition at line 80 of file diagnostic.hpp.
end()
const_iterator quader::foundation::DiagnosticList::end () const inline nodiscard noexcept
Return an iterator one past the last diagnostic.
Returns
Constant end iterator.
Definition at line 141 of file diagnostic.hpp.
has_errors()
bool quader::foundation::DiagnosticList::has_errors () const inline nodiscard noexcept
Check whether the list contains any error diagnostic.
Returns
True when at least one diagnostic has Severity::Error.
Definition at line 98 of file diagnostic.hpp.
References quader::foundation::Error.
operator[]()
const Diagnostic & quader::foundation::DiagnosticList::operator[] (std::size_t index) const inline nodiscard noexcept
Access a diagnostic by index.
Parameters
index Zero-based diagnostic index.
Returns
Diagnostic at index.
Definition at line 123 of file diagnostic.hpp.
size()
std::size_t quader::foundation::DiagnosticList::size () const inline nodiscard noexcept
Return the number of stored diagnostics.
Returns
Diagnostic count.
Definition at line 89 of file diagnostic.hpp.
The documentation for this class was generated from the following file:
src/foundation/diagnostic.hpp