Quader: crimson::gpu::GpuMaterialCache Class Reference
crimson::gpu::GpuMaterialCache Class Reference final
Owns default GPU material resources and binds PBR material constants.
#include <gpu_material_cache.hpp>
Classes
struct Impl
Public Member Functions
GpuMaterialCache ()
Create an uninitialized material cache.
~GpuMaterialCache ()
Shut down and release material GPU resources.
GpuMaterialCache (const GpuMaterialCache &)=delete
Material caches cannot be copied because they own GPU resources.
GpuMaterialCache & operator= (const GpuMaterialCache &)=delete
Material caches cannot be copied because they own GPU resources.
bool initialize (RendererStatus &status)
void shutdown () noexcept
Release all owned GPU resources.
GpuPbrMaterialBlock material_block (const MaterialSystem &materials, RenderMaterialHandle material, const BaseShaderDefinition &definition) const noexcept
void bind_pbr_material (const GpuPbrMaterialBlock &block) const noexcept
std::size_t live_texture_count () const noexcept
Return the number of live default texture resources.
FrameUploadStats upload_stats () const noexcept
Return upload counters accumulated by the material cache.
bool initialized () const noexcept
Return true when the cache has initialized GPU resources.
Detailed Description
Owns default GPU material resources and binds PBR material constants.
Definition at line 48 of file gpu_material_cache.hpp.
Constructor & Destructor Documentation
GpuMaterialCache() [1/2]
crimson::gpu::GpuMaterialCache::GpuMaterialCache ()
Create an uninitialized material cache.
Definition at line 169 of file gpu_material_cache.cpp.
Referenced by GpuMaterialCache(), and operator=().
~GpuMaterialCache()
crimson::gpu::GpuMaterialCache::~GpuMaterialCache () default
Shut down and release material GPU resources.
GpuMaterialCache() [2/2]
crimson::gpu::GpuMaterialCache::GpuMaterialCache (const GpuMaterialCache &) delete
Material caches cannot be copied because they own GPU resources.
References GpuMaterialCache().
Member Function Documentation
bind_pbr_material()
void crimson::gpu::GpuMaterialCache::bind_pbr_material (const GpuPbrMaterialBlock & block) const noexcept
Bind packed PBR material constants for subsequent draws.
Parameters
block Packed material constants.
Definition at line 243 of file gpu_material_cache.cpp.
Referenced by operator=().
initialize()
bool crimson::gpu::GpuMaterialCache::initialize (RendererStatus & status) nodiscard
Initialize default textures and uniforms.
Parameters
status Status receiving diagnostics.
Returns
True when initialization succeeds.
Definition at line 174 of file gpu_material_cache.cpp.
References crimson::Data, crimson::Linear, shutdown(), and crimson::Srgb.
initialized()
bool crimson::gpu::GpuMaterialCache::initialized () const nodiscard noexcept
Return true when the cache has initialized GPU resources.
Definition at line 269 of file gpu_material_cache.cpp.
Referenced by operator=().
live_texture_count()
std::size_t crimson::gpu::GpuMaterialCache::live_texture_count () const nodiscard noexcept
Return the number of live default texture resources.
Definition at line 255 of file gpu_material_cache.cpp.
Referenced by operator=().
material_block()
GpuPbrMaterialBlock crimson::gpu::GpuMaterialCache::material_block (const MaterialSystem & materials, RenderMaterialHandle material, const BaseShaderDefinition & definition) const nodiscard noexcept
Return a packed material block.
Parameters
materials Material system used to resolve material.
material Material handle to resolve.
definition Base shader definition used for packing.
Returns
Packed material block, using defaults when resolution fails.
Definition at line 233 of file gpu_material_cache.cpp.
References crimson::make_default_material_instance(), and crimson::gpu::pack_pbr_material_block().
Referenced by operator=().
operator=()
GpuMaterialCache & crimson::gpu::GpuMaterialCache::operator= (const GpuMaterialCache &) delete
Material caches cannot be copied because they own GPU resources.
References bind_pbr_material(), GpuMaterialCache(), initialized(), live_texture_count(), material_block(), and upload_stats().
shutdown()
void crimson::gpu::GpuMaterialCache::shutdown () noexcept
Release all owned GPU resources.
Definition at line 219 of file gpu_material_cache.cpp.
References crimson::Linear.
Referenced by initialize().
upload_stats()
FrameUploadStats crimson::gpu::GpuMaterialCache::upload_stats () const nodiscard noexcept
Return upload counters accumulated by the material cache.
Definition at line 265 of file gpu_material_cache.cpp.
Referenced by operator=().
The documentation for this class was generated from the following files:
src/crimson/gpu/gpu_material_cache.hpp
src/crimson/gpu/gpu_material_cache.cpp