Quader: quader::ui::NotificationService Class Reference
quader::ui::NotificationService Class Reference final
Broadcasts status, warning, and error messages to Qt UI surfaces.
#include <notification_service.hpp>
Signals
void notification_posted (const quader::ui::NotificationMessage &message)
Emitted whenever a notification is posted.
Public Member Functions
NotificationService (QObject *parent=nullptr)
Construct a notification service parented to parent.
void post (const NotificationMessage &message)
Post a fully-specified notification.
void show_status (QString summary, int timeout_ms=3000)
Post a transient status notification.
void show_info (NotificationMessage message)
Post an informational notification.
void show_warning (NotificationMessage message)
Post a warning notification.
void show_error (NotificationMessage message)
Post an error notification.
Detailed Description
Broadcasts status, warning, and error messages to Qt UI surfaces.
Definition at line 38 of file notification_service.hpp.
Constructor & Destructor Documentation
NotificationService()
quader::ui::NotificationService::NotificationService (QObject * parent = nullptr) explicit
Construct a notification service parented to parent.
Definition at line 16 of file notification_service.cpp.
Member Function Documentation
notification_posted
void quader::ui::NotificationService::notification_posted (const quader::ui::NotificationMessage & message) signal
Emitted whenever a notification is posted.
Referenced by post().
post()
void quader::ui::NotificationService::post (const NotificationMessage & message)
Post a fully-specified notification.
Definition at line 19 of file notification_service.cpp.
References notification_posted().
Referenced by show_error(), show_info(), show_status(), and show_warning().
show_error()
void quader::ui::NotificationService::show_error (NotificationMessage message)
Post an error notification.
Definition at line 48 of file notification_service.cpp.
References quader::ui::Error, post(), quader::ui::NotificationMessage::severity, and quader::ui::NotificationMessage::timeout_ms.
show_info()
void quader::ui::NotificationService::show_info (NotificationMessage message)
Post an informational notification.
Definition at line 32 of file notification_service.cpp.
References quader::ui::Info, post(), quader::ui::NotificationMessage::severity, and quader::ui::NotificationMessage::timeout_ms.
show_status()
void quader::ui::NotificationService::show_status (QString summary, int timeout_ms = 3000)
Post a transient status notification.
Definition at line 23 of file notification_service.cpp.
References post(), and quader::ui::Status.
show_warning()
void quader::ui::NotificationService::show_warning (NotificationMessage message)
Post a warning notification.
Definition at line 40 of file notification_service.cpp.
References post(), quader::ui::NotificationMessage::severity, quader::ui::NotificationMessage::timeout_ms, and quader::ui::Warning.
The documentation for this class was generated from the following files:
src/ui/services/notification_service.hpp
src/ui/services/notification_service.cpp