Quader: quader::document::Document Class Reference
quader::document::Document Class Reference final
#include <document.hpp>
Public Member Functions
quader::foundation::Result< ObjectId, DocumentError > create_mesh_object (std::string name, quader::mesh::Polyhedron mesh, Transform transform={}, PbrMaterial material=default_box_material())
quader::foundation::Result< void, DocumentError > restore_mesh_object (MeshObject object)
quader::foundation::Result< void, DocumentError > delete_object (ObjectId id)
quader::foundation::Result< MeshObject, DocumentError > extract_mesh_object (ObjectId id)
quader::foundation::Result< void, DocumentError > rename_object (ObjectId id, std::string name)
quader::foundation::Result< void, DocumentError > set_transform (ObjectId id, Transform transform)
MeshObject * find_mesh_object (ObjectId id) noexcept
Return a mutable mesh object pointer, or nullptr for invalid/stale ids.
const MeshObject * find_mesh_object (ObjectId id) const noexcept
Return a const mesh object pointer, or nullptr for invalid/stale ids.
quader::foundation::Result< void, DocumentError > validate_object_id (ObjectId id) const
quader::foundation::Result< void, DocumentError > validate_component_ref (const ComponentRef &component) const
const Selection & selection () const noexcept
Return the current document selection.
quader::foundation::Result< void, DocumentError > set_selection (Selection selection)
void clear_selection ()
Clear selection and emit a selection change only when it was non-empty.
quader::foundation::Result< void, DocumentError > mark_mesh_topology_changed (ObjectId id)
Mark mesh topology dirty for a live object.
quader::foundation::Result< void, DocumentError > mark_mesh_geometry_changed (ObjectId id)
Mark mesh geometry dirty for a live object.
bool is_dirty () const noexcept
Return true when any dirty flag is set.
DocumentDirtyFlags dirty_flags () const noexcept
Return the current dirty flag bitmask.
bool has_dirty_flag (DocumentDirtyFlag flag) const noexcept
Return true when flag is present in the current dirty bitmask.
void clear_dirty ()
Clear all dirty flags and emit a dirty-state change when needed.
std::vector< DocumentChange > take_pending_changes ()
Move out and clear queued document changes.
std::size_t object_count () const noexcept
Return the number of live objects.
std::vector< ObjectId > object_ids () const
Return ids for all live objects in document slot order.
Detailed Description
Owns editable scene objects, selection, dirty state, and document events.
All mutations validate inputs, update dirty flags, and enqueue document changes for UI/render adapters to drain.
Definition at line 31 of file document.hpp.
Member Function Documentation
clear_dirty()
void quader::document::Document::clear_dirty ()
Clear all dirty flags and emit a dirty-state change when needed.
Definition at line 293 of file document.cpp.
References quader::document::DirtyStateChanged, quader::foundation::GenerationalId< ObjectTag >::invalid(), and quader::document::kDocumentDirtyNone.
clear_selection()
void quader::document::Document::clear_selection ()
Clear selection and emit a selection change only when it was non-empty.
Definition at line 249 of file document.cpp.
References quader::document::Selection, quader::document::SelectionChanged, and quader::document::to_dirty_flags().
create_mesh_object()
quader::foundation::Result< ObjectId, DocumentError > quader::document::Document::create_mesh_object (std::string name, quader::mesh::Polyhedron mesh, Transform transform = {}, PbrMaterial material = default_box_material()) nodiscard
Create a validated mesh object.
Parameters
name Object name.
mesh Mesh payload to move into the document.
transform Initial object transform.
material Initial material values.
Returns
Created object id, or a validation/store error.
Definition at line 41 of file document.cpp.
References quader::foundation::Result< T, E >::failure(), quader::document::InvalidMaterial, quader::document::InvalidTransform, quader::document::is_finite(), quader::document::is_valid(), quader::document::make_document_error(), quader::document::ObjectCreated, quader::document::Objects, and quader::document::to_dirty_flags().
delete_object()
quader::foundation::Result< void, DocumentError > quader::document::Document::delete_object (ObjectId id) nodiscard
Delete an object from the document.
Parameters
id Object id to delete.
Returns
Success, or InvalidObject when id is not live.
Definition at line 91 of file document.cpp.
References extract_mesh_object(), quader::foundation::Result< T, E >::failure(), and quader::foundation::Result< T, E >::success().
dirty_flags()
DocumentDirtyFlags quader::document::Document::dirty_flags () const nodiscard noexcept
Return the current dirty flag bitmask.
Definition at line 285 of file document.cpp.
extract_mesh_object()
quader::foundation::Result< MeshObject, DocumentError > quader::document::Document::extract_mesh_object (ObjectId id) nodiscard
Remove an object and return its payload for undo storage.
Selection references to the object are pruned.
Parameters
id Object id to extract.
Returns
Removed object, or InvalidObject when id is not live.
Definition at line 100 of file document.cpp.
References quader::document::ObjectDeleted, quader::document::Objects, quader::document::Selection, quader::document::SelectionChanged, and quader::document::to_dirty_flags().
Referenced by delete_object().
find_mesh_object() [1/2]
const MeshObject * quader::document::Document::find_mesh_object (ObjectId id) const nodiscard noexcept
Return a const mesh object pointer, or nullptr for invalid/stale ids.
Definition at line 173 of file document.cpp.
find_mesh_object() [2/2]
MeshObject * quader::document::Document::find_mesh_object (ObjectId id) nodiscard noexcept
Return a mutable mesh object pointer, or nullptr for invalid/stale ids.
Definition at line 169 of file document.cpp.
Referenced by rename_object(), set_transform(), validate_component_ref(), and validate_object_id().
has_dirty_flag()
bool quader::document::Document::has_dirty_flag (DocumentDirtyFlag flag) const nodiscard noexcept
Return true when flag is present in the current dirty bitmask.
Definition at line 289 of file document.cpp.
References quader::document::has_dirty_flag().
is_dirty()
bool quader::document::Document::is_dirty () const nodiscard noexcept
Return true when any dirty flag is set.
Definition at line 281 of file document.cpp.
References quader::document::kDocumentDirtyNone.
mark_mesh_geometry_changed()
quader::foundation::Result< void, DocumentError > quader::document::Document::mark_mesh_geometry_changed (ObjectId id) nodiscard
Mark mesh geometry dirty for a live object.
Definition at line 270 of file document.cpp.
References quader::document::MeshGeometry, quader::document::MeshGeometryChanged, quader::foundation::Result< T, E >::success(), quader::document::to_dirty_flags(), and validate_object_id().
mark_mesh_topology_changed()
quader::foundation::Result< void, DocumentError > quader::document::Document::mark_mesh_topology_changed (ObjectId id) nodiscard
Mark mesh topology dirty for a live object.
Definition at line 259 of file document.cpp.
References quader::document::MeshTopology, quader::document::MeshTopologyChanged, quader::foundation::Result< T, E >::success(), quader::document::to_dirty_flags(), and validate_object_id().
object_count()
std::size_t quader::document::Document::object_count () const nodiscard noexcept
Return the number of live objects.
Definition at line 308 of file document.cpp.
object_ids()
std::vector< ObjectId > quader::document::Document::object_ids () const nodiscard
Return ids for all live objects in document slot order.
Definition at line 312 of file document.cpp.
rename_object()
quader::foundation::Result< void, DocumentError > quader::document::Document::rename_object (ObjectId id, std::string name) nodiscard
Rename a live object.
Parameters
id Object id to rename.
name New object name.
Returns
Success, or InvalidObject when id is not live.
Definition at line 125 of file document.cpp.
References quader::foundation::Result< T, E >::failure(), find_mesh_object(), quader::document::InvalidObject, quader::document::make_document_error(), quader::document::ObjectProperties, quader::document::ObjectRenamed, quader::foundation::Result< T, E >::success(), and quader::document::to_dirty_flags().
restore_mesh_object()
quader::foundation::Result< void, DocumentError > quader::document::Document::restore_mesh_object (MeshObject object) nodiscard
Restore a previously extracted mesh object.
Parameters
object Object snapshot to restore with its original id.
Returns
Success, or a validation/store error.
Definition at line 74 of file document.cpp.
References quader::document::ObjectCreated, quader::document::Objects, quader::foundation::Result< T, E >::success(), and quader::document::to_dirty_flags().
selection()
const Selection & quader::document::Document::selection () const nodiscard noexcept
Return the current document selection.
Definition at line 229 of file document.cpp.
Referenced by set_selection().
set_selection()
quader::foundation::Result< void, DocumentError > quader::document::Document::set_selection (Selection selection) nodiscard
Replace the document selection after resolving all ids.
Parameters
selection Selection to store.
Returns
Success, or a validation error for unresolved ids.
Definition at line 233 of file document.cpp.
References quader::document::Selection, selection(), quader::document::SelectionChanged, quader::foundation::Result< T, E >::success(), and quader::document::to_dirty_flags().
set_transform()
quader::foundation::Result< void, DocumentError > quader::document::Document::set_transform (ObjectId id, Transform transform) nodiscard
Replace a live object's transform.
Parameters
id Object id to mutate.
transform Finite transform to store.
Returns
Success, InvalidObject, or InvalidTransform.
Definition at line 144 of file document.cpp.
References quader::foundation::Result< T, E >::failure(), find_mesh_object(), quader::document::InvalidObject, quader::document::InvalidTransform, quader::document::is_finite(), quader::document::make_document_error(), quader::foundation::Result< T, E >::success(), quader::document::to_dirty_flags(), quader::document::TransformChanged, and quader::document::Transforms.
take_pending_changes()
std::vector< DocumentChange > quader::document::Document::take_pending_changes () nodiscard
Move out and clear queued document changes.
Definition at line 302 of file document.cpp.
validate_component_ref()
quader::foundation::Result< void, DocumentError > quader::document::Document::validate_component_ref (const ComponentRef & component) const nodiscard
Validate that a component reference resolves in this document.
Parameters
component Component reference to validate.
Returns
Success, or the matching object/component error.
Definition at line 187 of file document.cpp.
References quader::document::ComponentRef::component, quader::document::component_id_is_valid(), quader::document::component_kind(), quader::foundation::Result< T, E >::failure(), find_mesh_object(), quader::document::InvalidEdge, quader::document::InvalidFace, quader::document::InvalidObject, quader::document::InvalidVertex, quader::document::make_document_error(), quader::document::ComponentRef::object, and quader::foundation::Result< T, E >::success().
validate_object_id()
quader::foundation::Result< void, DocumentError > quader::document::Document::validate_object_id (ObjectId id) const nodiscard
Validate that an object id resolves in this document.
Parameters
id Object id to validate.
Returns
Success, or InvalidObject.
Definition at line 177 of file document.cpp.
References quader::foundation::Result< T, E >::failure(), find_mesh_object(), quader::document::InvalidObject, quader::document::make_document_error(), and quader::foundation::Result< T, E >::success().
Referenced by mark_mesh_geometry_changed(), and mark_mesh_topology_changed().
The documentation for this class was generated from the following files:
src/document/document.hpp
src/document/document.cpp