Quader: quader::commands::ClearSelectionCommand Class Reference
quader::commands::ClearSelectionCommand Class Reference final
Command that clears the document selection and can restore the prior selection.
#include <selection_commands.hpp>
Public Member Functions
std::string_view name () const noexcept override
CommandResult execute (quader::document::Document &document) override
CommandResult undo (quader::document::Document &document) override
Public Member Functions inherited from quader::commands::ICommand
virtual ~ICommand ()=default
Destroy a command through the base interface.
virtual bool can_merge_with (const ICommand &next) const noexcept
virtual CommandResult merge_with (std::unique_ptr< ICommand > next)
Detailed Description
Command that clears the document selection and can restore the prior selection.
Definition at line 57 of file selection_commands.hpp.
Member Function Documentation
execute()
CommandResult quader::commands::ClearSelectionCommand::execute (quader::document::Document & document) nodiscard override virtual
Clear the document selection.
Parameters
document Document to mutate.
Returns
Applied result after storing the previous selection.
Implements quader::commands::ICommand.
Definition at line 63 of file selection_commands.cpp.
References quader::commands::CommandResult::applied(), and quader::commands::CommandResult::rejected().
name()
std::string_view quader::commands::ClearSelectionCommand::name () const nodiscard override virtual noexcept
Return the display name used by undo/redo UI.
Returns
Static command name.
Implements quader::commands::ICommand.
Definition at line 59 of file selection_commands.cpp.
undo()
CommandResult quader::commands::ClearSelectionCommand::undo (quader::document::Document & document) nodiscard override virtual
Restore the selection captured during execute().
Parameters
document Document to mutate.
Returns
Applied result when a previous selection was captured.
Implements quader::commands::ICommand.
Definition at line 74 of file selection_commands.cpp.
References quader::commands::CommandResult::applied(), and quader::commands::CommandResult::rejected().
The documentation for this class was generated from the following files:
src/commands/selection_commands.hpp
src/commands/selection_commands.cpp