Quader: quader::ui::DocumentUiController Class Reference
quader::ui::DocumentUiController Class Reference final
#include <document_ui_controller.hpp>
Signals
void object_list_changed ()
Emitted when the object list changes.
void object_changed (quader::document::ObjectId object)
Emitted when one object's displayable data changes.
void selection_changed ()
Emitted when document selection changes.
void dirty_state_changed (quader::document::DocumentDirtyFlags flags)
Emitted when document dirty flags change.
void command_history_changed ()
Emitted when undo/redo availability may have changed.
void document_events_drained ()
Emitted after a drain cycle completes.
Public Member Functions
DocumentUiController (quader::document::Document &document, quader::commands::CommandHistory &command_history, ActionStateUpdater &action_state_updater, NotificationService &notifications, QObject *parent=nullptr)
Construct the controller over non-owning document/service references.
const quader::document::Document & document () const noexcept
Return the document as read-only UI state.
const quader::commands::CommandHistory & command_history () const noexcept
Return the command history as read-only UI state.
quader::commands::CommandResult execute_command (std::unique_ptr< quader::commands::ICommand > command, CommandFeedback feedback=CommandFeedback::NotifyOnReject)
Execute a command, drain document changes, and refresh actions.
quader::commands::CommandResult undo (CommandFeedback feedback=CommandFeedback::NotifyOnReject)
Undo through command history, drain document changes, and refresh actions.
quader::commands::CommandResult redo (CommandFeedback feedback=CommandFeedback::NotifyOnReject)
Redo through command history, drain document changes, and refresh actions.
void refresh_from_document ()
Drain pending document events and refresh dependent UI state.
Detailed Description
UI-facing document mutation controller.
Commands are executed through CommandHistory; document changes are drained into Qt signals for models, panels, and action state.
Definition at line 46 of file document_ui_controller.hpp.
Constructor & Destructor Documentation
DocumentUiController()
quader::ui::DocumentUiController::DocumentUiController (quader::document::Document & document, quader::commands::CommandHistory & command_history, ActionStateUpdater & action_state_updater, NotificationService & notifications, QObject * parent = nullptr)
Construct the controller over non-owning document/service references.
Definition at line 36 of file document_ui_controller.cpp.
References command_history(), and document().
Member Function Documentation
command_history()
const quader::commands::CommandHistory & quader::ui::DocumentUiController::command_history () const nodiscard noexcept
Return the command history as read-only UI state.
Definition at line 52 of file document_ui_controller.cpp.
Referenced by DocumentUiController().
command_history_changed
void quader::ui::DocumentUiController::command_history_changed () signal
Emitted when undo/redo availability may have changed.
Referenced by execute_command(), redo(), and undo().
dirty_state_changed
void quader::ui::DocumentUiController::dirty_state_changed (quader::document::DocumentDirtyFlags flags) signal
Emitted when document dirty flags change.
document()
const quader::document::Document & quader::ui::DocumentUiController::document () const nodiscard noexcept
Return the document as read-only UI state.
Definition at line 48 of file document_ui_controller.cpp.
Referenced by DocumentUiController().
document_events_drained
void quader::ui::DocumentUiController::document_events_drained () signal
Emitted after a drain cycle completes.
execute_command()
quader::commands::CommandResult quader::ui::DocumentUiController::execute_command (std::unique_ptr< quader::commands::ICommand > command, CommandFeedback feedback = CommandFeedback::NotifyOnReject) nodiscard
Execute a command, drain document changes, and refresh actions.
Definition at line 56 of file document_ui_controller.cpp.
References command_history_changed(), and quader::ui::NotifyOnReject.
object_changed
void quader::ui::DocumentUiController::object_changed (quader::document::ObjectId object) signal
Emitted when one object's displayable data changes.
Referenced by quader::ui::DocumentItemModel::DocumentItemModel(), and quader::ui::PropertyItemModel::PropertyItemModel().
object_list_changed
void quader::ui::DocumentUiController::object_list_changed () signal
Emitted when the object list changes.
Referenced by quader::ui::DocumentItemModel::DocumentItemModel(), and quader::ui::PropertyItemModel::PropertyItemModel().
redo()
quader::commands::CommandResult quader::ui::DocumentUiController::redo (CommandFeedback feedback = CommandFeedback::NotifyOnReject) nodiscard
Redo through command history, drain document changes, and refresh actions.
Definition at line 84 of file document_ui_controller.cpp.
References command_history_changed(), and quader::ui::NotifyOnReject.
refresh_from_document()
void quader::ui::DocumentUiController::refresh_from_document ()
Drain pending document events and refresh dependent UI state.
Definition at line 97 of file document_ui_controller.cpp.
selection_changed
void quader::ui::DocumentUiController::selection_changed () signal
Emitted when document selection changes.
Referenced by quader::ui::DocumentItemModel::DocumentItemModel(), quader::ui::DocumentSelectionAdapter::DocumentSelectionAdapter(), and quader::ui::PropertyItemModel::PropertyItemModel().
undo()
quader::commands::CommandResult quader::ui::DocumentUiController::undo (CommandFeedback feedback = CommandFeedback::NotifyOnReject) nodiscard
Undo through command history, drain document changes, and refresh actions.
Definition at line 71 of file document_ui_controller.cpp.
References command_history_changed(), and quader::ui::NotifyOnReject.
The documentation for this class was generated from the following files:
src/ui/services/document_ui_controller.hpp
src/ui/services/document_ui_controller.cpp