Quader: crimson::MaterialSystem Class Reference
crimson::MaterialSystem Class Reference final
Owns renderer material instances and validates them against base shader schemas.
#include <material_system.hpp>
Public Member Functions
MaterialSystem ()
Construct with the built-in V1 base shader registry.
MaterialSystem (BaseShaderRegistry registry)
Construct with an explicit base shader registry.
const BaseShaderRegistry & registry () const noexcept
Return the base shader registry used for validation.
quader::foundation::Result< RenderMaterialHandle, RendererDiagnostic > create_default_material (BaseShaderId base_shader_id)
quader::foundation::Result< RenderMaterialHandle, RendererDiagnostic > create_material (const MaterialInstance &instance)
const MaterialInstance * get (RenderMaterialHandle handle) const noexcept
Return a const material pointer, or nullptr for invalid/stale handles.
MaterialInstance * get (RenderMaterialHandle handle) noexcept
Return a mutable material pointer, or nullptr for invalid/stale handles.
bool destroy (RenderMaterialHandle handle) noexcept
Destroy a material handle, returning false for invalid/stale handles.
std::size_t live_material_count () const noexcept
Return the number of live material instances.
quader::foundation::Result< void, RendererDiagnostic > set_parameter (RenderMaterialHandle handle, std::string name, MaterialParameterValue value)
Set one named material parameter after schema validation.
quader::foundation::Result< void, RendererDiagnostic > bind_texture (RenderMaterialHandle handle, std::string name, RenderTextureHandle texture)
Bind a texture handle to one named texture slot after schema validation.
Detailed Description
Owns renderer material instances and validates them against base shader schemas.
Definition at line 32 of file material_system.hpp.
Constructor & Destructor Documentation
MaterialSystem() [1/2]
crimson::MaterialSystem::MaterialSystem ()
Construct with the built-in V1 base shader registry.
Definition at line 69 of file material_system.cpp.
References crimson::make_v1_base_shader_registry(), and MaterialSystem().
Referenced by MaterialSystem().
MaterialSystem() [2/2]
crimson::MaterialSystem::MaterialSystem (BaseShaderRegistry registry) explicit
Construct with an explicit base shader registry.
Definition at line 72 of file material_system.cpp.
References registry().
Member Function Documentation
bind_texture()
quader::foundation::Result< void, RendererDiagnostic > crimson::MaterialSystem::bind_texture (RenderMaterialHandle handle, std::string name, RenderTextureHandle texture) nodiscard
Bind a texture handle to one named texture slot after schema validation.
Definition at line 185 of file material_system.cpp.
References quader::foundation::Result< T, E >::failure(), get(), crimson::MaterialTextureBinding::name, quader::foundation::Result< T, E >::success(), crimson::MaterialTextureBinding::texture, and crimson::MaterialInstance::textures.
create_default_material()
quader::foundation::Result< RenderMaterialHandle, RendererDiagnostic > crimson::MaterialSystem::create_default_material (BaseShaderId base_shader_id) nodiscard
Create a material using default values for a base shader.
Parameters
base_shader_id Base shader id to instantiate.
Returns
Stable material handle, or a renderer diagnostic.
Definition at line 79 of file material_system.cpp.
References crimson::base_shader_id_name(), create_material(), quader::foundation::Result< T, E >::failure(), crimson::make_default_material_instance(), and crimson::MaterialSchemaInvalid.
Referenced by crimson::gpu::GpuDevice::initialize(), and quader::benchmarks::run_crimson_packet_pipeline_benchmark().
create_material()
quader::foundation::Result< RenderMaterialHandle, RendererDiagnostic > crimson::MaterialSystem::create_material (const MaterialInstance & instance) nodiscard
Create a validated material instance.
Parameters
instance Material instance to normalize and store.
Returns
Stable material handle, or a renderer diagnostic.
Definition at line 93 of file material_system.cpp.
References quader::foundation::Result< T, E >::failure(), and quader::foundation::Result< T, E >::success().
Referenced by create_default_material().
destroy()
bool crimson::MaterialSystem::destroy (RenderMaterialHandle handle) nodiscard noexcept
Destroy a material handle, returning false for invalid/stale handles.
Definition at line 133 of file material_system.cpp.
get() [1/2]
const MaterialInstance * crimson::MaterialSystem::get (RenderMaterialHandle handle) const nodiscard noexcept
Return a const material pointer, or nullptr for invalid/stale handles.
Definition at line 123 of file material_system.cpp.
Referenced by bind_texture(), and set_parameter().
get() [2/2]
MaterialInstance * crimson::MaterialSystem::get (RenderMaterialHandle handle) nodiscard noexcept
Return a mutable material pointer, or nullptr for invalid/stale handles.
Definition at line 128 of file material_system.cpp.
live_material_count()
std::size_t crimson::MaterialSystem::live_material_count () const nodiscard noexcept
Return the number of live material instances.
Definition at line 147 of file material_system.cpp.
registry()
const BaseShaderRegistry & crimson::MaterialSystem::registry () const nodiscard noexcept
Return the base shader registry used for validation.
Definition at line 75 of file material_system.cpp.
Referenced by MaterialSystem(), and quader::benchmarks::run_crimson_packet_pipeline_benchmark().
set_parameter()
quader::foundation::Result< void, RendererDiagnostic > crimson::MaterialSystem::set_parameter (RenderMaterialHandle handle, std::string name, MaterialParameterValue value) nodiscard
Set one named material parameter after schema validation.
Definition at line 151 of file material_system.cpp.
References quader::foundation::Result< T, E >::failure(), get(), crimson::MaterialParameter::name, crimson::MaterialInstance::parameters, quader::foundation::Result< T, E >::success(), and crimson::MaterialParameter::value.
The documentation for this class was generated from the following files:
src/crimson/material/material_system.hpp
src/crimson/material/material_system.cpp