Quader: crimson::gpu::GpuFrameResources Class Reference
crimson::gpu::GpuFrameResources Class Reference final
Owns GPU frame targets synchronized from the render graph.
#include <gpu_frame_resources.hpp>
Public Member Functions
void synchronize_descriptors (const RenderGraph &graph)
bool synchronize (const RenderGraph &graph, RendererStatus &status)
void clear () noexcept
Release all frame target handles and descriptors.
std::span< const GpuFrameTargetRecord > targets () const noexcept
Return target records in graph order.
const GpuFrameTargetRecord * find (std::string_view name) const noexcept
std::uint64_t graph_resize_generation () const noexcept
Return the graph resize generation currently synchronized.
bgfx::TextureHandle texture (std::string_view name) const noexcept
bgfx::FrameBufferHandle framebuffer (std::string_view name) const noexcept
bgfx::FrameBufferHandle scene_depth_framebuffer () const noexcept
Return the composite framebuffer for scene depth.
bgfx::FrameBufferHandle hdr_scene_framebuffer () const noexcept
Return the composite framebuffer for HDR scene color.
bgfx::FrameBufferHandle tone_mapped_color_framebuffer () const noexcept
Return the composite framebuffer for tone-mapped color.
bgfx::FrameBufferHandle tone_mapped_framebuffer () const noexcept
Return the tone-mapped framebuffer alias.
bgfx::FrameBufferHandle picking_framebuffer () const noexcept
Return the picking framebuffer.
Detailed Description
Owns GPU frame targets synchronized from the render graph.
Definition at line 66 of file gpu_frame_resources.hpp.
Member Function Documentation
clear()
void crimson::gpu::GpuFrameResources::clear () noexcept
Release all frame target handles and descriptors.
Definition at line 154 of file gpu_frame_resources.cpp.
find()
const GpuFrameTargetRecord * crimson::gpu::GpuFrameResources::find (std::string_view name) const nodiscard noexcept
Find a target record by graph resource name.
Parameters
name Resource name.
Returns
Borrowed record, or nullptr when absent.
Definition at line 166 of file gpu_frame_resources.cpp.
Referenced by framebuffer(), and texture().
framebuffer()
bgfx::FrameBufferHandle crimson::gpu::GpuFrameResources::framebuffer (std::string_view name) const nodiscard noexcept
Return a framebuffer handle by resource name.
Parameters
name Resource name.
Returns
Framebuffer handle, or an invalid handle when absent.
Definition at line 182 of file gpu_frame_resources.cpp.
References find(), crimson::gpu::GpuFrameTargetRecord::framebuffer, and crimson::gpu::UniqueGpuHandle< Handle, Traits >::get().
Referenced by scene_depth_framebuffer(), and tone_mapped_color_framebuffer().
graph_resize_generation()
std::uint64_t crimson::gpu::GpuFrameResources::graph_resize_generation () const nodiscard noexcept
Return the graph resize generation currently synchronized.
Definition at line 173 of file gpu_frame_resources.cpp.
hdr_scene_framebuffer()
bgfx::FrameBufferHandle crimson::gpu::GpuFrameResources::hdr_scene_framebuffer () const nodiscard noexcept
Return the composite framebuffer for HDR scene color.
Definition at line 191 of file gpu_frame_resources.cpp.
picking_framebuffer()
bgfx::FrameBufferHandle crimson::gpu::GpuFrameResources::picking_framebuffer () const nodiscard noexcept
Return the picking framebuffer.
Definition at line 203 of file gpu_frame_resources.cpp.
scene_depth_framebuffer()
bgfx::FrameBufferHandle crimson::gpu::GpuFrameResources::scene_depth_framebuffer () const nodiscard noexcept
Return the composite framebuffer for scene depth.
Definition at line 187 of file gpu_frame_resources.cpp.
References framebuffer(), and crimson::kSceneDepthTargetName.
synchronize()
bool crimson::gpu::GpuFrameResources::synchronize (const RenderGraph & graph, RendererStatus & status) nodiscard
Synchronize descriptors and runtime target handles.
Parameters
graph Render graph source.
status Status receiving diagnostics.
Returns
True when required runtime targets are ready.
Definition at line 138 of file gpu_frame_resources.cpp.
References synchronize_descriptors().
synchronize_descriptors()
void crimson::gpu::GpuFrameResources::synchronize_descriptors (const RenderGraph & graph)
Synchronize stored descriptors from a graph without creating runtime handles.
Parameters
graph Render graph source.
Definition at line 104 of file gpu_frame_resources.cpp.
References crimson::gpu::GpuFrameTargetRecord::desc, crimson::gpu::GpuFrameTargetRecord::framebuffer, crimson::gpu::GpuFrameTargetRecord::graph_generation, crimson::gpu::GpuFrameTargetRecord::recreate_count, crimson::gpu::UniqueGpuHandle< Handle, Traits >::reset(), crimson::RenderGraph::resize_generation(), crimson::RenderGraph::resources(), crimson::RenderResourceRegistry::resources(), and crimson::gpu::GpuFrameTargetRecord::texture.
Referenced by synchronize().
targets()
std::span< const GpuFrameTargetRecord > crimson::gpu::GpuFrameResources::targets () const nodiscard noexcept
Return target records in graph order.
Definition at line 162 of file gpu_frame_resources.cpp.
texture()
bgfx::TextureHandle crimson::gpu::GpuFrameResources::texture (std::string_view name) const nodiscard noexcept
Return a texture handle by resource name.
Parameters
name Resource name.
Returns
Texture handle, or an invalid handle when absent.
Definition at line 177 of file gpu_frame_resources.cpp.
References find(), crimson::gpu::UniqueGpuHandle< Handle, Traits >::get(), and crimson::gpu::GpuFrameTargetRecord::texture.
tone_mapped_color_framebuffer()
bgfx::FrameBufferHandle crimson::gpu::GpuFrameResources::tone_mapped_color_framebuffer () const nodiscard noexcept
Return the composite framebuffer for tone-mapped color.
Definition at line 195 of file gpu_frame_resources.cpp.
References framebuffer(), and crimson::kToneMappedColorTargetName.
tone_mapped_framebuffer()
bgfx::FrameBufferHandle crimson::gpu::GpuFrameResources::tone_mapped_framebuffer () const nodiscard noexcept
Return the tone-mapped framebuffer alias.
Definition at line 199 of file gpu_frame_resources.cpp.
The documentation for this class was generated from the following files:
src/crimson/gpu/gpu_frame_resources.hpp
src/crimson/gpu/gpu_frame_resources.cpp