Quader: crimson::gpu::GpuMeshCache Class Reference
crimson::gpu::GpuMeshCache Class Reference final
Owns GPU mesh resources used by the runtime renderer path.
#include <gpu_mesh_cache.hpp>
Public Member Functions
RenderMeshHandle create_unit_box (RendererStatus &status)
bool upload_mesh (const RenderMeshUploadDesc &desc, RendererStatus &status)
const GpuMeshResource * get (RenderMeshHandle handle) const noexcept
std::size_t live_mesh_count () const noexcept
Return the number of live mesh resources.
FrameUploadStats upload_stats () const noexcept
Return upload counters accumulated by the mesh cache.
void clear () noexcept
Destroy all mesh resources.
Detailed Description
Owns GPU mesh resources used by the runtime renderer path.
Definition at line 20 of file gpu_mesh_cache.hpp.
Member Function Documentation
clear()
void crimson::gpu::GpuMeshCache::clear () noexcept
Destroy all mesh resources.
Definition at line 205 of file gpu_mesh_cache.cpp.
create_unit_box()
RenderMeshHandle crimson::gpu::GpuMeshCache::create_unit_box (RendererStatus & status) nodiscard
Create and store the built-in unit box mesh.
Parameters
status Status receiving resource diagnostics.
Returns
Handle for the created mesh, or an invalid handle on failure.
Definition at line 125 of file gpu_mesh_cache.cpp.
References crimson::gpu::GpuMeshResource::index_buffer, crimson::gpu::UniqueGpuHandle< Handle, Traits >::reset(), crimson::gpu::GpuMeshResource::valid(), crimson::gpu::GpuMeshResource::vertex_buffer, and crimson::gpu::GpuMeshResource::vertex_layout.
get()
const GpuMeshResource * crimson::gpu::GpuMeshCache::get (RenderMeshHandle handle) const nodiscard noexcept
Resolve an immutable mesh resource.
Parameters
handle Mesh handle to resolve.
Returns
Borrowed resource, or nullptr for invalid/stale handles.
Definition at line 193 of file gpu_mesh_cache.cpp.
Referenced by crimson::gpu::GpuPicking::submit_frame_requests(), and upload_mesh().
live_mesh_count()
std::size_t crimson::gpu::GpuMeshCache::live_mesh_count () const nodiscard noexcept
Return the number of live mesh resources.
Definition at line 197 of file gpu_mesh_cache.cpp.
upload_mesh()
bool crimson::gpu::GpuMeshCache::upload_mesh (const RenderMeshUploadDesc & desc, RendererStatus & status) nodiscard
Upload or replace a caller-owned render mesh.
Parameters
desc Upload descriptor with stable public mesh handle.
status Status receiving resource diagnostics.
Returns
True when the mesh resource is resident after the call.
Definition at line 149 of file gpu_mesh_cache.cpp.
References get(), crimson::RenderMeshUploadDesc::handle, crimson::gpu::GpuMeshResource::index_buffer, crimson::RenderMeshUploadRecord::index_bytes, crimson::RenderMeshUploadDesc::indices, crimson::RenderMeshUploadDesc::position_normal_interleaved, crimson::gpu::UniqueGpuHandle< Handle, Traits >::reset(), crimson::gpu::GpuMeshResource::valid(), crimson::validate_render_mesh_upload_desc(), crimson::gpu::GpuMeshResource::vertex_buffer, crimson::RenderMeshUploadRecord::vertex_bytes, and crimson::gpu::GpuMeshResource::vertex_layout.
upload_stats()
FrameUploadStats crimson::gpu::GpuMeshCache::upload_stats () const nodiscard noexcept
Return upload counters accumulated by the mesh cache.
Definition at line 201 of file gpu_mesh_cache.cpp.
The documentation for this class was generated from the following files:
src/crimson/gpu/gpu_mesh_cache.hpp
src/crimson/gpu/gpu_mesh_cache.cpp