Quader: quader::ui::ViewportDiagnosticsService Class Reference
quader::ui::ViewportDiagnosticsService Class Reference final
Tracks the active viewport render host and exposes latest diagnostics.
#include <viewport_diagnostics_service.hpp>
Signals
void diagnostics_changed ()
Emitted when diagnostics data changes.
void diagnostics_unavailable ()
Emitted when diagnostics become unavailable.
void summary_changed ()
Emitted when the summary may have changed.
Public Member Functions
ViewportDiagnosticsService (QObject *parent=nullptr)
Construct an empty diagnostics service.
void attach_render_host (IViewportRenderHost &render_host) noexcept
Attach a render host as the diagnostics provider.
void detach_render_host (const IViewportRenderHost &render_host) noexcept
Detach the render host if it is the current provider.
void clear_render_host () noexcept
Clear the current render host provider.
void refresh ()
Refresh the latest snapshot from the provider.
const std::optional< ViewportDiagnosticsSnapshot > & latest_snapshot () const noexcept
Return the latest diagnostics snapshot, if available.
ViewportDiagnosticsSummary summary () const
Return a compact summary of the latest snapshot.
bool has_provider () const noexcept
Return true when a render host provider is attached.
Detailed Description
Tracks the active viewport render host and exposes latest diagnostics.
Definition at line 46 of file viewport_diagnostics_service.hpp.
Constructor & Destructor Documentation
ViewportDiagnosticsService()
quader::ui::ViewportDiagnosticsService::ViewportDiagnosticsService (QObject * parent = nullptr) explicit
Construct an empty diagnostics service.
Definition at line 59 of file viewport_diagnostics_service.cpp.
Member Function Documentation
attach_render_host()
void quader::ui::ViewportDiagnosticsService::attach_render_host (IViewportRenderHost & render_host) noexcept
Attach a render host as the diagnostics provider.
Definition at line 62 of file viewport_diagnostics_service.cpp.
clear_render_host()
void quader::ui::ViewportDiagnosticsService::clear_render_host () noexcept
Clear the current render host provider.
Definition at line 72 of file viewport_diagnostics_service.cpp.
Referenced by detach_render_host().
detach_render_host()
void quader::ui::ViewportDiagnosticsService::detach_render_host (const IViewportRenderHost & render_host) noexcept
Detach the render host if it is the current provider.
Definition at line 66 of file viewport_diagnostics_service.cpp.
References clear_render_host().
diagnostics_changed
void quader::ui::ViewportDiagnosticsService::diagnostics_changed () signal
Emitted when diagnostics data changes.
Referenced by quader::ui::DiagnosticsItemModel::DiagnosticsItemModel(), and refresh().
diagnostics_unavailable
void quader::ui::ViewportDiagnosticsService::diagnostics_unavailable () signal
Emitted when diagnostics become unavailable.
Referenced by quader::ui::DiagnosticsItemModel::DiagnosticsItemModel(), and quader::ui::DiagnosticsPanel::DiagnosticsPanel().
has_provider()
bool quader::ui::ViewportDiagnosticsService::has_provider () const nodiscard noexcept
Return true when a render host provider is attached.
Definition at line 157 of file viewport_diagnostics_service.cpp.
latest_snapshot()
const std::optional< ViewportDiagnosticsSnapshot > & quader::ui::ViewportDiagnosticsService::latest_snapshot () const nodiscard noexcept
Return the latest diagnostics snapshot, if available.
Definition at line 94 of file viewport_diagnostics_service.cpp.
refresh()
void quader::ui::ViewportDiagnosticsService::refresh ()
Refresh the latest snapshot from the provider.
Definition at line 77 of file viewport_diagnostics_service.cpp.
References diagnostics_changed(), and summary_changed().
Referenced by quader::ui::DiagnosticsPanel::DiagnosticsPanel().
summary()
ViewportDiagnosticsSummary quader::ui::ViewportDiagnosticsService::summary () const nodiscard
Return a compact summary of the latest snapshot.
Definition at line 98 of file viewport_diagnostics_service.cpp.
References quader::ui::ViewportDiagnosticsSummary::available, quader::ui::ViewportDiagnosticsSummary::counter_count, quader::ui::ViewportDiagnosticsSnapshot::counters, quader::ui::ViewportDiagnosticsSummary::diagnostic_count, quader::ui::ViewportDiagnosticsSnapshot::diagnostics, quader::ui::ViewportDiagnosticsSummary::error_count, quader::ui::ViewportDiagnosticsSnapshot::frame, quader::ui::ViewportDiagnosticsSummary::frame, quader::ui::ViewportDiagnosticsSummary::pass_count, quader::ui::ViewportDiagnosticsSnapshot::passes, quader::ui::ViewportDiagnosticsSnapshot::renderer_name, quader::ui::ViewportDiagnosticsSummary::renderer_name, quader::ui::ViewportRendererDiagnosticRow::severity, quader::ui::ViewportDiagnosticsSummary::status_text, quader::ui::ViewportDiagnosticsSummary::tooltip_text, and quader::ui::ViewportDiagnosticsSummary::warning_count.
summary_changed
void quader::ui::ViewportDiagnosticsService::summary_changed () signal
Emitted when the summary may have changed.
Referenced by quader::ui::DiagnosticsPanel::DiagnosticsPanel(), and refresh().
The documentation for this class was generated from the following files:
src/ui/services/viewport_diagnostics_service.hpp
src/ui/services/viewport_diagnostics_service.cpp