Quader: quader::mesh::ops Namespace Reference
quader::mesh::ops Namespace Reference
Classes
struct BoxDimensions
Axis-aligned box bounds used by the mesh box builder.
struct BoxCorners
Oriented box corner set consumed by the mesh box builder.
Functions
quader::foundation::Result< quader::mesh::Polyhedron, quader::mesh::MeshError > make_box_from_bounds (BoxDimensions bounds)
quader::foundation::Result< quader::mesh::Polyhedron, quader::mesh::MeshError > make_box_from_bounds (quader::math::Aabb bounds)
quader::foundation::Result< quader::mesh::Polyhedron, quader::mesh::MeshError > make_box_from_corners (const BoxCorners &corners)
Function Documentation
make_box_from_bounds() [1/2]
quader::foundation::Result< quader::mesh::Polyhedron, quader::mesh::MeshError > quader::mesh::ops::make_box_from_bounds (BoxDimensions bounds) nodiscard
Build a closed six-face polyhedron from axis-aligned bounds.
Parameters
bounds Minimum and maximum bounds; reversed axes are normalized.
Returns
Valid box mesh, or a mesh error for non-finite or degenerate bounds.
Definition at line 131 of file box_builder.cpp.
References quader::foundation::Result< T, E >::failure(), make_box_from_corners(), quader::mesh::ops::BoxDimensions::max, quader::mesh::ops::BoxDimensions::min, quader::math::Vec3::x, quader::math::Vec3::y, and quader::math::Vec3::z.
Referenced by make_box_from_bounds().
make_box_from_bounds() [2/2]
quader::foundation::Result< quader::mesh::Polyhedron, quader::mesh::MeshError > quader::mesh::ops::make_box_from_bounds (quader::math::Aabb bounds) nodiscard
Build a closed six-face polyhedron from an axis-aligned bounding box.
Parameters
bounds Bounding box to convert into a mesh.
Returns
Valid box mesh, or a mesh error for non-finite or degenerate bounds.
Definition at line 154 of file box_builder.cpp.
References make_box_from_bounds(), quader::math::Aabb::max, and quader::math::Aabb::min.
make_box_from_corners()
quader::foundation::Result< quader::mesh::Polyhedron, quader::mesh::MeshError > quader::mesh::ops::make_box_from_corners (const BoxCorners & corners) nodiscard
Build a closed six-face polyhedron from oriented box corners.
Parameters
corners Eight finite, non-degenerate corners.
Returns
Valid box mesh, or a mesh error when any face degenerates.
Definition at line 162 of file box_builder.cpp.
References quader::foundation::Result< T, E >::failure(), quader::mesh::ops::BoxCorners::points, and quader::foundation::Result< T, E >::success().
Referenced by make_box_from_bounds().