Quader: quader::ui Namespace Reference
quader::ui Namespace Reference
Namespaces
namespace diagnostics_item_roles
namespace document_item_roles
namespace property_item_roles
Classes
class ActionRegistry
struct ActionSpec
Declarative configuration used when registering a canonical action.
class ActionStateUpdater
Applies editor state snapshots to registered action enabled/checked/text state.
class CrimsonViewportRenderHost
class DiagnosticsItemModel
Qt tree model presenting the latest viewport diagnostics snapshot.
class DiagnosticsPanel
Dockable panel that displays renderer diagnostics and frame stats.
class DocumentItemModel
Qt item model presenting document objects without owning document state.
class DocumentSelectionAdapter
Synchronizes document object selection with a Qt item selection model.
class DocumentUiController
class EditorActionController
Routes triggered actions to document commands, tool activation, and UI services.
class EditorActionStateProvider
Derives action state from document, command history, tools, and I/O services.
struct EditorStateSnapshot
Snapshot of editor state used to update canonical actions.
struct FileDialogFilter
One file-dialog filter entry.
class FusionStylePolicy
Applies the V1 Qt Fusion style baseline.
class IEditorStateProvider
Interface for components that can provide an EditorStateSnapshot.
class IFileDialogService
Abstract file dialog service for tests and platform-specific UI.
class ImportUiController
Coordinates import file dialogs, import service calls, and notifications.
class IViewportRenderHost
Abstract render host used by the Qt viewport controller.
class MainWindow
Top-level Qt shell for menus, panels, status UI, and viewport hosting.
struct NativeViewportSurface
Native window/surface handle passed to the render host.
struct NotificationMessage
Notification payload emitted to UI surfaces.
class NotificationService
Broadcasts status, warning, and error messages to Qt UI surfaces.
class NullEditorStateProvider
Null provider used when no editor state source is available.
struct OpenFileDialogRequest
Request data for opening one file.
struct PanelContext
Non-owning context passed to dock panels during construction.
class PanelHost
Owns dock widgets and workspace persistence for application panels.
struct PanelSpec
Declarative dock-panel registration metadata.
class PropertiesPanel
Dockable panel that displays editable properties for current selection.
struct PropertyDescriptor
Presentation descriptor for one row in the property model.
class PropertyItemModel
Qt table model exposing editable document property descriptors.
struct PropertyPath
Address of one editable/displayed property.
class PropertyValueDelegate
Delegate that edits property model values with kind-aware Qt editors.
struct QtApplicationMetadata
Qt application metadata applied before settings and widgets are used.
class QtFileDialogService
Qt-backed file dialog service.
struct SaveFileDialogRequest
Request data for saving one file.
class ScenePanel
Dockable panel that presents the document object hierarchy.
class SettingsService
Scoped wrapper around QSettings for workspace and viewport state.
struct UiContext
Non-owning service bundle passed to the Qt shell and panels.
struct UiMetrics
Centralized V1 UI spacing and icon metrics.
struct UiNodeId
Stable presentation-node id used inside Qt item models.
struct Vec3
Three-component single-precision vector.
class ViewportCameraController
Manages perspective and orthographic viewport cameras and navigation input.
struct ViewportCameraPose
Derived camera pose used by viewport rendering and ray reconstruction.
struct ViewportCameraSnapshot
CPU-side camera snapshot sent to a render host.
struct ViewportCameraState
Mutable camera state for one viewport pane.
class ViewportController
Coordinates viewport layout, navigation, tool input, and render-host calls.
class ViewportDiagnosticsService
Tracks the active viewport render host and exposes latest diagnostics.
struct ViewportDiagnosticsSnapshot
Full diagnostics snapshot exposed by a viewport render host.
struct ViewportDiagnosticsSummary
Compact summary derived from the latest viewport diagnostics snapshot.
struct ViewportFrameStats
Compact viewport frame stats presented in the UI.
class ViewportLayoutState
Stores split fractions and derives viewport pane rectangles.
struct ViewportPane
One viewport pane in the current layout.
struct ViewportPickPayload
Viewport-level picking payload.
struct ViewportPickRequest
Pixel readback request issued by viewport UI.
struct ViewportPickResult
Completed viewport picking result.
struct ViewportPixelSize
Viewport size in physical pixels.
struct ViewportPoint
Viewport-local point in physical pixels.
struct ViewportRect
Viewport rectangle in physical pixels.
struct ViewportRendererCounter
UI-facing renderer counter row.
struct ViewportRendererDiagnosticRow
UI-facing renderer diagnostic row.
struct ViewportRenderPassStats
UI-facing stats for one render pass.
struct ViewportRenderRequest
Render request submitted by the viewport controller.
struct ViewportRenderResult
Result returned by viewport render-host operations.
class ViewportWidget
QWidget host for native Crimson viewport rendering and input translation.
Typedefs
using ViewportPickRequestId = std::uint64_t
Stable id for viewport picking requests.
using ViewportPaneArray = std::array<ViewportPane, 4>
Fixed-capacity pane list for all supported viewport layouts.
using ViewportCameraSnapshotArray = std::array<ViewportCameraSnapshot, 4>
Fixed-capacity camera snapshot list for all supported viewport layouts.
Enumerations
enum class ActionId : std::uint16_t {
NewScene , OpenScene , SaveScene , SaveSceneAs ,
Exit , Undo , Redo , DuplicateSelection ,
DeleteSelection , SelectTool , MoveTool , RotateTool ,
ScaleTool , BoxTool , CreateCube , CreateLight ,
CreateCamera , ViewPerspective , ViewShaded , ToggleQuadViewports ,
FocusViewport , ShowScenePanel , ShowPropertiesPanel , ShowDiagnosticsPanel ,
ResetWorkspaceLayout
}
Stable identifiers for canonical user-visible Qt actions.
enum class DiagnosticsNodeKind : std::uint8_t {
Section , SummaryField , RenderPass , Counter ,
Diagnostic
}
Row kinds exposed by the viewport diagnostics model.
enum class DiagnosticsItemColumn : int { Name = 0 , Value = 1 , Detail = 2 }
Columns exposed by the viewport diagnostics model.
enum class DocumentItemKind : std::uint8_t { MeshObject }
Row kind exposed by the document item model.
enum class DocumentItemColumn : int { Name = 0 , Kind = 1 }
Columns exposed by the document item model.
enum class PropertyValueKind : std::uint8_t {
String , Float , Int , Vector3 ,
ReadOnlyText
}
Value/editor kind exposed by a property descriptor.
enum class PropertyField : std::uint8_t {
ObjectName , ObjectKind , VertexCount , EdgeCount ,
FaceCount , TranslationX , TranslationY , TranslationZ ,
RotationX , RotationY , RotationZ , ScaleX ,
ScaleY , ScaleZ , SelectionSummary
}
Stable property fields exposed by the property model.
enum class PropertyItemColumn : int { Label = 0 , Value = 1 }
Columns exposed by the property item model.
enum class PanelId : std::uint16_t { Properties , Scene , Diagnostics }
Stable identifiers for dockable panels.
enum class CommandFeedback { Silent , NotifyOnReject }
User-feedback policy for command execution failures.
enum class ImportUiResult { NoImporterRegistered , Canceled , ImportFailed , ParsedNotApplied }
Result of the UI import flow.
enum class NotificationSeverity { Status , Info , Warning , Error }
Severity level for UI notifications.
enum class ViewportFlyKey { Forward , Backward , Left , Right }
Fly-navigation movement key.
enum class ViewportLayoutMode { Single , Quad }
Viewport layout mode.
enum class ViewportSplitHandle { None , Vertical , Horizontal }
Splitter handle under the pointer.
enum class ViewportMouseButton { Left , Middle , Right , Other }
Toolkit-neutral viewport mouse button.
enum class ViewportKey {
W , A , S , D ,
Escape , Other
}
Toolkit-neutral viewport key used by navigation/tools.
enum class CameraProjection { Perspective , Orthographic }
Camera projection mode.
enum class NavigationMode { None , Orbit , Pan , Fly }
Active viewport navigation mode.
enum class ViewportPickElementKind : std::uint8_t {
None , Object , Submesh , Face ,
Edge , Vertex
}
Viewport-level picking payload kind.
Functions
std::string_view action_id_name (ActionId id) noexcept
Return the stable debug name for an action id.
void register_standard_actions (ActionRegistry &registry)
Register the standard V1 action set.
void register_ui_model_metatypes ()
Register Qt metatypes used by UI item models.
std::vector< PropertyDescriptor > build_property_descriptors (const quader::document::Document &document)
Build property descriptors for the current document selection.
QString panel_id_name (PanelId id)
Return the user-visible panel name.
QString panel_object_name (PanelId id)
Return the stable Qt object name used for workspace persistence.
void apply_qt_application_metadata (QApplication &app, const QtApplicationMetadata &metadata)
Apply Qt application metadata from app configuration.
QList< FileDialogFilter > import_filters_from_formats (const std::vector< quader::io::FileFormatDescriptor > &formats)
Convert import file format descriptors into Qt file-dialog filters.
ViewportDiagnosticsSnapshot viewport_diagnostics_from_crimson (const crimson::RendererDiagnosticsSnapshot &snapshot, QString renderer_name)
std::unique_ptr< IViewportRenderHost > create_crimson_viewport_render_host ()
Create a standalone Crimson viewport render host with prototype content.
std::unique_ptr< IViewportRenderHost > create_crimson_viewport_render_host (const quader::document::Document &document, const quader::tools::ToolManager &tool_manager)
void append_tool_preview_line_overlays (const quader::tools::ToolPreview &preview, std::size_t view_count, std::vector< crimson::OverlayCommand > &overlays, std::vector< crimson::LineOverlaySegment > &line_payloads)
constexpr int pane_count_for_layout (ViewportLayoutMode mode) noexcept
Return the number of panes for a layout mode.
Vec3 cross (Vec3 left, Vec3 right) noexcept
float dot (Vec2 left, Vec2 right) noexcept
float length (Vec3 value) noexcept
Vec3 normalized (Vec3 value, float epsilon=kDefaultEpsilon) noexcept
Variables
constexpr crimson::ColorSrgb kBoxToolPreviewLineColorSrgb
Reference Box tool preview line color in sRGB.
constexpr float kBoxToolPreviewLineOpacity = 1.0F
Reference Box tool preview opacity. Alpha is carried in the color value.
constexpr float kBoxToolPreviewLineThicknessPx = 2.0F
Reference Box tool preview line thickness in physical pixels.
constexpr int kViewportSplitterWidth = 4
Visible splitter width in pixels.
constexpr int kViewportSplitterHitTolerance = 6
Splitter hit-test tolerance in pixels.
constexpr int kMinimumViewportExtent = 96
Minimum pane extent in pixels.
Typedef Documentation
ViewportCameraSnapshotArray
using quader::ui::ViewportCameraSnapshotArray = std::array<ViewportCameraSnapshot, 4>
Fixed-capacity camera snapshot list for all supported viewport layouts.
Definition at line 298 of file viewport_types.hpp.
ViewportPaneArray
using quader::ui::ViewportPaneArray = std::array<ViewportPane, 4>
Fixed-capacity pane list for all supported viewport layouts.
Definition at line 296 of file viewport_types.hpp.
ViewportPickRequestId
using quader::ui::ViewportPickRequestId = std::uint64_t
Stable id for viewport picking requests.
Definition at line 143 of file viewport_types.hpp.
Enumeration Type Documentation
ActionId
enum class quader::ui::ActionId : std::uint16_t strong
Stable identifiers for canonical user-visible Qt actions.
Enumerator
NewScene
Create a new scene.
OpenScene
Open an existing scene.
SaveScene
Save the current scene.
SaveSceneAs
Save the current scene to a new path.
Exit
Quit the application.
Undo
Undo the last command.
Redo
Redo the next command.
DuplicateSelection
Duplicate the current selection.
DeleteSelection
Delete the current selection.
SelectTool
Activate the selection tool.
MoveTool
Activate the move tool.
RotateTool
Activate the rotate tool.
ScaleTool
Activate the scale tool.
BoxTool
Activate the box creation tool.
CreateCube
Create a cube primitive.
CreateLight
Create a light object.
CreateCamera
Create a camera object.
ViewPerspective
Switch the active view to perspective mode.
ViewShaded
Switch the viewport to shaded mode.
ToggleQuadViewports
Toggle single/quad viewport layout.
FocusViewport
Focus the viewport on the current selection.
ShowScenePanel
Show or hide the scene panel.
ShowPropertiesPanel
Show or hide the properties panel.
ShowDiagnosticsPanel
Show or hide the diagnostics panel.
ResetWorkspaceLayout
Restore the default workspace layout.
Definition at line 18 of file action_id.hpp.
CameraProjection
enum class quader::ui::CameraProjection strong
Camera projection mode.
Enumerator
Perspective
Perspective projection.
Orthographic
Orthographic projection.
Definition at line 99 of file viewport_types.hpp.
CommandFeedback
enum class quader::ui::CommandFeedback strong
User-feedback policy for command execution failures.
Enumerator
Silent
Do not post rejection notifications.
NotifyOnReject
Post rejection notifications.
Definition at line 35 of file document_ui_controller.hpp.
DiagnosticsItemColumn
enum class quader::ui::DiagnosticsItemColumn : int strong
Columns exposed by the viewport diagnostics model.
Enumerator
Name
Name or category column.
Value
Value or severity column.
Detail
Detail column.
Definition at line 38 of file diagnostics_item_model.hpp.
DiagnosticsNodeKind
enum class quader::ui::DiagnosticsNodeKind : std::uint8_t strong
Row kinds exposed by the viewport diagnostics model.
Enumerator
Section
Top-level grouping row.
SummaryField
Summary key/value row.
RenderPass
Render pass statistics row.
Counter
Renderer counter row.
Diagnostic
Renderer diagnostic row.
Definition at line 29 of file diagnostics_item_model.hpp.
DocumentItemColumn
enum class quader::ui::DocumentItemColumn : int strong
Columns exposed by the document item model.
Enumerator
Name
Object name column.
Kind
Object kind column.
Definition at line 38 of file item_model_roles.hpp.
DocumentItemKind
enum class quader::ui::DocumentItemKind : std::uint8_t strong
Row kind exposed by the document item model.
Enumerator
MeshObject
Mesh object row.
Definition at line 33 of file item_model_roles.hpp.
ImportUiResult
enum class quader::ui::ImportUiResult strong
Result of the UI import flow.
Enumerator
NoImporterRegistered
No import formats are registered.
Canceled
User canceled the dialog.
ImportFailed
Import service returned an error.
ParsedNotApplied
File parsed but document application is not wired yet.
Definition at line 36 of file import_ui_controller.hpp.
NavigationMode
enum class quader::ui::NavigationMode strong
Active viewport navigation mode.
Enumerator
None
No navigation gesture.
Orbit
Orbit around the camera target.
Pan
Pan camera target/eye.
Fly
Free-look fly navigation.
Definition at line 105 of file viewport_types.hpp.
NotificationSeverity
enum class quader::ui::NotificationSeverity strong
Severity level for UI notifications.
Enumerator
Status
Short status-bar style message.
Info
Informational message.
Warning
Recoverable warning.
Error
Error message.
Definition at line 18 of file notification_service.hpp.
PanelId
enum class quader::ui::PanelId : std::uint16_t strong
Stable identifiers for dockable panels.
Enumerator
Properties
Properties panel.
Scene
Scene hierarchy panel.
Diagnostics
Renderer diagnostics panel.
Definition at line 19 of file panel_id.hpp.
PropertyField
enum class quader::ui::PropertyField : std::uint8_t strong
Stable property fields exposed by the property model.
Enumerator
ObjectName
Object name.
ObjectKind
Object kind label.
VertexCount
Mesh vertex count.
EdgeCount
Mesh edge count.
FaceCount
Mesh face count.
TranslationX
X translation component.
TranslationY
Y translation component.
TranslationZ
Z translation component.
RotationX
X Euler rotation component.
RotationY
Y Euler rotation component.
RotationZ
Z Euler rotation component.
ScaleX
X scale component.
ScaleY
Y scale component.
ScaleZ
Z scale component.
SelectionSummary
Read-only selection summary.
Definition at line 38 of file property_descriptor.hpp.
PropertyItemColumn
enum class quader::ui::PropertyItemColumn : int strong
Columns exposed by the property item model.
Enumerator
Label
Property label.
Value
Property value/editor.
Definition at line 26 of file property_item_model.hpp.
PropertyValueKind
enum class quader::ui::PropertyValueKind : std::uint8_t strong
Value/editor kind exposed by a property descriptor.
Enumerator
String
Editable string value.
Float
Editable floating-point value.
Int
Editable integer value.
Vector3
Three-component vector value.
ReadOnlyText
Display-only text.
Definition at line 29 of file property_descriptor.hpp.
ViewportFlyKey
enum class quader::ui::ViewportFlyKey strong
Fly-navigation movement key.
Enumerator
Forward
Move forward.
Backward
Move backward.
Left
Strafe left.
Right
Strafe right.
Definition at line 21 of file viewport_camera_controller.hpp.
ViewportKey
enum class quader::ui::ViewportKey strong
Toolkit-neutral viewport key used by navigation/tools.
Enumerator
W
W key.
A
A key.
S
S key.
D
D key.
Escape
Escape key.
Other
Unsupported key.
Definition at line 89 of file viewport_types.hpp.
ViewportLayoutMode
enum class quader::ui::ViewportLayoutMode strong
Viewport layout mode.
Enumerator
Single
One viewport pane.
Quad
Four viewport panes.
Definition at line 68 of file viewport_types.hpp.
ViewportMouseButton
enum class quader::ui::ViewportMouseButton strong
Toolkit-neutral viewport mouse button.
Enumerator
Left
Left button.
Middle
Middle button.
Right
Right button.
Other
Unsupported or auxiliary button.
Definition at line 81 of file viewport_types.hpp.
ViewportPickElementKind
enum class quader::ui::ViewportPickElementKind : std::uint8_t strong
Viewport-level picking payload kind.
Enumerator
None
No hit.
Object
Object-level hit.
Submesh
Submesh hit.
Face
Face hit.
Edge
Edge hit.
Vertex
Vertex hit.
Definition at line 146 of file viewport_types.hpp.
ViewportSplitHandle
enum class quader::ui::ViewportSplitHandle strong
Splitter handle under the pointer.
Enumerator
None
No splitter.
Vertical
Vertical splitter.
Horizontal
Horizontal splitter.
Definition at line 74 of file viewport_types.hpp.
Function Documentation
action_id_name()
std::string_view quader::ui::action_id_name (ActionId id) nodiscard noexcept
Return the stable debug name for an action id.
Definition at line 14 of file action_id.cpp.
References BoxTool, CreateCamera, CreateCube, CreateLight, DeleteSelection, DuplicateSelection, Exit, FocusViewport, MoveTool, NewScene, OpenScene, Redo, ResetWorkspaceLayout, RotateTool, SaveScene, SaveSceneAs, ScaleTool, SelectTool, ShowDiagnosticsPanel, ShowPropertiesPanel, ShowScenePanel, ToggleQuadViewports, Undo, ViewPerspective, and ViewShaded.
append_tool_preview_line_overlays()
void quader::ui::append_tool_preview_line_overlays (const quader::tools::ToolPreview & preview, std::size_t view_count, std::vector< crimson::OverlayCommand > & overlays, std::vector< crimson::LineOverlaySegment > & line_payloads)
Convert a tool preview's world line segments into Crimson overlay commands.
Parameters
preview Tool preview to convert.
view_count Number of active render views.
overlays Destination overlay command list.
line_payloads Destination line segment payload list.
Definition at line 35 of file tool_preview_overlay_adapter.cpp.
References quader::tools::ToolPreview::active, quader::tools::ToolPreviewBox::active, crimson::AlwaysOnTop, quader::tools::ToolPreview::boxes, quader::tools::ToolPreviewBox::corners, quader::tools::ToolPreviewWorldSegment::end, kBoxToolPreviewLineColorSrgb, kBoxToolPreviewLineOpacity, kBoxToolPreviewLineThicknessPx, crimson::LineList, crimson::OverlayUnlit, quader::tools::ToolPreviewWorldSegment::start, quader::tools::ToolPreview::view_index, and quader::tools::ToolPreview::world_segments.
apply_qt_application_metadata()
void quader::ui::apply_qt_application_metadata (QApplication & app, const QtApplicationMetadata & metadata)
Apply Qt application metadata from app configuration.
Definition at line 16 of file qt_application_bootstrap.cpp.
References quader::ui::QtApplicationMetadata::application_name, and quader::ui::QtApplicationMetadata::organization_name.
Referenced by quader::app::Application::Application().
build_property_descriptors()
std::vector< PropertyDescriptor > quader::ui::build_property_descriptors (const quader::document::Document & document)
Build property descriptors for the current document selection.
Definition at line 95 of file property_descriptor.cpp.
References EdgeCount, FaceCount, Int, ObjectKind, ObjectName, ReadOnlyText, String, and VertexCount.
Referenced by quader::ui::PropertyItemModel::rebuild_from_document().
create_crimson_viewport_render_host() [1/2]
std::unique_ptr< IViewportRenderHost > quader::ui::create_crimson_viewport_render_host ()
Create a standalone Crimson viewport render host with prototype content.
Definition at line 695 of file crimson_viewport_render_host.cpp.
create_crimson_viewport_render_host() [2/2]
std::unique_ptr< IViewportRenderHost > quader::ui::create_crimson_viewport_render_host (const quader::document::Document & document, const quader::tools::ToolManager & tool_manager)
Create a Crimson viewport render host backed by document and tool state.
Parameters
document Document state to translate into frame snapshots.
tool_manager Tool manager whose preview is translated into overlays.
Returns
Render host owned by the caller.
Definition at line 699 of file crimson_viewport_render_host.cpp.
cross()
Vec3 quader::math::cross (Vec3 left, Vec3 right) inline nodiscard noexcept
Compute a cross product.
Parameters
left First vector.
right Second vector.
Returns
Vector perpendicular to left and right using right-handed order.
Definition at line 96 of file vec3.hpp.
dot()
float quader::math::dot (Vec2 left, Vec2 right) inline nodiscard noexcept
Compute a dot product.
Parameters
left First vector.
right Second vector.
Returns
Sum of component-wise products.
Definition at line 68 of file vec2.hpp.
Referenced by quader::ui::ViewportCameraController::camera_pose().
import_filters_from_formats()
QList< FileDialogFilter > quader::ui::import_filters_from_formats (const std::vector< quader::io::FileFormatDescriptor > & formats) nodiscard
Convert import file format descriptors into Qt file-dialog filters.
Definition at line 168 of file import_ui_controller.cpp.
References quader::io::FileFormatDescriptor::extensions.
Referenced by quader::ui::ImportUiController::import_filters().
length()
float quader::math::length (Vec3 value) inline nodiscard noexcept
Compute vector length.
Parameters
value Vector to measure.
Returns
Euclidean length.
Definition at line 118 of file vec3.hpp.
Referenced by quader::ui::ViewportCameraController::camera_pose(), quader::ui::ViewportCameraController::tick_fly_navigation(), and quader::ui::ViewportCameraController::update_navigation().
normalized()
Vec3 quader::math::normalized (Vec3 value, float epsilon = kDefaultEpsilon) inline nodiscard noexcept
Normalize a vector with a zero fallback.
Parameters
value Vector to normalize.
epsilon Length threshold treated as degenerate.
Returns
Unit vector, or the zero vector when value is degenerate.
Definition at line 129 of file vec3.hpp.
Referenced by quader::ui::ViewportCameraController::camera_pose(), quader::ui::ViewportCameraController::tick_fly_navigation(), and quader::ui::ViewportCameraController::update_navigation().
pane_count_for_layout()
int quader::ui::pane_count_for_layout (ViewportLayoutMode mode) nodiscard constexpr noexcept
Return the number of panes for a layout mode.
Definition at line 291 of file viewport_types.hpp.
References Quad.
Referenced by quader::ui::ViewportLayoutState::pane_count().
panel_id_name()
QString quader::ui::panel_id_name (PanelId id) nodiscard
Return the user-visible panel name.
Definition at line 14 of file panel_id.cpp.
References Diagnostics, Properties, and Scene.
Referenced by panel_object_name(), quader::ui::SettingsService::panel_visible(), and quader::ui::SettingsService::set_panel_visible().
panel_object_name()
QString quader::ui::panel_object_name (PanelId id) nodiscard
Return the stable Qt object name used for workspace persistence.
Definition at line 27 of file panel_id.cpp.
References panel_id_name().
Referenced by quader::ui::PanelHost::add_panel().
register_standard_actions()
void quader::ui::register_standard_actions (ActionRegistry & registry)
Register the standard V1 action set.
Definition at line 61 of file action_registry.cpp.
References BoxTool, CreateCamera, CreateCube, CreateLight, DeleteSelection, DuplicateSelection, Exit, FocusViewport, MoveTool, NewScene, OpenScene, Redo, quader::ui::ActionRegistry::register_action(), ResetWorkspaceLayout, RotateTool, SaveScene, SaveSceneAs, ScaleTool, SelectTool, ShowDiagnosticsPanel, ShowPropertiesPanel, ShowScenePanel, ToggleQuadViewports, Undo, ViewPerspective, and ViewShaded.
Referenced by quader::app::AppServices::AppServices().
register_ui_model_metatypes()
void quader::ui::register_ui_model_metatypes ()
Register Qt metatypes used by UI item models.
Definition at line 19 of file item_model_roles.cpp.
Referenced by quader::ui::DiagnosticsItemModel::DiagnosticsItemModel(), quader::ui::DocumentItemModel::DocumentItemModel(), and quader::ui::PropertyItemModel::PropertyItemModel().
viewport_diagnostics_from_crimson()
ViewportDiagnosticsSnapshot quader::ui::viewport_diagnostics_from_crimson (const crimson::RendererDiagnosticsSnapshot & snapshot, QString renderer_name = {}) nodiscard
Convert Crimson diagnostics into UI-facing viewport diagnostics.
Parameters
snapshot Crimson diagnostics snapshot.
renderer_name Optional renderer name override.
Returns
UI diagnostics snapshot.
Definition at line 329 of file crimson_viewport_render_host.cpp.
References crimson::RendererStatus::backend_name, crimson::RendererDiagnostic::code, crimson::RendererDiagnosticsSnapshot::counters, quader::ui::ViewportDiagnosticsSnapshot::counters, crimson::RenderPassStats::cpu_time_us, crimson::RendererDiagnostic::detail, quader::ui::ViewportDiagnosticsSnapshot::diagnostics, crimson::RendererCounter::domain, crimson::RenderPassStats::draw_call_count, crimson::RenderPassStats::draw_packet_count, quader::ui::ViewportDiagnosticsSnapshot::frame, crimson::RendererDiagnosticsSnapshot::frame_graph_dump, quader::ui::ViewportDiagnosticsSnapshot::frame_graph_dump, crimson::RendererDiagnostic::frame_index, crimson::RendererDiagnosticsSnapshot::latest_frame_stats, crimson::RendererDiagnostic::message, crimson::RendererCounter::name, crimson::RenderPassStats::pass_name, crimson::RendererDiagnosticsSnapshot::pass_stats, quader::ui::ViewportDiagnosticsSnapshot::passes, crimson::RendererDiagnosticsSnapshot::recent_diagnostics, crimson::renderer_counter_domain_name(), crimson::renderer_diagnostic_code_name(), crimson::renderer_diagnostic_severity_name(), crimson::renderer_metric_unit_name(), quader::ui::ViewportDiagnosticsSnapshot::renderer_name, crimson::RendererDiagnostic::resource_name, crimson::RenderPassStats::resource_read_count, crimson::RenderPassStats::resource_write_count, crimson::RendererDiagnostic::severity, crimson::RendererDiagnosticsSnapshot::status, crimson::RendererDiagnostic::subsystem, crimson::RendererCounter::unit, and crimson::RendererCounter::value.
Referenced by quader::ui::CrimsonViewportRenderHost::latest_diagnostics().
Variable Documentation
kBoxToolPreviewLineColorSrgb
crimson::ColorSrgb quader::ui::kBoxToolPreviewLineColorSrgb inline constexpr
Initial value:
{
    1.0F,
    235.0F / 255.0F,
    41.0F / 255.0F,
    209.0F / 255.0F,
}
Reference Box tool preview line color in sRGB.
Definition at line 21 of file tool_preview_overlay_adapter.hpp.
Referenced by append_tool_preview_line_overlays().
kBoxToolPreviewLineOpacity
float quader::ui::kBoxToolPreviewLineOpacity = 1.0F inline constexpr
Reference Box tool preview opacity. Alpha is carried in the color value.
Definition at line 28 of file tool_preview_overlay_adapter.hpp.
Referenced by append_tool_preview_line_overlays().
kBoxToolPreviewLineThicknessPx
float quader::ui::kBoxToolPreviewLineThicknessPx = 2.0F inline constexpr
Reference Box tool preview line thickness in physical pixels.
Definition at line 30 of file tool_preview_overlay_adapter.hpp.
Referenced by append_tool_preview_line_overlays().
kMinimumViewportExtent
int quader::ui::kMinimumViewportExtent = 96 constexpr
Minimum pane extent in pixels.
Definition at line 288 of file viewport_types.hpp.
kViewportSplitterHitTolerance
int quader::ui::kViewportSplitterHitTolerance = 6 constexpr
Splitter hit-test tolerance in pixels.
Definition at line 286 of file viewport_types.hpp.
Referenced by quader::ui::ViewportLayoutState::splitter_at().
kViewportSplitterWidth
int quader::ui::kViewportSplitterWidth = 4 constexpr
Visible splitter width in pixels.
Definition at line 284 of file viewport_types.hpp.