Quader: quader::document Namespace Reference
quader::document Namespace Reference
Classes
struct ComponentRef
Reference to one mesh component on a document object.
class Document
struct DocumentChange
One queued document change notification.
struct DocumentError
Structured document-layer error with a user-presentable diagnostic.
struct MeshObject
Editable mesh object stored by the document.
class ObjectStore
struct PbrMaterial
Document-owned PBR material values for mesh objects.
class Selection
struct Transform
Document object transform stored as translation, Euler rotation, and scale.
Typedefs
using DocumentDirtyFlags = std::uint32_t
Packed bitmask of DocumentDirtyFlag values.
using ObjectId = quader::foundation::GenerationalId<ObjectTag>
Stable generational id for scene objects stored in a document.
Enumerations
enum class DocumentErrorCode {
InvalidObject , ObjectAlreadyExists , InvalidMesh , InvalidTransform ,
InvalidMaterial , InvalidSelection , InvalidVertex , InvalidEdge ,
InvalidFace
}
Error categories reported by document validation and mutation APIs.
enum class DocumentChangeKind {
ObjectCreated , ObjectDeleted , ObjectRenamed , TransformChanged ,
MeshTopologyChanged , MeshGeometryChanged , SelectionChanged , DirtyStateChanged
}
Kinds of document changes emitted into the pending change queue.
enum class DocumentDirtyFlag : std::uint32_t {
None = 0U , Objects = 1U << 0U , ObjectProperties = 1U << 1U , Transforms = 1U << 2U ,
MeshTopology = 1U << 3U , MeshGeometry = 1U << 4U , Selection = 1U << 5U
}
Bit values that identify which document subsystems are dirty.
enum class SceneObjectKind { Mesh }
Scene object categories currently supported by the document.
enum class ComponentKind { Vertex , Edge , Face }
Mesh component category held by a component selection reference.
Functions
DocumentError make_document_error (DocumentErrorCode code, std::string message)
constexpr DocumentDirtyFlags to_dirty_flags (DocumentDirtyFlag flag) noexcept
constexpr DocumentDirtyFlags operator| (DocumentDirtyFlag left, DocumentDirtyFlag right) noexcept
constexpr DocumentDirtyFlags operator| (DocumentDirtyFlags left, DocumentDirtyFlag right) noexcept
constexpr bool has_dirty_flag (DocumentDirtyFlags flags, DocumentDirtyFlag flag) noexcept
constexpr PbrMaterial default_box_material () noexcept
bool is_finite (PbrMaterial material) noexcept
bool is_valid (PbrMaterial material) noexcept
ComponentKind component_kind (const ComponentRef &ref) noexcept
bool component_id_is_valid (const ComponentRef &ref)
constexpr bool vec3_exactly_equal (quader::math::Vec3 left, quader::math::Vec3 right) noexcept
constexpr bool operator== (Transform left, Transform right) noexcept
bool is_finite (Transform transform) noexcept
Variables
constexpr DocumentDirtyFlags kDocumentDirtyNone = 0U
Empty dirty flag mask.
Typedef Documentation
DocumentDirtyFlags
using quader::document::DocumentDirtyFlags = std::uint32_t
Packed bitmask of DocumentDirtyFlag values.
Definition at line 42 of file document_events.hpp.
ObjectId
using quader::document::ObjectId = quader::foundation::GenerationalId<ObjectTag>
Stable generational id for scene objects stored in a document.
Definition at line 20 of file object_id.hpp.
Enumeration Type Documentation
ComponentKind
enum class quader::document::ComponentKind strong
Mesh component category held by a component selection reference.
Enumerator
Vertex
Vertex component.
Edge
Edge component.
Face
Face component.
Definition at line 24 of file selection.hpp.
DocumentChangeKind
enum class quader::document::DocumentChangeKind strong
Kinds of document changes emitted into the pending change queue.
Enumerator
ObjectCreated
A scene object was added or restored.
ObjectDeleted
A scene object was removed.
ObjectRenamed
An object's display name changed.
TransformChanged
An object's transform changed.
MeshTopologyChanged
Mesh connectivity or element identity changed.
MeshGeometryChanged
Mesh positions or geometric attributes changed.
SelectionChanged
Document selection changed.
DirtyStateChanged
Dirty flags changed.
Definition at line 19 of file document_events.hpp.
DocumentDirtyFlag
enum class quader::document::DocumentDirtyFlag : std::uint32_t strong
Bit values that identify which document subsystems are dirty.
Enumerator
None
No dirty subsystem.
Objects
Object list changed.
ObjectProperties
Object metadata or material changed.
Transforms
Object transform changed.
MeshTopology
Mesh connectivity changed.
MeshGeometry
Mesh geometry changed.
Selection
Selection changed.
Definition at line 31 of file document_events.hpp.
DocumentErrorCode
enum class quader::document::DocumentErrorCode strong
Error categories reported by document validation and mutation APIs.
Enumerator
InvalidObject
Object id is unknown, stale, or otherwise unusable.
ObjectAlreadyExists
A restore operation targets an already-live object slot.
InvalidMesh
Mesh topology or geometry failed document validation.
InvalidTransform
Transform contains non-finite values.
InvalidMaterial
Material values are non-finite or outside accepted ranges.
InvalidSelection
Selection payload cannot be represented by the document.
InvalidVertex
Vertex component reference is invalid.
InvalidEdge
Edge component reference is invalid.
InvalidFace
Face component reference is invalid.
Definition at line 20 of file document_error.hpp.
SceneObjectKind
enum class quader::document::SceneObjectKind strong
Scene object categories currently supported by the document.
Enumerator
Mesh
Editable mesh object.
Definition at line 22 of file scene_object.hpp.
Function Documentation
component_id_is_valid()
bool quader::document::component_id_is_valid (const ComponentRef & ref) nodiscard
Check whether the component id itself is non-null.
Parameters
ref Component reference to inspect.
Returns
True when the contained mesh id is structurally valid.
Definition at line 73 of file selection.cpp.
References quader::document::ComponentRef::component.
Referenced by quader::document::Selection::set_components(), and quader::document::Document::validate_component_ref().
component_kind()
ComponentKind quader::document::component_kind (const ComponentRef & ref) nodiscard noexcept
Return the component kind stored by a component reference.
Parameters
ref Component reference to inspect.
Returns
Variant kind represented by ref.
Definition at line 60 of file selection.cpp.
References Edge, Face, and Vertex.
Referenced by quader::document::Selection::set_components(), and quader::document::Document::validate_component_ref().
default_box_material()
PbrMaterial quader::document::default_box_material () nodiscard constexpr noexcept
Return the default material assigned to newly committed Box tool meshes.
Returns
Neutral gray, fully rough, non-metallic PBR material values.
Definition at line 37 of file material.hpp.
has_dirty_flag()
bool quader::document::has_dirty_flag (DocumentDirtyFlags flags, DocumentDirtyFlag flag) nodiscard constexpr noexcept
Check whether a dirty flag is present in a bitmask.
Parameters
flags Dirty flag bitmask.
flag Flag to test.
Returns
True when flag is present.
Definition at line 87 of file document_events.hpp.
References to_dirty_flags().
Referenced by quader::document::Document::has_dirty_flag().
is_finite() [1/2]
bool quader::document::is_finite (PbrMaterial material) inline nodiscard noexcept
Check whether all material scalar values are finite.
Parameters
material Material to validate.
Returns
True when every stored value is finite.
Definition at line 47 of file material.hpp.
References quader::math::is_finite().
Referenced by quader::document::Document::create_mesh_object(), is_valid(), quader::document::Document::set_transform(), and quader::io::validate_document_fragment().
is_finite() [2/2]
bool quader::document::is_finite (Transform transform) inline nodiscard noexcept
Check whether every transform component is finite.
Parameters
transform Transform to validate.
Returns
True when translation, rotation, and scale contain only finite values.
Definition at line 53 of file transform.hpp.
References quader::math::is_finite().
is_valid()
bool quader::document::is_valid (PbrMaterial material) inline nodiscard noexcept
Check whether a material is finite and within normalized PBR ranges.
Parameters
material Material to validate.
Returns
True when the material is valid for document storage and rendering adapters.
Definition at line 57 of file material.hpp.
References is_finite().
Referenced by quader::document::Document::create_mesh_object(), quader::document::ObjectStore::find_mesh_object(), quader::document::ObjectStore::find_mesh_object(), and quader::document::ObjectStore::restore_mesh_object().
make_document_error()
DocumentError quader::document::make_document_error (DocumentErrorCode code, std::string message) inline nodiscard
Build a document error diagnostic with error severity.
Parameters
code Error category.
message Diagnostic message to move into the error.
Returns
Document error carrying code and message.
Definition at line 47 of file document_error.hpp.
References quader::foundation::Error.
Referenced by quader::document::Document::create_mesh_object(), quader::document::ObjectStore::remove_mesh_object(), quader::document::Document::rename_object(), quader::document::ObjectStore::restore_mesh_object(), quader::document::Selection::set_components(), quader::document::Selection::set_objects(), quader::document::Document::set_transform(), quader::document::Document::validate_component_ref(), and quader::document::Document::validate_object_id().
operator==()
bool quader::document::operator== (Transform left, Transform right) nodiscard constexpr noexcept
Compare two transforms with exact component equality.
Parameters
left,right Transforms to compare.
Returns
True when translation, rotation, and scale match exactly.
Definition at line 43 of file transform.hpp.
References vec3_exactly_equal().
operator|() [1/2]
DocumentDirtyFlags quader::document::operator| (DocumentDirtyFlag left, DocumentDirtyFlag right) nodiscard constexpr noexcept
Combine two dirty flags into a bitmask.
Parameters
left,right Flags to combine.
Returns
Bitmask containing both flags.
Definition at line 63 of file document_events.hpp.
References to_dirty_flags().
operator|() [2/2]
DocumentDirtyFlags quader::document::operator| (DocumentDirtyFlags left, DocumentDirtyFlag right) nodiscard constexpr noexcept
Add a dirty flag to an existing bitmask.
Parameters
left Existing bitmask.
right Flag to add.
Returns
Combined dirty flag bitmask.
Definition at line 75 of file document_events.hpp.
References to_dirty_flags().
to_dirty_flags()
DocumentDirtyFlags quader::document::to_dirty_flags (DocumentDirtyFlag flag) nodiscard constexpr noexcept
Convert one dirty flag into its bitmask representation.
Parameters
flag Flag to convert.
Returns
Bitmask containing flag.
Definition at line 53 of file document_events.hpp.
Referenced by quader::document::Document::clear_selection(), quader::document::Document::create_mesh_object(), quader::document::Document::extract_mesh_object(), has_dirty_flag(), quader::document::Document::mark_mesh_geometry_changed(), quader::document::Document::mark_mesh_topology_changed(), operator|(), operator|(), quader::document::Document::rename_object(), quader::document::Document::restore_mesh_object(), quader::document::Document::set_selection(), and quader::document::Document::set_transform().
vec3_exactly_equal()
bool quader::document::vec3_exactly_equal (quader::math::Vec3 left, quader::math::Vec3 right) nodiscard constexpr noexcept
Compare two vectors with exact component equality.
Parameters
left,right Vectors to compare.
Returns
True when all components match exactly.
Definition at line 32 of file transform.hpp.
Referenced by operator==().
Variable Documentation
kDocumentDirtyNone
DocumentDirtyFlags quader::document::kDocumentDirtyNone = 0U constexpr
Empty dirty flag mask.
Definition at line 45 of file document_events.hpp.
Referenced by quader::document::Document::clear_dirty(), and quader::document::Document::is_dirty().