Quader: quader::math Namespace Reference
quader::math Namespace Reference
Namespaces
namespace detail
Classes
struct Aabb
Axis-aligned bounding box with an empty default state.
struct Vec2
Two-component single-precision vector.
struct Vec3
Three-component single-precision vector.
Functions
bool empty (Aabb bounds) noexcept
void expand (Aabb &bounds, Vec3 point) noexcept
Vec3 center (Aabb bounds) noexcept
bool nearly_equal (float left, float right, float epsilon=kDefaultEpsilon) noexcept
bool is_near_zero (float value, float epsilon=kDefaultEpsilon) noexcept
bool is_finite (float value) noexcept
Vec2 operator+ (Vec2 left, Vec2 right) noexcept
Vec2 operator- (Vec2 left, Vec2 right) noexcept
Vec2 operator* (Vec2 value, float scale) noexcept
float dot (Vec2 left, Vec2 right) noexcept
float length_squared (Vec2 value) noexcept
bool is_finite (Vec2 value) noexcept
bool nearly_equal (Vec2 left, Vec2 right, float epsilon=kDefaultEpsilon) noexcept
Vec3 operator+ (Vec3 left, Vec3 right) noexcept
Vec3 operator- (Vec3 left, Vec3 right) noexcept
Vec3 operator* (Vec3 value, float scale) noexcept
Vec3 operator/ (Vec3 value, float scale) noexcept
float dot (Vec3 left, Vec3 right) noexcept
Vec3 cross (Vec3 left, Vec3 right) noexcept
float length_squared (Vec3 value) noexcept
float length (Vec3 value) noexcept
Vec3 normalized (Vec3 value, float epsilon=kDefaultEpsilon) noexcept
bool is_finite (Vec3 value) noexcept
bool nearly_equal (Vec3 left, Vec3 right, float epsilon=kDefaultEpsilon) noexcept
Variables
constexpr float kDefaultEpsilon = 1.0e-6F
Default tolerance for scalar and vector approximate comparisons.
Function Documentation
center()
Vec3 quader::math::center (Aabb bounds) inline nodiscard noexcept
Compute the center point of bounds.
Parameters
bounds Bounds to sample.
Returns
Midpoint between bounds.min and bounds.max.
Definition at line 66 of file aabb.hpp.
Referenced by crimson::cull_object_bounds().
cross()
Vec3 quader::math::cross (Vec3 left, Vec3 right) inline nodiscard noexcept
Compute a cross product.
Parameters
left First vector.
right Second vector.
Returns
Vector perpendicular to left and right using right-handed order.
Definition at line 96 of file vec3.hpp.
References quader::math::detail::cross().
Referenced by quader::tools::make_box_construction_plane(), crimson::make_camera_frustum(), and quader::geometry::triangle_normal().
dot() [1/2]
float quader::math::dot (Vec2 left, Vec2 right) inline nodiscard noexcept
Compute a dot product.
Parameters
left First vector.
right Second vector.
Returns
Sum of component-wise products.
Definition at line 68 of file vec2.hpp.
References quader::math::detail::dot().
Referenced by crimson::cull_object_bounds(), and quader::tools::make_box_construction_plane().
dot() [2/2]
float quader::math::dot (Vec3 left, Vec3 right) inline nodiscard noexcept
Compute a dot product.
Parameters
left First vector.
right Second vector.
Returns
Sum of component-wise products.
Definition at line 84 of file vec3.hpp.
References quader::math::detail::dot().
empty()
bool quader::math::empty (Aabb bounds) inline nodiscard noexcept
Check whether bounds contain no points.
Parameters
bounds Bounds to test.
Returns
True when any minimum component is greater than its maximum.
Definition at line 41 of file aabb.hpp.
expand()
void quader::math::expand (Aabb & bounds, Vec3 point) inline noexcept
Expand bounds to include a point.
Parameters
[in,out] bounds Bounds to mutate.
point Point included in the resulting bounds.
Definition at line 51 of file aabb.hpp.
References quader::math::detail::component_max(), and quader::math::detail::component_min().
is_finite() [1/3]
bool quader::math::is_finite (float value) inline nodiscard noexcept
Check whether a scalar is finite.
Parameters
value Value to test.
Returns
True when value is neither NaN nor infinity.
Definition at line 50 of file scalar.hpp.
Referenced by quader::geometry::all_points_finite(), quader::document::is_finite(), quader::document::is_finite(), is_finite(), is_finite(), quader::mesh::Polyhedron::set_vertex_position(), and quader::mesh::Polyhedron::validate_mesh.
is_finite() [2/3]
bool quader::math::is_finite (Vec2 value) inline nodiscard noexcept
Check whether every component is finite.
Parameters
value Vector to test.
Returns
True when both components are finite.
Definition at line 88 of file vec2.hpp.
References is_finite().
is_finite() [3/3]
bool quader::math::is_finite (Vec3 value) inline nodiscard noexcept
Check whether every component is finite.
Parameters
value Vector to test.
Returns
True when all components are finite.
Definition at line 145 of file vec3.hpp.
References is_finite().
is_near_zero()
bool quader::math::is_near_zero (float value, float epsilon = kDefaultEpsilon) inline nodiscard noexcept
Check whether a scalar is within tolerance of zero.
Parameters
value Value to test.
epsilon Maximum absolute value accepted as zero.
Returns
True when value is in [-epsilon, epsilon].
Definition at line 40 of file scalar.hpp.
References kDefaultEpsilon.
length()
float quader::math::length (Vec3 value) inline nodiscard noexcept
Compute vector length.
Parameters
value Vector to measure.
Returns
Euclidean length.
Definition at line 118 of file vec3.hpp.
References quader::math::detail::length().
Referenced by normalized().
length_squared() [1/2]
float quader::math::length_squared (Vec2 value) inline nodiscard noexcept
Compute squared vector length.
Parameters
value Vector to measure.
Returns
Dot product of value with itself.
Definition at line 78 of file vec2.hpp.
References quader::math::detail::length_squared().
Referenced by quader::geometry::has_degenerate_area(), and crimson::make_camera_frustum().
length_squared() [2/2]
float quader::math::length_squared (Vec3 value) inline nodiscard noexcept
Compute squared vector length.
Parameters
value Vector to measure.
Returns
Dot product of value with itself.
Definition at line 108 of file vec3.hpp.
References quader::math::detail::length_squared().
nearly_equal() [1/3]
bool quader::math::nearly_equal (float left, float right, float epsilon = kDefaultEpsilon) inline nodiscard noexcept
Compare two scalar values with an absolute tolerance.
Parameters
left First value to compare.
right Second value to compare.
epsilon Maximum absolute difference accepted as equal.
Returns
True when the absolute difference is no greater than epsilon.
Definition at line 27 of file scalar.hpp.
References kDefaultEpsilon.
Referenced by nearly_equal(), and nearly_equal().
nearly_equal() [2/3]
bool quader::math::nearly_equal (Vec2 left, Vec2 right, float epsilon = kDefaultEpsilon) inline nodiscard noexcept
Compare two vectors with an absolute component tolerance.
Parameters
left First vector.
right Second vector.
epsilon Maximum per-component absolute difference.
Returns
True when both component pairs are nearly equal.
Definition at line 100 of file vec2.hpp.
References kDefaultEpsilon, and nearly_equal().
nearly_equal() [3/3]
bool quader::math::nearly_equal (Vec3 left, Vec3 right, float epsilon = kDefaultEpsilon) inline nodiscard noexcept
Compare two vectors with an absolute component tolerance.
Parameters
left First vector.
right Second vector.
epsilon Maximum per-component absolute difference.
Returns
True when all component pairs are nearly equal.
Definition at line 157 of file vec3.hpp.
References kDefaultEpsilon, and nearly_equal().
normalized()
Vec3 quader::math::normalized (Vec3 value, float epsilon = kDefaultEpsilon) inline nodiscard noexcept
Normalize a vector with a zero fallback.
Parameters
value Vector to normalize.
epsilon Length threshold treated as degenerate.
Returns
Unit vector, or the zero vector when value is degenerate.
Definition at line 129 of file vec3.hpp.
References kDefaultEpsilon, length(), and quader::math::detail::normalized().
Referenced by crimson::make_camera_frustum().
operator*() [1/2]
Vec2 quader::math::operator* (Vec2 value, float scale) inline nodiscard noexcept
Scale a vector.
Parameters
value Vector to scale.
scale Scalar multiplier.
Returns
Scaled vector.
Definition at line 56 of file vec2.hpp.
References quader::math::detail::scale().
operator*() [2/2]
Vec3 quader::math::operator* (Vec3 value, float scale) inline nodiscard noexcept
Scale a vector.
Parameters
value Vector to scale.
scale Scalar multiplier.
Returns
Scaled vector.
Definition at line 60 of file vec3.hpp.
References quader::math::detail::scale().
operator+() [1/2]
Vec2 quader::math::operator+ (Vec2 left, Vec2 right) inline nodiscard noexcept
Add two vectors component-wise.
Parameters
left First addend.
right Second addend.
Returns
Component-wise sum.
Definition at line 32 of file vec2.hpp.
References quader::math::detail::add().
operator+() [2/2]
Vec3 quader::math::operator+ (Vec3 left, Vec3 right) inline nodiscard noexcept
Add two vectors component-wise.
Parameters
left First addend.
right Second addend.
Returns
Component-wise sum.
Definition at line 34 of file vec3.hpp.
References quader::math::detail::add().
operator-() [1/2]
Vec2 quader::math::operator- (Vec2 left, Vec2 right) inline nodiscard noexcept
Subtract two vectors component-wise.
Parameters
left Minuend.
right Subtrahend.
Returns
Component-wise difference.
Definition at line 44 of file vec2.hpp.
References quader::math::detail::subtract().
operator-() [2/2]
Vec3 quader::math::operator- (Vec3 left, Vec3 right) inline nodiscard noexcept
Subtract two vectors component-wise.
Parameters
left Minuend.
right Subtrahend.
Returns
Component-wise difference.
Definition at line 47 of file vec3.hpp.
References quader::math::detail::subtract().
operator/()
Vec3 quader::math::operator/ (Vec3 value, float scale) inline nodiscard noexcept
Divide a vector by a scalar.
Parameters
value Vector to divide.
scale Scalar divisor.
Returns
Component-wise quotient.
Definition at line 72 of file vec3.hpp.
References quader::math::detail::divide().
Variable Documentation
kDefaultEpsilon
float quader::math::kDefaultEpsilon = 1.0e-6F constexpr
Default tolerance for scalar and vector approximate comparisons.
Definition at line 17 of file scalar.hpp.
Referenced by quader::geometry::has_degenerate_area(), is_near_zero(), crimson::make_camera_frustum(), nearly_equal(), nearly_equal(), nearly_equal(), and normalized().