Quader: quader::io Namespace Reference
quader::io Namespace Reference
Namespaces
namespace gltf
Classes
struct DocumentFragment
Imported document subtree that can be appended to an existing document.
struct ExportOptions
Options that affect deterministic document export.
struct ExportRequest
Request passed to an exporter.
struct ExportResult
Result returned by a successful export operation.
class ExportService
Service that selects an exporter from the registry and runs it.
struct FileFormatDescriptor
Descriptor for an import/export file format.
struct FragmentValidationResult
Result of validating an imported document fragment.
class IExporter
Interface implemented by project-owned document exporters.
class IImporter
Interface implemented by project-owned document importers.
struct ImportedDocument
Full imported document payload.
struct ImportedMaterialMetadata
Material metadata preserved from an imported source file.
struct ImportedMeshObject
Mesh object payload imported before insertion into a Document.
class ImportExportRegistry
Owns registered importers and exporters and resolves them by path.
struct ImportOptions
Options that control import payload shape and validation.
struct ImportRequest
Request passed to an importer.
struct ImportResult
Result returned by a successful import operation.
class ImportService
Service that selects an importer from the registry and runs it.
struct IoDiagnostic
One diagnostic produced by an import/export operation.
class IoDiagnosticList
Ordered collection of import/export diagnostics.
struct IoError
Structured I/O error with primary and related diagnostics.
struct SourceLocation
Optional source location attached to an I/O diagnostic.
Enumerations
enum class FragmentValidationCode { EmptyFragment , InvalidMesh , InvalidTransform , InvalidMaterialReference }
Validation issue categories for imported document fragments.
enum class DocumentImportMode { ReplaceDocument , AppendFragment }
Import mode requested by the caller.
enum class IoSeverity { Info , Warning , Error }
Severity level for import/export diagnostics.
enum class IoDiagnosticCode {
Unknown , UnsupportedFormat , FileNotFound , FileReadFailed ,
FileWriteFailed , ParseFailed , ValidationFailed , MeshValidationFailed ,
DocumentValidationFailed , MaterialMappingFailed , UnsupportedFeaturePreserved , ExportNotSupported
}
Machine-readable import/export diagnostic category.
enum class IoErrorCode {
UnsupportedFormat , FileAccessFailed , ParseFailed , ValidationFailed ,
ExportFailed
}
Expected failure categories for import/export services.
Functions
FragmentValidationResult validate_document_fragment (const DocumentFragment &fragment)
quader::foundation::Result< quader::document::Document, IoError > build_document_from_import (ImportedDocument imported)
std::string normalize_extension (std::string_view extension)
std::string path_extension_without_dot (const std::filesystem::path &path)
bool descriptor_supports_extension (const FileFormatDescriptor &descriptor, const std::filesystem::path &path)
quader::foundation::Severity to_foundation_severity (IoSeverity severity) noexcept
quader::foundation::Diagnostic to_foundation_diagnostic (const IoDiagnostic &diagnostic)
quader::foundation::DiagnosticList to_foundation_diagnostics (const IoDiagnosticList &diagnostics)
IoError make_io_error (IoErrorCode code, IoDiagnostic diagnostic)
IoError make_io_error (IoErrorCode error_code, IoDiagnosticCode diagnostic_code, std::string message, std::filesystem::path source_path={}, std::string subject={})
Enumeration Type Documentation
DocumentImportMode
enum class quader::io::DocumentImportMode strong
Import mode requested by the caller.
Enumerator
ReplaceDocument
Replace the current document with the imported document.
AppendFragment
Append an imported fragment to the current document.
Definition at line 15 of file import_options.hpp.
FragmentValidationCode
enum class quader::io::FragmentValidationCode strong
Validation issue categories for imported document fragments.
Enumerator
EmptyFragment
Fragment contains no importable content.
InvalidMesh
Fragment contains invalid mesh data.
InvalidTransform
Fragment contains an invalid object transform.
InvalidMaterialReference
Fragment references a material index that is not present.
Definition at line 18 of file document_fragment_validator.hpp.
IoDiagnosticCode
enum class quader::io::IoDiagnosticCode strong
Machine-readable import/export diagnostic category.
Enumerator
Unknown
Unclassified diagnostic.
UnsupportedFormat
No importer or exporter supports the requested format.
FileNotFound
Source file was not found.
FileReadFailed
Source file could not be read.
FileWriteFailed
Destination file could not be written.
ParseFailed
Source data could not be parsed.
ValidationFailed
Imported or exported data failed validation.
MeshValidationFailed
Mesh validation failed.
DocumentValidationFailed
Document validation failed.
MaterialMappingFailed
Material mapping failed.
UnsupportedFeaturePreserved
Unsupported source feature was preserved as metadata.
ExportNotSupported
Requested export operation is unsupported.
Definition at line 34 of file io_diagnostic.hpp.
IoErrorCode
enum class quader::io::IoErrorCode strong
Expected failure categories for import/export services.
Enumerator
UnsupportedFormat
No registered importer/exporter supports the requested format.
FileAccessFailed
Filesystem access failed.
ParseFailed
Source data could not be parsed.
ValidationFailed
Imported or exported data failed validation.
ExportFailed
Export operation failed.
Definition at line 21 of file io_error.hpp.
IoSeverity
enum class quader::io::IoSeverity strong
Severity level for import/export diagnostics.
Enumerator
Info
Informational diagnostic with no failure implied.
Warning
Recoverable or noteworthy condition.
Error
Error condition that should block the current operation.
Definition at line 24 of file io_diagnostic.hpp.
Function Documentation
build_document_from_import()
quader::foundation::Result< quader::document::Document, IoError > quader::io::build_document_from_import (ImportedDocument imported) nodiscard
Build a Document from imported data.
Parameters
imported Imported payload to consume.
Returns
Document on success, or an I/O validation error.
Definition at line 130 of file document_fragment_validator.cpp.
References quader::io::IoDiagnosticList::add(), quader::io::IoDiagnosticList::append(), DocumentValidationFailed, Error, quader::foundation::Result< T, E >::failure(), quader::io::IoDiagnosticList::has_errors(), quader::io::DocumentFragment::mesh_objects, quader::io::ImportedDocument::root_fragment, quader::foundation::Result< T, E >::success(), validate_document_fragment(), and ValidationFailed.
descriptor_supports_extension()
bool quader::io::descriptor_supports_extension (const FileFormatDescriptor & descriptor, const std::filesystem::path & path) inline nodiscard
Check whether a descriptor supports a path extension.
Parameters
descriptor Descriptor to test.
path Path whose extension is matched.
Returns
True when any descriptor extension matches the path extension.
Definition at line 75 of file file_format.hpp.
References quader::io::FileFormatDescriptor::extensions, and path_extension_without_dot().
Referenced by quader::io::ImportExportRegistry::exporter_for_path(), and quader::io::ImportExportRegistry::importer_for_path().
make_io_error() [1/2]
IoError quader::io::make_io_error (IoErrorCode code, IoDiagnostic diagnostic) inline nodiscard
Create an I/O error from an existing diagnostic.
Parameters
code Error category.
diagnostic Primary diagnostic.
Returns
Error whose related list includes the primary diagnostic.
Definition at line 51 of file io_error.hpp.
References quader::io::IoDiagnosticList::add(), quader::io::IoError::code, quader::io::IoError::diagnostic, and quader::io::IoError::related.
Referenced by quader::io::ExportService::export_file(), and quader::io::ImportService::import_file().
make_io_error() [2/2]
IoError quader::io::make_io_error (IoErrorCode error_code, IoDiagnosticCode diagnostic_code, std::string message, std::filesystem::path source_path = {}, std::string subject = {}) inline nodiscard
Create an I/O error from diagnostic fields.
Parameters
error_code Error category.
diagnostic_code Diagnostic category.
message Diagnostic message.
source_path Optional path associated with the error.
subject Optional subject associated with the error.
Returns
Error whose related list includes the primary diagnostic.
Definition at line 69 of file io_error.hpp.
normalize_extension()
std::string quader::io::normalize_extension (std::string_view extension) inline nodiscard
Normalize a file extension for descriptor matching.
Parameters
extension Extension with or without a leading dot.
Returns
Lowercase extension without a leading dot.
Definition at line 45 of file file_format.hpp.
Referenced by path_extension_without_dot().
path_extension_without_dot()
std::string quader::io::path_extension_without_dot (const std::filesystem::path & path) inline nodiscard
Return a path extension in normalized descriptor form.
Parameters
path Path to inspect.
Returns
Lowercase extension without a leading dot.
Definition at line 64 of file file_format.hpp.
References normalize_extension().
Referenced by descriptor_supports_extension(), quader::io::ExportService::export_file(), and quader::io::ImportService::import_file().
to_foundation_diagnostic()
quader::foundation::Diagnostic quader::io::to_foundation_diagnostic (const IoDiagnostic & diagnostic) nodiscard
Convert an I/O diagnostic to a foundation diagnostic.
Parameters
diagnostic I/O diagnostic to convert.
Returns
Foundation diagnostic carrying severity and message.
Definition at line 83 of file io_diagnostic.cpp.
References quader::io::IoDiagnostic::message, quader::io::IoDiagnostic::severity, and to_foundation_severity().
Referenced by to_foundation_diagnostics().
to_foundation_diagnostics()
quader::foundation::DiagnosticList quader::io::to_foundation_diagnostics (const IoDiagnosticList & diagnostics) nodiscard
Convert an I/O diagnostic list to a foundation diagnostic list.
Parameters
diagnostics I/O diagnostics to copy.
Returns
Foundation diagnostic list.
Definition at line 90 of file io_diagnostic.cpp.
References quader::foundation::DiagnosticList::add(), and to_foundation_diagnostic().
to_foundation_severity()
quader::foundation::Severity quader::io::to_foundation_severity (IoSeverity severity) nodiscard noexcept
Convert an I/O severity to a foundation severity.
Parameters
severity I/O severity to convert.
Returns
Equivalent foundation severity.
Definition at line 70 of file io_diagnostic.cpp.
References quader::foundation::Error, Error, quader::foundation::Info, Info, quader::foundation::Warning, and Warning.
Referenced by to_foundation_diagnostic().
validate_document_fragment()
FragmentValidationResult quader::io::validate_document_fragment (const DocumentFragment & fragment) nodiscard
Validate imported fragment data before document insertion.
Parameters
fragment Fragment to inspect.
Returns
Validation diagnostics and success state.
Definition at line 86 of file document_fragment_validator.cpp.
References quader::io::FragmentValidationResult::diagnostics, Error, quader::document::is_finite(), quader::io::DocumentFragment::materials, quader::io::DocumentFragment::mesh_objects, MeshValidationFailed, quader::mesh::validate_mesh(), ValidationFailed, and Warning.
Referenced by build_document_from_import().