Quader: quader::math::detail Namespace Reference
quader::math::detail Namespace Reference
Classes
struct Components2
Two-component scalar payload used at the Quader/GLM boundary.
struct Components3
Three-component scalar payload used at the Quader/GLM boundary.
Functions
glm::vec2 to_glm (Components2 value) noexcept
glm::vec3 to_glm (Components3 value) noexcept
Components2 from_glm (glm::vec2 value) noexcept
Components3 from_glm (glm::vec3 value) noexcept
Components2 add (Components2 left, Components2 right) noexcept
Components3 add (Components3 left, Components3 right) noexcept
Components2 subtract (Components2 left, Components2 right) noexcept
Components3 subtract (Components3 left, Components3 right) noexcept
Components2 scale (Components2 value, float scalar) noexcept
Components3 scale (Components3 value, float scalar) noexcept
Components3 divide (Components3 value, float scalar) noexcept
float dot (Components2 left, Components2 right) noexcept
float dot (Components3 left, Components3 right) noexcept
Components3 cross (Components3 left, Components3 right) noexcept
float length_squared (Components2 value) noexcept
float length_squared (Components3 value) noexcept
float length (Components3 value) noexcept
Components3 normalized (Components3 value) noexcept
Components3 component_min (Components3 left, Components3 right) noexcept
Components3 component_max (Components3 left, Components3 right) noexcept
Function Documentation
add() [1/2]
Components2 quader::math::detail::add (Components2 left, Components2 right) inline nodiscard noexcept
Add two component vectors.
Parameters
left First addend.
right Second addend.
Returns
Component-wise sum.
Definition at line 86 of file glm_adapter.hpp.
References from_glm(), and to_glm().
Referenced by quader::math::operator+(), and quader::math::operator+().
add() [2/2]
Components3 quader::math::detail::add (Components3 left, Components3 right) inline nodiscard noexcept
Add two component vectors.
Parameters
left First addend.
right Second addend.
Returns
Component-wise sum.
Definition at line 97 of file glm_adapter.hpp.
References from_glm(), and to_glm().
component_max()
Components3 quader::math::detail::component_max (Components3 left, Components3 right) inline nodiscard noexcept
Compute component-wise maxima.
Parameters
left First vector.
right Second vector.
Returns
Component-wise maximum.
Definition at line 247 of file glm_adapter.hpp.
References from_glm(), and to_glm().
Referenced by quader::math::expand().
component_min()
Components3 quader::math::detail::component_min (Components3 left, Components3 right) inline nodiscard noexcept
Compute component-wise minima.
Parameters
left First vector.
right Second vector.
Returns
Component-wise minimum.
Definition at line 236 of file glm_adapter.hpp.
References from_glm(), and to_glm().
Referenced by quader::math::expand().
cross()
Components3 quader::math::detail::cross (Components3 left, Components3 right) inline nodiscard noexcept
Compute the cross product of two three-component vectors.
Parameters
left First vector.
right Second vector.
Returns
Cross product.
Definition at line 185 of file glm_adapter.hpp.
References from_glm(), and to_glm().
Referenced by quader::math::cross().
divide()
Components3 quader::math::detail::divide (Components3 value, float scalar) inline nodiscard noexcept
Divide a component vector by a scalar.
Parameters
value Vector to divide.
scalar Divisor.
Returns
Divided vector.
Definition at line 152 of file glm_adapter.hpp.
References from_glm(), and to_glm().
Referenced by quader::math::operator/().
dot() [1/2]
float quader::math::detail::dot (Components2 left, Components2 right) inline nodiscard noexcept
Compute the dot product of two component vectors.
Parameters
left First vector.
right Second vector.
Returns
Dot product.
Definition at line 163 of file glm_adapter.hpp.
References to_glm().
Referenced by quader::math::dot(), quader::math::dot(), length_squared(), and length_squared().
dot() [2/2]
float quader::math::detail::dot (Components3 left, Components3 right) inline nodiscard noexcept
Compute the dot product of two component vectors.
Parameters
left First vector.
right Second vector.
Returns
Dot product.
Definition at line 174 of file glm_adapter.hpp.
References to_glm().
from_glm() [1/2]
Components2 quader::math::detail::from_glm (glm::vec2 value) inline nodiscard noexcept
Convert a GLM two-vector to scalar components.
Parameters
value GLM vector to convert.
Returns
Components with matching coordinates.
Definition at line 65 of file glm_adapter.hpp.
Referenced by add(), add(), component_max(), component_min(), cross(), divide(), normalized(), scale(), scale(), subtract(), and subtract().
from_glm() [2/2]
Components3 quader::math::detail::from_glm (glm::vec3 value) inline nodiscard noexcept
Convert a GLM three-vector to scalar components.
Parameters
value GLM vector to convert.
Returns
Components with matching coordinates.
Definition at line 75 of file glm_adapter.hpp.
length()
float quader::math::detail::length (Components3 value) inline nodiscard noexcept
Compute vector length.
Parameters
value Vector to measure.
Returns
Euclidean length.
Definition at line 215 of file glm_adapter.hpp.
References to_glm().
Referenced by quader::math::length().
length_squared() [1/2]
float quader::math::detail::length_squared (Components2 value) inline nodiscard noexcept
Compute squared vector length.
Parameters
value Vector to measure.
Returns
Squared Euclidean length.
Definition at line 195 of file glm_adapter.hpp.
References dot().
Referenced by quader::math::length_squared(), and quader::math::length_squared().
length_squared() [2/2]
float quader::math::detail::length_squared (Components3 value) inline nodiscard noexcept
Compute squared vector length.
Parameters
value Vector to measure.
Returns
Squared Euclidean length.
Definition at line 205 of file glm_adapter.hpp.
References dot().
normalized()
Components3 quader::math::detail::normalized (Components3 value) inline nodiscard noexcept
Normalize a vector using GLM's normalization semantics.
Parameters
value Vector to normalize.
Returns
Normalized vector.
Definition at line 225 of file glm_adapter.hpp.
References from_glm(), and to_glm().
Referenced by quader::math::normalized().
scale() [1/2]
Components2 quader::math::detail::scale (Components2 value, float scalar) inline nodiscard noexcept
Multiply a component vector by a scalar.
Parameters
value Vector to scale.
scalar Scale factor.
Returns
Scaled vector.
Definition at line 130 of file glm_adapter.hpp.
References from_glm(), and to_glm().
Referenced by quader::math::operator*(), and quader::math::operator*().
scale() [2/2]
Components3 quader::math::detail::scale (Components3 value, float scalar) inline nodiscard noexcept
Multiply a component vector by a scalar.
Parameters
value Vector to scale.
scalar Scale factor.
Returns
Scaled vector.
Definition at line 141 of file glm_adapter.hpp.
References from_glm(), and to_glm().
subtract() [1/2]
Components2 quader::math::detail::subtract (Components2 left, Components2 right) inline nodiscard noexcept
Subtract one component vector from another.
Parameters
left Minuend.
right Subtrahend.
Returns
Component-wise difference.
Definition at line 108 of file glm_adapter.hpp.
References from_glm(), and to_glm().
Referenced by quader::math::operator-(), and quader::math::operator-().
subtract() [2/2]
Components3 quader::math::detail::subtract (Components3 left, Components3 right) inline nodiscard noexcept
Subtract one component vector from another.
Parameters
left Minuend.
right Subtrahend.
Returns
Component-wise difference.
Definition at line 119 of file glm_adapter.hpp.
References from_glm(), and to_glm().
to_glm() [1/2]
glm::vec2 quader::math::detail::to_glm (Components2 value) inline nodiscard noexcept
Convert two scalar components to a GLM vector.
Parameters
value Components to convert.
Returns
GLM vector with matching coordinates.
Definition at line 45 of file glm_adapter.hpp.
Referenced by add(), add(), component_max(), component_min(), cross(), divide(), dot(), dot(), length(), normalized(), scale(), scale(), subtract(), and subtract().
to_glm() [2/2]
glm::vec3 quader::math::detail::to_glm (Components3 value) inline nodiscard noexcept
Convert three scalar components to a GLM vector.
Parameters
value Components to convert.
Returns
GLM vector with matching coordinates.
Definition at line 55 of file glm_adapter.hpp.