Quader: quader::tests::document_fixtures Namespace Reference
quader::tests::document_fixtures Namespace Reference
Classes
struct TriangleMeshFixture
Mesh fixture containing one triangular face and representative component ids.
struct DocumentMeshFixture
Document fixture containing one mesh object built from a triangle.
struct SemanticMeshObjectState
Semantic snapshot of a mesh object used for document command comparisons.
struct DocumentSemanticState
Semantic snapshot of document state used to compare undo/redo effects.
Functions
TriangleMeshFixture make_triangle_mesh ()
Build a simple triangle mesh fixture with stable ids for tests.
DocumentMeshFixture make_document_with_triangle_object ()
Build a document containing one triangle mesh object.
DocumentSemanticState capture_document_state (const quader::document::Document &document)
Capture the document state used by command and document tests.
Function Documentation
capture_document_state()
DocumentSemanticState quader::tests::document_fixtures::capture_document_state (const quader::document::Document & document) inline
Capture the document state used by command and document tests.
Definition at line 130 of file document_test_helpers.hpp.
References quader::tests::document_fixtures::DocumentSemanticState::dirty, quader::tests::document_fixtures::DocumentSemanticState::dirty_flags, quader::tests::document_fixtures::DocumentSemanticState::objects, QUADER_ASSERT, quader::tests::document_fixtures::DocumentSemanticState::selected_components, and quader::tests::document_fixtures::DocumentSemanticState::selected_objects.
make_document_with_triangle_object()
DocumentMeshFixture quader::tests::document_fixtures::make_document_with_triangle_object () inline
Build a document containing one triangle mesh object.
Definition at line 113 of file document_test_helpers.hpp.
References make_triangle_mesh(), and QUADER_ASSERT.
make_triangle_mesh()
TriangleMeshFixture quader::tests::document_fixtures::make_triangle_mesh () inline
Build a simple triangle mesh fixture with stable ids for tests.
Definition at line 89 of file document_test_helpers.hpp.
References quader::mesh::face_edges(), and QUADER_ASSERT.
Referenced by make_document_with_triangle_object().