Quader: quader::render_tests Namespace Reference
quader::render_tests Namespace Reference
Classes
struct GoldenImage
In-memory RGBA8 sRGB image used by golden-image tests.
class GoldenImageComparator
Compares two in-memory golden images with a tolerance.
struct GoldenImageDiff
Difference report returned by golden-image comparison.
struct GoldenTolerance
Pixel-difference tolerance for golden-image comparison.
struct RenderTestScene
Metadata for a planned render-test scene.
Functions
std::size_t expected_rgba8_byte_count (const GoldenImage &image) noexcept
bool has_expected_rgba8_byte_count (const GoldenImage &image) noexcept
std::vector< RenderTestScene > planned_v1_golden_scenes ()
Function Documentation
expected_rgba8_byte_count()
std::size_t quader::render_tests::expected_rgba8_byte_count (const GoldenImage & image) nodiscard noexcept
Compute expected RGBA8 byte count for an image.
Parameters
image Image whose dimensions are inspected.
Returns
width * height * 4.
Definition at line 25 of file golden_image.cpp.
Referenced by has_expected_rgba8_byte_count().
has_expected_rgba8_byte_count()
bool quader::render_tests::has_expected_rgba8_byte_count (const GoldenImage & image) nodiscard noexcept
Check whether an image's pixel buffer matches its dimensions.
Parameters
image Image to validate.
Returns
True when rgba8_srgb.size() equals the expected byte count.
Definition at line 39 of file golden_image.cpp.
References expected_rgba8_byte_count().
Referenced by quader::render_tests::GoldenImageComparator::compare().
planned_v1_golden_scenes()
std::vector< RenderTestScene > quader::render_tests::planned_v1_golden_scenes () nodiscard
Return the planned V1 golden-image scene metadata.
Returns
Scene descriptors used by render-test scaffolding.
Definition at line 14 of file render_test_scene.cpp.