Quader: quader::benchmarks Namespace Reference
quader::benchmarks Namespace Reference
Classes
struct BenchmarkRunConfig
Runtime configuration shared by benchmark executables.
struct BenchmarkResult
Result row emitted by benchmark helpers.
Typedefs
using BenchmarkBody = std::function<std::vector<crimson::RendererCounter>()>
Callable benchmark body that returns renderer counters for one iteration.
Functions
BenchmarkRunConfig parse_benchmark_config (int argc, char **argv)
BenchmarkResult run_benchmark (std::string name, const BenchmarkRunConfig &config, const BenchmarkBody &body)
void print_jsonl (const BenchmarkResult &result)
BenchmarkResult run_crimson_packet_pipeline_benchmark (const BenchmarkRunConfig &config)
BenchmarkResult run_crimson_upload_benchmark (const BenchmarkRunConfig &config)
Typedef Documentation
BenchmarkBody
using quader::benchmarks::BenchmarkBody = std::function<std::vector<crimson::RendererCounter>()>
Callable benchmark body that returns renderer counters for one iteration.
Definition at line 48 of file benchmark_main.hpp.
Function Documentation
parse_benchmark_config()
BenchmarkRunConfig quader::benchmarks::parse_benchmark_config (int argc, char ** argv) nodiscard
Parse benchmark command-line options.
Parameters
argc Argument count from main.
argv Argument vector from main.
Returns
Benchmark configuration with invalid numeric values clamped to defaults.
Definition at line 56 of file benchmark_main.cpp.
References quader::benchmarks::BenchmarkRunConfig::fixture_size, quader::benchmarks::BenchmarkRunConfig::measured_iterations, and quader::benchmarks::BenchmarkRunConfig::warmup_iterations.
Referenced by main().
print_jsonl()
void quader::benchmarks::print_jsonl (const BenchmarkResult & result)
Print a benchmark result as one JSONL record.
Parameters
result Result to print.
Definition at line 93 of file benchmark_main.cpp.
References quader::benchmarks::BenchmarkResult::counters, crimson::RendererCounter::domain, quader::benchmarks::BenchmarkResult::iterations, quader::benchmarks::BenchmarkResult::max_us, quader::benchmarks::BenchmarkResult::median_us, quader::benchmarks::BenchmarkResult::min_us, crimson::RendererCounter::name, quader::benchmarks::BenchmarkResult::name, crimson::renderer_counter_domain_name(), and crimson::RendererCounter::value.
Referenced by main().
run_benchmark()
BenchmarkResult quader::benchmarks::run_benchmark (std::string name, const BenchmarkRunConfig & config, const BenchmarkBody & body) nodiscard
Run a benchmark body with warmup and measured iterations.
Parameters
name Benchmark name.
config Benchmark run configuration.
body Callable measured by the benchmark harness.
Returns
Timing result and counters from the final measured iteration.
Definition at line 66 of file benchmark_main.cpp.
References quader::benchmarks::BenchmarkRunConfig::measured_iterations, and quader::benchmarks::BenchmarkRunConfig::warmup_iterations.
Referenced by run_crimson_packet_pipeline_benchmark(), and run_crimson_upload_benchmark().
run_crimson_packet_pipeline_benchmark()
BenchmarkResult quader::benchmarks::run_crimson_packet_pipeline_benchmark (const BenchmarkRunConfig & config) nodiscard
Run the Crimson draw-packet pipeline benchmark.
Parameters
config Benchmark run configuration.
Returns
Benchmark timing result.
Definition at line 57 of file crimson_packet_pipeline_bench.cpp.
References crimson::DrawPacketBuildResult::alpha_cutout, crimson::build_draw_packets(), crimson::build_instance_batches(), crimson::MaterialSystem::create_default_material(), crimson::DrawPacketBuildResult::culling, crimson::DrawPacketBuildResult::draw_packet_count(), quader::benchmarks::BenchmarkRunConfig::fixture_size, crimson::make_frame_stats(), crimson::make_instancing_stats(), crimson::make_renderer_counters(), crimson::DrawPacketBuildResult::opaque, crimson::OpaquePbr, crimson::DrawPacketBuildResult::packets, crimson::MaterialSystem::registry(), run_benchmark(), crimson::DrawPacketBuildResult::transparent, and crimson::TransparentPbr.
Referenced by main().
run_crimson_upload_benchmark()
BenchmarkResult quader::benchmarks::run_crimson_upload_benchmark (const BenchmarkRunConfig & config) nodiscard
Run the Crimson render-mesh upload benchmark.
Parameters
config Benchmark run configuration.
Returns
Benchmark timing result.
Definition at line 67 of file crimson_upload_bench.cpp.
References quader::benchmarks::BenchmarkRunConfig::fixture_size, crimson::make_frame_stats(), crimson::make_renderer_counters(), crimson::FrameUploadStats::mesh_create_count, crimson::RenderMeshUploadTracker::process_uploads(), run_benchmark(), crimson::FrameUploadStats::skipped_clean_resource_count, crimson::FrameUploadStats::uploaded_index_bytes, and crimson::FrameUploadStats::uploaded_vertex_bytes.
Referenced by main().