Quader: crimson::gpu Namespace Reference
crimson::gpu Namespace Reference
Classes
struct FrameBufferHandleTraits
Destruction traits for bgfx::FrameBufferHandle.
struct FullscreenTriangleUvRange
UV range used by the fullscreen triangle shader.
struct GpuCapabilityInput
Capability flags reported by the graphics runtime.
struct GpuCapabilityValidation
Result of validating runtime capabilities against Crimson V1 requirements.
class GpuDevice
Owns the selected graphics backend and per-frame GPU execution path.
class GpuFrameResources
Owns GPU frame targets synchronized from the render graph.
struct GpuFrameTargetRecord
Runtime GPU resource record for one render graph target.
class GpuMaterialCache
Owns default GPU material resources and binds PBR material constants.
class GpuMeshCache
Owns GPU mesh resources used by the runtime renderer path.
struct GpuMeshResource
GPU vertex/index buffer resource.
class GpuOverlayRenderer
Owns GPU state needed to submit unlit overlay grid and line primitives.
struct GpuPbrMaterialBlock
Packed material constants uploaded or bound for PBR shaders.
class GpuPicking
Owns GPU picking target submission and delayed readback resolution.
struct GpuPickingFrameResult
Picking results and readback counts completed during one GPU frame submission.
class GpuProgramCache
Loads and owns GPU shader programs keyed by Crimson program ids.
struct GpuProgramResource
GPU shader program resource.
class GpuResourceTable
struct GpuShaderResource
GPU shader binary resource.
struct IndexBufferHandleTraits
Destruction traits for bgfx::IndexBufferHandle.
struct ProgramHandleTraits
Destruction traits for bgfx::ProgramHandle.
struct ShaderBinaryRef
Reference to one compiled shader binary.
struct ShaderHandleTraits
Destruction traits for bgfx::ShaderHandle.
class ShaderLibrary
Resolves compiled shader binary paths from a shader root.
struct TextureHandleTraits
Destruction traits for bgfx::TextureHandle.
struct UniformHandleTraits
Destruction traits for bgfx::UniformHandle.
class UniqueGpuHandle
struct Vec3
Three-component single-precision vector.
struct VertexBufferHandleTraits
Destruction traits for bgfx::VertexBufferHandle.
Typedefs
using UniqueVertexBufferHandle = UniqueGpuHandle<bgfx::VertexBufferHandle, VertexBufferHandleTraits>
Unique RAII wrapper for a bgfx vertex buffer.
using UniqueIndexBufferHandle = UniqueGpuHandle<bgfx::IndexBufferHandle, IndexBufferHandleTraits>
Unique RAII wrapper for a bgfx index buffer.
using UniqueProgramHandle = UniqueGpuHandle<bgfx::ProgramHandle, ProgramHandleTraits>
Unique RAII wrapper for a bgfx program.
using UniqueShaderHandle = UniqueGpuHandle<bgfx::ShaderHandle, ShaderHandleTraits>
Unique RAII wrapper for a bgfx shader.
using UniqueTextureHandle = UniqueGpuHandle<bgfx::TextureHandle, TextureHandleTraits>
Unique RAII wrapper for a bgfx texture.
using UniqueUniformHandle = UniqueGpuHandle<bgfx::UniformHandle, UniformHandleTraits>
Unique RAII wrapper for a bgfx uniform.
using UniqueFrameBufferHandle = UniqueGpuHandle<bgfx::FrameBufferHandle, FrameBufferHandleTraits>
Unique RAII wrapper for a bgfx framebuffer.
using PbrDrawPacket = DrawPacket
Draw packet type consumed by the GPU PBR pass.
using PbrPassPackets = DrawPacketBuildResult
Queue-separated packet result consumed by the GPU PBR pass.
using GpuMeshTable = GpuResourceTable<GpuMeshResource, RenderMeshHandle>
Resource table for GPU mesh resources keyed by public mesh handles.
using GpuProgramTable = GpuResourceTable<GpuProgramResource, RenderProgramHandle>
Resource table for GPU program resources keyed by public program handles.
Enumerations
enum class GraphicsBackend { Vulkan , Metal , Direct3D12 , Direct3D11 }
Concrete graphics backend selected by the GPU layer.
enum class ScreenOrigin { TopLeft , BottomLeft }
Screen-space origin convention reported by the graphics runtime.
enum class ShaderTarget { Vulkan , Direct3D11 , Direct3D12 , Metal }
Compiled shader target platform.
enum class ShaderStage { Vertex , Fragment }
Shader stage in a compiled program pair.
Functions
std::optional< GraphicsBackend > choose_backend (NativeSurfacePlatform platform, GraphicsBackendPreference preference, std::span< const GraphicsBackend > supported_backends) noexcept
RendererDiagnostic make_backend_unsupported_diagnostic (NativeSurfacePlatform platform, GraphicsBackendPreference preference)
GpuCapabilityValidation validate_v1_capabilities (const GpuCapabilityInput &input, const DisplayConversionSettings &display_conversion)
constexpr std::string_view graphics_backend_name (GraphicsBackend backend) noexcept
GpuPbrMaterialBlock pack_pbr_material_block (const MaterialInstance &material, const BaseShaderDefinition &definition) noexcept
PbrPassPackets prepare_pbr_pass_packets (std::span< const RenderObject > objects, const BaseShaderRegistry &registry, const MaterialSystem &materials, const RenderCamera &camera, RenderMeshHandle unit_box_mesh, RenderMaterialHandle fallback_material, float view_aspect_ratio)
void destroy_gpu_mesh_resource (GpuMeshResource &resource) noexcept
void destroy_gpu_program_resource (GpuProgramResource &resource) noexcept
void destroy_gpu_shader_resource (GpuShaderResource &resource) noexcept
constexpr ScreenOrigin screen_origin_from_bgfx (bool origin_bottom_left) noexcept
constexpr FullscreenTriangleUvRange fullscreen_triangle_uv_range (ScreenOrigin origin) noexcept
bgfx::ShaderHandle load_shader (const ShaderLibrary &library, ShaderProgramId program, ShaderStage stage, ShaderTarget target, std::vector< RendererDiagnostic > &diagnostics)
std::string_view shader_target_name (ShaderTarget target) noexcept
std::string_view shader_target_directory_name (ShaderTarget target) noexcept
std::string_view shader_stage_name (ShaderStage stage) noexcept
std::string_view shader_file_name (ShaderProgramId program, ShaderStage stage) noexcept
Typedef Documentation
GpuMeshTable
using crimson::gpu::GpuMeshTable = GpuResourceTable<GpuMeshResource, RenderMeshHandle>
Resource table for GPU mesh resources keyed by public mesh handles.
Definition at line 37 of file gpu_runtime_resources.hpp.
GpuProgramTable
using crimson::gpu::GpuProgramTable = GpuResourceTable<GpuProgramResource, RenderProgramHandle>
Resource table for GPU program resources keyed by public program handles.
Definition at line 39 of file gpu_runtime_resources.hpp.
PbrDrawPacket
using crimson::gpu::PbrDrawPacket = DrawPacket
Draw packet type consumed by the GPU PBR pass.
Definition at line 20 of file gpu_pbr_pass.hpp.
PbrPassPackets
using crimson::gpu::PbrPassPackets = DrawPacketBuildResult
Queue-separated packet result consumed by the GPU PBR pass.
Definition at line 22 of file gpu_pbr_pass.hpp.
UniqueFrameBufferHandle
using crimson::gpu::UniqueFrameBufferHandle = UniqueGpuHandle<bgfx::FrameBufferHandle, FrameBufferHandleTraits>
Unique RAII wrapper for a bgfx framebuffer.
Definition at line 220 of file gpu_handles.hpp.
UniqueIndexBufferHandle
using crimson::gpu::UniqueIndexBufferHandle = UniqueGpuHandle<bgfx::IndexBufferHandle, IndexBufferHandleTraits>
Unique RAII wrapper for a bgfx index buffer.
Definition at line 210 of file gpu_handles.hpp.
UniqueProgramHandle
using crimson::gpu::UniqueProgramHandle = UniqueGpuHandle<bgfx::ProgramHandle, ProgramHandleTraits>
Unique RAII wrapper for a bgfx program.
Definition at line 212 of file gpu_handles.hpp.
UniqueShaderHandle
using crimson::gpu::UniqueShaderHandle = UniqueGpuHandle<bgfx::ShaderHandle, ShaderHandleTraits>
Unique RAII wrapper for a bgfx shader.
Definition at line 214 of file gpu_handles.hpp.
UniqueTextureHandle
using crimson::gpu::UniqueTextureHandle = UniqueGpuHandle<bgfx::TextureHandle, TextureHandleTraits>
Unique RAII wrapper for a bgfx texture.
Definition at line 216 of file gpu_handles.hpp.
UniqueUniformHandle
using crimson::gpu::UniqueUniformHandle = UniqueGpuHandle<bgfx::UniformHandle, UniformHandleTraits>
Unique RAII wrapper for a bgfx uniform.
Definition at line 218 of file gpu_handles.hpp.
UniqueVertexBufferHandle
using crimson::gpu::UniqueVertexBufferHandle = UniqueGpuHandle<bgfx::VertexBufferHandle, VertexBufferHandleTraits>
Unique RAII wrapper for a bgfx vertex buffer.
Definition at line 208 of file gpu_handles.hpp.
Enumeration Type Documentation
GraphicsBackend
enum class crimson::gpu::GraphicsBackend strong
Concrete graphics backend selected by the GPU layer.
Enumerator
Vulkan
Vulkan backend.
Metal
Metal backend.
Direct3D12
Direct3D 12 backend.
Direct3D11
Direct3D 11 backend.
Definition at line 24 of file gpu_capabilities.hpp.
ScreenOrigin
enum class crimson::gpu::ScreenOrigin strong
Screen-space origin convention reported by the graphics runtime.
Enumerator
TopLeft
Texture coordinate origin is the top-left corner.
BottomLeft
Texture coordinate origin is the bottom-left corner.
Definition at line 15 of file gpu_view_policy.hpp.
ShaderStage
enum class crimson::gpu::ShaderStage strong
Shader stage in a compiled program pair.
Enumerator
Vertex
Vertex shader stage.
Fragment
Fragment shader stage.
Definition at line 33 of file shader_library.hpp.
ShaderTarget
enum class crimson::gpu::ShaderTarget strong
Compiled shader target platform.
Enumerator
Vulkan
Vulkan shader target.
Direct3D11
Direct3D 11 shader target.
Direct3D12
Direct3D 12 shader target.
Metal
Metal shader target.
Definition at line 21 of file shader_library.hpp.
Function Documentation
choose_backend()
std::optional< GraphicsBackend > crimson::gpu::choose_backend (NativeSurfacePlatform platform, GraphicsBackendPreference preference, std::span< const GraphicsBackend > supported_backends) noexcept
Choose a backend for a platform and preference.
Parameters
platform Native surface platform.
preference User/backend preference.
supported_backends Backends reported as available.
Returns
Selected backend, or empty when none satisfy the request.
Definition at line 121 of file gpu_capabilities.cpp.
Referenced by crimson::gpu::GpuDevice::initialize().
destroy_gpu_mesh_resource()
void crimson::gpu::destroy_gpu_mesh_resource (GpuMeshResource & resource) noexcept
Destroy handles owned by a mesh resource.
Parameters
resource Mesh resource whose owned handles are destroyed.
Definition at line 52 of file gpu_resources.cpp.
destroy_gpu_program_resource()
void crimson::gpu::destroy_gpu_program_resource (GpuProgramResource & resource) noexcept
Destroy handles owned by a program resource.
Parameters
resource Program resource whose owned handle is destroyed.
Definition at line 56 of file gpu_resources.cpp.
destroy_gpu_shader_resource()
void crimson::gpu::destroy_gpu_shader_resource (GpuShaderResource & resource) noexcept
Destroy handles owned by a shader resource.
Parameters
resource Shader resource whose owned handle is destroyed.
Definition at line 60 of file gpu_resources.cpp.
fullscreen_triangle_uv_range()
FullscreenTriangleUvRange crimson::gpu::fullscreen_triangle_uv_range (ScreenOrigin origin) nodiscard constexpr noexcept
Return fullscreen-triangle UVs for a screen-origin convention.
Parameters
origin Screen origin convention.
Returns
UV range for the fullscreen triangle.
Definition at line 50 of file gpu_view_policy.hpp.
References BottomLeft.
graphics_backend_name()
std::string_view crimson::gpu::graphics_backend_name (GraphicsBackend backend) constexpr noexcept
Return the stable graphics-backend name.
Parameters
backend Backend to name.
Returns
Static backend name.
Definition at line 41 of file gpu_capabilities.hpp.
References Direct3D11, Direct3D12, Metal, and Vulkan.
Referenced by crimson::gpu::GpuDevice::initialize().
load_shader()
bgfx::ShaderHandle crimson::gpu::load_shader (const ShaderLibrary & library, ShaderProgramId program, ShaderStage stage, ShaderTarget target, std::vector< RendererDiagnostic > & diagnostics) nodiscard
Load one compiled shader binary into bgfx.
Parameters
library Shader path resolver.
program Shader program identifier.
stage Shader stage.
target Compiled target platform.
[out] diagnostics Diagnostics appended for load failures.
Returns
bgfx shader handle, or an invalid handle on failure.
Definition at line 65 of file shader_library.cpp.
References crimson::Error, crimson::gpu::ShaderLibrary::shader_binary(), crimson::gpu::ShaderLibrary::shader_root(), shader_target_directory_name(), crimson::ShaderFileMissing, crimson::ShaderManifestInvalid, crimson::ShaderProgramCreationFailed, and crimson::ShaderTargetMissing.
Referenced by crimson::gpu::GpuProgramCache::load_program().
make_backend_unsupported_diagnostic()
RendererDiagnostic crimson::gpu::make_backend_unsupported_diagnostic (NativeSurfacePlatform platform, GraphicsBackendPreference preference)
Build a diagnostic for an unsupported backend request.
Parameters
platform Native surface platform.
preference Requested preference.
Returns
Renderer diagnostic describing the unsupported backend.
Definition at line 140 of file gpu_capabilities.cpp.
References crimson::BackendUnsupported, crimson::Fatal, crimson::graphics_backend_preference_name(), and crimson::native_surface_platform_name().
Referenced by crimson::gpu::GpuDevice::initialize().
pack_pbr_material_block()
GpuPbrMaterialBlock crimson::gpu::pack_pbr_material_block (const MaterialInstance & material, const BaseShaderDefinition & definition) nodiscard noexcept
Pack a material instance into the GPU PBR constant layout.
Parameters
material Material instance to pack.
definition Base shader definition used to interpret parameters.
Returns
Packed PBR material block.
Definition at line 123 of file gpu_material_cache.cpp.
References crimson::MaterialColorSrgb::a, crimson::AlphaCutoutPbr, crimson::gpu::GpuPbrMaterialBlock::base_color_factor_linear, crimson::gpu::GpuPbrMaterialBlock::emissive_factor_linear, crimson::gpu::GpuPbrMaterialBlock::factors, crimson::gpu::GpuPbrMaterialBlock::flags, crimson::TransparentPbr, crimson::gpu::GpuPbrMaterialBlock::uv_transform_0, crimson::MaterialVec2::x, and crimson::MaterialVec2::y.
Referenced by crimson::gpu::GpuMaterialCache::material_block().
prepare_pbr_pass_packets()
PbrPassPackets crimson::gpu::prepare_pbr_pass_packets (std::span< const RenderObject > objects, const BaseShaderRegistry & registry, const MaterialSystem & materials, const RenderCamera & camera, RenderMeshHandle unit_box_mesh, RenderMaterialHandle fallback_material, float view_aspect_ratio = 1.0F) nodiscard
Prepare PBR draw packets for GPU submission.
Parameters
objects Render objects to inspect.
registry Base shader registry used for shader schema lookup.
materials Material system used for material lookup.
camera Camera used for culling and distance sorting.
unit_box_mesh Built-in unit box mesh for explicitly marked objects.
fallback_material Material handle substituted when an object has no material.
view_aspect_ratio View aspect ratio used for frustum culling.
Returns
Queue-separated PBR packets and counters.
Definition at line 14 of file gpu_pbr_pass.cpp.
References crimson::build_draw_packets().
Referenced by crimson::gpu::GpuDevice::render_frame().
screen_origin_from_bgfx()
ScreenOrigin crimson::gpu::screen_origin_from_bgfx (bool origin_bottom_left) nodiscard constexpr noexcept
Convert bgfx origin policy into Crimson screen origin.
Parameters
origin_bottom_left bgfx origin flag.
Returns
Matching screen origin.
Definition at line 40 of file gpu_view_policy.hpp.
References BottomLeft, and TopLeft.
shader_file_name()
std::string_view crimson::gpu::shader_file_name (ShaderProgramId program, ShaderStage stage) noexcept
Return the compiled shader file name.
Parameters
program Program id.
stage Shader stage.
Returns
Static shader file name.
Definition at line 186 of file shader_library.cpp.
References crimson::AlphaCutoutPbr, crimson::OpaquePbr, crimson::OverlayLine, crimson::OverlayUnlit, crimson::Picking, crimson::Present, crimson::PrototypeGridOverlay, crimson::PrototypeLitCube, crimson::ToneMap, crimson::TransparentPbr, and Vertex.
Referenced by crimson::gpu::ShaderLibrary::shader_binary(), and crimson::gpu::ShaderLibrary::shader_path().
shader_stage_name()
std::string_view crimson::gpu::shader_stage_name (ShaderStage stage) noexcept
Return the stable shader stage name.
Parameters
stage Shader stage to name.
Returns
Static stage name.
Definition at line 175 of file shader_library.cpp.
References Fragment, and Vertex.
shader_target_directory_name()
std::string_view crimson::gpu::shader_target_directory_name (ShaderTarget target) noexcept
Return the stable shader target directory name.
Parameters
target Shader target to name as a directory.
Returns
Static directory name.
Definition at line 160 of file shader_library.cpp.
References Direct3D11, Direct3D12, Metal, and Vulkan.
Referenced by load_shader(), crimson::gpu::ShaderLibrary::shader_binary(), and crimson::gpu::ShaderLibrary::shader_path().
shader_target_name()
std::string_view crimson::gpu::shader_target_name (ShaderTarget target) noexcept
Return the stable shader target name.
Parameters
target Shader target to name.
Returns
Static target name.
Definition at line 145 of file shader_library.cpp.
References Direct3D11, Direct3D12, Metal, and Vulkan.
validate_v1_capabilities()
GpuCapabilityValidation crimson::gpu::validate_v1_capabilities (const GpuCapabilityInput & input, const DisplayConversionSettings & display_conversion)
Validate required V1 GPU capabilities.
Parameters
input Runtime capability flags.
display_conversion Display conversion policy.
Returns
Capability status rows and missing-capability diagnostics.
Definition at line 153 of file gpu_capabilities.cpp.
References crimson::DisplayConversionSettings::allow_manual_final_srgb, crimson::gpu::GpuCapabilityInput::depth_texture, crimson::DepthTexture, crimson::gpu::GpuCapabilityValidation::diagnostics, crimson::gpu::GpuCapabilityInput::floating_point_render_target, crimson::FloatingPointRenderTarget, crimson::Instancing, crimson::gpu::GpuCapabilityInput::instancing, crimson::gpu::GpuCapabilityInput::integer_picking_target, crimson::IntegerPickingTarget, crimson::gpu::GpuCapabilityInput::manual_srgb_final_conversion, crimson::ManualSrgbFinalConversion, crimson::DisplayConversionSettings::prefer_srgb_backbuffer, crimson::Readback, crimson::gpu::GpuCapabilityInput::readback, crimson::gpu::GpuCapabilityInput::render_to_texture, crimson::RenderToTexture, crimson::gpu::GpuCapabilityInput::rgba8_picking_target, crimson::Rgba8PickingTarget, crimson::gpu::GpuCapabilityInput::srgb_backbuffer, crimson::gpu::GpuCapabilityInput::srgb_texture_sampling, crimson::SrgbBackbuffer, crimson::SrgbTextureSampling, crimson::gpu::GpuCapabilityValidation::statuses, crimson::Texture2D, crimson::gpu::GpuCapabilityInput::texture_2d, crimson::gpu::GpuCapabilityInput::texture_cube, and crimson::TextureCube.
Referenced by crimson::gpu::GpuDevice::initialize().