Quader: quader::io::gltf Namespace Reference
quader::io::gltf Namespace Reference
Classes
struct GltfMaterialMapping
Result payload for mapping one glTF material to Crimson.
struct GltfMaterialSource
Project-owned glTF material DTO used before Crimson mapping.
struct GltfPbrMetallicRoughness
glTF metallic/roughness material fields.
struct GltfTextureRef
Reference to a texture in a glTF source material.
struct TextureSlotMapping
Mapping from a glTF texture reference to a Crimson material texture slot.
Enumerations
enum class GltfAlphaMode { Opaque , Mask , Blend }
glTF alpha mode values used for material base-shader selection.
Functions
quader::foundation::Result< GltfMaterialMapping, IoError > map_gltf_material_to_crimson (const GltfMaterialSource &source, const crimson::BaseShaderRegistry &registry)
Enumeration Type Documentation
GltfAlphaMode
enum class quader::io::gltf::GltfAlphaMode strong
glTF alpha mode values used for material base-shader selection.
Enumerator
Opaque
Fully opaque material.
Mask
Alpha-tested material using alpha_cutoff.
Blend
Alpha-blended transparent material.
Definition at line 22 of file gltf_material_source.hpp.
Function Documentation
map_gltf_material_to_crimson()
quader::foundation::Result< GltfMaterialMapping, IoError > quader::io::gltf::map_gltf_material_to_crimson (const GltfMaterialSource & source, const crimson::BaseShaderRegistry & registry) nodiscard
Map a glTF material source into a Crimson material instance.
Parameters
source Source glTF material fields.
registry Base shader registry used to choose material schema.
Returns
Mapped material payload, or an I/O material-mapping error.
Definition at line 171 of file gltf_material_mapper.cpp.
References crimson::MaterialColorSrgb::a, quader::io::gltf::GltfMaterialSource::alpha_cutoff, quader::io::gltf::GltfMaterialSource::alpha_mode, quader::io::IoDiagnosticList::append(), quader::io::gltf::GltfPbrMetallicRoughness::base_color_factor, crimson::base_shader_id_name(), Blend, crimson::MaterialInstance::debug_name, quader::io::gltf::GltfMaterialMapping::diagnostics, crimson::MaterialRenderOverrides::double_sided, quader::io::gltf::GltfMaterialSource::double_sided, quader::io::gltf::GltfMaterialSource::emissive_factor, quader::foundation::Result< T, E >::failure(), crimson::BaseShaderRegistry::find(), crimson::find_parameter_desc(), crimson::make_default_material_instance(), Mask, quader::io::gltf::GltfMaterialMapping::material, quader::io::gltf::GltfMaterialMapping::metadata, quader::io::gltf::GltfPbrMetallicRoughness::metallic_factor, quader::io::gltf::GltfMaterialSource::name, quader::io::gltf::GltfMaterialSource::normal_scale, quader::io::gltf::GltfMaterialSource::occlusion_strength, crimson::MaterialInstance::overrides, quader::io::gltf::GltfMaterialSource::pbr, quader::io::IoError::related, quader::io::gltf::GltfPbrMetallicRoughness::roughness_factor, quader::io::ImportedMaterialMetadata::source_format, quader::io::ImportedMaterialMetadata::source_material_id, quader::io::ImportedMaterialMetadata::source_name, quader::foundation::Result< T, E >::success(), and crimson::validate_material_instance().