Quader: quader::geometry Namespace Reference
quader::geometry Namespace Reference
Functions
quader::math::Vec3 triangle_normal (quader::math::Vec3 a, quader::math::Vec3 b, quader::math::Vec3 c) noexcept
quader::math::Vec3 polygon_normal (std::span< const quader::math::Vec3 > points) noexcept
bool has_degenerate_area (std::span< const quader::math::Vec3 > points, float epsilon=quader::math::kDefaultEpsilon) noexcept
bool all_points_finite (std::span< const quader::math::Vec3 > points) noexcept
Function Documentation
all_points_finite()
bool quader::geometry::all_points_finite (std::span< const quader::math::Vec3 > points) inline nodiscard noexcept
Check whether all points contain finite coordinates.
Parameters
points Points to test.
Returns
True when every point has finite x, y, and z components.
Definition at line 25 of file predicates.hpp.
References quader::math::is_finite().
Referenced by quader::mesh::Polyhedron::create_face(), and quader::mesh::Polyhedron::validate_mesh.
has_degenerate_area()
bool quader::geometry::has_degenerate_area (std::span< const quader::math::Vec3 > points, float epsilon = quader::math::kDefaultEpsilon) inline nodiscard noexcept
Check whether a polygon has degenerate area.
Parameters
points Polygon vertices in winding order.
epsilon Normal-length threshold treated as degenerate.
Returns
True when the accumulated normal length squared is below threshold.
Definition at line 65 of file normals.hpp.
References quader::math::kDefaultEpsilon, quader::math::length_squared(), and polygon_normal().
Referenced by quader::mesh::Polyhedron::create_face(), and quader::mesh::Polyhedron::validate_mesh.
polygon_normal()
quader::math::Vec3 quader::geometry::polygon_normal (std::span< const quader::math::Vec3 > points) inline nodiscard noexcept
Compute an unnormalized polygon normal with Newell accumulation.
Parameters
points Polygon vertices in winding order.
Returns
Accumulated normal, or the zero vector for fewer than three points.
Definition at line 39 of file normals.hpp.
References quader::math::Vec3::x, quader::math::Vec3::y, and quader::math::Vec3::z.
Referenced by has_degenerate_area().
triangle_normal()
quader::math::Vec3 quader::geometry::triangle_normal (quader::math::Vec3 a, quader::math::Vec3 b, quader::math::Vec3 c) inline nodiscard noexcept
Compute an unnormalized triangle normal.
Parameters
a First triangle vertex.
b Second triangle vertex.
c Third triangle vertex.
Returns
Cross product (b - a) x (c - a).
Definition at line 27 of file normals.hpp.
References quader::math::cross().