Quader: quader::mesh Namespace Reference
quader::mesh Namespace Reference
Namespaces
namespace detail
namespace ops
Classes
struct AttributeDescriptor
Descriptor for one mesh attribute array.
struct AttributeValueTraits
struct AttributeValueTraits< float >
Attribute value traits for float.
struct AttributeValueTraits< quader::math::Vec2 >
Attribute value traits for Vec2.
struct AttributeValueTraits< quader::math::Vec3 >
Attribute value traits for Vec3.
struct AttributeValueTraits< std::uint32_t >
Attribute value traits for std::uint32_t.
class MeshAttributes
struct MeshCompactionReport
Counts returned after storage compaction.
struct MeshError
Structured mesh error with a code and user/developer diagnostic.
struct MeshValidationIssue
One mesh validation issue.
class MeshValidationReport
Collection of issues produced by mesh validation.
class Polyhedron
Typedefs
using VertexId = quader::foundation::GenerationalId<VertexTag>
Generational identifier for a vertex record.
using HalfedgeId = quader::foundation::GenerationalId<HalfedgeTag>
Generational identifier for a halfedge record.
using EdgeId = quader::foundation::GenerationalId<EdgeTag>
Generational identifier for an edge record.
using FaceId = quader::foundation::GenerationalId<FaceTag>
Generational identifier for a face record.
using AttributeId = quader::foundation::Id<AttributeTag>
Index-only identifier for an attribute descriptor.
Enumerations
enum class AttributeDomain { Vertex , Halfedge , Edge , Face }
Mesh element domain that owns an attribute array.
enum class AttributeValueType { Float32 , Vec2Float32 , Vec3Float32 , UInt32 }
Runtime value kind stored by an attribute array.
enum class MeshErrorCode {
InvalidVertex , InvalidHalfedge , InvalidEdge , InvalidFace ,
InvalidAttribute , AttributeNameAlreadyExists , AttributeTypeMismatch , AttributeIndexOutOfRange ,
FaceNeedsAtLeastThreeVertices , NonFinitePosition , DegenerateFace , VertexStillReferenced ,
BrokenFaceCycle , NonManifoldTopology , BackendRejectedFace , BackendMappingCorrupt ,
CompactionFailed , InvalidGeometry
}
Mesh-core error categories returned by expected-failure APIs.
enum class MeshValidationCode {
InvalidId , MissingBackendHandle , MissingQuaderId , ReverseMappingMismatch ,
DeletedElementMapped , AttributeDomainMismatch , BrokenOppositePair , BrokenNextPrevCycle ,
FaceCycleMismatch , VertexReferenceMismatch , EdgeReferenceMismatch , BoundaryPlaceholderMismatch ,
DegenerateFace , NonFinitePosition , BrokenFaceCycle
}
Mesh validation issue categories.
Functions
MeshError make_mesh_error (MeshErrorCode code, std::string message)
quader::foundation::Result< std::vector< VertexId >, MeshError > face_vertices (const Polyhedron &mesh, FaceId face)
quader::foundation::Result< std::vector< EdgeId >, MeshError > face_edges (const Polyhedron &mesh, FaceId face)
HalfedgeId find_halfedge (const Polyhedron &mesh, VertexId origin, VertexId target) noexcept
MeshValidationReport validate_mesh (const Polyhedron &mesh)
Typedef Documentation
AttributeId
using quader::mesh::AttributeId = quader::foundation::Id<AttributeTag>
Index-only identifier for an attribute descriptor.
Definition at line 36 of file mesh_ids.hpp.
EdgeId
using quader::mesh::EdgeId = quader::foundation::GenerationalId<EdgeTag>
Generational identifier for an edge record.
Definition at line 32 of file mesh_ids.hpp.
FaceId
using quader::mesh::FaceId = quader::foundation::GenerationalId<FaceTag>
Generational identifier for a face record.
Definition at line 34 of file mesh_ids.hpp.
HalfedgeId
using quader::mesh::HalfedgeId = quader::foundation::GenerationalId<HalfedgeTag>
Generational identifier for a halfedge record.
Definition at line 30 of file mesh_ids.hpp.
VertexId
using quader::mesh::VertexId = quader::foundation::GenerationalId<VertexTag>
Generational identifier for a vertex record.
Definition at line 28 of file mesh_ids.hpp.
Enumeration Type Documentation
AttributeDomain
enum class quader::mesh::AttributeDomain strong
Mesh element domain that owns an attribute array.
Enumerator
Vertex
One value per vertex slot.
Halfedge
One value per halfedge slot.
Edge
One value per edge slot.
Face
One value per face slot.
Definition at line 33 of file mesh_attributes.hpp.
AttributeValueType
enum class quader::mesh::AttributeValueType strong
Runtime value kind stored by an attribute array.
Enumerator
Float32
Single float value.
Vec2Float32
Vec2 single-precision value.
Vec3Float32
Vec3 single-precision value.
UInt32
Unsigned 32-bit integer value.
Definition at line 45 of file mesh_attributes.hpp.
MeshErrorCode
enum class quader::mesh::MeshErrorCode strong
Mesh-core error categories returned by expected-failure APIs.
Enumerator
InvalidVertex
Vertex identifier is invalid, stale, or not present.
InvalidHalfedge
Halfedge identifier is invalid, stale, or not present.
InvalidEdge
Edge identifier is invalid, stale, or not present.
InvalidFace
Face identifier is invalid, stale, or not present.
InvalidAttribute
Attribute identifier is invalid or not present.
AttributeNameAlreadyExists
Attribute name already exists in the requested domain.
AttributeTypeMismatch
Attribute storage type does not match the requested value type.
AttributeIndexOutOfRange
Attribute slot index is outside the attribute array.
FaceNeedsAtLeastThreeVertices
Face creation received fewer than three vertices.
NonFinitePosition
Geometry contains a NaN or infinity coordinate.
DegenerateFace
Face geometry has degenerate area.
VertexStillReferenced
Vertex cannot be deleted because topology still references it.
BrokenFaceCycle
Face traversal detected an invalid cycle.
NonManifoldTopology
Topology would become or already is non-manifold.
BackendRejectedFace
Backend mesh storage rejected a face operation.
BackendMappingCorrupt
Quader ID to backend-handle mapping is inconsistent.
CompactionFailed
Storage compaction failed to preserve mesh mappings.
InvalidGeometry
Input geometry failed validation.
Definition at line 20 of file mesh_error.hpp.
MeshValidationCode
enum class quader::mesh::MeshValidationCode strong
Mesh validation issue categories.
Enumerator
InvalidId
A Quader identifier is invalid or stale.
MissingBackendHandle
A live Quader element has no backend handle.
MissingQuaderId
A live backend element has no Quader ID.
ReverseMappingMismatch
Forward and reverse backend mappings disagree.
DeletedElementMapped
A deleted element is still present in an active mapping.
AttributeDomainMismatch
Attribute array size does not match its element domain.
BrokenOppositePair
Opposite halfedge links are not reciprocal.
BrokenNextPrevCycle
Next/previous halfedge links are not reciprocal.
FaceCycleMismatch
Halfedge face membership does not match the face cycle.
VertexReferenceMismatch
Vertex reference is missing or inconsistent.
EdgeReferenceMismatch
Edge reference is missing or inconsistent.
BoundaryPlaceholderMismatch
Boundary placeholder representation is inconsistent.
DegenerateFace
Face has degenerate geometric area.
NonFinitePosition
Vertex position contains NaN or infinity.
BrokenFaceCycle
Face cycle traversal failed.
Definition at line 23 of file mesh_validation.hpp.
Function Documentation
face_edges()
quader::foundation::Result< std::vector< EdgeId >, MeshError > quader::mesh::face_edges (const Polyhedron & mesh, FaceId face) inline nodiscard
Return the edges that bound a face.
Parameters
mesh Mesh to query.
face Face whose halfedge cycle is traversed.
Returns
Edge IDs in face-cycle order, or a mesh error.
Definition at line 61 of file mesh_traversal.hpp.
Referenced by quader::tests::document_fixtures::make_triangle_mesh().
face_vertices()
quader::foundation::Result< std::vector< VertexId >, MeshError > quader::mesh::face_vertices (const Polyhedron & mesh, FaceId face) inline nodiscard
Return the vertices that bound a face.
Parameters
mesh Mesh to query.
face Face whose halfedge cycle is traversed.
Returns
Vertex IDs in face-cycle order, or a mesh error.
Definition at line 29 of file mesh_traversal.hpp.
find_halfedge()
HalfedgeId quader::mesh::find_halfedge (const Polyhedron & mesh, VertexId origin, VertexId target) inline nodiscard noexcept
Find a directed halfedge between two vertices.
Parameters
mesh Mesh to scan.
origin Origin vertex.
target Target vertex.
Returns
Matching halfedge, or HalfedgeId::invalid() when absent or inputs are invalid.
Definition at line 93 of file mesh_traversal.hpp.
References quader::foundation::GenerationalId< HalfedgeTag >::invalid().
make_mesh_error()
MeshError quader::mesh::make_mesh_error (MeshErrorCode code, std::string message) inline nodiscard
Create a mesh error from a code and message.
Parameters
code Mesh error category.
message Diagnostic message to store.
Returns
Error with Severity::Error.
Definition at line 74 of file mesh_error.hpp.
References quader::foundation::Error.
Referenced by quader::mesh::Polyhedron::compact_storage(), quader::mesh::MeshAttributes::create(), quader::mesh::Polyhedron::create_face(), quader::mesh::Polyhedron::delete_face(), quader::mesh::Polyhedron::delete_vertex(), quader::mesh::Polyhedron::edge_halfedges(), quader::mesh::Polyhedron::face_halfedges(), quader::mesh::Polyhedron::halfedge_edge(), quader::mesh::Polyhedron::halfedge_face(), quader::mesh::Polyhedron::halfedge_origin(), quader::mesh::Polyhedron::halfedge_target(), quader::mesh::Polyhedron::is_boundary_halfedge(), quader::mesh::Polyhedron::next_halfedge(), quader::mesh::Polyhedron::opposite_halfedge(), quader::mesh::Polyhedron::previous_halfedge(), quader::mesh::Polyhedron::set_vertex_position(), quader::mesh::MeshAttributes::value(), quader::mesh::MeshAttributes::value(), quader::mesh::Polyhedron::vertex_attribute(), quader::mesh::Polyhedron::vertex_attribute(), quader::mesh::Polyhedron::vertex_outgoing_halfedge(), and quader::mesh::Polyhedron::vertex_position().
validate_mesh()
MeshValidationReport quader::mesh::validate_mesh (const Polyhedron & mesh) nodiscard
Validate mesh topology, mappings, attributes, and geometry invariants.
Parameters
mesh Mesh to inspect.
Returns
Validation report containing every issue detected by the pass.
Definition at line 116 of file mesh_validation.cpp.
Referenced by quader::io::validate_document_fragment().