Quader: quader::foundation Namespace Reference
quader::foundation Namespace Reference
Classes
struct Diagnostic
One diagnostic message with a severity.
class DiagnosticList
class GenerationalId
class Id
class Result
class Result< void, E >
Typedefs
using IdIndex = std::uint32_t
Storage type used for index portions of project-owned handles.
using IdGeneration = std::uint32_t
Storage type used to invalidate stale generational handles after reuse.
using LogSink = void (*)(LogLevel level, std::string_view message)
Callback type that receives log messages.
Enumerations
enum class Severity { Info , Warning , Error }
Severity level for developer-facing diagnostics.
enum class LogLevel { Debug , Info , Warning , Error }
Logging level used by the foundation logging sink.
Functions
void assertion_failed (const char *condition, const char *file, int line, const char *function)
void set_log_sink (LogSink sink) noexcept
LogSink log_sink () noexcept
std::string_view log_level_name (LogLevel level) noexcept
void log_message (LogLevel level, std::string_view message)
Variables
constexpr IdIndex kInvalidIdIndex = std::numeric_limits<IdIndex>::max()
Sentinel index used by invalid handles.
Typedef Documentation
IdGeneration
using quader::foundation::IdGeneration = std::uint32_t
Storage type used to invalidate stale generational handles after reuse.
Definition at line 22 of file id.hpp.
IdIndex
using quader::foundation::IdIndex = std::uint32_t
Storage type used for index portions of project-owned handles.
Definition at line 20 of file id.hpp.
LogSink
using quader::foundation::LogSink = void (*)(LogLevel level, std::string_view message)
Callback type that receives log messages.
Definition at line 29 of file logging.hpp.
Enumeration Type Documentation
LogLevel
enum class quader::foundation::LogLevel strong
Logging level used by the foundation logging sink.
Enumerator
Debug
Verbose developer diagnostics.
Info
Informational messages.
Warning
Recoverable warnings.
Error
Error messages.
Definition at line 17 of file logging.hpp.
Severity
enum class quader::foundation::Severity strong
Severity level for developer-facing diagnostics.
Enumerator
Info
Informational diagnostic with no failure implied.
Warning
Recoverable or noteworthy condition.
Error
Error condition that should block the current operation.
Definition at line 21 of file diagnostic.hpp.
Function Documentation
assertion_failed()
void quader::foundation::assertion_failed (const char * condition, const char * file, int line, const char * function) inline
Log an assertion failure and terminate the process.
Parameters
condition Stringized failed condition.
file Source file where the assertion failed.
line Source line where the assertion failed.
function Function where the assertion failed.
Definition at line 27 of file assert.hpp.
References Error, and log_message().
log_level_name()
std::string_view quader::foundation::log_level_name (LogLevel level) nodiscard noexcept
Return the stable display name for a log level.
Parameters
level Level to name.
Returns
Static string view for the level.
Definition at line 69 of file logging.cpp.
References Debug, Error, Info, and Warning.
log_message()
void quader::foundation::log_message (LogLevel level, std::string_view message)
Emit a message through the active sink.
Parameters
level Severity level for the message.
message Borrowed message text.
Definition at line 84 of file logging.cpp.
References log_sink().
Referenced by assertion_failed().
log_sink()
LogSink quader::foundation::log_sink () nodiscard noexcept
Return the active logging sink.
Returns
Current process-local sink callback.
Definition at line 65 of file logging.cpp.
Referenced by log_message().
set_log_sink()
void quader::foundation::set_log_sink (LogSink sink) noexcept
Replace the process-local logging sink.
Parameters
sink Sink callback, or nullptr to restore the default behavior.
Definition at line 61 of file logging.cpp.
Variable Documentation
kInvalidIdIndex
IdIndex quader::foundation::kInvalidIdIndex = std::numeric_limits<IdIndex>::max() constexpr
Sentinel index used by invalid handles.
Definition at line 25 of file id.hpp.
Referenced by quader::foundation::GenerationalId< ObjectTag >::is_valid(), quader::foundation::Id< AttributeTag >::is_valid(), quader::foundation::GenerationalId< ObjectTag >::operator<=>, and quader::foundation::Id< AttributeTag >::operator<=>.