Quader: quader::tests::mesh_fixtures Namespace Reference
quader::tests::mesh_fixtures Namespace Reference
Classes
struct MeshCorruptionAccess
Test-only accessors for intentionally corrupting mesh internals.
struct SingleTriangleMesh
Mesh fixture containing one triangular face.
Functions
quader::mesh::Polyhedron make_invalid_triangle_with_nonfinite_vertex_position (quader::math::Vec3 position)
SingleTriangleMesh make_single_triangle ()
Function Documentation
make_invalid_triangle_with_nonfinite_vertex_position()
quader::mesh::Polyhedron quader::tests::mesh_fixtures::make_invalid_triangle_with_nonfinite_vertex_position (quader::math::Vec3 position) inline
Create an invalid triangle fixture with a corrupted vertex position.
Parameters
position Position written to the first vertex through test hooks.
Returns
Mesh containing the intentionally invalid vertex position.
Definition at line 91 of file mesh_corruption_fixtures.hpp.
References make_single_triangle(), and quader::tests::mesh_fixtures::MeshCorruptionAccess::set_vertex_position_unchecked().
make_single_triangle()
SingleTriangleMesh quader::tests::mesh_fixtures::make_single_triangle () inline
Create a single-triangle mesh fixture.
Returns
Mesh with three vertices and one triangular face.
Definition at line 37 of file mesh_fixtures.hpp.
References QUADER_ASSERT.
Referenced by make_invalid_triangle_with_nonfinite_vertex_position().