Quader: crimson Namespace Reference
crimson Namespace Reference
Namespaces
namespace gpu
Classes
struct BaseShaderDefinition
Static schema describing one Crimson base shader.
class BaseShaderRegistry
Immutable lookup table for Crimson base shader definitions.
struct CameraFrustum
Camera frustum data prepared for CPU culling.
struct ColorLinear
Color stored in linear light space.
struct ColorSrgb
Color stored in sRGB transfer space.
struct CullingDecision
CPU culling decision for one object bounds test.
class DiagnosticRing
Fixed-capacity ring buffer of renderer diagnostics.
struct DisplayConversionSettings
Settings that choose the final linear-to-sRGB display path.
struct DrawPacket
CPU-side draw command prepared from render objects and material state.
struct DrawPacketBuildResult
Result of building draw packets for one view.
class FrameBuilder
Builds immutable frame snapshots from viewport-facing input data.
struct FrameCullingStats
CPU culling counters for one frame.
struct FrameInstancingStats
Instancing and batching counters for one frame.
struct FramePacketStats
Draw-packet counters for one frame.
struct FrameQueueStats
Queue-level draw counts used to assemble FrameStats.
struct FrameRenderResult
CPU-side result produced after submitting one renderer frame.
struct FrameResourceStats
Live resource counts used to assemble FrameStats.
class FrameSnapshot
struct FrameStats
Aggregated diagnostics and performance counters for one frame.
struct FrameStatsInput
Input bundle used to construct an aggregated frame stats record.
struct FrameTargetDescriptor
Render-resource descriptor plus semantic frame-target metadata.
struct FrameTimingStats
CPU timing counters in microseconds.
struct FrameUploadStats
Resource upload counters for one frame.
struct GridOverlayCommand
Grid overlay payload consumed by the overlay renderer.
struct InstanceBatch
Instancing group containing compatible draw packets.
struct InstanceBatchKey
Key used to group compatible draw packets into one instanced submission.
struct LineOverlaySegment
World-space line segment payload for overlay line lists.
struct MaterialColorSrgb
sRGB color material parameter value.
struct MaterialEnumValue
Integer-backed enum material parameter value.
struct MaterialInstance
Material instance bound to one base shader and its declared parameters.
struct MaterialParameter
Concrete material parameter value keyed by schema name.
struct MaterialParameterDesc
Schema entry for one material parameter.
struct MaterialRenderOverrides
Per-material render-state overrides outside the base shader schema.
class MaterialSystem
Owns renderer material instances and validates them against base shader schemas.
struct MaterialTextureBinding
Concrete texture binding keyed by slot name.
struct MaterialTextureSlotDesc
Schema entry for one material texture slot.
struct MaterialUiFieldDesc
One UI field exposed by a base shader schema.
struct MaterialVec2
Two-component material parameter value.
struct MaterialVec3
Three-component material parameter value.
struct MaterialVec4
Four-component material parameter value.
struct NativeSurfaceDescriptor
Native host surface passed to Crimson at startup.
struct OverlayCommand
Renderer command describing one overlay draw payload.
struct OverlayDrawBucket
Prepared overlay commands for one depth bucket.
struct OverlayDrawLists
Prepared overlay commands split by depth policy.
class OverlaySystem
Converts overlay snapshot commands into depth buckets and linear colors.
struct PackedPickingIdRgba8
RGBA8 representation of a raw picking id.
class PickingIdAllocator
struct PickingPayload
Decoded picking payload associated with a submitted raw id.
struct PickingRequest
One viewport pixel readback request.
struct PickingResult
Completed picking request result.
struct PreparedGridOverlayCommand
Prepared grid overlay command and shader-facing colors.
struct PreparedLineOverlayCommand
Prepared line overlay command and copied line payloads.
struct PreparedOverlayCommand
Overlay command after color conversion for renderer submission.
struct PrototypeCamera
Camera state consumed by the legacy prototype viewport path.
struct PrototypeViewportFrame
Per-frame payload for the legacy prototype viewport renderer.
struct PrototypeViewportRect
Pixel rectangle for one prototype viewport pane.
struct PrototypeViewportView
One view submitted through the prototype viewport path.
struct RenderCamera
Camera data consumed by a render view.
struct RenderCameraMatrices
View and projection matrices produced with the same conventions Crimson submits to bgfx.
struct RenderCameraRay
World-space ray reconstructed from a Crimson render camera and viewport position.
struct RenderCameraViewportSize
Pixel size of the viewport rectangle used for camera projection.
struct RenderEnvironment
Environment and clear-color settings for a render snapshot.
struct RenderEnvironmentHandle
CPU-side handle for a renderer environment resource.
class Renderer
struct RendererCapabilityStatus
Support status for one renderer capability.
struct RendererConfig
Startup configuration for a Crimson renderer instance.
struct RendererCounter
One named renderer counter.
struct RendererDiagnostic
Structured renderer diagnostic entry.
struct RendererDiagnosticsSnapshot
Value-copy diagnostics snapshot for UI and tests.
struct RendererStatus
Snapshot of renderer startup/runtime status.
struct RenderFrameBufferHandle
CPU-side handle for a renderer framebuffer resource.
class RenderGraph
Minimal render graph for named frame resources and passes.
struct RenderLight
CPU-side renderer light payload.
struct RenderMaterialHandle
CPU-side handle for a renderer material resource.
struct RenderMeshHandle
CPU-side handle for a renderer mesh resource.
struct RenderMeshRevision
Revision tuple used to decide whether a render mesh upload is stale.
struct RenderMeshUpload
Snapshot-owned render mesh upload payload.
struct RenderMeshUploadDesc
CPU-side render mesh upload descriptor.
struct RenderMeshUploadRecord
Record of the revision and byte counts uploaded for one render mesh.
class RenderMeshUploadTracker
Tracks uploaded render mesh revisions and upload counters.
struct RenderObject
CPU-side object submitted to the render world.
struct RenderPass
CPU-side render graph pass declaration.
struct RenderPassStats
Per-pass renderer statistics exposed to diagnostics UI/tests.
struct RenderProgramHandle
CPU-side handle for a renderer shader program resource.
struct RenderResourceDesc
Description of one render graph resource.
struct RenderResourceRecord
Live render graph resource record.
class RenderResourceRegistry
Owns render graph resource records and resize generations.
struct RenderTextureHandle
CPU-side handle for a renderer texture resource.
struct RenderView
One camera/view rectangle rendered into a frame target.
struct RenderViewportRect
Pixel rectangle occupied by a render view inside the frame target.
class RenderWorld
Mutable CPU-side collection of renderer objects.
struct ResourceUse
Resource access declared by one render pass.
class ScopedCpuTimer
RAII CPU timer that writes elapsed microseconds into a counter.
struct Vec3
Three-component single-precision vector.
struct ViewportExtent
Pixel extent and scale of a renderer viewport target.
struct ViewportSettings
Per-viewport render settings.
Typedefs
using VertexAttributeMask = std::uint32_t
Bitmask of VertexAttribute values.
using MaterialParameterValue
Variant storing all supported material parameter value types.
using PickingRequestId = std::uint64_t
Stable id used to match asynchronous picking readbacks to UI requests.
using RenderObjectId = std::uint64_t
Stable renderer object identifier used for drawing and picking.
Enumerations
enum class TextureDataRole : std::uint8_t {
BaseColor , Emissive , MetallicRoughness , Normal ,
Occlusion , PickingId , Depth , ShadowLike
}
Semantic texture role used to choose sampling color encoding.
enum class TextureColorEncoding : std::uint8_t { LinearData , Srgb }
Texture color encoding requested from the graphics runtime.
enum class RendererMetricUnit : std::uint8_t { Count , Bytes , Microseconds , Frames }
Unit used to display a renderer counter.
enum class RendererCounterDomain : std::uint8_t {
Frame , Graph , Culling , Packets ,
Instancing , Upload , Resources , Picking ,
Overlay , Diagnostics
}
Diagnostics domain associated with a renderer counter.
enum class DebugViewMode { FinalColor }
Renderer debug visualization selected for the frame.
enum class FrameTargetKind {
BackbufferColor , BackbufferDepth , HdrSceneColor , SceneDepth ,
PickingId , ToneMappedColor
}
Logical frame targets used by the V1 render graph.
enum class PickingIdTargetFormat { R32Uint , Rgba8Data }
GPU format policy for picking-id targets.
enum class RenderResourceFormat {
BackbufferColor , BackbufferDepth , Rgba8Unorm , Rgba16Float ,
D24S8 , D32Float , R32Uint
}
Frame resource format used by the render graph.
enum class RenderResourceAccess { Read , Write , ReadWrite }
Access mode declared by a pass for one resource.
enum class DepthMode : std::uint8_t { Disabled , TestWrite , TestReadOnly , OverlayCommand }
Depth-state policy declared by a base shader.
enum class BlendMode : std::uint8_t { Off , AlphaBlend }
Blend-state policy declared by a base shader.
enum class CullMode : std::uint8_t { Back , None }
Face-culling policy declared by a base shader.
enum class ShadowMode : std::uint8_t { None , CastAndReceive , AlphaTestedCastAndReceive }
Shadow behavior declared by a base shader.
enum VertexAttribute : std::uint32_t {
VertexAttributePosition = 1u << 0u , VertexAttributeNormal = 1u << 1u , VertexAttributeTangent = 1u << 2u , VertexAttributeUv0 = 1u << 3u ,
VertexAttributeUv1 = 1u << 4u , VertexAttributeColor0 = 1u << 5u
}
Vertex attribute bits required by base shaders.
enum class MaterialParameterKind : std::uint8_t {
Float , Vec2 , Vec3 , Vec4 ,
ColorSrgb , Bool , Enum
}
Runtime kind of a material parameter value.
enum class TextureColorSpace : std::uint8_t { Srgb , Linear , Data }
Color-space interpretation for material texture sampling.
enum class MaterialUiFieldKind : std::uint8_t { Parameter , TextureSlot }
Material schema binding kind represented by a UI field.
enum class MaterialUiControl : std::uint8_t {
Float , Vec2 , Color , Checkbox ,
Combo , Texture
}
Control kind requested by a material UI schema field.
enum class NativeSurfacePlatform {
Unknown , Windows , LinuxX11 , LinuxWayland ,
MacOS
}
Host platform used to interpret native surface handles.
enum class OverlayDepthMode : std::uint8_t { DepthTested , XRay , AlwaysOnTop }
Depth policy used when compositing editor overlays.
enum class OverlayPrimitive : std::uint8_t { Grid , LineList , SolidTriangles }
Overlay primitive payload type.
enum class PickingElementKind : std::uint8_t {
None , Object , Submesh , Face ,
Edge , Vertex
}
Kind of renderer payload stored in a picking id.
enum class DisplayConversionPath { SrgbBackbuffer , ManualFinalShader }
Final display conversion path selected for the active backend.
enum class PrototypeCameraProjection { Perspective , Orthographic }
Projection mode used by the legacy prototype viewport adapter.
enum class GraphicsBackendPreference {
Auto , Vulkan , Metal , Direct3D12 ,
Direct3D11
}
Requested graphics backend selection policy for Crimson startup.
enum class ToneMapper : std::uint8_t { AcesFitted , AgxApprox , Reinhard , Linear }
Tone-mapping operator applied during display conversion.
enum class RendererDiagnosticSeverity { Info , Warning , Error , Fatal }
Severity level for renderer diagnostics.
enum class RendererDiagnosticCode {
SurfaceUnavailable , BackendUnsupported , CapabilityMissing , RuntimeInitializationFailed ,
ShaderManifestInvalid , ShaderTargetMissing , ShaderFileMissing , ShaderProgramCreationFailed ,
ResourceCreationFailed , FrameGraphValidationFailed , InvalidFrameSnapshot , ResizeFailed ,
ColorSpaceInvalid , MaterialSchemaInvalid , MaterialValidationFailed , PickingReadbackFailed ,
FrameBufferUnsupported , ResourceLifetimeError , PerformanceCounterInvalid , GoldenCaptureUnsupported ,
GoldenReadbackFailed , UploadSkippedInvalidResource , BenchmarkConfigurationInvalid
}
Machine-readable renderer diagnostic category.
enum class RendererCapability {
Instancing , Texture2D , TextureCube , FloatingPointRenderTarget ,
RenderToTexture , DepthTexture , SrgbTextureSampling , SrgbBackbuffer ,
ManualSrgbFinalConversion , IntegerPickingTarget , Rgba8PickingTarget , Readback
}
Renderer capability used by startup validation and diagnostics.
enum class ShaderProgramId : std::uint16_t {
PrototypeLitCube , PrototypeGridOverlay , OpaquePbr , AlphaCutoutPbr ,
TransparentPbr , OverlayUnlit , OverlayLine , Picking ,
ToneMap , Present
}
Shader program identifiers known to the compiled shader manifest.
enum class BaseShaderId : std::uint16_t { OpaquePbr , AlphaCutoutPbr , TransparentPbr , OverlayUnlit }
Base shader schemas supported by V1 material instances.
enum class RenderDomain : std::uint8_t {
LitSurface , TransparentSurface , Overlay , Picking ,
Post
}
High-level render domain used for material and pass separation.
enum class RenderQueue : std::uint8_t {
PrototypeOpaque , Opaque , AlphaCutout , Transparent ,
OverlayDepthTested , OverlayXRay , OverlayAlwaysOnTop , Picking
}
Queue used for sorting and routing draw packets.
enum class CameraProjection { Perspective , Orthographic }
Camera projection mode for renderer views.
enum class RenderLightKind { Directional , Point , Spot }
Light type consumed by renderer snapshots.
enum class BuiltInRenderMesh { None , UnitBox }
Built-in mesh payloads supplied by Crimson when no uploaded mesh is needed.
Functions
ColorLinear srgb_to_linear (ColorSrgb color) noexcept
ColorSrgb linear_to_srgb (ColorLinear color) noexcept
TextureColorEncoding texture_color_encoding (TextureDataRole role) noexcept
bool texture_role_uses_srgb (TextureDataRole role) noexcept
DiagnosticRing make_diagnostic_ring_from_recent (const std::vector< RendererDiagnostic > &diagnostics, std::size_t capacity)
std::vector< RenderPassStats > make_render_pass_stats (const RenderGraph &graph, const FrameStats *stats)
std::vector< RendererCounter > make_renderer_counters (const FrameStats &stats)
RendererStatus make_bounded_renderer_status_snapshot (const RendererStatus &status, std::vector< RendererDiagnostic > recent_diagnostics)
constexpr std::string_view renderer_metric_unit_name (RendererMetricUnit unit) noexcept
constexpr std::string_view renderer_counter_domain_name (RendererCounterDomain domain) noexcept
bool is_valid_render_view (const RenderView &view) noexcept
FrameStats make_frame_stats (const FrameStatsInput &input) noexcept
std::array< FrameTargetDescriptor, 6 > v1_frame_target_descriptors (PickingIdTargetFormat picking_format=PickingIdTargetFormat::R32Uint) noexcept
Return V1 frame target descriptors for the requested picking format.
std::vector< RenderResourceDesc > make_v1_frame_target_resource_descs (ViewportExtent extent, PickingIdTargetFormat picking_format=PickingIdTargetFormat::R32Uint)
Convert V1 frame targets into render graph resource descriptors.
bool is_color_managed_frame_target (std::string_view name) noexcept
Return true when the target name denotes a color-managed target.
bool is_hdr_frame_target (std::string_view name) noexcept
Return true when the target name denotes a linear HDR target.
bool is_data_frame_target (std::string_view name) noexcept
Return true when the target name denotes a data target.
const char * render_resource_format_name (RenderResourceFormat format) noexcept
const char * render_resource_access_name (RenderResourceAccess access) noexcept
RenderPass make_cpu_pass (std::string name)
RenderPass make_pass (std::string name, std::vector< ResourceUse > resources)
RenderGraph make_minimal_prototype_render_graph (ViewportExtent extent)
RenderGraph make_v1_correctness_render_graph (ViewportExtent extent, PickingIdTargetFormat picking_format)
const MaterialParameterDesc * find_parameter_desc (const BaseShaderDefinition &definition, std::string_view name) noexcept
Find a parameter descriptor by name, or return nullptr.
const MaterialTextureSlotDesc * find_texture_slot_desc (const BaseShaderDefinition &definition, std::string_view name) noexcept
Find a texture slot descriptor by name, or return nullptr.
const char * depth_mode_name (DepthMode mode) noexcept
Return the stable debug name for a depth mode.
const char * blend_mode_name (BlendMode mode) noexcept
Return the stable debug name for a blend mode.
const char * cull_mode_name (CullMode mode) noexcept
Return the stable debug name for a cull mode.
const char * shadow_mode_name (ShadowMode mode) noexcept
Return the stable debug name for a shadow mode.
BaseShaderRegistry make_v1_base_shader_registry ()
Build the built-in V1 base shader registry.
MaterialParameterKind material_parameter_value_kind (const MaterialParameterValue &value) noexcept
Return the value kind held by a material parameter variant.
const char * material_parameter_kind_name (MaterialParameterKind kind) noexcept
Return the stable debug name for a material parameter kind.
MaterialInstance make_default_material_instance (const BaseShaderDefinition &definition)
const char * texture_color_space_name (TextureColorSpace color_space) noexcept
Return the stable debug name for a texture color-space policy.
quader::foundation::Result< void, RendererDiagnostic > validate_material_instance (const BaseShaderRegistry &registry, const MaterialInstance &instance)
quader::foundation::Result< RenderMeshUploadRecord, RendererDiagnostic > validate_render_mesh_upload_desc (const RenderMeshUploadDesc &desc)
constexpr std::string_view native_surface_platform_name (NativeSurfacePlatform platform) noexcept
constexpr bool is_valid_native_surface_descriptor (const NativeSurfaceDescriptor &surface) noexcept
GridOverlayCommand make_grid_overlay_for_view (const RenderView &view)
OverlayCommand make_grid_overlay_command (const GridOverlayCommand &grid, std::uint32_t payload_offset)
RenderQueue render_queue_for_overlay_depth_mode (OverlayDepthMode depth_mode) noexcept
Return the render queue corresponding to an overlay depth mode.
std::array< float, 4 > to_linear_sdr_array (ColorSrgb color, float opacity=1.0F) noexcept
Convert an sRGB overlay color to a linear SDR RGBA array.
PackedPickingIdRgba8 encode_picking_id_rgba8 (std::uint32_t raw_id) noexcept
Encode a raw picking id into RGBA8 bytes.
std::uint32_t decode_picking_id_rgba8 (PackedPickingIdRgba8 encoded) noexcept
Decode RGBA8 bytes into a raw picking id.
std::array< float, 4 > picking_id_rgba8_to_unorm (PackedPickingIdRgba8 encoded) noexcept
Convert encoded RGBA8 bytes to normalized float channels for shader uploads.
bool picking_readback_requested (std::span< const PickingRequest > requests) noexcept
Return true when at least one picking request needs readback.
PickingPayload picking_payload_for_object (const RenderObject &object) noexcept
Build the default object-level picking payload for a render object.
DrawPacketBuildResult build_draw_packets (std::span< const RenderObject > objects, const BaseShaderRegistry &registry, const MaterialSystem &materials, const RenderCamera &camera, RenderMeshHandle unit_box_mesh, RenderMaterialHandle fallback_material, float view_aspect_ratio)
bool opaque_draw_packet_less (const DrawPacket &left, const DrawPacket &right) noexcept
bool transparent_draw_packet_less (const DrawPacket &left, const DrawPacket &right) noexcept
void sort_opaque_draw_packets (std::span< DrawPacket > packets)
void sort_transparent_draw_packets (std::span< DrawPacket > packets)
CameraFrustum make_camera_frustum (const RenderCamera &camera, float aspect_ratio) noexcept
CullingDecision cull_object_bounds (const CameraFrustum &frustum, quader::math::Aabb bounds) noexcept
float object_camera_distance_sq (const RenderObject &object, const RenderCamera &camera) noexcept
bool render_queue_supports_instancing (RenderQueue queue) noexcept
InstanceBatchKey instance_batch_key_for (const DrawPacket &packet) noexcept
std::vector< InstanceBatch > build_instance_batches (std::span< const DrawPacket > packets)
FrameInstancingStats make_instancing_stats (std::span< const InstanceBatch > batches) noexcept
float exposure_multiplier_from_ev100 (float ev100, float compensation_ev) noexcept
ColorLinear apply_exposure (ColorLinear hdr, float exposure_multiplier) noexcept
ColorLinear apply_tone_mapper (ToneMapper mapper, ColorLinear hdr) noexcept
std::optional< DisplayConversionPath > choose_display_conversion_path (bool srgb_backbuffer_supported, DisplayConversionSettings settings) noexcept
constexpr bool is_valid_prototype_view (const PrototypeViewportView &view) noexcept
constexpr std::string_view graphics_backend_preference_name (GraphicsBackendPreference preference) noexcept
constexpr std::string_view tone_mapper_name (ToneMapper tone_mapper) noexcept
constexpr std::string_view renderer_diagnostic_severity_name (RendererDiagnosticSeverity severity) noexcept
constexpr std::string_view renderer_diagnostic_code_name (RendererDiagnosticCode code) noexcept
constexpr std::string_view renderer_capability_name (RendererCapability capability) noexcept
bool has_error_diagnostic (const RendererStatus &status)
bool has_structured_context (const RendererDiagnostic &diagnostic) noexcept
template<typename Handle>
constexpr bool is_valid_handle (const Handle &handle) noexcept
constexpr bool is_valid_extent (const ViewportExtent &extent) noexcept
constexpr std::string_view shader_program_id_name (ShaderProgramId id) noexcept
constexpr std::string_view base_shader_id_name (BaseShaderId id) noexcept
constexpr std::string_view render_domain_name (RenderDomain domain) noexcept
constexpr std::string_view render_queue_name (RenderQueue queue) noexcept
bool current_render_homogeneous_depth () noexcept
RenderCameraMatrices render_camera_matrices (const RenderCamera &camera, float aspect_ratio, bool homogeneous_depth)
RenderCameraRay render_camera_ray_from_viewport_point (const RenderCamera &camera, RenderCameraViewportSize viewport_size, quader::math::Vec2 local_point_px, bool homogeneous_depth)
constexpr std::array< float, 16 > identity_transform () noexcept
float length (Vec3 value) noexcept
Vec3 normalized (Vec3 value, float epsilon=kDefaultEpsilon) noexcept
Variables
constexpr std::string_view kBackbufferColorTargetName = "BackbufferColor"
Name of the external color target presented by the viewport.
constexpr std::string_view kBackbufferDepthTargetName = "BackbufferDepth"
Name of the external depth target paired with the backbuffer.
constexpr std::string_view kHdrSceneColorTargetName = "HdrSceneColor"
Name of the linear HDR scene color target.
constexpr std::string_view kSceneDepthTargetName = "SceneDepth"
Name of the scene depth target.
constexpr std::string_view kPickingIdTargetName = "PickingId"
Name of the picking-id data target.
constexpr std::string_view kToneMappedColorTargetName = "ToneMappedColor"
Name of the SDR tone-mapped scene color target.
Typedef Documentation
MaterialParameterValue
using crimson::MaterialParameterValue
Initial value:
std::variant<
       float,
       MaterialVec2,
       MaterialVec3,
       MaterialVec4,
       MaterialColorSrgb,
       bool,
       MaterialEnumValue>
Variant storing all supported material parameter value types.
Definition at line 88 of file material_parameter.hpp.
PickingRequestId
using crimson::PickingRequestId = std::uint64_t
Stable id used to match asynchronous picking readbacks to UI requests.
Definition at line 23 of file picking.hpp.
RenderObjectId
using crimson::RenderObjectId = std::uint64_t
Stable renderer object identifier used for drawing and picking.
Definition at line 21 of file render_object.hpp.
VertexAttributeMask
using crimson::VertexAttributeMask = std::uint32_t
Bitmask of VertexAttribute values.
Definition at line 61 of file base_shader.hpp.
Enumeration Type Documentation
BaseShaderId
enum class crimson::BaseShaderId : std::uint16_t strong
Base shader schemas supported by V1 material instances.
Enumerator
OpaquePbr
Opaque metallic/roughness PBR shader.
AlphaCutoutPbr
Alpha-cutout metallic/roughness PBR shader.
TransparentPbr
Transparent metallic/roughness PBR shader.
OverlayUnlit
Unlit editor/debug overlay shader.
Definition at line 173 of file renderer_types.hpp.
BlendMode
enum class crimson::BlendMode : std::uint8_t strong
Blend-state policy declared by a base shader.
Enumerator
Off
Disable blending.
AlphaBlend
Use alpha blending.
Definition at line 32 of file base_shader.hpp.
BuiltInRenderMesh
enum class crimson::BuiltInRenderMesh strong
Built-in mesh payloads supplied by Crimson when no uploaded mesh is needed.
Enumerator
None
No built-in mesh is requested.
UnitBox
Unit box mesh owned by the renderer runtime.
Definition at line 24 of file render_object.hpp.
CameraProjection
enum class crimson::CameraProjection strong
Camera projection mode for renderer views.
Enumerator
Perspective
Perspective projection.
Orthographic
Orthographic projection.
Definition at line 17 of file render_camera.hpp.
CullMode
enum class crimson::CullMode : std::uint8_t strong
Face-culling policy declared by a base shader.
Enumerator
Back
Cull back faces.
None
Disable face culling.
Definition at line 38 of file base_shader.hpp.
DebugViewMode
enum class crimson::DebugViewMode strong
Renderer debug visualization selected for the frame.
Enumerator
FinalColor
Final shaded and composited viewport color.
Definition at line 31 of file frame_snapshot.hpp.
DepthMode
enum class crimson::DepthMode : std::uint8_t strong
Depth-state policy declared by a base shader.
Enumerator
Disabled
Disable depth testing and writes.
TestWrite
Test against depth and write depth.
TestReadOnly
Test against depth without writing depth.
OverlayCommand
Depth policy is selected per overlay command.
Definition at line 24 of file base_shader.hpp.
DisplayConversionPath
enum class crimson::DisplayConversionPath strong
Final display conversion path selected for the active backend.
Enumerator
SrgbBackbuffer
Hardware sRGB conversion on the backbuffer.
ManualFinalShader
Manual final shader conversion from linear to sRGB.
Definition at line 20 of file tone_mapping.hpp.
FrameTargetKind
enum class crimson::FrameTargetKind strong
Logical frame targets used by the V1 render graph.
Enumerator
BackbufferColor
External color output.
BackbufferDepth
External depth output.
HdrSceneColor
Linear HDR scene color.
SceneDepth
Scene depth.
PickingId
Data target storing picking ids.
ToneMappedColor
SDR scene color after tone mapping.
Definition at line 34 of file frame_targets.hpp.
GraphicsBackendPreference
enum class crimson::GraphicsBackendPreference strong
Requested graphics backend selection policy for Crimson startup.
Enumerator
Auto
Select the best supported backend for the platform.
Vulkan
Prefer Vulkan.
Metal
Prefer Metal.
Direct3D12
Prefer Direct3D 12.
Direct3D11
Prefer Direct3D 11.
Definition at line 19 of file renderer_config.hpp.
MaterialParameterKind
enum class crimson::MaterialParameterKind : std::uint8_t strong
Runtime kind of a material parameter value.
Enumerator
Float
Scalar float.
Vec2
Two-component vector.
Vec3
Three-component vector.
Vec4
Four-component vector.
ColorSrgb
sRGB color.
Bool
Boolean toggle.
Enum
Integer-backed enum.
Definition at line 77 of file material_parameter.hpp.
MaterialUiControl
enum class crimson::MaterialUiControl : std::uint8_t strong
Control kind requested by a material UI schema field.
Enumerator
Float
Scalar numeric editor.
Vec2
Two-component numeric editor.
Color
Color editor.
Checkbox
Boolean editor.
Combo
Enum/list editor.
Texture
Texture picker.
Definition at line 24 of file material_ui_schema.hpp.
MaterialUiFieldKind
enum class crimson::MaterialUiFieldKind : std::uint8_t strong
Material schema binding kind represented by a UI field.
Enumerator
Parameter
Field edits a material parameter.
TextureSlot
Field edits a texture slot binding.
Definition at line 18 of file material_ui_schema.hpp.
NativeSurfacePlatform
enum class crimson::NativeSurfacePlatform strong
Host platform used to interpret native surface handles.
Enumerator
Unknown
Unknown or unsupported platform.
Windows
Win32 window handle.
LinuxX11
X11 window and display handles.
LinuxWayland
Wayland surface/display handles.
MacOS
macOS layer handle.
Definition at line 19 of file native_surface.hpp.
OverlayDepthMode
enum class crimson::OverlayDepthMode : std::uint8_t strong
Depth policy used when compositing editor overlays.
Enumerator
DepthTested
Hidden by scene depth.
XRay
Blended through scene depth.
AlwaysOnTop
Drawn without depth testing.
Definition at line 21 of file overlay_command.hpp.
OverlayPrimitive
enum class crimson::OverlayPrimitive : std::uint8_t strong
Overlay primitive payload type.
Enumerator
Grid
Grid payload in GridOverlayCommand.
LineList
Line segment payloads in LineOverlaySegment.
SolidTriangles
Triangle overlay payloads.
Definition at line 28 of file overlay_command.hpp.
PickingElementKind
enum class crimson::PickingElementKind : std::uint8_t strong
Kind of renderer payload stored in a picking id.
Enumerator
None
No payload.
Object
Object-level hit.
Submesh
Submesh-level hit.
Face
Mesh face hit.
Edge
Mesh edge hit.
Vertex
Mesh vertex hit.
Definition at line 26 of file picking.hpp.
PickingIdTargetFormat
enum class crimson::PickingIdTargetFormat strong
GPU format policy for picking-id targets.
Enumerator
R32Uint
Use an unsigned integer target.
Rgba8Data
Use RGBA8-encoded ids.
Definition at line 44 of file frame_targets.hpp.
PrototypeCameraProjection
enum class crimson::PrototypeCameraProjection strong
Projection mode used by the legacy prototype viewport adapter.
Enumerator
Perspective
Perspective projection.
Orthographic
Orthographic projection.
Definition at line 26 of file prototype_viewport.hpp.
RenderDomain
enum class crimson::RenderDomain : std::uint8_t strong
High-level render domain used for material and pass separation.
Enumerator
LitSurface
Lit opaque or alpha-tested surface domain.
TransparentSurface
Transparent lit surface domain.
Overlay
Editor overlay domain.
Picking
Picking/ID output domain.
Post
Post-processing domain.
Definition at line 206 of file renderer_types.hpp.
RendererCapability
enum class crimson::RendererCapability strong
Renderer capability used by startup validation and diagnostics.
Enumerator
Instancing
Hardware instancing support.
Texture2D
2D texture support.
TextureCube
Cube texture support.
FloatingPointRenderTarget
Floating-point render-target support.
RenderToTexture
Render-to-texture support.
DepthTexture
Depth texture support.
SrgbTextureSampling
Hardware sRGB texture sampling support.
SrgbBackbuffer
sRGB backbuffer support.
ManualSrgbFinalConversion
Manual final sRGB conversion support.
IntegerPickingTarget
Integer picking target support.
Rgba8PickingTarget
RGBA8 encoded picking target support.
Readback
GPU readback support.
Definition at line 82 of file renderer_diagnostics.hpp.
RendererCounterDomain
enum class crimson::RendererCounterDomain : std::uint8_t strong
Diagnostics domain associated with a renderer counter.
Enumerator
Frame
Frame-level counters.
Graph
Render graph counters.
Culling
CPU culling counters.
Packets
Draw-packet counters.
Instancing
Instancing counters.
Upload
Upload counters.
Resources
Runtime resource counters.
Picking
Picking counters.
Overlay
Overlay counters.
Diagnostics
Diagnostic counters.
Definition at line 37 of file renderer_diagnostics_snapshot.hpp.
RendererDiagnosticCode
enum class crimson::RendererDiagnosticCode strong
Machine-readable renderer diagnostic category.
Enumerator
SurfaceUnavailable
Native host surface is missing or invalid.
BackendUnsupported
Requested graphics backend is unavailable.
CapabilityMissing
Required renderer capability is missing.
RuntimeInitializationFailed
Graphics runtime initialization failed.
ShaderManifestInvalid
Shader manifest is missing or inconsistent.
ShaderTargetMissing
Compiled shader target is missing.
ShaderFileMissing
Compiled shader binary is missing.
ShaderProgramCreationFailed
GPU shader program creation failed.
ResourceCreationFailed
GPU resource creation failed.
FrameGraphValidationFailed
Render graph validation failed.
InvalidFrameSnapshot
Frame snapshot is invalid.
ResizeFailed
Resize request failed.
ColorSpaceInvalid
Color-space configuration is invalid.
MaterialSchemaInvalid
Material schema is invalid.
MaterialValidationFailed
Material instance failed validation.
PickingReadbackFailed
Picking readback failed.
FrameBufferUnsupported
Framebuffer format or setup is unsupported.
ResourceLifetimeError
Runtime resource lifetime is inconsistent.
PerformanceCounterInvalid
Performance counter data is invalid.
GoldenCaptureUnsupported
Golden image capture is unsupported by the active path.
GoldenReadbackFailed
Golden image readback failed.
UploadSkippedInvalidResource
Upload was skipped because the resource was invalid.
BenchmarkConfigurationInvalid
Benchmark configuration is invalid.
Definition at line 32 of file renderer_diagnostics.hpp.
RendererDiagnosticSeverity
enum class crimson::RendererDiagnosticSeverity strong
Severity level for renderer diagnostics.
Enumerator
Info
Informational diagnostic.
Warning
Recoverable renderer warning.
Error
Error that prevents part of the requested operation.
Fatal
Fatal error that prevents renderer startup or continued operation.
Definition at line 20 of file renderer_diagnostics.hpp.
RendererMetricUnit
enum class crimson::RendererMetricUnit : std::uint8_t strong
Unit used to display a renderer counter.
Enumerator
Count
Unitless count.
Bytes
Byte count.
Microseconds
Microsecond duration.
Frames
Frame count.
Definition at line 25 of file renderer_diagnostics_snapshot.hpp.
RenderLightKind
enum class crimson::RenderLightKind strong
Light type consumed by renderer snapshots.
Enumerator
Directional
Directional light using direction and illuminance-like intensity.
Point
Point light using position, range, and intensity.
Spot
Spot light using position, direction, range, and intensity.
Definition at line 17 of file render_light.hpp.
RenderQueue
enum class crimson::RenderQueue : std::uint8_t strong
Queue used for sorting and routing draw packets.
Enumerator
PrototypeOpaque
Legacy prototype opaque queue.
Opaque
Opaque surface queue.
AlphaCutout
Alpha-tested surface queue.
Transparent
Transparent surface queue.
OverlayDepthTested
Depth-tested overlay queue.
OverlayXRay
X-ray overlay queue.
OverlayAlwaysOnTop
Always-on-top overlay queue.
Picking
Picking queue.
Definition at line 243 of file renderer_types.hpp.
RenderResourceAccess
enum class crimson::RenderResourceAccess strong
Access mode declared by a pass for one resource.
Enumerator
Read
Pass reads the resource.
Write
Pass writes the resource.
ReadWrite
Pass reads and writes the resource.
Definition at line 38 of file render_resource_desc.hpp.
RenderResourceFormat
enum class crimson::RenderResourceFormat strong
Frame resource format used by the render graph.
Enumerator
BackbufferColor
External backbuffer color target.
BackbufferDepth
External backbuffer depth target.
Rgba8Unorm
8-bit normalized RGBA target.
Rgba16Float
16-bit floating-point RGBA target.
D24S8
24-bit depth plus 8-bit stencil target.
D32Float
32-bit floating-point depth target.
R32Uint
32-bit unsigned integer target.
Definition at line 20 of file render_resource_desc.hpp.
ShaderProgramId
enum class crimson::ShaderProgramId : std::uint16_t strong
Shader program identifiers known to the compiled shader manifest.
Enumerator
PrototypeLitCube
Legacy prototype lit cube program.
PrototypeGridOverlay
Legacy prototype grid overlay program.
OpaquePbr
Opaque PBR surface program.
AlphaCutoutPbr
Alpha-cutout PBR surface program.
TransparentPbr
Transparent PBR surface program.
OverlayUnlit
Unlit overlay program.
OverlayLine
Unlit line-list overlay program.
Picking
Object and element picking program.
ToneMap
Tone-mapping program.
Present
Present/composite program.
Definition at line 116 of file renderer_types.hpp.
ShadowMode
enum class crimson::ShadowMode : std::uint8_t strong
Shadow behavior declared by a base shader.
Enumerator
None
Do not cast or receive shadows.
CastAndReceive
Cast and receive opaque shadows.
AlphaTestedCastAndReceive
Cast alpha-tested shadows and receive shadows.
Definition at line 44 of file base_shader.hpp.
TextureColorEncoding
enum class crimson::TextureColorEncoding : std::uint8_t strong
Texture color encoding requested from the graphics runtime.
Enumerator
LinearData
Treat texture channels as linear data.
Srgb
Sample texture with sRGB-to-linear conversion.
Definition at line 61 of file color_space.hpp.
TextureColorSpace
enum class crimson::TextureColorSpace : std::uint8_t strong
Color-space interpretation for material texture sampling.
Enumerator
Srgb
sRGB color data.
Linear
Linear scalar/vector data.
Data
Non-color data such as normal maps or ids.
Definition at line 20 of file material_texture.hpp.
TextureDataRole
enum class crimson::TextureDataRole : std::uint8_t strong
Semantic texture role used to choose sampling color encoding.
Enumerator
BaseColor
Base-color texture data.
Emissive
Emissive texture data.
MetallicRoughness
Packed metallic/roughness texture data.
Normal
Normal-map texture data.
Occlusion
Ambient-occlusion texture data.
PickingId
Picking identifier texture data.
Depth
Depth texture data.
ShadowLike
Shadow-map-like texture data.
Definition at line 41 of file color_space.hpp.
ToneMapper
enum class crimson::ToneMapper : std::uint8_t strong
Tone-mapping operator applied during display conversion.
Enumerator
AcesFitted
ACES fitted approximation.
AgxApprox
AgX-inspired approximation.
Reinhard
Reinhard tone mapper.
Linear
Linear pass-through clamp path.
Definition at line 33 of file renderer_config.hpp.
VertexAttribute
enum crimson::VertexAttribute : std::uint32_t
Vertex attribute bits required by base shaders.
Enumerator
VertexAttributePosition
Position attribute.
VertexAttributeNormal
Normal attribute.
VertexAttributeTangent
Tangent attribute.
VertexAttributeUv0
First texture coordinate attribute.
VertexAttributeUv1
Second texture coordinate attribute.
VertexAttributeColor0
First vertex color attribute.
Definition at line 51 of file base_shader.hpp.
Function Documentation
apply_exposure()
ColorLinear crimson::apply_exposure (ColorLinear hdr, float exposure_multiplier) nodiscard noexcept
Apply exposure to an HDR color.
Parameters
hdr Linear HDR color.
exposure_multiplier Linear exposure multiplier.
Returns
Exposed linear color with alpha preserved.
Definition at line 26 of file exposure.cpp.
apply_tone_mapper()
ColorLinear crimson::apply_tone_mapper (ToneMapper mapper, ColorLinear hdr) nodiscard noexcept
Apply a tone mapper to a linear HDR color.
Parameters
mapper Tone mapper to apply.
hdr Linear HDR input color.
Returns
Tone-mapped linear SDR color with alpha preserved.
Definition at line 63 of file tone_mapping.cpp.
base_shader_id_name()
std::string_view crimson::base_shader_id_name (BaseShaderId id) constexpr noexcept
Return the stable base shader name.
Parameters
id Base shader identifier.
Returns
Static base shader name.
Definition at line 190 of file renderer_types.hpp.
References AlphaCutoutPbr, OpaquePbr, OverlayUnlit, and TransparentPbr.
Referenced by crimson::MaterialSystem::create_default_material(), quader::io::gltf::map_gltf_material_to_crimson(), and validate_material_instance().
blend_mode_name()
const char * crimson::blend_mode_name (BlendMode mode) nodiscard noexcept
Return the stable debug name for a blend mode.
Definition at line 53 of file base_shader.cpp.
References AlphaBlend, and Off.
build_draw_packets()
DrawPacketBuildResult crimson::build_draw_packets (std::span< const RenderObject > objects, const BaseShaderRegistry & registry, const MaterialSystem & materials, const RenderCamera & camera, RenderMeshHandle unit_box_mesh, RenderMaterialHandle fallback_material, float view_aspect_ratio = 1.0F) nodiscard
Build draw packets from visible render objects.
Parameters
objects Render objects to inspect.
registry Base shader registry used for shader schema lookup.
materials Material system used for material lookup.
camera Camera used for culling and distance sorting.
unit_box_mesh Built-in unit box mesh for explicitly marked objects.
fallback_material Material handle substituted when an object has no material.
view_aspect_ratio View aspect ratio used for frustum culling.
Returns
Queue-separated draw packets and frame counters.
Definition at line 72 of file draw_packet.cpp.
References crimson::DrawPacketBuildResult::alpha_cutout, crimson::FramePacketStats::alpha_cutout_packet_count, AlphaCutout, cull_object_bounds(), crimson::FrameCullingStats::culled_object_count, crimson::DrawPacketBuildResult::culling, crimson::BaseShaderDefinition::domain, crimson::DrawPacketBuildResult::draw_packet_count(), crimson::FramePacketStats::draw_packet_count, crimson::FrameCullingStats::input_object_count, crimson::CullingDecision::invalid_bounds, crimson::FrameCullingStats::invalid_bounds_count, is_valid_handle(), LitSurface, make_camera_frustum(), None, Opaque, crimson::DrawPacketBuildResult::opaque, crimson::FramePacketStats::opaque_packet_count, OverlayAlwaysOnTop, OverlayDepthTested, OverlayXRay, crimson::DrawPacketBuildResult::packets, Picking, PrototypeOpaque, crimson::DrawPacket::queue, sort_opaque_draw_packets(), sort_transparent_draw_packets(), crimson::FramePacketStats::sorted_packet_count, Transparent, crimson::DrawPacketBuildResult::transparent, crimson::FramePacketStats::transparent_packet_count, TransparentSurface, crimson::CullingDecision::visible, and crimson::FrameCullingStats::visible_object_count.
Referenced by crimson::gpu::prepare_pbr_pass_packets(), and quader::benchmarks::run_crimson_packet_pipeline_benchmark().
build_instance_batches()
std::vector< InstanceBatch > crimson::build_instance_batches (std::span< const DrawPacket > packets) nodiscard
Group draw packets into instancing batches.
Parameters
packets Packets to group.
Returns
Instance batches in deterministic order.
Definition at line 60 of file instancing_batcher.cpp.
References instance_batch_key_for(), and render_queue_supports_instancing().
Referenced by crimson::gpu::GpuDevice::render_frame(), and quader::benchmarks::run_crimson_packet_pipeline_benchmark().
choose_display_conversion_path()
std::optional< DisplayConversionPath > crimson::choose_display_conversion_path (bool srgb_backbuffer_supported, DisplayConversionSettings settings) nodiscard noexcept
Choose the display conversion path for backend capabilities and settings.
Parameters
srgb_backbuffer_supported Whether the active backend supports sRGB backbuffers.
settings Display conversion preferences.
Returns
Selected path, or empty when neither path is allowed.
Definition at line 72 of file tone_mapping.cpp.
References ManualFinalShader, and SrgbBackbuffer.
cull_mode_name()
const char * crimson::cull_mode_name (CullMode mode) nodiscard noexcept
Return the stable debug name for a cull mode.
Definition at line 64 of file base_shader.cpp.
References Back, and None.
cull_object_bounds()
CullingDecision crimson::cull_object_bounds (const CameraFrustum & frustum, quader::math::Aabb bounds) nodiscard noexcept
Cull object bounds against a frustum.
Parameters
frustum Frustum to test against.
bounds World-space bounds.
Returns
Culling decision with invalid-bounds state.
Definition at line 76 of file frustum_culler.cpp.
References quader::math::center(), quader::math::dot(), and Orthographic.
Referenced by build_draw_packets().
current_render_homogeneous_depth()
bool crimson::current_render_homogeneous_depth () nodiscard noexcept
Return the active bgfx homogeneous-depth convention.
Returns
True when the current bgfx backend uses homogeneous depth.
Definition at line 41 of file render_camera_projection.cpp.
decode_picking_id_rgba8()
std::uint32_t crimson::decode_picking_id_rgba8 (PackedPickingIdRgba8 encoded) nodiscard noexcept
Decode RGBA8 bytes into a raw picking id.
Definition at line 26 of file picking.cpp.
depth_mode_name()
const char * crimson::depth_mode_name (DepthMode mode) nodiscard noexcept
Return the stable debug name for a depth mode.
Definition at line 38 of file base_shader.cpp.
References Disabled, OverlayCommand, TestReadOnly, and TestWrite.
encode_picking_id_rgba8()
PackedPickingIdRgba8 crimson::encode_picking_id_rgba8 (std::uint32_t raw_id) nodiscard noexcept
Encode a raw picking id into RGBA8 bytes.
Definition at line 17 of file picking.cpp.
Referenced by crimson::gpu::GpuPicking::submit_frame_requests().
exposure_multiplier_from_ev100()
float crimson::exposure_multiplier_from_ev100 (float ev100, float compensation_ev) nodiscard noexcept
Convert camera EV100 and exposure compensation into a multiplier.
Parameters
ev100 Camera exposure value at ISO 100.
compensation_ev Exposure compensation in stops.
Returns
Linear multiplier applied to HDR scene color.
Definition at line 17 of file exposure.cpp.
Referenced by crimson::gpu::GpuDevice::render_frame().
find_parameter_desc()
const MaterialParameterDesc * crimson::find_parameter_desc (const BaseShaderDefinition & definition, std::string_view name) nodiscard noexcept
Find a parameter descriptor by name, or return nullptr.
Definition at line 14 of file base_shader.cpp.
References crimson::MaterialParameterDesc::name.
Referenced by quader::io::gltf::map_gltf_material_to_crimson(), and validate_material_instance().
find_texture_slot_desc()
const MaterialTextureSlotDesc * crimson::find_texture_slot_desc (const BaseShaderDefinition & definition, std::string_view name) nodiscard noexcept
Find a texture slot descriptor by name, or return nullptr.
Definition at line 26 of file base_shader.cpp.
References crimson::MaterialTextureSlotDesc::name.
Referenced by validate_material_instance().
graphics_backend_preference_name()
std::string_view crimson::graphics_backend_preference_name (GraphicsBackendPreference preference) constexpr noexcept
Return the stable display name for a backend preference.
Parameters
preference Backend preference to name.
Returns
Static display name.
Definition at line 50 of file renderer_config.hpp.
References Auto, Direct3D11, Direct3D12, Metal, and Vulkan.
Referenced by crimson::gpu::make_backend_unsupported_diagnostic().
has_error_diagnostic()
bool crimson::has_error_diagnostic (const RendererStatus & status) inline
Check whether renderer status contains an error or fatal diagnostic.
Parameters
status Status to inspect.
Returns
True when any diagnostic is Error or Fatal.
Definition at line 272 of file renderer_diagnostics.hpp.
References crimson::RendererStatus::diagnostics, Error, Fatal, and crimson::RendererDiagnostic::severity.
Referenced by crimson::gpu::GpuDevice::initialize().
has_structured_context()
bool crimson::has_structured_context (const RendererDiagnostic & diagnostic) inline noexcept
Check whether a diagnostic has subsystem and resource context.
Parameters
diagnostic Diagnostic to inspect.
Returns
True when both context fields are non-empty.
Definition at line 288 of file renderer_diagnostics.hpp.
identity_transform()
std::array< float, 16 > crimson::identity_transform () nodiscard constexpr noexcept
Create a column-major identity transform.
Returns
Sixteen floats representing an identity matrix.
Definition at line 36 of file render_object.hpp.
instance_batch_key_for()
InstanceBatchKey crimson::instance_batch_key_for (const DrawPacket & packet) nodiscard noexcept
Build an instancing key for one draw packet.
Parameters
packet Packet to convert.
Returns
Batch key containing the packet's grouping fields.
Definition at line 48 of file instancing_batcher.cpp.
Referenced by build_instance_batches().
is_color_managed_frame_target()
bool crimson::is_color_managed_frame_target (std::string_view name) nodiscard noexcept
Return true when the target name denotes a color-managed target.
Definition at line 100 of file frame_targets.cpp.
References v1_frame_target_descriptors().
is_data_frame_target()
bool crimson::is_data_frame_target (std::string_view name) nodiscard noexcept
Return true when the target name denotes a data target.
Definition at line 118 of file frame_targets.cpp.
References v1_frame_target_descriptors().
is_hdr_frame_target()
bool crimson::is_hdr_frame_target (std::string_view name) nodiscard noexcept
Return true when the target name denotes a linear HDR target.
Definition at line 109 of file frame_targets.cpp.
References v1_frame_target_descriptors().
is_valid_extent()
bool crimson::is_valid_extent (const ViewportExtent & extent) constexpr noexcept
Check whether a viewport extent can be rendered.
Parameters
extent Extent to test.
Returns
True when dimensions and device pixel ratio are positive.
Definition at line 111 of file renderer_types.hpp.
Referenced by crimson::RenderResourceRegistry::add(), crimson::FrameBuilder::build_prototype_snapshot(), is_valid_native_surface_descriptor(), crimson::gpu::GpuDevice::render_frame(), crimson::gpu::GpuDevice::resize(), and crimson::RenderResourceRegistry::resize().
is_valid_handle()
template<typename Handle> bool crimson::is_valid_handle (const Handle & handle) constexpr noexcept
Check whether a renderer handle is non-sentinel.
Template Parameters
Handle Handle type with index and generation members.
Parameters
handle Handle to test.
Returns
True when both index and generation are non-zero.
Definition at line 91 of file renderer_types.hpp.
Referenced by build_draw_packets(), crimson::gpu::GpuPicking::submit_frame_requests(), crimson::gpu::GpuResourceTable< GpuMeshResource, RenderMeshHandle >::upsert(), and validate_render_mesh_upload_desc().
is_valid_native_surface_descriptor()
bool crimson::is_valid_native_surface_descriptor (const NativeSurfaceDescriptor & surface) constexpr noexcept
Check whether a native surface descriptor has required fields.
Parameters
surface Surface descriptor to validate.
Returns
True when platform, window handle, and extent are valid.
Definition at line 75 of file native_surface.hpp.
References is_valid_extent(), and Unknown.
Referenced by crimson::gpu::GpuDevice::initialize().
is_valid_prototype_view()
bool crimson::is_valid_prototype_view (const PrototypeViewportView & view) nodiscard constexpr noexcept
Check whether a prototype view references a valid pane and camera slot.
Parameters
view View to validate.
Returns
True when dimensions are non-zero and camera_index is within the prototype limit.
Definition at line 103 of file prototype_viewport.hpp.
Referenced by crimson::FrameBuilder::build_prototype_snapshot().
is_valid_render_view()
bool crimson::is_valid_render_view (const RenderView & view) nodiscard noexcept
Validate a render view rectangle and camera payload.
Parameters
view View to validate.
Returns
True when the view has a non-empty rectangle and usable camera data.
Definition at line 102 of file frame_snapshot.cpp.
Referenced by crimson::gpu::GpuDevice::render_frame().
length()
float quader::math::length (Vec3 value) inline nodiscard noexcept
Compute vector length.
Parameters
value Vector to measure.
Returns
Euclidean length.
Definition at line 118 of file vec3.hpp.
linear_to_srgb()
ColorSrgb crimson::linear_to_srgb (ColorLinear color) nodiscard noexcept
Convert a linear-light color to sRGB.
Parameters
color Color in linear light.
Returns
sRGB color with alpha preserved.
Definition at line 55 of file color_space.cpp.
make_bounded_renderer_status_snapshot()
RendererStatus crimson::make_bounded_renderer_status_snapshot (const RendererStatus & status, std::vector< RendererDiagnostic > recent_diagnostics) nodiscard
Build a status snapshot with externally bounded recent diagnostics.
Parameters
status Source renderer status.
recent_diagnostics Bounded diagnostics to attach to the copied status.
Returns
Status copy using recent_diagnostics.
Definition at line 132 of file renderer_diagnostics_snapshot.cpp.
References crimson::RendererStatus::backend_name, crimson::RendererStatus::capabilities, and crimson::RendererStatus::initialized.
Referenced by crimson::Renderer::diagnostics_snapshot().
make_camera_frustum()
CameraFrustum crimson::make_camera_frustum (const RenderCamera & camera, float aspect_ratio = 1.0F) nodiscard noexcept
Build frustum data from a render camera.
Parameters
camera Camera to convert.
aspect_ratio View aspect ratio.
Returns
Camera frustum used by CPU culling.
Definition at line 48 of file frustum_culler.cpp.
References quader::math::cross(), quader::math::kDefaultEpsilon, quader::math::length_squared(), and quader::math::normalized().
Referenced by build_draw_packets().
make_cpu_pass()
RenderPass crimson::make_cpu_pass (std::string name) nodiscard
Create a CPU-only pass with no declared resources.
Parameters
name Pass name.
Returns
Render pass descriptor.
Definition at line 73 of file render_graph.cpp.
Referenced by make_minimal_prototype_render_graph(), and make_v1_correctness_render_graph().
make_default_material_instance()
MaterialInstance crimson::make_default_material_instance (const BaseShaderDefinition & definition) nodiscard
Build a material instance populated with a base shader's default values.
Parameters
definition Base shader definition providing defaults.
Returns
Normalized default material instance.
Definition at line 46 of file material_system.cpp.
References crimson::MaterialInstance::base_shader_id, crimson::MaterialInstance::debug_name, crimson::MaterialTextureSlotDesc::default_texture, crimson::MaterialParameterDesc::default_value, crimson::BaseShaderDefinition::id, crimson::BaseShaderDefinition::name, crimson::MaterialParameterDesc::name, crimson::MaterialTextureSlotDesc::name, crimson::BaseShaderDefinition::parameters, crimson::MaterialInstance::parameters, crimson::BaseShaderDefinition::texture_slots, and crimson::MaterialInstance::textures.
Referenced by crimson::MaterialSystem::create_default_material(), quader::io::gltf::map_gltf_material_to_crimson(), and crimson::gpu::GpuMaterialCache::material_block().
make_diagnostic_ring_from_recent()
DiagnosticRing crimson::make_diagnostic_ring_from_recent (const std::vector< RendererDiagnostic > & diagnostics, std::size_t capacity = 256) nodiscard
Build a bounded ring from an existing diagnostic list.
Parameters
diagnostics Diagnostics copied into the ring.
capacity Maximum number of diagnostics retained.
Returns
Ring containing the most recent diagnostics up to capacity.
Definition at line 55 of file diagnostic_ring.cpp.
References crimson::DiagnosticRing::push().
Referenced by crimson::Renderer::diagnostics_snapshot().
make_frame_stats()
FrameStats crimson::make_frame_stats (const FrameStatsInput & input) nodiscard noexcept
Combine per-domain frame counters into one public stats record.
Parameters
input Source counters collected during frame submission.
Returns
Aggregated frame stats.
Definition at line 27 of file frame_stats.cpp.
References crimson::FramePacketStats::draw_packet_count.
Referenced by crimson::gpu::GpuDevice::render_frame(), quader::benchmarks::run_crimson_packet_pipeline_benchmark(), and quader::benchmarks::run_crimson_upload_benchmark().
make_grid_overlay_command()
OverlayCommand crimson::make_grid_overlay_command (const GridOverlayCommand & grid, std::uint32_t payload_offset) nodiscard
Build an overlay command that references one grid payload.
Parameters
grid Grid payload to reference.
payload_offset Offset of grid in the frame grid payload array.
Returns
Overlay command for the grid payload.
Definition at line 121 of file grid_overlay.cpp.
References DepthTested, Grid, crimson::GridOverlayCommand::minor_line_scale, OverlayUnlit, and crimson::GridOverlayCommand::view_index.
Referenced by crimson::FrameBuilder::build_prototype_snapshot().
make_grid_overlay_for_view()
GridOverlayCommand crimson::make_grid_overlay_for_view (const RenderView & view) nodiscard
Build the default viewport grid payload for a render view.
Parameters
view Render view that determines grid orientation and scale.
Returns
Grid overlay payload for view.
Definition at line 69 of file grid_overlay.cpp.
References crimson::GridOverlayCommand::axis_line_scale, crimson::GridOverlayCommand::axis_u_color, crimson::GridOverlayCommand::axis_v_color, crimson::RenderView::camera, crimson::GridOverlayCommand::edge_softness_m, crimson::RenderCamera::eye, crimson::GridOverlayCommand::fade_end_m, crimson::GridOverlayCommand::fade_start_m, crimson::RenderViewportRect::height, crimson::GridOverlayCommand::major_line_scale, crimson::GridOverlayCommand::major_spacing_m, crimson::GridOverlayCommand::minor_line_scale, crimson::GridOverlayCommand::minor_spacing_m, crimson::GridOverlayCommand::origin, Orthographic, crimson::GridOverlayCommand::orthographic_height_m, crimson::RenderCamera::orthographic_height_m, crimson::GridOverlayCommand::plane_height, crimson::GridOverlayCommand::plane_width, crimson::RenderCamera::projection, crimson::RenderView::rect, crimson::GridOverlayCommand::rotation_x, crimson::GridOverlayCommand::rotation_z, crimson::GridOverlayCommand::u_axis, crimson::GridOverlayCommand::v_axis, crimson::GridOverlayCommand::view_index, crimson::RenderView::view_index, crimson::GridOverlayCommand::viewport_height_px, crimson::RenderViewportRect::width, quader::math::Vec3::x, quader::math::Vec3::y, and quader::math::Vec3::z.
Referenced by crimson::FrameBuilder::build_prototype_snapshot().
make_instancing_stats()
FrameInstancingStats crimson::make_instancing_stats (std::span< const InstanceBatch > batches) nodiscard noexcept
Build instancing stats from batches.
Parameters
batches Instance batches to count.
Returns
Frame instancing counters.
Definition at line 83 of file instancing_batcher.cpp.
References crimson::FrameInstancingStats::batch_count, crimson::FrameInstancingStats::instanced_batch_count, crimson::FrameInstancingStats::saved_draw_call_count, crimson::FrameInstancingStats::single_draw_batch_count, and crimson::FrameInstancingStats::submitted_instance_count.
Referenced by crimson::gpu::GpuDevice::render_frame(), and quader::benchmarks::run_crimson_packet_pipeline_benchmark().
make_minimal_prototype_render_graph()
RenderGraph crimson::make_minimal_prototype_render_graph (ViewportExtent extent) nodiscard
Create the legacy prototype render graph.
Parameters
extent Viewport extent used by resize-dependent resources.
Returns
Render graph configured for the prototype path.
Definition at line 263 of file render_graph.cpp.
References crimson::RenderGraph::add_pass(), crimson::RenderGraph::add_resource(), make_cpu_pass(), make_pass(), Read, and ReadWrite.
make_pass()
RenderPass crimson::make_pass (std::string name, std::vector< ResourceUse > resources) nodiscard
Create a pass with declared resource uses.
Parameters
name Pass name.
resources Resource access declarations.
Returns
Render pass descriptor.
Definition at line 77 of file render_graph.cpp.
Referenced by make_minimal_prototype_render_graph(), and make_v1_correctness_render_graph().
make_render_pass_stats()
std::vector< RenderPassStats > crimson::make_render_pass_stats (const RenderGraph & graph, const FrameStats * stats = nullptr) nodiscard
Build per-pass diagnostics rows from a render graph.
Parameters
graph Graph whose passes are reported.
stats Optional latest frame stats used to attach pass counters.
Returns
Per-pass stats rows.
Definition at line 41 of file renderer_diagnostics_snapshot.cpp.
References crimson::ResourceUse::access, crimson::FrameStats::alpha_cutout_draw_count, crimson::FramePacketStats::alpha_cutout_packet_count, crimson::FrameTimingStats::cpu_resource_upload_us, crimson::RenderPassStats::cpu_time_us, crimson::RenderPassStats::draw_call_count, crimson::RenderPassStats::draw_packet_count, crimson::FrameStats::opaque_draw_count, crimson::FramePacketStats::opaque_packet_count, crimson::FrameStats::overlay_draw_count, crimson::FramePacketStats::overlay_packet_count, crimson::FrameStats::packets, crimson::RenderPassStats::pass_name, crimson::RenderGraph::passes(), crimson::RenderPassStats::resource_read_count, crimson::RenderPassStats::resource_write_count, crimson::FrameStats::timings, crimson::FrameStats::transparent_draw_count, and crimson::FramePacketStats::transparent_packet_count.
Referenced by crimson::Renderer::diagnostics_snapshot(), and crimson::gpu::GpuDevice::render_frame().
make_renderer_counters()
std::vector< RendererCounter > crimson::make_renderer_counters (const FrameStats & stats) nodiscard
Flatten frame stats into named counters.
Parameters
stats Frame stats to convert.
Returns
Counter rows grouped by domain.
Definition at line 84 of file renderer_diagnostics_snapshot.cpp.
References crimson::FramePacketStats::alpha_cutout_packet_count, crimson::FrameInstancingStats::batch_count, Bytes, crimson::FrameTimingStats::cpu_frame_us, crimson::FrameTimingStats::cpu_packet_build_us, crimson::FrameTimingStats::cpu_resource_upload_us, crimson::FrameTimingStats::cpu_submit_us, crimson::FrameCullingStats::culled_object_count, Culling, crimson::FrameStats::culling, crimson::FrameStats::diagnostic_count, Diagnostics, crimson::FrameStats::draw_call_count, crimson::FrameStats::draw_packet_count, Frame, crimson::FrameStats::frame_index, Frames, Graph, crimson::FrameStats::graph_pass_count, crimson::FrameCullingStats::input_object_count, crimson::FrameInstancingStats::instanced_batch_count, Instancing, crimson::FrameStats::instancing, crimson::FrameCullingStats::invalid_bounds_count, crimson::FrameStats::live_material_count, crimson::FrameStats::live_mesh_count, crimson::FrameStats::live_program_count, crimson::FrameStats::live_texture_count, crimson::FrameUploadStats::material_upload_count, crimson::FrameUploadStats::mesh_create_count, crimson::FrameUploadStats::mesh_destroy_count, crimson::FrameUploadStats::mesh_update_count, Microseconds, crimson::FramePacketStats::opaque_packet_count, Overlay, crimson::FrameStats::overlay_draw_count, crimson::FramePacketStats::overlay_packet_count, Packets, crimson::FrameStats::packets, Picking, crimson::FrameStats::picking_readback_count, crimson::FrameStats::picking_request_count, Resources, crimson::FrameInstancingStats::saved_draw_call_count, crimson::FrameInstancingStats::single_draw_batch_count, crimson::FrameUploadStats::skipped_clean_resource_count, crimson::FramePacketStats::sorted_packet_count, crimson::FrameInstancingStats::submitted_instance_count, crimson::FrameUploadStats::texture_upload_count, crimson::FrameStats::timings, crimson::FramePacketStats::transparent_packet_count, Upload, crimson::FrameUploadStats::uploaded_index_bytes, crimson::FrameUploadStats::uploaded_texture_bytes, crimson::FrameUploadStats::uploaded_vertex_bytes, crimson::FrameStats::uploads, crimson::FrameStats::view_count, and crimson::FrameCullingStats::visible_object_count.
Referenced by crimson::Renderer::diagnostics_snapshot(), quader::benchmarks::run_crimson_packet_pipeline_benchmark(), and quader::benchmarks::run_crimson_upload_benchmark().
make_v1_base_shader_registry()
BaseShaderRegistry crimson::make_v1_base_shader_registry () nodiscard
Build the built-in V1 base shader registry.
Definition at line 303 of file base_shader_registry.cpp.
Referenced by crimson::BaseShaderRegistry::BaseShaderRegistry(), and crimson::MaterialSystem::MaterialSystem().
make_v1_correctness_render_graph()
RenderGraph crimson::make_v1_correctness_render_graph (ViewportExtent extent, PickingIdTargetFormat picking_format = PickingIdTargetFormat::R32Uint) nodiscard
Create the V1 correctness render graph.
Parameters
extent Viewport extent used by resize-dependent resources.
picking_format Picking target format.
Returns
Render graph configured for the V1 pass sequence.
Definition at line 300 of file render_graph.cpp.
References crimson::RenderGraph::add_pass(), crimson::RenderGraph::add_resource(), kBackbufferColorTargetName, kHdrSceneColorTargetName, kPickingIdTargetName, kSceneDepthTargetName, kToneMappedColorTargetName, make_cpu_pass(), make_pass(), make_v1_frame_target_resource_descs(), Read, ReadWrite, and Write.
Referenced by crimson::Renderer::create().
make_v1_frame_target_resource_descs()
std::vector< RenderResourceDesc > crimson::make_v1_frame_target_resource_descs (ViewportExtent extent, PickingIdTargetFormat picking_format) nodiscard
Convert V1 frame targets into render graph resource descriptors.
Definition at line 88 of file frame_targets.cpp.
References v1_frame_target_descriptors().
Referenced by make_v1_correctness_render_graph().
material_parameter_kind_name()
const char * crimson::material_parameter_kind_name (MaterialParameterKind kind) nodiscard noexcept
Return the stable debug name for a material parameter kind.
Definition at line 18 of file material_parameter.cpp.
References Bool, ColorSrgb, Enum, Float, Vec2, Vec3, and Vec4.
Referenced by validate_material_instance().
material_parameter_value_kind()
MaterialParameterKind crimson::material_parameter_value_kind (const MaterialParameterValue & value) nodiscard noexcept
Return the value kind held by a material parameter variant.
Definition at line 14 of file material_parameter.cpp.
Referenced by validate_material_instance().
native_surface_platform_name()
std::string_view crimson::native_surface_platform_name (NativeSurfacePlatform platform) constexpr noexcept
Return the stable native-surface platform name.
Parameters
platform Platform to name.
Returns
Static platform name.
Definition at line 52 of file native_surface.hpp.
References LinuxWayland, LinuxX11, MacOS, Unknown, and Windows.
Referenced by crimson::gpu::make_backend_unsupported_diagnostic().
normalized()
Vec3 quader::math::normalized (Vec3 value, float epsilon = kDefaultEpsilon) inline nodiscard noexcept
Normalize a vector with a zero fallback.
Parameters
value Vector to normalize.
epsilon Length threshold treated as degenerate.
Returns
Unit vector, or the zero vector when value is degenerate.
Definition at line 129 of file vec3.hpp.
object_camera_distance_sq()
float crimson::object_camera_distance_sq (const RenderObject & object, const RenderCamera & camera) nodiscard noexcept
Compute squared camera distance for object sorting.
Parameters
object Object to measure.
camera Camera used as the distance origin.
Returns
Squared distance from camera eye to object bounds center.
Definition at line 117 of file frustum_culler.cpp.
opaque_draw_packet_less()
bool crimson::opaque_draw_packet_less (const DrawPacket & left, const DrawPacket & right) nodiscard noexcept
Compare opaque packets for queue/material/mesh-oriented sorting.
Parameters
left First packet.
right Second packet.
Returns
True when left should sort before right.
Definition at line 17 of file draw_packet_sort.cpp.
Referenced by sort_opaque_draw_packets().
picking_id_rgba8_to_unorm()
std::array< float, 4 > crimson::picking_id_rgba8_to_unorm (PackedPickingIdRgba8 encoded) nodiscard noexcept
Convert encoded RGBA8 bytes to normalized float channels for shader uploads.
Definition at line 30 of file picking.cpp.
Referenced by crimson::gpu::GpuPicking::submit_frame_requests().
picking_payload_for_object()
PickingPayload crimson::picking_payload_for_object (const RenderObject & object) nodiscard noexcept
Build the default object-level picking payload for a render object.
Definition at line 77 of file picking.cpp.
References Object.
Referenced by crimson::gpu::GpuPicking::submit_frame_requests().
picking_readback_requested()
bool crimson::picking_readback_requested (std::span< const PickingRequest > requests) nodiscard noexcept
Return true when at least one picking request needs readback.
Definition at line 40 of file picking.cpp.
Referenced by crimson::gpu::GpuPicking::submit_frame_requests().
render_camera_matrices()
RenderCameraMatrices crimson::render_camera_matrices (const RenderCamera & camera, float aspect_ratio, bool homogeneous_depth) nodiscard
Build render camera matrices with Crimson's bgfx-facing projection conventions.
Parameters
camera Camera state to project.
aspect_ratio Viewport width divided by height.
homogeneous_depth Active bgfx homogeneous-depth convention.
Returns
View and projection matrices matching scene rendering.
Definition at line 46 of file render_camera_projection.cpp.
References crimson::RenderCamera::eye, crimson::RenderCamera::far_plane_m, crimson::RenderCamera::near_plane_m, Orthographic, crimson::RenderCamera::orthographic_height_m, crimson::RenderCamera::projection, crimson::RenderCameraMatrices::projection, crimson::RenderCamera::target, crimson::RenderCamera::up, crimson::RenderCamera::vertical_fov_degrees, and crimson::RenderCameraMatrices::view.
Referenced by render_camera_ray_from_viewport_point().
render_camera_ray_from_viewport_point()
RenderCameraRay crimson::render_camera_ray_from_viewport_point (const RenderCamera & camera, RenderCameraViewportSize viewport_size, quader::math::Vec2 local_point_px, bool homogeneous_depth) nodiscard
Reconstruct a world ray from a viewport-local pixel position.
The math intentionally shares the same view-projection path as Crimson scene rendering so tools and picking do not drift from what the user sees.
Parameters
camera Camera state to project.
viewport_size Viewport rectangle size in physical pixels.
local_point_px Pointer position relative to the viewport rectangle.
homogeneous_depth Active bgfx homogeneous-depth convention.
Returns
World-space ray corresponding to local_point_px.
Definition at line 79 of file render_camera_projection.cpp.
References crimson::RenderCamera::eye, crimson::RenderCamera::forward, crimson::RenderCameraViewportSize::height_px, Orthographic, crimson::RenderCamera::projection, crimson::RenderCameraMatrices::projection, render_camera_matrices(), crimson::RenderCameraMatrices::view, crimson::RenderCameraViewportSize::width_px, quader::math::Vec2::x, and quader::math::Vec2::y.
render_domain_name()
std::string_view crimson::render_domain_name (RenderDomain domain) constexpr noexcept
Return the stable render-domain name.
Parameters
domain Render domain to name.
Returns
Static domain name.
Definition at line 225 of file renderer_types.hpp.
References LitSurface, Overlay, Picking, Post, and TransparentSurface.
render_queue_for_overlay_depth_mode()
RenderQueue crimson::render_queue_for_overlay_depth_mode (OverlayDepthMode depth_mode) nodiscard noexcept
Return the render queue corresponding to an overlay depth mode.
Definition at line 92 of file overlay_system.cpp.
References AlwaysOnTop, DepthTested, OverlayAlwaysOnTop, OverlayDepthTested, OverlayXRay, and XRay.
render_queue_name()
std::string_view crimson::render_queue_name (RenderQueue queue) constexpr noexcept
Return the stable render-queue name.
Parameters
queue Render queue to name.
Returns
Static queue name.
Definition at line 268 of file renderer_types.hpp.
References AlphaCutout, Opaque, OverlayAlwaysOnTop, OverlayDepthTested, OverlayXRay, Picking, PrototypeOpaque, and Transparent.
render_queue_supports_instancing()
bool crimson::render_queue_supports_instancing (RenderQueue queue) nodiscard noexcept
Check whether a render queue supports instanced drawing.
Parameters
queue Queue to test.
Returns
True when the queue can be grouped into instance batches.
Definition at line 44 of file instancing_batcher.cpp.
References AlphaCutout, Opaque, and Transparent.
Referenced by build_instance_batches().
render_resource_access_name()
const char * crimson::render_resource_access_name (RenderResourceAccess access) nodiscard noexcept
Return the stable resource-access name.
Parameters
access Access mode to name.
Returns
Static access name.
Definition at line 60 of file render_graph.cpp.
References Read, ReadWrite, and Write.
Referenced by crimson::RenderGraph::debug_dump().
render_resource_format_name()
const char * crimson::render_resource_format_name (RenderResourceFormat format) nodiscard noexcept
Return the stable resource-format name.
Parameters
format Format to name.
Returns
Static format name.
Definition at line 39 of file render_graph.cpp.
References BackbufferColor, BackbufferDepth, D24S8, D32Float, R32Uint, Rgba16Float, and Rgba8Unorm.
Referenced by crimson::RenderGraph::debug_dump().
renderer_capability_name()
std::string_view crimson::renderer_capability_name (RendererCapability capability) constexpr noexcept
Return the stable capability name.
Parameters
capability Capability to name.
Returns
Static capability name.
Definition at line 235 of file renderer_diagnostics.hpp.
References DepthTexture, FloatingPointRenderTarget, Instancing, IntegerPickingTarget, ManualSrgbFinalConversion, Readback, RenderToTexture, Rgba8PickingTarget, SrgbBackbuffer, SrgbTextureSampling, Texture2D, and TextureCube.
renderer_counter_domain_name()
std::string_view crimson::renderer_counter_domain_name (RendererCounterDomain domain) nodiscard constexpr noexcept
Return the stable counter-domain name.
Parameters
domain Counter domain to name.
Returns
Static domain name.
Definition at line 131 of file renderer_diagnostics_snapshot.hpp.
References Culling, Diagnostics, Frame, Graph, Instancing, Overlay, Packets, Picking, Resources, and Upload.
Referenced by quader::benchmarks::print_jsonl(), and quader::ui::viewport_diagnostics_from_crimson().
renderer_diagnostic_code_name()
std::string_view crimson::renderer_diagnostic_code_name (RendererDiagnosticCode code) constexpr noexcept
Return the stable diagnostic-code name.
Parameters
code Diagnostic code to name.
Returns
Static diagnostic-code name.
Definition at line 176 of file renderer_diagnostics.hpp.
References BackendUnsupported, BenchmarkConfigurationInvalid, CapabilityMissing, ColorSpaceInvalid, FrameBufferUnsupported, FrameGraphValidationFailed, GoldenCaptureUnsupported, GoldenReadbackFailed, InvalidFrameSnapshot, MaterialSchemaInvalid, MaterialValidationFailed, PerformanceCounterInvalid, PickingReadbackFailed, ResizeFailed, ResourceCreationFailed, ResourceLifetimeError, RuntimeInitializationFailed, ShaderFileMissing, ShaderManifestInvalid, ShaderProgramCreationFailed, ShaderTargetMissing, SurfaceUnavailable, and UploadSkippedInvalidResource.
Referenced by quader::ui::viewport_diagnostics_from_crimson().
renderer_diagnostic_severity_name()
std::string_view crimson::renderer_diagnostic_severity_name (RendererDiagnosticSeverity severity) constexpr noexcept
Return the stable severity name.
Parameters
severity Severity to name.
Returns
Static severity name.
Definition at line 155 of file renderer_diagnostics.hpp.
References Error, Fatal, Info, and Warning.
Referenced by quader::ui::viewport_diagnostics_from_crimson().
renderer_metric_unit_name()
std::string_view crimson::renderer_metric_unit_name (RendererMetricUnit unit) nodiscard constexpr noexcept
Return the stable metric-unit name.
Parameters
unit Metric unit to name.
Returns
Static unit name.
Definition at line 110 of file renderer_diagnostics_snapshot.hpp.
References Bytes, Count, Frames, and Microseconds.
Referenced by quader::ui::viewport_diagnostics_from_crimson().
shader_program_id_name()
std::string_view crimson::shader_program_id_name (ShaderProgramId id) constexpr noexcept
Return the stable shader program name.
Parameters
id Shader program identifier.
Returns
Static program name.
Definition at line 145 of file renderer_types.hpp.
References AlphaCutoutPbr, OpaquePbr, OverlayLine, OverlayUnlit, Picking, Present, PrototypeGridOverlay, PrototypeLitCube, ToneMap, and TransparentPbr.
shadow_mode_name()
const char * crimson::shadow_mode_name (ShadowMode mode) nodiscard noexcept
Return the stable debug name for a shadow mode.
Definition at line 75 of file base_shader.cpp.
References AlphaTestedCastAndReceive, CastAndReceive, and None.
sort_opaque_draw_packets()
void crimson::sort_opaque_draw_packets (std::span< DrawPacket > packets)
Sort opaque draw packets for deterministic front-end submission.
Parameters
[in,out] packets Packets sorted in place.
Definition at line 51 of file draw_packet_sort.cpp.
References opaque_draw_packet_less().
Referenced by build_draw_packets().
sort_transparent_draw_packets()
void crimson::sort_transparent_draw_packets (std::span< DrawPacket > packets)
Sort transparent draw packets for back-to-front submission.
Parameters
[in,out] packets Packets sorted in place.
Definition at line 55 of file draw_packet_sort.cpp.
References transparent_draw_packet_less().
Referenced by build_draw_packets().
srgb_to_linear()
ColorLinear crimson::srgb_to_linear (ColorSrgb color) nodiscard noexcept
Convert an sRGB color to linear light.
Parameters
color Color in sRGB transfer space.
Returns
Linear-light color with alpha preserved.
Definition at line 46 of file color_space.cpp.
Referenced by to_linear_sdr_array().
texture_color_encoding()
TextureColorEncoding crimson::texture_color_encoding (TextureDataRole role) nodiscard noexcept
Return the texture encoding for a semantic data role.
Parameters
role Texture data role.
Returns
Required texture color encoding.
Definition at line 64 of file color_space.cpp.
References BaseColor, Depth, Emissive, LinearData, MetallicRoughness, Normal, Occlusion, PickingId, ShadowLike, and Srgb.
Referenced by texture_role_uses_srgb().
texture_color_space_name()
const char * crimson::texture_color_space_name (TextureColorSpace color_space) nodiscard noexcept
Return the stable debug name for a texture color-space policy.
Definition at line 14 of file material_texture.cpp.
References Data, Linear, and Srgb.
texture_role_uses_srgb()
bool crimson::texture_role_uses_srgb (TextureDataRole role) nodiscard noexcept
Check whether a texture role uses sRGB sampling.
Parameters
role Texture data role.
Returns
True when the role should be sampled as sRGB.
Definition at line 81 of file color_space.cpp.
References Srgb, and texture_color_encoding().
to_linear_sdr_array()
std::array< float, 4 > crimson::to_linear_sdr_array (ColorSrgb color, float opacity) nodiscard noexcept
Convert an sRGB overlay color to a linear SDR RGBA array.
Definition at line 105 of file overlay_system.cpp.
References crimson::ColorLinear::a, crimson::ColorLinear::b, crimson::ColorLinear::g, crimson::ColorLinear::r, and srgb_to_linear().
Referenced by crimson::OverlaySystem::prepare().
tone_mapper_name()
std::string_view crimson::tone_mapper_name (ToneMapper tone_mapper) constexpr noexcept
Return the stable display name for a tone mapper.
Parameters
tone_mapper Tone mapper to name.
Returns
Static display name.
Definition at line 73 of file renderer_config.hpp.
References AcesFitted, AgxApprox, Linear, and Reinhard.
transparent_draw_packet_less()
bool crimson::transparent_draw_packet_less (const DrawPacket & left, const DrawPacket & right) nodiscard noexcept
Compare transparent packets for back-to-front sorting.
Parameters
left First packet.
right Second packet.
Returns
True when left should sort before right.
Definition at line 41 of file draw_packet_sort.cpp.
Referenced by sort_transparent_draw_packets().
v1_frame_target_descriptors()
std::array< FrameTargetDescriptor, 6 > crimson::v1_frame_target_descriptors (PickingIdTargetFormat format) nodiscard noexcept
Return V1 frame target descriptors for the requested picking format.
Definition at line 38 of file frame_targets.cpp.
References BackbufferColor, BackbufferDepth, D24S8, HdrSceneColor, kBackbufferColorTargetName, kBackbufferDepthTargetName, kHdrSceneColorTargetName, kPickingIdTargetName, kSceneDepthTargetName, kToneMappedColorTargetName, PickingId, Rgba16Float, SceneDepth, and ToneMappedColor.
Referenced by is_color_managed_frame_target(), is_data_frame_target(), is_hdr_frame_target(), and make_v1_frame_target_resource_descs().
validate_material_instance()
quader::foundation::Result< void, RendererDiagnostic > crimson::validate_material_instance (const BaseShaderRegistry & registry, const MaterialInstance & instance) nodiscard
Validate a material instance against a base shader registry.
Parameters
registry Registry that owns base shader schemas.
instance Material instance to validate.
Returns
Success, or a renderer diagnostic naming the invalid schema/binding.
Definition at line 46 of file material_validation.cpp.
References crimson::MaterialInstance::base_shader_id, base_shader_id_name(), crimson::MaterialInstance::debug_name, quader::foundation::Result< T, E >::failure(), crimson::BaseShaderRegistry::find(), find_parameter_desc(), find_texture_slot_desc(), crimson::MaterialParameterDesc::kind, material_parameter_kind_name(), material_parameter_value_kind(), MaterialSchemaInvalid, MaterialValidationFailed, crimson::BaseShaderDefinition::name, crimson::MaterialParameter::name, crimson::MaterialTextureBinding::name, crimson::MaterialInstance::parameters, quader::foundation::Result< T, E >::success(), crimson::MaterialInstance::textures, and crimson::MaterialParameter::value.
Referenced by quader::io::gltf::map_gltf_material_to_crimson().
validate_render_mesh_upload_desc()
quader::foundation::Result< RenderMeshUploadRecord, RendererDiagnostic > crimson::validate_render_mesh_upload_desc (const RenderMeshUploadDesc & desc) nodiscard
Validate a render mesh upload descriptor.
Parameters
desc Upload descriptor to inspect.
Returns
Upload record with byte counts, or a renderer diagnostic.
Definition at line 47 of file render_mesh_upload.cpp.
References crimson::RenderMeshUploadDesc::attributes, crimson::RenderMeshUploadDesc::bounds, quader::foundation::Result< T, E >::failure(), crimson::RenderMeshUploadDesc::handle, crimson::RenderMeshUploadDesc::indices, is_valid_handle(), crimson::RenderMeshUploadDesc::position_normal_interleaved, crimson::RenderMeshUploadDesc::revision, quader::foundation::Result< T, E >::success(), and VertexAttributePosition.
Referenced by crimson::RenderMeshUploadTracker::process_uploads(), and crimson::gpu::GpuMeshCache::upload_mesh().
Variable Documentation
kBackbufferColorTargetName
std::string_view crimson::kBackbufferColorTargetName = "BackbufferColor" inline constexpr
Name of the external color target presented by the viewport.
Definition at line 21 of file frame_targets.hpp.
Referenced by make_v1_correctness_render_graph(), and v1_frame_target_descriptors().
kBackbufferDepthTargetName
std::string_view crimson::kBackbufferDepthTargetName = "BackbufferDepth" inline constexpr
Name of the external depth target paired with the backbuffer.
Definition at line 23 of file frame_targets.hpp.
Referenced by v1_frame_target_descriptors().
kHdrSceneColorTargetName
std::string_view crimson::kHdrSceneColorTargetName = "HdrSceneColor" inline constexpr
Name of the linear HDR scene color target.
Definition at line 25 of file frame_targets.hpp.
Referenced by make_v1_correctness_render_graph(), crimson::gpu::GpuDevice::render_frame(), and v1_frame_target_descriptors().
kPickingIdTargetName
std::string_view crimson::kPickingIdTargetName = "PickingId" inline constexpr
Name of the picking-id data target.
Definition at line 29 of file frame_targets.hpp.
Referenced by make_v1_correctness_render_graph(), and v1_frame_target_descriptors().
kSceneDepthTargetName
std::string_view crimson::kSceneDepthTargetName = "SceneDepth" inline constexpr
Name of the scene depth target.
Definition at line 27 of file frame_targets.hpp.
Referenced by make_v1_correctness_render_graph(), crimson::gpu::GpuFrameResources::scene_depth_framebuffer(), and v1_frame_target_descriptors().
kToneMappedColorTargetName
std::string_view crimson::kToneMappedColorTargetName = "ToneMappedColor" inline constexpr
Name of the SDR tone-mapped scene color target.
Definition at line 31 of file frame_targets.hpp.
Referenced by make_v1_correctness_render_graph(), crimson::gpu::GpuDevice::render_frame(), crimson::gpu::GpuFrameResources::tone_mapped_color_framebuffer(), and v1_frame_target_descriptors().