Quader: quader::ui::ViewportRenderResult Struct Reference
quader::ui::ViewportRenderResult Struct Reference
Result returned by viewport render-host operations.
#include <viewport_render_host.hpp>
Static Public Member Functions
static ViewportRenderResult success (QString renderer_name={}, std::vector< ViewportPickResult > completed_pick_results={})
Build a successful result.
static ViewportRenderResult failure (QString summary, QString detail={})
Build a failed result.
Public Attributes
bool ok = true
True when the operation succeeded.
QString summary
Short failure summary when ok is false.
QString detail
Optional failure detail text.
QString renderer_name
Renderer display name.
std::vector< ViewportPickResult > completed_pick_results
Picking results completed during the operation.
Detailed Description
Result returned by viewport render-host operations.
Definition at line 22 of file viewport_render_host.hpp.
Member Function Documentation
failure()
ViewportRenderResult quader::ui::ViewportRenderResult::failure (QString summary, QString detail = {}) static nodiscard
Build a failed result.
Definition at line 26 of file viewport_render_host.cpp.
References detail, and summary.
Referenced by quader::ui::CrimsonViewportRenderHost::render_frame(), and quader::ui::CrimsonViewportRenderHost::resize_surface().
success()
ViewportRenderResult quader::ui::ViewportRenderResult::success (QString renderer_name = {}, std::vector< ViewportPickResult > completed_pick_results = {}) static nodiscard
Build a successful result.
Definition at line 16 of file viewport_render_host.cpp.
References completed_pick_results, and renderer_name.
Referenced by quader::ui::CrimsonViewportRenderHost::initialize_surface(), quader::ui::CrimsonViewportRenderHost::render_frame(), and quader::ui::CrimsonViewportRenderHost::resize_surface().
Member Data Documentation
completed_pick_results
std::vector<ViewportPickResult> quader::ui::ViewportRenderResult::completed_pick_results
Picking results completed during the operation.
Definition at line 32 of file viewport_render_host.hpp.
Referenced by success().
detail
QString quader::ui::ViewportRenderResult::detail
Optional failure detail text.
Definition at line 28 of file viewport_render_host.hpp.
Referenced by failure().
ok
bool quader::ui::ViewportRenderResult::ok = true
True when the operation succeeded.
Definition at line 24 of file viewport_render_host.hpp.
Referenced by quader::ui::ViewportController::initialize_surface(), quader::ui::ViewportController::render_frame(), and quader::ui::ViewportController::resize_surface().
renderer_name
QString quader::ui::ViewportRenderResult::renderer_name
Renderer display name.
Definition at line 30 of file viewport_render_host.hpp.
Referenced by quader::ui::ViewportController::initialize_surface(), and success().
summary
QString quader::ui::ViewportRenderResult::summary
Short failure summary when ok is false.
Definition at line 26 of file viewport_render_host.hpp.
Referenced by failure().
The documentation for this struct was generated from the following files:
src/ui/viewport/viewport_render_host.hpp
src/ui/viewport/viewport_render_host.cpp