Quader: crimson::gpu::GpuFrameTargetRecord Struct Reference
crimson::gpu::GpuFrameTargetRecord Struct Reference
Runtime GPU resource record for one render graph target.
#include <gpu_frame_resources.hpp>
Public Member Functions
GpuFrameTargetRecord () noexcept=default
Create an empty target record.
GpuFrameTargetRecord (const GpuFrameTargetRecord &)=delete
Target records are move-only because they own GPU handles.
GpuFrameTargetRecord & operator= (const GpuFrameTargetRecord &)=delete
Target records are move-only because they own GPU handles.
GpuFrameTargetRecord (GpuFrameTargetRecord &&) noexcept=default
Move a target record and its GPU handles.
GpuFrameTargetRecord & operator= (GpuFrameTargetRecord &&) noexcept=default
Move-assign a target record and its GPU handles.
bool external () const noexcept
bool runtime_ready () const noexcept
Public Attributes
RenderResourceDesc desc
Graph resource descriptor.
std::uint64_t graph_generation = 0
Render graph generation associated with the runtime handles.
std::uint32_t recreate_count = 0
Number of times the runtime target has been recreated.
UniqueTextureHandle texture
Texture handle owned for non-external targets.
UniqueFrameBufferHandle framebuffer
Framebuffer handle owned for non-external targets or composites.
Detailed Description
Runtime GPU resource record for one render graph target.
Definition at line 28 of file gpu_frame_resources.hpp.
Constructor & Destructor Documentation
GpuFrameTargetRecord() [1/3]
crimson::gpu::GpuFrameTargetRecord::GpuFrameTargetRecord () default noexcept
Create an empty target record.
Referenced by GpuFrameTargetRecord(), GpuFrameTargetRecord(), operator=(), and operator=().
GpuFrameTargetRecord() [2/3]
crimson::gpu::GpuFrameTargetRecord::GpuFrameTargetRecord (const GpuFrameTargetRecord &) delete
Target records are move-only because they own GPU handles.
References GpuFrameTargetRecord().
GpuFrameTargetRecord() [3/3]
crimson::gpu::GpuFrameTargetRecord::GpuFrameTargetRecord (GpuFrameTargetRecord &&) default noexcept
Move a target record and its GPU handles.
References GpuFrameTargetRecord().
Member Function Documentation
external()
bool crimson::gpu::GpuFrameTargetRecord::external () const nodiscard noexcept
Check whether the target is externally owned.
Returns
True when the descriptor is external.
Definition at line 96 of file gpu_frame_resources.cpp.
References desc.
Referenced by operator=().
operator=() [1/2]
GpuFrameTargetRecord & crimson::gpu::GpuFrameTargetRecord::operator= (const GpuFrameTargetRecord &) delete
Target records are move-only because they own GPU handles.
References GpuFrameTargetRecord().
operator=() [2/2]
GpuFrameTargetRecord & crimson::gpu::GpuFrameTargetRecord::operator= (GpuFrameTargetRecord &&) default noexcept
Move-assign a target record and its GPU handles.
References external(), GpuFrameTargetRecord(), and runtime_ready().
runtime_ready()
bool crimson::gpu::GpuFrameTargetRecord::runtime_ready () const nodiscard noexcept
Check whether runtime handles are ready.
Returns
True when the external target needs no handle or owned handles are valid.
Definition at line 100 of file gpu_frame_resources.cpp.
References desc, framebuffer, and texture.
Referenced by operator=().
Member Data Documentation
desc
RenderResourceDesc crimson::gpu::GpuFrameTargetRecord::desc
Graph resource descriptor.
Definition at line 30 of file gpu_frame_resources.hpp.
Referenced by external(), runtime_ready(), and crimson::gpu::GpuFrameResources::synchronize_descriptors().
framebuffer
UniqueFrameBufferHandle crimson::gpu::GpuFrameTargetRecord::framebuffer
Framebuffer handle owned for non-external targets or composites.
Definition at line 38 of file gpu_frame_resources.hpp.
Referenced by crimson::gpu::GpuFrameResources::framebuffer(), runtime_ready(), and crimson::gpu::GpuFrameResources::synchronize_descriptors().
graph_generation
std::uint64_t crimson::gpu::GpuFrameTargetRecord::graph_generation = 0
Render graph generation associated with the runtime handles.
Definition at line 32 of file gpu_frame_resources.hpp.
Referenced by crimson::gpu::GpuFrameResources::synchronize_descriptors().
recreate_count
std::uint32_t crimson::gpu::GpuFrameTargetRecord::recreate_count = 0
Number of times the runtime target has been recreated.
Definition at line 34 of file gpu_frame_resources.hpp.
Referenced by crimson::gpu::GpuFrameResources::synchronize_descriptors().
texture
UniqueTextureHandle crimson::gpu::GpuFrameTargetRecord::texture
Texture handle owned for non-external targets.
Definition at line 36 of file gpu_frame_resources.hpp.
Referenced by runtime_ready(), crimson::gpu::GpuFrameResources::synchronize_descriptors(), and crimson::gpu::GpuFrameResources::texture().
The documentation for this struct was generated from the following files:
src/crimson/gpu/gpu_frame_resources.hpp
src/crimson/gpu/gpu_frame_resources.cpp