Quader: quader::commands::CommandResult Struct Reference
quader::commands::CommandResult Struct Reference final
Result payload returned by command operations.
#include <command_result.hpp>
Public Member Functions
bool is_applied () const noexcept
Static Public Member Functions
static CommandResult applied ()
static CommandResult rejected (quader::foundation::Diagnostic diagnostic)
static CommandResult rejected (const std::string &message)
static CommandResult not_mergeable ()
Public Attributes
CommandStatus status = CommandStatus::Rejected
High-level command outcome.
quader::foundation::DiagnosticList diagnostics
Diagnostics explaining rejected commands or merge failures.
Detailed Description
Result payload returned by command operations.
Definition at line 29 of file command_result.hpp.
Member Function Documentation
applied()
CommandResult quader::commands::CommandResult::applied () static nodiscard
Create a successful command result.
Returns
Result with CommandStatus::Applied.
Definition at line 16 of file command_result.cpp.
References quader::commands::Applied.
Referenced by quader::commands::ClearSelectionCommand::execute(), quader::commands::CreateMeshObjectCommand::execute(), quader::commands::DeleteObjectCommand::execute(), quader::commands::RenameObjectCommand::execute(), quader::commands::SetObjectTransformCommand::execute(), quader::commands::SetSelectionCommand::execute(), quader::commands::ClearSelectionCommand::undo(), quader::commands::CreateMeshObjectCommand::undo(), quader::commands::DeleteObjectCommand::undo(), quader::commands::RenameObjectCommand::undo(), quader::commands::SetObjectTransformCommand::undo(), and quader::commands::SetSelectionCommand::undo().
is_applied()
bool quader::commands::CommandResult::is_applied () const inline nodiscard noexcept
Check whether the command applied successfully.
Returns
True when status is CommandStatus::Applied.
Definition at line 40 of file command_result.hpp.
References quader::commands::Applied, and status.
not_mergeable()
CommandResult quader::commands::CommandResult::not_mergeable () static nodiscard
Create a non-mergeable command result.
Returns
Result with CommandStatus::NotMergeable.
Definition at line 39 of file command_result.cpp.
References quader::commands::NotMergeable.
Referenced by quader::commands::ICommand::merge_with().
rejected() [1/2]
CommandResult quader::commands::CommandResult::rejected (const std::string & message) static nodiscard
Create a rejected command result from an error message.
Parameters
message Message explaining the rejection.
Returns
Result with CommandStatus::Rejected.
Definition at line 32 of file command_result.cpp.
References quader::foundation::Error, and rejected().
rejected() [2/2]
CommandResult quader::commands::CommandResult::rejected (quader::foundation::Diagnostic diagnostic) static nodiscard
Create a rejected command result from a diagnostic.
Parameters
diagnostic Diagnostic explaining the rejection.
Returns
Result with CommandStatus::Rejected.
Definition at line 23 of file command_result.cpp.
References quader::foundation::DiagnosticList::add(), diagnostics, and quader::commands::Rejected.
Referenced by quader::commands::ClearSelectionCommand::execute(), quader::commands::CommandHistory::execute(), quader::commands::CreateMeshObjectCommand::execute(), quader::commands::RenameObjectCommand::execute(), quader::commands::SetObjectTransformCommand::execute(), quader::commands::SetSelectionCommand::execute(), quader::commands::CommandHistory::redo(), rejected(), quader::commands::ClearSelectionCommand::undo(), quader::commands::CommandHistory::undo(), quader::commands::CreateMeshObjectCommand::undo(), quader::commands::DeleteObjectCommand::undo(), quader::commands::RenameObjectCommand::undo(), quader::commands::SetObjectTransformCommand::undo(), and quader::commands::SetSelectionCommand::undo().
Member Data Documentation
diagnostics
quader::foundation::DiagnosticList quader::commands::CommandResult::diagnostics
Diagnostics explaining rejected commands or merge failures.
Definition at line 33 of file command_result.hpp.
Referenced by rejected().
status
CommandStatus quader::commands::CommandResult::status = CommandStatus::Rejected
High-level command outcome.
Definition at line 31 of file command_result.hpp.
Referenced by is_applied().
The documentation for this struct was generated from the following files:
src/commands/command_result.hpp
src/commands/command_result.cpp